// Check logic derived from Prowler (Apache-2.0, https://github.com/prowler-cloud/prowler)
import { CheckMetadata } from '../../types';

export const appserviceChecks: CheckMetadata[] = [
  // ── Pre-existing checks (migrated from this.finding() to this.emit()) ──
  // No direct Prowler equivalent existed for these prior to Tranche 2, so
  // checkIds are invented in the `azure_appservice_*` namespace.
  {
    checkId: 'azure_appservice_https_only_enforced',
    provider: 'azure',
    service: 'appservice',
    title: 'App Service Enforces HTTPS-Only Traffic',
    severity: 'HIGH',
    description: 'Checks that the App Service enforces HTTPS-only access, so users cannot connect over unencrypted HTTP.',
    remediation: 'Enable the "HTTPS Only" setting on the App Service.',
    tags: ['appservice', 'tls'],
  },
  {
    checkId: 'azure_appservice_minimum_tls_version_12',
    provider: 'azure',
    service: 'appservice',
    title: 'App Service Enforces Minimum TLS Version 1.2',
    severity: 'MEDIUM',
    description: 'Checks that the App Service minimum TLS version is set to 1.2. TLS 1.0/1.1 are deprecated and vulnerable.',
    remediation: 'Set the minimum TLS version to 1.2 in the App Service TLS/SSL settings.',
    tags: ['appservice', 'tls'],
  },
  {
    checkId: 'azure_appservice_ftp_disabled_or_ftps_only',
    provider: 'azure',
    service: 'appservice',
    title: 'App Service Disables Unencrypted FTP Access',
    severity: 'HIGH',
    description: 'Checks that the App Service FTP state is not "AllAllowed", which would permit plain-text FTP connections carrying credentials and code unencrypted.',
    remediation: 'Set FTP state to "FtpsOnly" or "Disabled". Use FTPS or deployment slots/GitHub Actions instead.',
    tags: ['appservice', 'ftp'],
  },
  {
    checkId: 'azure_appservice_remote_debugging_disabled',
    provider: 'azure',
    service: 'appservice',
    title: 'App Service Has Remote Debugging Disabled',
    severity: 'HIGH',
    description: 'Checks that remote debugging is disabled on the App Service. An open debug port can be exploited to inspect running code and inject breakpoints.',
    remediation: 'Disable remote debugging in the App Service configuration. Only enable it temporarily when needed.',
    tags: ['appservice', 'debugging'],
  },
  {
    checkId: 'azure_appservice_managed_identity_configured',
    provider: 'azure',
    service: 'appservice',
    title: 'App Service Uses a Managed Identity',
    severity: 'MEDIUM',
    description: 'Checks that the App Service has a system- or user-assigned managed identity, so it can authenticate to Key Vault, Storage, and other services without credentials stored in code.',
    remediation: 'Enable system-assigned managed identity so the app can authenticate to dependent services without credentials in code.',
    tags: ['appservice', 'identity'],
  },
  {
    checkId: 'azure_appservice_authentication_configured',
    provider: 'azure',
    service: 'appservice',
    title: 'App Service Has Platform Authentication (Easy Auth) Configured',
    severity: 'LOW',
    description: 'Checks that the App Service has Azure AD authentication (Easy Auth) enabled, adding a platform-level authentication layer in front of the application.',
    remediation: 'Consider enabling Easy Auth with Azure AD to add a platform-level authentication layer in front of the application.',
    tags: ['appservice', 'authentication'],
  },

  // ── Newly ported Prowler checks (Tranche 2) ──
  {
    checkId: 'app_client_certificates_on',
    provider: 'azure',
    service: 'appservice',
    title: 'App Service Requires Incoming Client Certificates',
    severity: 'MEDIUM',
    description: 'Checks that the App Service client certificate mode is set to "Required", so every inbound request must present a valid client certificate that the app can validate (mutual TLS).',
    remediation: 'Set the client certificate mode to "Required" for apps that should enforce mutual TLS with trusted clients.',
    tags: ['appservice', 'tls', 'mtls'],
  },
  {
    checkId: 'app_ensure_using_http20',
    provider: 'azure',
    service: 'appservice',
    title: 'App Service Has HTTP/2.0 Enabled',
    severity: 'LOW',
    description: 'Checks that the App Service site configuration has http20Enabled set to true, so the site can serve traffic using the HTTP/2 protocol.',
    remediation: 'Enable HTTP/2.0 in the App Service configuration for improved performance and modern protocol support.',
    tags: ['appservice', 'configuration'],
  },
  {
    checkId: 'app_http_logs_enabled',
    provider: 'azure',
    service: 'appservice',
    title: 'App Service Has HTTP Logs Enabled in Diagnostic Settings',
    severity: 'LOW',
    description: 'Checks that the App Service has a diagnostic setting with the AppServiceHTTPLogs category (or the allLogs group) enabled, so web access events are captured for audit.',
    remediation: 'Add a diagnostic setting on the App Service that streams AppServiceHTTPLogs (or allLogs) to a Log Analytics workspace.',
    tags: ['appservice', 'logging'],
  },
  {
    checkId: 'app_ensure_java_version_is_latest',
    provider: 'azure',
    service: 'appservice',
    title: 'App Service Uses the Latest Supported Java Version',
    severity: 'LOW',
    description: 'Checks that App Service apps running Java are configured to use the latest supported major (LTS) version, across Linux and Windows stacks.',
    remediation: 'Update the App Service Java runtime to the latest supported LTS version. Test in a staging slot before swapping to production.',
    tags: ['appservice', 'eol-version'],
  },
  {
    checkId: 'app_ensure_php_version_is_latest',
    provider: 'azure',
    service: 'appservice',
    title: 'App Service Uses the Latest Supported PHP Version',
    severity: 'LOW',
    description: 'Checks that App Service apps running PHP are configured to use the latest supported PHP release.',
    remediation: 'Update the App Service PHP runtime to the latest supported version. Test in a staging slot before swapping to production.',
    tags: ['appservice', 'eol-version'],
  },
  {
    checkId: 'app_ensure_python_version_is_latest',
    provider: 'azure',
    service: 'appservice',
    title: 'App Service Uses the Latest Supported Python Version',
    severity: 'LOW',
    description: 'Checks that App Service apps running Python are configured to use the latest supported Python release.',
    remediation: 'Update the App Service Python runtime to the latest supported version. Test in a staging slot before swapping to production.',
    tags: ['appservice', 'eol-version'],
  },
];
