// Check logic derived from Prowler (Apache-2.0, https://github.com/prowler-cloud/prowler)
import { CheckMetadata } from '../../types';

export const cosmosChecks: CheckMetadata[] = [
  {
    checkId: 'azure_cosmosdb_public_network_access_disabled',
    provider: 'azure',
    service: 'cosmos',
    title: 'CosmosDB Account Has Public Network Access Disabled',
    severity: 'HIGH',
    description: 'Checks that CosmosDB account public network access is disabled, so the data-plane endpoint is not reachable from the public internet.',
    remediation: 'Set publicNetworkAccess to "Disabled" and use Private Endpoint for connectivity. Update all application connection strings to use the private DNS FQDN.',
    tags: ['cosmosdb', 'network', 'public-access'],
  },
  {
    checkId: 'azure_cosmosdb_firewall_rules_configured',
    provider: 'azure',
    service: 'cosmos',
    title: 'CosmosDB Account Has IP or VNet Firewall Rules Configured',
    severity: 'HIGH',
    description: 'Checks that a CosmosDB account with public network access not explicitly disabled has at least one IP firewall rule or virtual network rule configured, so it is not open to every client on the internet.',
    remediation: 'Add IP firewall rules restricting access to known application server IPs, or configure VNet service endpoints/Private Endpoint to eliminate public access entirely.',
    tags: ['cosmosdb', 'firewall', 'network'],
  },
  {
    checkId: 'cosmosdb_account_firewall_use_selected_networks',
    provider: 'azure',
    service: 'cosmos',
    title: 'CosmosDB Account Firewall Restricts Access to Selected Networks',
    severity: 'HIGH',
    description: 'Checks that CosmosDB account virtual network filtering is enabled so access is restricted to selected networks rather than being open to all networks.',
    remediation: 'Enable the virtual network filter on the CosmosDB account and configure specific VNet/subnet rules for trusted networks.',
    tags: ['cosmosdb', 'firewall', 'network'],
  },
  {
    checkId: 'azure_cosmosdb_network_acl_bypass_restricted',
    provider: 'azure',
    service: 'cosmos',
    title: 'CosmosDB Account Does Not Allow All Azure Services to Bypass Firewall',
    severity: 'MEDIUM',
    description: 'Checks that CosmosDB account networkAclBypass is not set to "AzureServices", which would allow any Azure service in any tenant to bypass the IP firewall.',
    remediation: 'Set networkAclBypass to "None" and explicitly allow only required Azure services (e.g. Azure Data Factory) via their managed identity or VNet integration.',
    tags: ['cosmosdb', 'firewall', 'network'],
  },
  {
    checkId: 'cosmosdb_account_use_aad_and_rbac',
    provider: 'azure',
    service: 'cosmos',
    title: 'CosmosDB Account Uses AAD and RBAC Authentication',
    severity: 'MEDIUM',
    description: 'Checks that CosmosDB account local (key-based) authentication is disabled, so clients must use Azure AD (RBAC) authentication with least-privilege roles instead of unrestricted account keys.',
    remediation: 'Set disableLocalAuth=true and migrate all clients to use Azure AD (RBAC) authentication with least-privilege roles (Cosmos DB Built-in Data Reader, etc.).',
    tags: ['cosmosdb', 'authentication'],
  },
  {
    checkId: 'azure_cosmosdb_automatic_failover_enabled',
    provider: 'azure',
    service: 'cosmos',
    title: 'CosmosDB Account Has Automatic Failover Enabled',
    severity: 'LOW',
    description: 'Checks that CosmosDB account automatic failover is enabled, so a regional outage triggers failover without manual intervention, reducing recovery time objective (RTO).',
    remediation: 'Enable automatic failover and configure at least one additional write region to ensure high availability.',
    tags: ['cosmosdb', 'availability'],
  },
  {
    checkId: 'azure_cosmosdb_backup_interval_sufficient',
    provider: 'azure',
    service: 'cosmos',
    title: 'CosmosDB Account Periodic Backup Interval Does Not Exceed 24 Hours',
    severity: 'MEDIUM',
    description: 'Checks that, for CosmosDB accounts using periodic backup mode, the backup interval does not exceed 24 hours, keeping the recovery point objective (RPO) reasonable.',
    remediation: 'Reduce the backup interval to at most 4 hours. Consider migrating to Continuous backup mode for point-in-time restore capability.',
    tags: ['cosmosdb', 'backup'],
  },
  {
    checkId: 'azure_cosmosdb_backup_retention_sufficient',
    provider: 'azure',
    service: 'cosmos',
    title: 'CosmosDB Account Backup Retention Is at Least 7 Days',
    severity: 'LOW',
    description: 'Checks that, for CosmosDB accounts using periodic backup mode, the backup retention period is at least 7 days (168 hours), sufficient for detecting and recovering from data corruption.',
    remediation: 'Increase backup retention to at least 7 days (168 hours). For compliance workloads, consider 30 days.',
    tags: ['cosmosdb', 'backup'],
  },
  {
    checkId: 'cosmosdb_account_backup_policy_continuous',
    provider: 'azure',
    service: 'cosmos',
    title: 'CosmosDB Account Uses Continuous Backup Policy',
    severity: 'MEDIUM',
    description: 'Checks that the CosmosDB account backup policy type is "Continuous", enabling point-in-time restore rather than relying solely on periodic snapshots.',
    remediation: 'Migrate the CosmosDB account to Continuous backup mode (7-day or 30-day tier) to enable point-in-time restore and reduce data-loss risk.',
    tags: ['cosmosdb', 'backup'],
  },
  {
    checkId: 'cosmosdb_account_minimum_tls_version',
    provider: 'azure',
    service: 'cosmos',
    title: 'CosmosDB Account Enforces TLS 1.2 or Higher',
    severity: 'MEDIUM',
    description: 'Checks that the CosmosDB account minimalTlsVersion is set to Tls12 or higher, so clients cannot connect using outdated, insecure TLS versions.',
    remediation: 'Set the minimalTlsVersion property on the CosmosDB account to Tls12 (or Tls13 where supported) and update client SDKs/drivers as needed.',
    tags: ['cosmosdb', 'encryption-in-transit', 'tls'],
  },
  {
    checkId: 'cosmosdb_account_use_private_endpoints',
    provider: 'azure',
    service: 'cosmos',
    title: 'CosmosDB Account Uses Private Endpoint Connections',
    severity: 'HIGH',
    description: 'Checks that the CosmosDB account has at least one Private Endpoint connection configured, allowing access from within a virtual network without traversing the public internet.',
    remediation: 'Create a Private Endpoint for the CosmosDB account in the relevant virtual network(s) and update application connection strings to use the private DNS FQDN.',
    tags: ['cosmosdb', 'network', 'private-endpoint'],
  },
];
