// Check logic derived from Prowler (Apache-2.0, https://github.com/prowler-cloud/prowler)
import { CheckMetadata } from '../../types';

export const defenderChecks: CheckMetadata[] = [
  {
    checkId: 'defender_additional_email_configured_with_a_security_contact',
    provider: 'azure',
    service: 'defender',
    title: 'Security Contact Has Additional Email Addresses Configured',
    severity: 'LOW',
    description: 'Checks that Microsoft Defender for Cloud security contact settings include at least one additional email recipient to receive alert notifications, rather than relying solely on subscription owners.',
    remediation: 'Configure a monitored, team-managed distribution list (e.g. SOC/on-call) as the security contact email address for the subscription so alerts are never missed due to owner turnover.',
    tags: ['defender', 'security-contact', 'notifications'],
  },
  {
    checkId: 'defender_assessments_vm_endpoint_protection_installed',
    provider: 'azure',
    service: 'defender',
    title: 'Virtual Machines Have Endpoint Protection Installed',
    severity: 'HIGH',
    description: 'Checks the Defender for Cloud "Install endpoint protection solution on virtual machines" assessment and flags the subscription when any VM is missing a healthy endpoint protection (antimalware) solution.',
    remediation: 'Install and enable an endpoint protection/EDR solution on every virtual machine, then verify the recommendation shows Healthy in Defender for Cloud.',
    tags: ['defender', 'vm', 'endpoint-protection'],
  },
  {
    checkId: 'defender_attack_path_notifications_properly_configured',
    provider: 'azure',
    service: 'defender',
    title: 'Attack Path Email Notifications Are Properly Configured',
    severity: 'HIGH',
    description: 'Checks that Microsoft Defender for Cloud attack path email notifications are enabled for the security contact with a minimal risk level at or above the configured threshold (default High).',
    remediation: 'Enable attack path notifications on the security contact and set the minimal risk level to High (or your configured tolerance) so exploitable attack paths are reported promptly.',
    tags: ['defender', 'security-contact', 'attack-path', 'notifications'],
  },
  {
    checkId: 'defender_auto_provisioning_log_analytics_agent_vms_on',
    provider: 'azure',
    service: 'defender',
    title: 'Auto-Provisioning of Log Analytics Agent for VMs Is Enabled',
    severity: 'HIGH',
    description: 'Checks that Microsoft Defender for Cloud auto-provisioning of the Log Analytics agent to Azure virtual machines is set to On at the subscription level, ensuring all VMs receive security telemetry.',
    remediation: 'Set the Defender for Cloud auto-provisioning setting for the Log Analytics agent to On so every VM is enrolled for monitoring automatically.',
    tags: ['defender', 'auto-provisioning', 'log-analytics', 'vm'],
  },
  {
    checkId: 'defender_auto_provisioning_vulnerabilty_assessments_machines_on',
    provider: 'azure',
    service: 'defender',
    title: 'Vulnerability Assessment Solution Installed on All Machines',
    severity: 'MEDIUM',
    description: 'Checks the Defender for Cloud "Machines should have a vulnerability assessment solution" assessment and flags the subscription when any Azure or Arc-enabled machine lacks healthy vulnerability assessment coverage.',
    remediation: 'Enable subscription-wide auto-provisioning of a vulnerability assessment solution (e.g. Microsoft Defender Vulnerability Management) for all machines.',
    tags: ['defender', 'vulnerability-assessment', 'vm'],
  },
  {
    checkId: 'defender_container_images_resolved_vulnerabilities',
    provider: 'azure',
    service: 'defender',
    title: 'Running Container Images Have No Unresolved Vulnerabilities',
    severity: 'CRITICAL',
    description: 'Checks the Defender for Cloud assessment for running container images and flags the subscription when applicable images have unresolved vulnerabilities reported by Microsoft Defender Vulnerability Management.',
    remediation: 'Rebuild affected container images from patched base images, redeploy, and confirm the "running container images should have vulnerabilities resolved" recommendation returns to Healthy.',
    tags: ['defender', 'containers', 'vulnerability-assessment'],
  },
  {
    checkId: 'defender_container_images_scan_enabled',
    provider: 'azure',
    service: 'defender',
    title: 'Container Image Vulnerability Scanning Is Enabled',
    severity: 'HIGH',
    description: 'Checks that the Defender for Containers pricing plan has the container registry vulnerability assessment extension enabled so pushed images are scanned automatically.',
    remediation: 'Enable Defender for Containers and turn on the ContainerRegistriesVulnerabilityAssessments extension so images are scanned on push and periodically thereafter.',
    tags: ['defender', 'containers', 'vulnerability-assessment'],
  },
  {
    checkId: 'defender_ensure_defender_cspm_is_on',
    provider: 'azure',
    service: 'defender',
    title: 'Defender CSPM Plan Is Set to On',
    severity: 'MEDIUM',
    description: 'Checks that the Microsoft Defender Cloud Security Posture Management (CSPM) pricing plan is set to the Standard tier for the subscription.',
    remediation: 'Enable the Defender CSPM plan (Standard pricing tier) under Defender for Cloud > Environment settings for the subscription.',
    tags: ['defender', 'cspm', 'pricing-tier'],
  },
  {
    checkId: 'defender_ensure_defender_for_app_services_is_on',
    provider: 'azure',
    service: 'defender',
    title: 'Defender for App Services Is Set to On',
    severity: 'HIGH',
    description: 'Checks that the Defender for App Services pricing plan is set to the Standard tier for the subscription.',
    remediation: 'Enable Defender for App Services (Standard pricing tier) under Defender for Cloud > Environment settings for the subscription.',
    tags: ['defender', 'appservice', 'pricing-tier'],
  },
  {
    checkId: 'defender_ensure_defender_for_arm_is_on',
    provider: 'azure',
    service: 'defender',
    title: 'Defender for Azure Resource Manager Is Set to On',
    severity: 'HIGH',
    description: 'Checks that the Defender for Azure Resource Manager (ARM) pricing plan is set to the Standard tier for the subscription, enabling detection of suspicious ARM control-plane operations.',
    remediation: 'Enable Defender for Resource Manager (Standard pricing tier) under Defender for Cloud > Environment settings for the subscription.',
    tags: ['defender', 'arm', 'pricing-tier'],
  },
  {
    checkId: 'defender_ensure_defender_for_azure_sql_databases_is_on',
    provider: 'azure',
    service: 'defender',
    title: 'Defender for Azure SQL Databases Is Set to On',
    severity: 'HIGH',
    description: 'Checks that the Defender for Azure SQL Database Servers pricing plan is set to the Standard tier for the subscription.',
    remediation: 'Enable Defender for Azure SQL Databases (Standard pricing tier) under Defender for Cloud > Environment settings for the subscription.',
    tags: ['defender', 'sql', 'pricing-tier'],
  },
  {
    checkId: 'defender_ensure_defender_for_containers_is_on',
    provider: 'azure',
    service: 'defender',
    title: 'Defender for Containers Is Set to On',
    severity: 'HIGH',
    description: 'Checks that the Defender for Containers pricing plan is set to the Standard tier for the subscription.',
    remediation: 'Enable Defender for Containers (Standard pricing tier) under Defender for Cloud > Environment settings for the subscription.',
    tags: ['defender', 'containers', 'pricing-tier'],
  },
  {
    checkId: 'defender_ensure_defender_for_cosmosdb_is_on',
    provider: 'azure',
    service: 'defender',
    title: 'Defender for Cosmos DB Is Set to On',
    severity: 'HIGH',
    description: 'Checks that the Defender for Cosmos DB pricing plan is set to the Standard tier for the subscription.',
    remediation: 'Enable Defender for Cosmos DB (Standard pricing tier) under Defender for Cloud > Environment settings for the subscription.',
    tags: ['defender', 'cosmosdb', 'pricing-tier'],
  },
  {
    checkId: 'defender_ensure_defender_for_databases_is_on',
    provider: 'azure',
    service: 'defender',
    title: 'Defender for Databases Is Set to On',
    severity: 'HIGH',
    description: 'Checks that all database-related Defender pricing plans — SQL Servers, SQL Server VMs, Open-Source Relational Databases, and Cosmos DB — are set to the Standard tier for the subscription.',
    remediation: 'Enable the Standard pricing tier for each Defender for Databases sub-plan (SQL Servers, SQL Server on VMs, Open-Source Relational Databases, Cosmos DB) under Defender for Cloud > Environment settings.',
    tags: ['defender', 'databases', 'pricing-tier'],
  },
  {
    checkId: 'defender_ensure_defender_for_dns_is_on',
    provider: 'azure',
    service: 'defender',
    title: 'Defender for DNS Is Set to On',
    severity: 'HIGH',
    description: 'Checks that the Defender for DNS pricing plan is set to the Standard tier for the subscription.',
    remediation: 'Enable Defender for DNS (Standard pricing tier) under Defender for Cloud > Environment settings for the subscription.',
    tags: ['defender', 'dns', 'pricing-tier'],
  },
  {
    checkId: 'defender_ensure_defender_for_keyvault_is_on',
    provider: 'azure',
    service: 'defender',
    title: 'Defender for Key Vault Is Set to On',
    severity: 'HIGH',
    description: 'Checks that the Defender for Key Vault pricing plan is set to the Standard tier for the subscription.',
    remediation: 'Enable Defender for Key Vault (Standard pricing tier) under Defender for Cloud > Environment settings for the subscription.',
    tags: ['defender', 'keyvault', 'pricing-tier'],
  },
  {
    checkId: 'defender_ensure_defender_for_os_relational_databases_is_on',
    provider: 'azure',
    service: 'defender',
    title: 'Defender for Open-Source Relational Databases Is Set to On',
    severity: 'HIGH',
    description: 'Checks that the Defender for Open-Source Relational Databases (PostgreSQL, MySQL, MariaDB) pricing plan is set to the Standard tier for the subscription.',
    remediation: 'Enable Defender for Open-Source Relational Databases (Standard pricing tier) under Defender for Cloud > Environment settings for the subscription.',
    tags: ['defender', 'postgres', 'mysql', 'pricing-tier'],
  },
  {
    checkId: 'defender_ensure_defender_for_server_is_on',
    provider: 'azure',
    service: 'defender',
    title: 'Defender for Servers Is Set to On',
    severity: 'HIGH',
    description: 'Checks that the Defender for Servers (virtual machines) pricing plan is set to the Standard tier for the subscription.',
    remediation: 'Enable Defender for Servers (Standard pricing tier) under Defender for Cloud > Environment settings for the subscription.',
    tags: ['defender', 'vm', 'pricing-tier'],
  },
  {
    checkId: 'defender_ensure_defender_for_sql_servers_is_on',
    provider: 'azure',
    service: 'defender',
    title: 'Defender for SQL Servers on Machines Is Set to On',
    severity: 'HIGH',
    description: 'Checks that the Defender for SQL Server Virtual Machines pricing plan is set to the Standard tier for the subscription.',
    remediation: 'Enable Defender for SQL servers on machines (Standard pricing tier) under Defender for Cloud > Environment settings for the subscription.',
    tags: ['defender', 'sql', 'pricing-tier'],
  },
  {
    checkId: 'defender_ensure_defender_for_storage_is_on',
    provider: 'azure',
    service: 'defender',
    title: 'Defender for Storage Is Set to On',
    severity: 'HIGH',
    description: 'Checks that the Defender for Storage pricing plan is set to the Standard tier for the subscription.',
    remediation: 'Enable Defender for Storage (Standard pricing tier) under Defender for Cloud > Environment settings for the subscription.',
    tags: ['defender', 'storage', 'pricing-tier'],
  },
  {
    checkId: 'defender_ensure_iot_hub_defender_is_on',
    provider: 'azure',
    service: 'defender',
    title: 'Defender for IoT Hub Is Set to On',
    severity: 'HIGH',
    description: 'Checks that an IoT Security Solution exists and is enabled for the subscription, indicating Defender for IoT protection is active for IoT Hub resources.',
    remediation: 'Create and enable an IoT Security Solution for each subscription that uses IoT Hub, so device and traffic telemetry is analyzed for threats.',
    tags: ['defender', 'iothub', 'pricing-tier'],
  },
  {
    checkId: 'defender_ensure_mcas_is_enabled',
    provider: 'azure',
    service: 'defender',
    title: 'Defender for Cloud Apps (MCAS) Integration Is Enabled',
    severity: 'MEDIUM',
    description: 'Checks that the Microsoft Defender for Cloud Apps (MCAS) integration setting exists and is enabled for the subscription, surfacing Defender for Cloud alerts in Microsoft Defender for Cloud Apps.',
    remediation: 'Enable the Microsoft Defender for Cloud Apps integration under Defender for Cloud > Environment settings > Integrations.',
    tags: ['defender', 'mcas', 'integration'],
  },
  {
    checkId: 'defender_ensure_notify_alerts_severity_is_high',
    provider: 'azure',
    service: 'defender',
    title: 'Alert Notifications Enabled at High Severity or Lower',
    severity: 'HIGH',
    description: 'Checks that the security contact is configured to receive email notifications for alerts at a minimal severity of High or lower (i.e. not restricted to Critical-only).',
    remediation: 'Set the security contact\'s alert notification minimal severity to High (or Medium/Low) so important alerts are not silently dropped.',
    tags: ['defender', 'security-contact', 'notifications'],
  },
  {
    checkId: 'defender_ensure_notify_emails_to_owners',
    provider: 'azure',
    service: 'defender',
    title: 'Security Contact Notifications Include the Owner Role',
    severity: 'MEDIUM',
    description: 'Checks that role-based email notifications are enabled on the security contact and that the Owner role is included, ensuring subscription owners are alerted directly.',
    remediation: 'Enable "notify roles" on the security contact and include the Owner role so subscription owners receive Defender for Cloud alert notifications.',
    tags: ['defender', 'security-contact', 'notifications'],
  },
  {
    checkId: 'defender_ensure_system_updates_are_applied',
    provider: 'azure',
    service: 'defender',
    title: 'System Updates Applied to All Virtual Machines',
    severity: 'HIGH',
    description: 'Checks the Defender for Cloud assessments for the Log Analytics agent, periodic update checks, and missing system updates, and flags the subscription when any of these report Unhealthy.',
    remediation: 'Install the Log Analytics agent on all VMs, enable periodic update checks, and apply outstanding system updates until all three related recommendations report Healthy.',
    tags: ['defender', 'vm', 'patch-management'],
  },
  {
    checkId: 'defender_ensure_wdatp_is_enabled',
    provider: 'azure',
    service: 'defender',
    title: 'Defender for Endpoint (WDATP) Integration Is Enabled',
    severity: 'HIGH',
    description: 'Checks that the Microsoft Defender for Endpoint (WDATP) integration setting exists and is enabled for the subscription, allowing Defender for Endpoint signals to feed Defender for Cloud.',
    remediation: 'Enable the Microsoft Defender for Endpoint integration under Defender for Cloud > Environment settings > Integrations.',
    tags: ['defender', 'wdatp', 'integration'],
  },
];
