// Check logic derived from Prowler (Apache-2.0, https://github.com/prowler-cloud/prowler)
import { CheckMetadata } from '../../types';

export const entraChecks: CheckMetadata[] = [
  // ── Existing checks (predate Prowler-parity work) — no Prowler equivalent ──
  // Conditional Access
  {
    checkId: 'entra_conditional_access_mfa_all_users',
    provider: 'azure',
    service: 'entra',
    title: 'Conditional Access Requires MFA For All Users',
    severity: 'CRITICAL',
    description: 'Checks that an enabled Conditional Access policy requires multi-factor authentication for all (or a broad set of) users, preventing password-only sign-in.',
    remediation: 'Create a Conditional Access policy targeting all users (excluding emergency access accounts) that requires MFA as a grant control. Use named locations to exclude trusted office networks if needed.',
    tags: ['entra', 'mfa', 'conditional-access'],
  },
  {
    checkId: 'entra_conditional_access_legacy_auth_blocked',
    provider: 'azure',
    service: 'entra',
    title: 'Conditional Access Blocks Legacy Authentication',
    severity: 'CRITICAL',
    description: 'Checks that an enabled Conditional Access policy blocks legacy authentication protocols (Basic Auth, SMTP AUTH, IMAP, POP, older Office clients), which bypass MFA.',
    remediation: 'Create a Conditional Access policy targeting all users with client app types "Exchange ActiveSync" and "Other clients" set to Block. Identify and migrate any legacy auth clients before enforcement.',
    tags: ['entra', 'legacy-auth', 'conditional-access'],
  },
  {
    checkId: 'entra_conditional_access_policies_exist',
    provider: 'azure',
    service: 'entra',
    title: 'Conditional Access Policies Are Configured',
    severity: 'CRITICAL',
    description: 'Checks that the tenant has at least one Conditional Access policy defined rather than relying solely on password strength.',
    remediation: 'Implement Conditional Access policies covering at minimum: MFA for all users, block legacy auth, require compliant device for privileged access.',
    tags: ['entra', 'conditional-access'],
  },
  {
    checkId: 'entra_conditional_access_not_report_only',
    provider: 'azure',
    service: 'entra',
    title: 'Conditional Access Policies Are Enforced, Not Report-Only',
    severity: 'HIGH',
    description: 'Checks that at least one Conditional Access policy is enabled (not left in report-only mode) so access controls are actually enforced.',
    remediation: 'Move Conditional Access policies from report-only to enabled after validating their impact using the CA insights workbook.',
    tags: ['entra', 'conditional-access'],
  },
  // Privileged directory roles
  {
    checkId: 'entra_directory_role_global_admin_count_bounded',
    provider: 'azure',
    service: 'entra',
    title: 'Global Administrator Assignments Are Bounded',
    severity: 'CRITICAL',
    description: 'Checks that permanent Global Administrator role assignments do not exceed a safe threshold, since each assignment expands the tenant-wide compromise blast radius.',
    remediation: 'Reduce permanent Global Admin assignments to emergency access accounts only. Use Azure AD PIM (Privileged Identity Management) for just-in-time access for all other admins.',
    tags: ['entra', 'global-admin', 'privileged-roles'],
  },
  {
    checkId: 'entra_directory_role_global_admin_breakglass_configured',
    provider: 'azure',
    service: 'entra',
    title: 'Break-Glass Global Administrator Accounts Configured',
    severity: 'MEDIUM',
    description: 'Checks that at least one principal is permanently assigned Global Administrator, since zero permanent assignments may indicate break-glass accounts are missing.',
    remediation: 'Configure at least 2 cloud-only break-glass Global Admin accounts with strong passwords and MFA for emergency access.',
    tags: ['entra', 'global-admin'],
  },
  {
    checkId: 'entra_directory_role_assignment_count_bounded',
    provider: 'azure',
    service: 'entra',
    title: 'Privileged Directory Role Assignments Are Bounded',
    severity: 'HIGH',
    description: 'Checks that no built-in privileged directory role (Privileged Role Administrator, Security Administrator, User Administrator, etc.) has an excessive number of permanent assignees.',
    remediation: 'Use Azure AD PIM to convert permanent privileged role assignments to eligible assignments requiring activation. Review and remove stale assignments.',
    tags: ['entra', 'privileged-roles', 'pim'],
  },
  {
    checkId: 'entra_directory_role_no_guest_assignees',
    provider: 'azure',
    service: 'entra',
    title: 'No Guest Users In Privileged Directory Roles',
    severity: 'CRITICAL',
    description: 'Checks that no guest (external) user is assigned a privileged Azure AD directory role.',
    remediation: 'Remove guest users from all privileged directory roles immediately. External parties should never hold directory administration rights.',
    tags: ['entra', 'guest', 'privileged-roles'],
  },
  // Guest hygiene
  {
    checkId: 'entra_guest_user_recent_signin',
    provider: 'azure',
    service: 'entra',
    title: 'Guest Users Have Signed In Recently',
    severity: 'MEDIUM',
    description: 'Checks that guest user accounts have signed in within the last 90 days; stale guest accounts increase the attack surface and may retain unreviewed access.',
    remediation: 'Implement Azure AD Access Reviews for external users. Configure a review cadence of 90 days and automatically remove access for guests who do not respond or re-confirm their need.',
    tags: ['entra', 'guest', 'stale-accounts'],
  },
  {
    checkId: 'entra_guest_user_population_bounded',
    provider: 'azure',
    service: 'entra',
    title: 'Guest User Population Is Bounded',
    severity: 'LOW',
    description: 'Checks that the tenant does not have an excessive number of guest users, since a large guest population increases the risk of forgotten or compromised external accounts.',
    remediation: 'Enable Azure AD Access Reviews for all guests on a quarterly cadence. Consider using Entitlement Management to govern external access with time-bound policies.',
    tags: ['entra', 'guest'],
  },
  // Service principal hygiene
  {
    checkId: 'entra_service_principal_credential_not_expiring',
    provider: 'azure',
    service: 'entra',
    title: 'Service Principal Credentials Are Not Expiring Soon',
    severity: 'HIGH',
    description: 'Checks that service principal credentials (keys or passwords) do not expire within the next 30 days, since expired credentials cause application outages.',
    remediation: 'Rotate service principal credentials before expiry. Use managed identities to eliminate credential rotation entirely where possible.',
    tags: ['entra', 'service-principal', 'credential-expiry'],
  },
  {
    checkId: 'entra_service_principal_credential_not_expired',
    provider: 'azure',
    service: 'entra',
    title: 'Service Principal Credentials Are Not Expired',
    severity: 'MEDIUM',
    description: 'Checks that service principal credentials have not already expired; applications with expired credentials are broken but may still hold role assignments.',
    remediation: 'Investigate each service principal with expired credentials. Remove orphaned app registrations and their role assignments. For active apps, rotate credentials immediately.',
    tags: ['entra', 'service-principal', 'orphaned'],
  },
  {
    checkId: 'entra_service_principal_not_multitenant',
    provider: 'azure',
    service: 'entra',
    title: 'No Unexpected Multi-Tenant Service Principals',
    severity: 'MEDIUM',
    description: 'Checks for service principals registered as multi-tenant applications, which can be consented to and used from any Azure AD tenant, expanding the attack surface.',
    remediation: 'Verify that each multi-tenant app registration is intentional. Change signInAudience to AzureADMyOrg for internal applications.',
    tags: ['entra', 'service-principal', 'multi-tenant'],
  },

  // ── Ported from Prowler (checkId verbatim) ──────────────────────────────
  {
    checkId: 'entra_app_registration_credential_not_expired',
    provider: 'azure',
    service: 'entra',
    title: 'App Registration Credentials Are Not Expired Or Expiring Soon',
    severity: 'HIGH',
    description: 'Checks each app registration\'s password secrets and certificate credentials for expiration; flags credentials that are already expired, expiring within 30 days, or have no expiration date.',
    remediation: 'Rotate app registration credentials before expiration. Set expiration to 6-12 months maximum. Prefer managed identities or federated credentials over secrets. Monitor credential expiry with Azure Monitor alerts or Microsoft Entra workbooks.',
    tags: ['entra', 'app-registration', 'credential-expiry'],
  },
  {
    checkId: 'entra_authentication_methods_policy_strong_auth_enforced',
    provider: 'azure',
    service: 'entra',
    title: 'Strong Authentication Methods Enabled With Registration Enforcement',
    severity: 'HIGH',
    description: 'Checks that the tenant authentication methods policy has the MFA registration campaign enabled and at least one strong, phishing-resistant method (Microsoft Authenticator, FIDO2, or X.509 Certificate) enabled.',
    remediation: 'Enable Microsoft Authenticator and FIDO2 security keys as authentication methods. Activate the MFA registration campaign to prompt users to register. Disable weak methods (SMS, voice) after migration.',
    tags: ['entra', 'mfa', 'authentication-methods'],
  },
  {
    checkId: 'entra_conditional_access_policy_require_mfa_for_admin_portals',
    provider: 'azure',
    service: 'entra',
    title: 'Conditional Access Requires MFA For Microsoft Admin Portals',
    severity: 'MEDIUM',
    description: 'Checks for an enabled Conditional Access policy that targets all users, includes the Microsoft Admin Portals app, and enforces an MFA grant control.',
    remediation: 'Create a Conditional Access policy that requires MFA for the Microsoft Admin Portals app targeting all users, excluding only break-glass accounts. Test in report-only mode before enforcing.',
    tags: ['entra', 'mfa', 'conditional-access', 'admin-portals'],
  },
  {
    checkId: 'entra_conditional_access_policy_require_mfa_for_management_api',
    provider: 'azure',
    service: 'entra',
    title: 'Conditional Access Requires MFA For Azure Service Management API',
    severity: 'MEDIUM',
    description: 'Checks for an enabled Conditional Access policy that targets all users, includes the Windows Azure Service Management API app (Azure CLI, PowerShell, ARM), and enforces an MFA grant control.',
    remediation: 'Create a Conditional Access policy that requires MFA for the Windows Azure Service Management API targeting all users, excluding only break-glass accounts. Test in report-only mode before enforcing.',
    tags: ['entra', 'mfa', 'conditional-access', 'management-api'],
  },
  {
    checkId: 'entra_global_admin_in_less_than_five_users',
    provider: 'azure',
    service: 'entra',
    title: 'Global Administrator Role Has Fewer Than Five Members',
    severity: 'HIGH',
    description: 'Checks that the number of principals assigned the Global Administrator directory role is fewer than five, limiting the tenant-wide privileged attack surface.',
    remediation: 'Limit the Global Administrator role to fewer than 5 users. Apply least privilege, use PIM for just-in-time access, enforce MFA and dedicated admin accounts, and run access reviews regularly.',
    tags: ['entra', 'global-admin', 'privileged-roles'],
  },
  {
    checkId: 'entra_non_privileged_user_has_mfa',
    provider: 'azure',
    service: 'entra',
    title: 'Non-Privileged User Has Multi-Factor Authentication Enabled',
    severity: 'MEDIUM',
    description: 'Checks that enabled, non-privileged Entra ID users have two or more registered authentication methods (MFA enrollment).',
    remediation: 'Enforce MFA for all users, including non-privileged. Prefer phishing-resistant methods (FIDO2/passkeys or Authenticator with number matching); avoid SMS/voice when possible.',
    tags: ['entra', 'mfa', 'user'],
  },
  {
    checkId: 'entra_policy_default_users_cannot_create_security_groups',
    provider: 'azure',
    service: 'entra',
    title: 'Authorization Policy Disallows Non-Admin Security Group Creation',
    severity: 'MEDIUM',
    description: 'Checks that the authorization policy\'s allowedToCreateSecurityGroups setting restricts security group creation to administrators.',
    remediation: 'Restrict creation to administrators or a narrowly delegated role. Set allowed_to_create_security_groups to false and use a request/approval process for new groups.',
    tags: ['entra', 'authorization-policy', 'groups'],
  },
  {
    checkId: 'entra_policy_ensure_default_user_cannot_create_apps',
    provider: 'azure',
    service: 'entra',
    title: 'Tenant Disallows Non-Admin Application Registration',
    severity: 'HIGH',
    description: 'Checks that the authorization policy\'s allowedToCreateApps setting restricts application registration to administrators or explicitly delegated roles.',
    remediation: 'Apply least privilege: restrict app registration to admins or delegated roles; set "Users can register applications" to No. Require admin consent workflows and routinely review app permissions.',
    tags: ['entra', 'authorization-policy', 'app-registration'],
  },
  {
    checkId: 'entra_policy_ensure_default_user_cannot_create_tenants',
    provider: 'azure',
    service: 'entra',
    title: 'Authorization Policy Restricts Non-Admin Tenant Creation',
    severity: 'MEDIUM',
    description: 'Checks that the authorization policy\'s allowedToCreateTenants setting restricts tenant creation to administrators, preventing shadow-IT tenant sprawl.',
    remediation: 'Set allowed_to_create_tenants to false so only vetted admins or a PIM-managed Tenant Creator role can create tenants. Enforce separation of duties and monitor audits.',
    tags: ['entra', 'authorization-policy', 'tenant-creation'],
  },
  {
    checkId: 'entra_policy_guest_invite_only_for_admin_roles',
    provider: 'azure',
    service: 'entra',
    title: 'Guest Invitations Restricted To Admin Roles',
    severity: 'HIGH',
    description: 'Checks that the authorization policy\'s guest invite setting is restricted to specific admin roles (adminsAndGuestInviters) or disabled entirely (none).',
    remediation: 'Restrict invitations to "Only users assigned to specific admin roles can invite guest users", or disable them where not needed. Apply least privilege and run periodic access reviews.',
    tags: ['entra', 'authorization-policy', 'guest'],
  },
  {
    checkId: 'entra_policy_guest_users_access_restrictions',
    provider: 'azure',
    service: 'entra',
    title: 'Guest User Access Restricted To Own Directory Object',
    severity: 'MEDIUM',
    description: 'Checks that the authorization policy\'s guest user role restricts guests to viewing only the properties and memberships of their own directory objects, rather than broader directory visibility.',
    remediation: 'Set guest access to "Restricted access" so guests can only view their own directory objects. Avoid assigning admin roles to guests and run periodic access reviews.',
    tags: ['entra', 'authorization-policy', 'guest'],
  },
  {
    checkId: 'entra_policy_restricts_user_consent_for_apps',
    provider: 'azure',
    service: 'entra',
    title: 'User Consent For Applications Is Restricted',
    severity: 'HIGH',
    description: 'Checks that the default user role\'s permission grant policies do not include ManagePermissionGrantsForSelf, meaning end users cannot self-consent to applications accessing organizational data.',
    remediation: 'Enforce least privilege by setting user consent to "Do not allow user consent". Use the admin consent workflow to review and pre-approve only vetted apps.',
    tags: ['entra', 'authorization-policy', 'consent'],
  },
  {
    checkId: 'entra_policy_user_consent_for_verified_apps',
    provider: 'azure',
    service: 'entra',
    title: 'User Consent Restricted To Verified Publishers',
    severity: 'HIGH',
    description: 'Checks that the default user role\'s permission grant policies do not include the legacy self-consent policy (microsoft-user-default-legacy), meaning consent is limited to verified publishers or low-impact scopes.',
    remediation: 'Remove microsoft-user-default-legacy from the default user role\'s permission grant policies. Allow consent only for verified publishers and low-impact permissions.',
    tags: ['entra', 'authorization-policy', 'consent'],
  },
  {
    checkId: 'entra_privileged_user_has_mfa',
    provider: 'azure',
    service: 'entra',
    title: 'Privileged User Has Multi-Factor Authentication Enabled',
    severity: 'HIGH',
    description: 'Checks that every user assigned to a privileged directory role has multiple authentication methods registered (MFA capable).',
    remediation: 'Enforce MFA for all privileged roles via Conditional Access or security defaults. Prefer phishing-resistant methods (FIDO2, passkeys) and protect break-glass accounts.',
    tags: ['entra', 'mfa', 'privileged-roles'],
  },
  {
    checkId: 'entra_security_defaults_enabled',
    provider: 'azure',
    service: 'entra',
    title: 'Security Defaults Are Enabled',
    severity: 'CRITICAL',
    description: 'Checks that Microsoft Entra Security Defaults (tenant-wide baseline MFA, legacy auth blocking, and privileged access protections) are enabled.',
    remediation: 'Activate Security defaults or implement equivalent Conditional Access as defense in depth: require MFA for all identities, block legacy authentication, and safeguard admin portals and APIs.',
    tags: ['entra', 'security-defaults'],
  },
  {
    checkId: 'entra_trusted_named_locations_exists',
    provider: 'azure',
    service: 'entra',
    title: 'Trusted Named Location With IP Ranges Exists',
    severity: 'LOW',
    description: 'Checks that at least one Conditional Access named location is marked trusted and has IP CIDR ranges defined, allowing policies to distinguish corporate networks from unknown sources.',
    remediation: 'Define named locations for your organization\'s egress IP ranges and mark them as trusted. Keep ranges accurate and narrow, and use them in Conditional Access policies.',
    tags: ['entra', 'conditional-access', 'named-locations'],
  },
  {
    checkId: 'entra_user_with_recent_sign_in',
    provider: 'azure',
    service: 'entra',
    title: 'Enabled User Has Signed In Within The Last 90 Days',
    severity: 'MEDIUM',
    description: 'Checks that enabled user accounts have an interactive sign-in within the last 90 days, flagging stale or dormant identities that should be reviewed or deprovisioned.',
    remediation: 'Implement automated Azure AD access reviews to periodically review and remove stale accounts. Disable accounts inactive for more than 90 days after confirming with managers.',
    tags: ['entra', 'user', 'stale-accounts'],
  },
  {
    checkId: 'entra_user_with_vm_access_has_mfa',
    provider: 'azure',
    service: 'entra',
    title: 'User With VM Access Has Multi-Factor Authentication Enabled',
    severity: 'HIGH',
    description: 'Checks that Entra users holding Azure roles granting VM sign-in or management access (Owner, Contributor, Virtual Machine Administrator/User Login, Virtual Machine Contributor, Windows Admin Center Administrator Login) have MFA enrolled.',
    remediation: 'Enforce MFA for all identities that can sign in to or manage VMs via Conditional Access. Apply least privilege by removing broad roles when not required, and use PIM/JIT for admin access.',
    tags: ['entra', 'mfa', 'vm-access'],
  },
  {
    checkId: 'entra_users_cannot_create_microsoft_365_groups',
    provider: 'azure',
    service: 'entra',
    title: 'Microsoft 365 Group Creation By Users Is Disabled',
    severity: 'MEDIUM',
    description: 'Checks the Group.Unified directory setting\'s EnableGroupCreation value to determine whether Microsoft 365 group creation is broadly allowed to end users.',
    remediation: 'Set EnableGroupCreation to false and allow only a controlled group via GroupCreationAllowedGroupId. Apply governed provisioning with naming policies and owner reviews.',
    tags: ['entra', 'authorization-policy', 'groups'],
  },
];
