// Check logic derived from Prowler (Apache-2.0, https://github.com/prowler-cloud/prowler)
import { CheckMetadata } from '../../types';

export const functionsChecks: CheckMetadata[] = [
  // ── Pre-existing checks (migrated from this.finding() to this.emit()) ──
  // No direct Prowler equivalent existed for these prior to Tranche 2, so
  // checkIds are invented in the `azure_functions_*` namespace.
  {
    checkId: 'azure_functions_https_only_enforced',
    provider: 'azure',
    service: 'functions',
    title: 'Function App Enforces HTTPS-Only Traffic',
    severity: 'HIGH',
    description: 'Checks that the Function App enforces HTTPS-only access, so invocation URLs, auth tokens, and response data are not transmitted in plaintext.',
    remediation: 'Enable httpsOnly on the Function App to redirect all HTTP requests to HTTPS.',
    tags: ['functions', 'encryption-in-transit'],
  },
  {
    checkId: 'azure_functions_minimum_tls_version_12',
    provider: 'azure',
    service: 'functions',
    title: 'Function App Enforces Minimum TLS Version 1.2',
    severity: 'HIGH',
    description: 'Checks that the Function App minimum TLS version is set to 1.2. TLS 1.0/1.1 are deprecated and vulnerable to downgrade attacks.',
    remediation: 'Set minTlsVersion to "1.2" in the Function App site configuration.',
    tags: ['functions', 'tls'],
  },
  {
    checkId: 'azure_functions_no_anonymous_http_triggers',
    provider: 'azure',
    service: 'functions',
    title: 'Function App Has No Anonymous HTTP Triggers',
    severity: 'HIGH',
    description: 'Checks that the Function App has no HTTP-triggered functions with authLevel set to "anonymous", which would allow any internet user to invoke them without authentication.',
    remediation: 'Set authLevel to "function" or "admin" on HTTP triggers, or use Entra ID authentication via APIM or an Azure AD App Registration.',
    tags: ['functions', 'authentication'],
  },
  {
    checkId: 'azure_functions_managed_identity_configured',
    provider: 'azure',
    service: 'functions',
    title: 'Function App Uses a Managed Identity',
    severity: 'MEDIUM',
    description: 'Checks that the Function App has a system- or user-assigned managed identity, avoiding credentials stored in application settings or connection strings.',
    remediation: 'Enable system-assigned managed identity on the Function App and update service connections to use Entra ID authentication.',
    tags: ['functions', 'identity'],
  },
  {
    checkId: 'azure_functions_cors_not_wildcard',
    provider: 'azure',
    service: 'functions',
    title: 'Function App CORS Does Not Allow All Origins',
    severity: 'MEDIUM',
    description: 'Checks that the Function App CORS configuration does not allow the wildcard origin (*), which would enable cross-site request forgery from any website.',
    remediation: 'Replace the wildcard (*) CORS origin with specific trusted domains. Remove origins that are no longer in use.',
    tags: ['functions', 'cors'],
  },
  {
    checkId: 'azure_functions_vnet_integration_enabled',
    provider: 'azure',
    service: 'functions',
    title: 'Function App Is Integrated With a Virtual Network',
    severity: 'LOW',
    description: 'Checks that the Function App has VNet integration configured, so outbound traffic can be routed through a private subnet instead of the public internet.',
    remediation: 'Configure VNet integration to route Function App outbound traffic through a private subnet.',
    tags: ['functions', 'network'],
  },
  {
    checkId: 'azure_functions_runtime_not_eol',
    provider: 'azure',
    service: 'functions',
    title: 'Function App Does Not Use an End-of-Life Runtime',
    severity: 'HIGH',
    description: 'Checks that the Function App language runtime version is not end-of-life. EOL runtimes no longer receive security patches.',
    remediation: 'Update the Function App to a supported runtime version. Test in a staging slot before swapping to production.',
    tags: ['functions', 'eol-version'],
  },
  {
    checkId: 'azure_functions_remote_debugging_disabled',
    provider: 'azure',
    service: 'functions',
    title: 'Function App Has Remote Debugging Disabled',
    severity: 'HIGH',
    description: 'Checks that remote debugging is disabled on the Function App. Remote debugging opens an additional port and allows code inspection from external tools.',
    remediation: 'Disable remote debugging on all production Function Apps. Use Application Insights for tracing instead.',
    tags: ['functions', 'debugging'],
  },
  {
    checkId: 'azure_functions_diagnostic_logs_configured',
    provider: 'azure',
    service: 'functions',
    title: 'Function App Has Diagnostic Logs Configured',
    severity: 'MEDIUM',
    description: 'Checks that the Function App has a diagnostic setting streaming logs to a destination such as Log Analytics, so execution errors and auth failures can be audited.',
    remediation: 'Enable diagnostic settings to stream FunctionAppLogs to a Log Analytics workspace.',
    tags: ['functions', 'logging'],
  },

  // ── Newly ported Prowler checks (Tranche 2) ──
  {
    checkId: 'app_function_access_keys_configured',
    provider: 'azure',
    service: 'functions',
    title: 'Function App Has Function Access Keys Configured',
    severity: 'HIGH',
    description: 'Checks that HTTP-triggered functions in the Function App have at least one function-level access key configured, rather than relying solely on the trigger authLevel.',
    remediation: 'Configure function-level access keys for HTTP-triggered functions and rotate them periodically. Distribute keys only to authorized callers.',
    tags: ['functions', 'authentication'],
  },
  {
    checkId: 'app_function_application_insights_enabled',
    provider: 'azure',
    service: 'functions',
    title: 'Function App Has Application Insights Configured',
    severity: 'MEDIUM',
    description: 'Checks that the Function App sends telemetry to Application Insights via the APPLICATIONINSIGHTS_CONNECTION_STRING or APPINSIGHTS_INSTRUMENTATIONKEY application setting.',
    remediation: 'Configure Application Insights for the Function App to capture execution telemetry, failures, and performance data.',
    tags: ['functions', 'logging', 'monitoring'],
  },
  {
    checkId: 'app_function_not_publicly_accessible',
    provider: 'azure',
    service: 'functions',
    title: 'Function App Is Not Publicly Accessible',
    severity: 'HIGH',
    description: 'Checks that the Function App publicNetworkAccess is not enabled, so the app is not reachable from the public internet without access restrictions or private endpoints.',
    remediation: 'Disable public network access on the Function App and use access restrictions or Private Endpoint for connectivity, or apply IP-based access restriction rules.',
    tags: ['functions', 'network', 'public-access'],
  },
  {
    checkId: 'app_function_ftps_deployment_disabled',
    provider: 'azure',
    service: 'functions',
    title: 'Function App Has FTP and FTPS Deployment Disabled',
    severity: 'MEDIUM',
    description: 'Checks that the Function App ftpsState is set to "Disabled", so deployment cannot occur over FTP or FTPS.',
    remediation: 'Set the Function App FTP state to "Disabled". Use source control or CI/CD-based deployment instead of FTP(S).',
    tags: ['functions', 'ftp'],
  },
];
