// Check logic derived from Prowler (Apache-2.0, https://github.com/prowler-cloud/prowler)
import { CheckMetadata } from '../../types';

export const keyvaultChecks: CheckMetadata[] = [
  {
    checkId: 'azure_keyvault_soft_delete_enabled',
    provider: 'azure',
    service: 'keyvault',
    title: 'Key Vault Soft Delete Is Enabled',
    severity: 'HIGH',
    description: 'Checks that Key Vault soft delete is enabled so that deleted secrets, keys, and certificates can be recovered within the retention window.',
    remediation: 'Enable soft delete with a retention of at least 7 days. Once enabled, soft delete cannot be disabled.',
    tags: ['keyvault', 'data-protection'],
  },
  {
    checkId: 'keyvault_recoverable',
    provider: 'azure',
    service: 'keyvault',
    title: 'Key Vault Has Soft Delete and Purge Protection Enabled',
    severity: 'HIGH',
    description: 'Checks that Key Vault has both soft delete and purge protection enabled, so vaulted objects cannot be permanently deleted before their retention period expires, even by a privileged user.',
    remediation: 'Enable both soft delete (minimum 7-day retention) and purge protection. This ensures deleted vault objects cannot be permanently removed until the retention period expires.',
    tags: ['keyvault', 'data-protection'],
  },
  {
    checkId: 'azure_keyvault_network_access_restricted',
    provider: 'azure',
    service: 'keyvault',
    title: 'Key Vault Network ACL Restricts Public Access',
    severity: 'HIGH',
    description: 'Checks that Key Vault network ACL default action is "Deny" rather than "Allow", so it is not reachable from any IP address on the internet by default.',
    remediation: 'Set the network ACL default action to "Deny" and whitelist only known IP ranges or virtual networks. Consider using Private Endpoint.',
    tags: ['keyvault', 'network'],
  },
  {
    checkId: 'keyvault_rbac_enabled',
    provider: 'azure',
    service: 'keyvault',
    title: 'Key Vault Uses Azure RBAC for Access Control',
    severity: 'HIGH',
    description: 'Checks that Key Vault uses the Azure RBAC permission model instead of legacy vault access policies. Access policies cannot be audited or scoped with the same granularity as RBAC role assignments.',
    remediation: 'Migrate Key Vault to Azure RBAC permission model for fine-grained, auditable access control.',
    tags: ['keyvault', 'rbac'],
  },
  {
    checkId: 'keyvault_logging_enabled',
    provider: 'azure',
    service: 'keyvault',
    title: 'Key Vault Has at Least One Diagnostic Setting With Audit Logging Enabled',
    severity: 'HIGH',
    description: 'Checks that Key Vault has a diagnostic setting configured with AuditEvent logging (or the audit/allLogs category group) enabled, so all access to secrets, keys, and certificates is recorded.',
    remediation: 'Enable diagnostic settings for the Key Vault with the AuditEvent log category (or audit/allLogs category groups) enabled, and send logs to a Log Analytics workspace with a minimum 90-day retention.',
    tags: ['keyvault', 'logging'],
  },
  {
    checkId: 'keyvault_private_endpoints',
    provider: 'azure',
    service: 'keyvault',
    title: 'Key Vault Uses Private Endpoints',
    severity: 'HIGH',
    description: 'Checks that Key Vault has at least one Private Endpoint connection configured, allowing access from within a virtual network without traversing the public internet.',
    remediation: 'Create a Private Endpoint for the Key Vault in the relevant virtual network(s) and update DNS to resolve the vault to its private IP.',
    tags: ['keyvault', 'network', 'private-endpoint'],
  },
  {
    checkId: 'keyvault_access_only_through_private_endpoints',
    provider: 'azure',
    service: 'keyvault',
    title: 'Key Vault Using Private Endpoints Has Public Network Access Disabled',
    severity: 'HIGH',
    description: 'Checks that, for Key Vaults with a Private Endpoint configured, public network access is disabled so the vault is not reachable over the public internet at all.',
    remediation: 'For any Key Vault with a Private Endpoint, set public network access to disabled so all access is forced through the private endpoint.',
    tags: ['keyvault', 'network', 'private-endpoint'],
  },
  {
    checkId: 'keyvault_key_rotation_enabled',
    provider: 'azure',
    service: 'keyvault',
    title: 'Key Vault Key Has Automatic Rotation Enabled',
    severity: 'HIGH',
    description: 'Checks that each Key Vault key has a rotation policy configured with a "Rotate" lifetime action, ensuring keys are rotated automatically rather than relying on manual processes.',
    remediation: 'Configure a key rotation policy with a "Rotate" lifetime action for every key vault key. Set an appropriate rotation interval (e.g. every 12 months, or shorter for sensitive workloads).',
    tags: ['keyvault', 'key-management', 'rotation'],
  },
  {
    checkId: 'azure_keyvault_key_expiration_set',
    provider: 'azure',
    service: 'keyvault',
    title: 'Key Vault Key Has an Expiration Date Set',
    severity: 'MEDIUM',
    description: 'Checks that enabled Key Vault keys have an expiration date set, whether the vault uses the legacy access-policy model or Azure RBAC. Keys without an expiration date remain valid indefinitely.',
    remediation: 'Set an expiration date on every enabled key vault key, and establish a process to rotate or renew keys before they expire.',
    tags: ['keyvault', 'key-management'],
  },
  {
    checkId: 'azure_keyvault_secret_expiration_set',
    provider: 'azure',
    service: 'keyvault',
    title: 'Key Vault Secret Has an Expiration Date Set',
    severity: 'MEDIUM',
    description: 'Checks that enabled Key Vault secrets have an expiration date set, whether the vault uses the legacy access-policy model or Azure RBAC. Secrets without an expiration date remain valid indefinitely.',
    remediation: 'Set an expiration date on every enabled key vault secret, and establish a process to rotate secrets before they expire.',
    tags: ['keyvault', 'secrets-management'],
  },
];
