// Check logic derived from Prowler (Apache-2.0, https://github.com/prowler-cloud/prowler)
import { CheckMetadata } from '../../types';

export const monitorChecks: CheckMetadata[] = [
  {
    checkId: 'monitor_alert_create_policy_assignment',
    provider: 'azure',
    service: 'monitor',
    title: 'Activity Log Alert Exists For Policy Assignment Creation',
    severity: 'MEDIUM',
    description: 'Checks that an enabled Azure Monitor Activity Log alert exists at subscription scope for the "Microsoft.Authorization/policyAssignments/write" operation, so new or modified Azure Policy assignments are detected.',
    remediation: 'Create a subscription-scoped Activity Log alert rule with condition operationName = Microsoft.Authorization/policyAssignments/write, enable it, and route notifications to an action group.',
    tags: ['monitor', 'activity-log-alert', 'policy', 'logging'],
  },
  {
    checkId: 'monitor_alert_create_update_nsg',
    provider: 'azure',
    service: 'monitor',
    title: 'Activity Log Alert Exists For NSG Create Or Update',
    severity: 'HIGH',
    description: 'Checks that an enabled Azure Monitor Activity Log alert exists at subscription scope for the "Microsoft.Network/networkSecurityGroups/write" operation, so Network Security Group create/update events are detected.',
    remediation: 'Create a subscription-scoped Activity Log alert rule with condition operationName = Microsoft.Network/networkSecurityGroups/write, enable it, and route notifications to an action group.',
    tags: ['monitor', 'activity-log-alert', 'nsg', 'network', 'logging'],
  },
  {
    checkId: 'monitor_alert_create_update_public_ip_address_rule',
    provider: 'azure',
    service: 'monitor',
    title: 'Activity Log Alert Exists For Public IP Create Or Update',
    severity: 'MEDIUM',
    description: 'Checks that an enabled Azure Monitor Activity Log alert exists at subscription scope for the "Microsoft.Network/publicIPAddresses/write" operation, so creation or modification of public IP resources is detected.',
    remediation: 'Create a subscription-scoped Activity Log alert rule with condition operationName = Microsoft.Network/publicIPAddresses/write, enable it, and route notifications to an action group.',
    tags: ['monitor', 'activity-log-alert', 'public-ip', 'network', 'logging'],
  },
  {
    checkId: 'monitor_alert_create_update_security_solution',
    provider: 'azure',
    service: 'monitor',
    title: 'Activity Log Alert Exists For Security Solution Create Or Update',
    severity: 'MEDIUM',
    description: 'Checks that an enabled Azure Monitor Activity Log alert exists at subscription scope for the "Microsoft.Security/securitySolutions/write" operation, so changes to connected security solutions are detected.',
    remediation: 'Create a subscription-scoped Activity Log alert rule with condition operationName = Microsoft.Security/securitySolutions/write, enable it, and route notifications to an action group.',
    tags: ['monitor', 'activity-log-alert', 'security-solution', 'logging'],
  },
  {
    checkId: 'monitor_alert_create_update_sqlserver_fr',
    provider: 'azure',
    service: 'monitor',
    title: 'Activity Log Alert Exists For SQL Server Firewall Rule Create Or Update',
    severity: 'MEDIUM',
    description: 'Checks that an enabled Azure Monitor Activity Log alert exists at subscription scope for the "Microsoft.Sql/servers/firewallRules/write" operation, so SQL Server firewall rule creation or modification is detected.',
    remediation: 'Create a subscription-scoped Activity Log alert rule with condition operationName = Microsoft.Sql/servers/firewallRules/write, enable it, and route notifications to an action group.',
    tags: ['monitor', 'activity-log-alert', 'sql', 'logging'],
  },
  {
    checkId: 'monitor_alert_delete_nsg',
    provider: 'azure',
    service: 'monitor',
    title: 'Activity Log Alert Exists For NSG Deletion',
    severity: 'HIGH',
    description: 'Checks that an enabled Azure Monitor Activity Log alert exists at subscription scope for the "Microsoft.Network/networkSecurityGroups/delete" (or classic equivalent) operation, so Network Security Group deletions are detected.',
    remediation: 'Create a subscription-scoped Activity Log alert rule with condition operationName = Microsoft.Network/networkSecurityGroups/delete, enable it, and route notifications to an action group.',
    tags: ['monitor', 'activity-log-alert', 'nsg', 'network', 'logging'],
  },
  {
    checkId: 'monitor_alert_delete_policy_assignment',
    provider: 'azure',
    service: 'monitor',
    title: 'Activity Log Alert Exists For Policy Assignment Deletion',
    severity: 'HIGH',
    description: 'Checks that an enabled Azure Monitor Activity Log alert exists at subscription scope for the "Microsoft.Authorization/policyAssignments/delete" operation, so removal of Azure Policy assignments is detected.',
    remediation: 'Create a subscription-scoped Activity Log alert rule with condition operationName = Microsoft.Authorization/policyAssignments/delete, enable it, and route notifications to an action group.',
    tags: ['monitor', 'activity-log-alert', 'policy', 'logging'],
  },
  {
    checkId: 'monitor_alert_delete_public_ip_address_rule',
    provider: 'azure',
    service: 'monitor',
    title: 'Activity Log Alert Exists For Public IP Deletion',
    severity: 'MEDIUM',
    description: 'Checks that an enabled Azure Monitor Activity Log alert exists at subscription scope for the "Microsoft.Network/publicIPAddresses/delete" operation, so removal of public IP resources is detected.',
    remediation: 'Create a subscription-scoped Activity Log alert rule with condition operationName = Microsoft.Network/publicIPAddresses/delete, enable it, and route notifications to an action group.',
    tags: ['monitor', 'activity-log-alert', 'public-ip', 'network', 'logging'],
  },
  {
    checkId: 'monitor_alert_delete_security_solution',
    provider: 'azure',
    service: 'monitor',
    title: 'Activity Log Alert Exists For Security Solution Deletion',
    severity: 'MEDIUM',
    description: 'Checks that an enabled Azure Monitor Activity Log alert exists at subscription scope for the "Microsoft.Security/securitySolutions/delete" operation, so removal of connected security solutions is detected.',
    remediation: 'Create a subscription-scoped Activity Log alert rule with condition operationName = Microsoft.Security/securitySolutions/delete, enable it, and route notifications to an action group.',
    tags: ['monitor', 'activity-log-alert', 'security-solution', 'logging'],
  },
  {
    checkId: 'monitor_alert_delete_sqlserver_fr',
    provider: 'azure',
    service: 'monitor',
    title: 'Activity Log Alert Exists For SQL Server Firewall Rule Deletion',
    severity: 'MEDIUM',
    description: 'Checks that an enabled Azure Monitor Activity Log alert exists at subscription scope for the "Microsoft.Sql/servers/firewallRules/delete" operation, so removal of SQL Server firewall rules is detected.',
    remediation: 'Create a subscription-scoped Activity Log alert rule with condition operationName = Microsoft.Sql/servers/firewallRules/delete, enable it, and route notifications to an action group.',
    tags: ['monitor', 'activity-log-alert', 'sql', 'logging'],
  },
  {
    checkId: 'monitor_alert_service_health_exists',
    provider: 'azure',
    service: 'monitor',
    title: 'Activity Log Alert Exists For Service Health Incidents',
    severity: 'MEDIUM',
    description: 'Checks that an enabled Azure Monitor Activity Log alert exists at subscription scope with category "ServiceHealth" and incidentType "Incident", so Azure service outages and degradations are surfaced to the team.',
    remediation: 'Create a Service Health alert (Service Health > Health alerts) scoped to the subscription, filtered to Service issues (Incidents), and ensure the rule is enabled.',
    tags: ['monitor', 'activity-log-alert', 'service-health', 'resilience'],
  },
  {
    checkId: 'monitor_diagnostic_setting_with_appropriate_categories',
    provider: 'azure',
    service: 'monitor',
    title: 'Diagnostic Setting Captures Administrative, Security, Alert, And Policy Categories',
    severity: 'HIGH',
    description: 'Checks that at least one subscription-level Activity Log diagnostic setting captures all four control-plane log categories: Administrative, Security, Alert, and Policy.',
    remediation: 'Edit or create a subscription Activity Log diagnostic setting and enable the Administrative, Security, Alert, and Policy log categories, routed to a centralized destination.',
    tags: ['monitor', 'diagnostic-settings', 'logging'],
  },
  {
    checkId: 'monitor_diagnostic_settings_exists',
    provider: 'azure',
    service: 'monitor',
    title: 'Activity Log Diagnostic Setting Exists',
    severity: 'HIGH',
    description: 'Checks that the subscription Activity Log has at least one diagnostic setting configured to export events to a Log Analytics workspace, Storage account, Event Hub, or partner destination.',
    remediation: 'Create a subscription Activity Log diagnostic setting and route it to a Log Analytics workspace (or equivalent) so control-plane events are centralized and retained.',
    tags: ['monitor', 'diagnostic-settings', 'logging'],
  },
  {
    checkId: 'monitor_storage_account_with_activity_logs_cmk_encrypted',
    provider: 'azure',
    service: 'monitor',
    title: 'Storage Account Holding Activity Logs Is Encrypted With A Customer-Managed Key',
    severity: 'MEDIUM',
    description: 'For every storage account referenced by an Activity Log diagnostic setting, checks that the account uses a customer-managed key (Microsoft.Keyvault) rather than a Microsoft-managed key for encryption at rest.',
    remediation: 'Assign a system-assigned identity to the storage account, grant it key permissions in Key Vault, and switch the account encryption key source to Microsoft.Keyvault (customer-managed key).',
    tags: ['monitor', 'storage', 'cmk', 'encryption'],
  },
  {
    checkId: 'monitor_storage_account_with_activity_logs_is_private',
    provider: 'azure',
    service: 'monitor',
    title: 'Storage Account Holding Activity Logs Blocks Public Blob Access',
    severity: 'HIGH',
    description: 'For every storage account referenced by an Activity Log diagnostic setting, checks that public blob access (allowBlobPublicAccess) is disabled so exported audit log data is not exposed to anonymous internet access.',
    remediation: 'Set allowBlobPublicAccess=false on any storage account that receives exported Activity Logs, and access the logs only via authenticated RBAC or scoped SAS tokens.',
    tags: ['monitor', 'storage', 'public-access', 'internet-exposed', 'logging'],
  },
];
