// Check logic derived from Prowler (Apache-2.0, https://github.com/prowler-cloud/prowler)
import { CheckMetadata } from '../../types';

export const networkChecks: CheckMetadata[] = [
  {
    checkId: 'azure_network_firewall_deployed',
    provider: 'azure',
    service: 'network',
    title: 'Azure Firewall Deployed in Subscription',
    severity: 'HIGH',
    description: 'Checks that at least one Azure Firewall instance is deployed in the subscription to provide centralised, layer-7 traffic inspection for east-west and north-south traffic.',
    remediation: 'Deploy Azure Firewall (Standard or Premium) in a hub VNet and route all spoke traffic through it. Use Firewall Policy to manage rules centrally. Azure Firewall Premium provides IDPS and TLS inspection.',
    tags: ['network', 'firewall'],
  },
  {
    checkId: 'azure_network_firewall_allocated',
    provider: 'azure',
    service: 'network',
    title: 'Azure Firewall Is Allocated and Inspecting Traffic',
    severity: 'HIGH',
    description: 'Checks that deployed Azure Firewall instances have an active public IP configuration and are not deallocated, so traffic is actually being inspected.',
    remediation: 'Allocate the Azure Firewall by assigning a public IP configuration. Use automation (Azure Policy, schedules) to prevent accidental deallocation.',
    tags: ['network', 'firewall'],
  },
  {
    checkId: 'azure_network_firewall_standard_or_premium_sku',
    provider: 'azure',
    service: 'network',
    title: 'Azure Firewall Uses Standard or Premium SKU',
    severity: 'MEDIUM',
    description: 'Checks that Azure Firewall instances use the Standard or Premium SKU rather than Basic, which lacks threat intelligence filtering, IDPS, and full policy support.',
    remediation: 'Upgrade to Azure Firewall Standard or Premium. Premium tier adds IDPS, TLS inspection, and URL/web category filtering.',
    tags: ['network', 'firewall'],
  },
  {
    checkId: 'azure_network_route_table_no_direct_internet_default_route',
    provider: 'azure',
    service: 'network',
    title: 'Route Table Does Not Send Default Traffic Directly to Internet',
    severity: 'HIGH',
    description: 'Checks that route tables do not have a 0.0.0.0/0 route with nextHopType "Internet", which would bypass Azure Firewall or NVA inspection for all unmatched egress traffic.',
    remediation: 'Change the 0.0.0.0/0 route nextHopType to "VirtualAppliance" and set the nextHopIpAddress to your Azure Firewall or NVA private IP to force-tunnel all egress traffic through inspection.',
    tags: ['network', 'routing', 'firewall-bypass'],
  },
  {
    checkId: 'azure_network_route_table_associated',
    provider: 'azure',
    service: 'network',
    title: 'Route Table Is Associated With a Subnet',
    severity: 'LOW',
    description: 'Checks that route tables are associated with at least one subnet; unassociated route tables provide no traffic control and may be orphaned resources.',
    remediation: 'Associate the route table with the appropriate subnets or delete it if no longer needed.',
    tags: ['network', 'routing'],
  },
  {
    checkId: 'network_subnet_nsg_associated',
    provider: 'azure',
    service: 'network',
    title: 'Subnet Has a Network Security Group Associated',
    severity: 'HIGH',
    description: 'Checks that every subnet (excluding Azure-managed subnets such as GatewaySubnet, AzureFirewallSubnet, AzureFirewallManagementSubnet, AzureBastionSubnet, RouteServerSubnet) has a Network Security Group associated to enforce inbound and outbound traffic filtering.',
    remediation: 'Attach an NSG to every subnet (except GatewaySubnet, AzureFirewallSubnet, AzureFirewallManagementSubnet, AzureBastionSubnet, RouteServerSubnet). Apply a deny-all default rule with explicit allow rules for required traffic.',
    tags: ['network', 'nsg', 'subnet'],
  },
  {
    checkId: 'network_vnet_ddos_protection_enabled',
    provider: 'azure',
    service: 'network',
    title: 'Virtual Network Has Azure DDoS Network Protection Enabled',
    severity: 'MEDIUM',
    description: 'Checks that virtual networks have an Azure DDoS Protection plan associated, providing always-on traffic monitoring and adaptive mitigation against volumetric, protocol, and application-layer attacks.',
    remediation: 'Enable DDoS Protection Standard on hub VNets hosting internet-facing resources. Link all spoke VNets to the same DDoS plan for cost efficiency.',
    tags: ['network', 'ddos'],
  },
  {
    checkId: 'network_bastion_host_exists',
    provider: 'azure',
    service: 'network',
    title: 'Subscription Has at Least One Bastion Host',
    severity: 'MEDIUM',
    description: 'Checks that the subscription has at least one Azure Bastion host deployed for secure RDP/SSH brokering over TLS on 443/TCP to virtual machines using private IPs, reducing the need to expose management ports directly.',
    remediation: 'Deploy Azure Bastion in the hub or spoke VNet and use it to connect to VMs via RDP/SSH over TLS instead of exposing public IPs or management ports directly.',
    tags: ['network', 'bastion', 'remote-access'],
  },
  {
    checkId: 'network_watcher_enabled',
    provider: 'azure',
    service: 'network',
    title: 'Network Watcher Is Enabled for All Locations in the Subscription',
    severity: 'HIGH',
    description: 'Checks that an Azure Network Watcher instance exists in every subscription location where resources may be deployed, enabling diagnostics, flow logging, and traffic analytics.',
    remediation: 'Enable Network Watcher in every Azure region where the subscription has resources deployed. Network Watcher is typically enabled automatically when a VNet is created but can be verified/enabled manually per region.',
    tags: ['network', 'monitoring', 'network-watcher'],
  },
  {
    checkId: 'network_flow_log_captured_sent',
    provider: 'azure',
    service: 'network',
    title: 'Network Watcher Flow Logs Are Enabled and Sent to Log Analytics',
    severity: 'HIGH',
    description: 'Checks that Network Watcher flow logs are enabled for supported targets (VNets, NSGs) and configured with Traffic Analytics to forward records to a Log Analytics workspace.',
    remediation: 'Enable NSG or VNet flow logs on every Network Watcher and configure Traffic Analytics with a target Log Analytics workspace to capture and analyze network traffic.',
    tags: ['network', 'logging', 'flow-logs'],
  },
  {
    checkId: 'network_flow_log_more_than_90_days',
    provider: 'azure',
    service: 'network',
    title: 'Network Watcher Flow Logs Retention Is at Least 90 Days',
    severity: 'MEDIUM',
    description: 'Checks that Network Watcher flow logs are enabled with a retention policy of at least 90 days (or 0 for unlimited retention), ensuring sufficient history for incident investigation.',
    remediation: 'Set the flow log retention policy to at least 90 days (or 0 for unlimited retention) on every Network Watcher flow log.',
    tags: ['network', 'logging', 'flow-logs'],
  },
];
