// Check logic derived from Prowler (Apache-2.0, https://github.com/prowler-cloud/prowler)
import { CheckMetadata } from '../../types';

export const nsgChecks: CheckMetadata[] = [
  {
    checkId: 'azure_nsg_rule_unrestricted_inbound_all_ports',
    provider: 'azure',
    service: 'nsg',
    title: 'NSG Rule Does Not Allow Unrestricted Inbound Traffic From the Internet',
    severity: 'CRITICAL',
    description: 'Checks that no Network Security Group inbound rule allows all ports and protocols from any source (0.0.0.0/0, *, or "Internet"), which would fully expose associated resources.',
    remediation: 'Remove rules that allow all inbound traffic from any source. Replace with specific source IP ranges and only open required ports.',
    tags: ['nsg', 'network', 'internet-exposure'],
  },
  {
    checkId: 'network_ssh_internet_access_restricted',
    provider: 'azure',
    service: 'nsg',
    title: 'SSH Access From the Internet Is Restricted',
    severity: 'CRITICAL',
    description: 'Checks that no Network Security Group inbound rule allows TCP port 22 (SSH) from any source on the internet.',
    remediation: 'Restrict the source address prefix to specific trusted IP ranges. Use Azure Bastion or Just-In-Time VM access instead of exposing SSH directly to the internet.',
    tags: ['nsg', 'network', 'internet-exposure', 'ssh'],
  },
  {
    checkId: 'network_rdp_internet_access_restricted',
    provider: 'azure',
    service: 'nsg',
    title: 'RDP Access From the Internet Is Restricted',
    severity: 'CRITICAL',
    description: 'Checks that no Network Security Group inbound rule allows TCP port 3389 (RDP) from any source on the internet.',
    remediation: 'Restrict the source address prefix to specific trusted IP ranges. Use Azure Bastion or Just-In-Time VM access instead of exposing RDP directly to the internet.',
    tags: ['nsg', 'network', 'internet-exposure', 'rdp'],
  },
  {
    checkId: 'network_http_internet_access_restricted',
    provider: 'azure',
    service: 'nsg',
    title: 'HTTP Access From the Internet Is Restricted',
    severity: 'HIGH',
    description: 'Checks that no Network Security Group inbound rule allows TCP port 80 (HTTP) from any source on the internet without a corresponding need for public HTTP exposure.',
    remediation: 'Restrict the source address prefix to specific trusted IP ranges, or terminate traffic at a WAF/Application Gateway/Front Door instead of exposing HTTP directly via NSG.',
    tags: ['nsg', 'network', 'internet-exposure', 'http'],
  },
  {
    checkId: 'network_udp_internet_access_restricted',
    provider: 'azure',
    service: 'nsg',
    title: 'UDP Access From the Internet Is Restricted',
    severity: 'HIGH',
    description: 'Checks that no Network Security Group inbound rule allows any UDP traffic from any source on the internet.',
    remediation: 'Restrict UDP inbound rules to specific trusted IP ranges and required ports only. Avoid blanket UDP allow rules from the internet.',
    tags: ['nsg', 'network', 'internet-exposure', 'udp'],
  },
  {
    checkId: 'azure_nsg_rule_sensitive_port_exposed_to_internet',
    provider: 'azure',
    service: 'nsg',
    title: 'NSG Rule Does Not Expose Sensitive Ports to the Internet',
    severity: 'HIGH',
    description: 'Checks that no Network Security Group inbound rule exposes sensitive management or data-plane ports (e.g. 1433, 3306, 5432, 27017, 6379, 5601, 9200, 8080, 443) to any source on the internet.',
    remediation: 'Restrict the source address prefix to specific trusted IP ranges for any rule exposing sensitive ports. Use Private Endpoint or VPN/ExpressRoute for data-plane access instead of public exposure.',
    tags: ['nsg', 'network', 'internet-exposure'],
  },
  {
    checkId: 'azure_nsg_associated',
    provider: 'azure',
    service: 'nsg',
    title: 'Network Security Group Is Associated With a Subnet or NIC',
    severity: 'LOW',
    description: 'Checks that every Network Security Group is associated with at least one subnet or network interface; unassociated NSGs provide no protection and may be orphaned resources.',
    remediation: 'Associate the NSG with the appropriate subnet(s) or NIC(s), or delete it if no longer needed.',
    tags: ['nsg', 'network'],
  },
];
