// Check logic derived from Prowler (Apache-2.0, https://github.com/prowler-cloud/prowler)
import { CheckMetadata } from '../../types';

export const postgresChecks: CheckMetadata[] = [
  {
    checkId: 'azure_postgresql_public_network_access_disabled',
    provider: 'azure',
    service: 'postgres',
    title: 'PostgreSQL Flexible Server Has Public Network Access Disabled',
    severity: 'HIGH',
    description: 'Checks that PostgreSQL Flexible Server public network access is disabled, so the server is not reachable from the public internet.',
    remediation: 'Set network.publicNetworkAccess to "Disabled" and configure private access (VNet integration) to restrict connectivity to trusted networks.',
    tags: ['postgresql', 'network', 'public-access'],
  },
  {
    checkId: 'azure_postgresql_ssl_enforced',
    provider: 'azure',
    service: 'postgres',
    title: 'PostgreSQL Flexible Server Requires SSL Connections',
    severity: 'CRITICAL',
    description: 'Checks that the require_secure_transport server parameter is set to "on", ensuring all client connections use SSL/TLS in transit.',
    remediation: 'Set the require_secure_transport server parameter to "on". Update all application connection strings to use SSL mode "require" or higher.',
    tags: ['postgresql', 'encryption-in-transit', 'ssl'],
  },
  {
    checkId: 'azure_postgresql_firewall_no_open_range',
    provider: 'azure',
    service: 'postgres',
    title: 'PostgreSQL Flexible Server Firewall Does Not Allow All IP Addresses',
    severity: 'CRITICAL',
    description: 'Checks that no PostgreSQL Flexible Server firewall rule permits the full 0.0.0.0–255.255.255.255 range or otherwise starts from 0.0.0.0, which would allow any internet host to attempt a connection.',
    remediation: 'Remove open-range firewall rules. Restrict access to specific application server IPs or use private access (VNet integration) instead.',
    tags: ['postgresql', 'firewall', 'network'],
  },
  {
    checkId: 'postgresql_flexible_server_allow_access_services_disabled',
    provider: 'azure',
    service: 'postgres',
    title: 'PostgreSQL Flexible Server Has "Allow Public Access From Any Azure Service" Disabled',
    severity: 'HIGH',
    description: 'Checks that the special firewall rule allowing all Azure services (0.0.0.0–0.0.0.0) to access the PostgreSQL Flexible Server is not present, since it permits any Azure tenant\'s resources to reach the server.',
    remediation: 'Remove the "Allow public access from any Azure service within Azure" firewall rule (start/end IP both 0.0.0.0). Use VNet integration or specific firewall rules for trusted Azure resources instead.',
    tags: ['postgresql', 'firewall', 'network'],
  },
  {
    checkId: 'azure_postgresql_backup_retention_sufficient',
    provider: 'azure',
    service: 'postgres',
    title: 'PostgreSQL Flexible Server Has Sufficient Backup Retention',
    severity: 'MEDIUM',
    description: 'Checks that PostgreSQL Flexible Server backup retention is at least 7 days, providing an adequate recovery point objective after data corruption or accidental deletion.',
    remediation: 'Set backup.backupRetentionDays to at least 7 days (35 days recommended for production) to ensure adequate recovery point objectives.',
    tags: ['postgresql', 'backup'],
  },
  {
    checkId: 'azure_postgresql_geo_redundant_backup_enabled',
    provider: 'azure',
    service: 'postgres',
    title: 'PostgreSQL Flexible Server Has Geo-Redundant Backup Enabled',
    severity: 'MEDIUM',
    description: 'Checks that PostgreSQL Flexible Server uses geo-redundant backups, so the server can be restored to a paired Azure region in the event of a full regional failure.',
    remediation: 'Enable geo-redundant backup to allow restore to a paired Azure region in case of a full regional failure.',
    tags: ['postgresql', 'backup', 'disaster-recovery'],
  },
  {
    checkId: 'azure_postgresql_high_availability_enabled',
    provider: 'azure',
    service: 'postgres',
    title: 'PostgreSQL Flexible Server Has High Availability Enabled',
    severity: 'MEDIUM',
    description: 'Checks that PostgreSQL Flexible Server has a High Availability mode (ZoneRedundant or SameZone) configured, allowing automatic failover with minimal downtime.',
    remediation: 'Enable High Availability (ZoneRedundant or SameZone mode) to allow automatic failover with minimal downtime.',
    tags: ['postgresql', 'availability'],
  },
  {
    checkId: 'postgresql_flexible_server_entra_id_authentication_enabled',
    provider: 'azure',
    service: 'postgres',
    title: 'PostgreSQL Flexible Server Uses Microsoft Entra ID Authentication',
    severity: 'MEDIUM',
    description: 'Checks that PostgreSQL Flexible Server has Microsoft Entra ID authentication enabled, allowing centrally managed, automatically rotated, identity-scoped credentials instead of relying solely on passwords.',
    remediation: 'Enable Microsoft Entra ID authentication (authConfig.activeDirectoryAuth = "Enabled") and migrate applications to use Managed Identity or service principal tokens.',
    tags: ['postgresql', 'authentication', 'entra-id'],
  },
  {
    checkId: 'azure_postgresql_version_not_eol',
    provider: 'azure',
    service: 'postgres',
    title: 'PostgreSQL Flexible Server Does Not Run an End-of-Life Version',
    severity: 'HIGH',
    description: 'Checks that PostgreSQL Flexible Server is not running a PostgreSQL major version that has reached end-of-life and no longer receives community security patches.',
    remediation: 'Upgrade to a supported PostgreSQL major version (15 or 16). Test application compatibility in a non-production environment using the major version upgrade feature of Flexible Server.',
    tags: ['postgresql', 'eol-version'],
  },
  {
    checkId: 'postgresql_flexible_server_connection_throttling_on',
    provider: 'azure',
    service: 'postgres',
    title: 'PostgreSQL Flexible Server Has Connection Throttling Enabled',
    severity: 'MEDIUM',
    description: 'Checks that the connection_throttling server parameter is set to "on", which protects against brute-force password guessing by inserting a delay after repeated failed logons from a given IP.',
    remediation: 'Set the connection_throttling server parameter to "on" to enable protection against brute-force login attempts.',
    tags: ['postgresql', 'hardening'],
  },
  {
    checkId: 'postgresql_flexible_server_log_connections_on',
    provider: 'azure',
    service: 'postgres',
    title: 'PostgreSQL Flexible Server Logs Database Connections',
    severity: 'LOW',
    description: 'Checks that the log_connections server parameter is set to "on", ensuring new client connections are recorded for audit and intrusion-detection purposes.',
    remediation: 'Set the log_connections server parameter to "on" to record all new client connections to the server.',
    tags: ['postgresql', 'logging'],
  },
  {
    checkId: 'postgresql_flexible_server_log_checkpoints_on',
    provider: 'azure',
    service: 'postgres',
    title: 'PostgreSQL Flexible Server Has Checkpoint Logging Enabled',
    severity: 'LOW',
    description: 'Checks that the log_checkpoints server parameter is set to "on", so checkpoint activity is recorded for performance and integrity troubleshooting.',
    remediation: 'Set the log_checkpoints server parameter to "on" to record checkpoint activity in the PostgreSQL server logs.',
    tags: ['postgresql', 'logging'],
  },
  {
    checkId: 'postgresql_flexible_server_log_disconnections_on',
    provider: 'azure',
    service: 'postgres',
    title: 'PostgreSQL Flexible Server Has Disconnection Logging Enabled',
    severity: 'MEDIUM',
    description: 'Checks that the log_disconnections server parameter is set to "on", so session end events are recorded, complementing connection logging for full session audit trails.',
    remediation: 'Set the log_disconnections server parameter to "on" to record client disconnection events in the PostgreSQL server logs.',
    tags: ['postgresql', 'logging'],
  },
  {
    checkId: 'postgresql_flexible_server_log_retention_days_greater_3',
    provider: 'azure',
    service: 'postgres',
    title: 'PostgreSQL Flexible Server Log Retention Is Between 4 and 7 Days',
    severity: 'MEDIUM',
    description: 'Checks that the log_retention_days server parameter is configured to a value greater than 3 and less than 8 days, giving enough log history for investigation without excessive storage cost.',
    remediation: 'Set the log_retention_days server parameter to a value between 4 and 7 days.',
    tags: ['postgresql', 'logging'],
  },
];
