// Check logic derived from Prowler (Apache-2.0, https://github.com/prowler-cloud/prowler)
import { CheckMetadata } from '../../types';

export const sqlChecks: CheckMetadata[] = [
  // ── Pre-existing checks (migrated from this.finding() to this.emit()) ──
  // No direct Prowler equivalent existed for these prior to Tranche 2, so
  // checkIds are invented in the `azure_sql_*` namespace.
  {
    checkId: 'azure_sql_public_network_access_disabled',
    provider: 'azure',
    service: 'sql',
    title: 'SQL Server Has Public Network Access Disabled',
    severity: 'HIGH',
    description: 'Checks that the SQL Server publicNetworkAccess is not "Enabled", so the server endpoint is not reachable from the public internet.',
    remediation: 'Set publicNetworkAccess to "Disabled" and use Private Endpoint for all database connectivity.',
    tags: ['sql', 'network', 'public-access'],
  },
  {
    checkId: 'azure_sql_firewall_no_allow_all_rule',
    provider: 'azure',
    service: 'sql',
    title: 'SQL Server Firewall Has No Allow-All Rule',
    severity: 'CRITICAL',
    description: 'Checks that the SQL Server firewall has no rule spanning the full IP range 0.0.0.0-255.255.255.255, which would expose the server to the entire internet.',
    remediation: 'Remove the overly permissive firewall rule. Restrict access to specific known IP ranges or use Private Endpoint.',
    tags: ['sql', 'firewall', 'network'],
  },
  {
    checkId: 'azure_sql_azuread_admin_configured',
    provider: 'azure',
    service: 'sql',
    title: 'SQL Server Has an Azure AD Administrator Configured',
    severity: 'HIGH',
    description: 'Checks that the SQL Server has at least one Azure Active Directory administrator configured, enabling MFA and conditional access instead of relying solely on SQL authentication.',
    remediation: 'Configure an Azure AD administrator for all SQL Servers. Disable SQL authentication for privileged access.',
    tags: ['sql', 'authentication', 'aad'],
  },
  {
    checkId: 'azure_sql_auditing_enabled',
    provider: 'azure',
    service: 'sql',
    title: 'SQL Server Has Auditing Enabled',
    severity: 'HIGH',
    description: 'Checks that the SQL Server blob auditing policy state is "Enabled", so malicious queries and unauthorized access can be detected.',
    remediation: 'Enable auditing for all SQL Servers and configure a log retention period of at least 90 days.',
    tags: ['sql', 'auditing', 'logging'],
  },
  {
    checkId: 'azure_sql_database_tde_enabled',
    provider: 'azure',
    service: 'sql',
    title: 'SQL Database Has Transparent Data Encryption Enabled',
    severity: 'HIGH',
    description: 'Checks that each SQL database (excluding master) has Transparent Data Encryption (TDE) enabled, so data at rest is encrypted.',
    remediation: 'Enable Transparent Data Encryption on all SQL databases.',
    tags: ['sql', 'tde', 'encryption'],
  },
  {
    checkId: 'azure_sql_database_threat_detection_enabled',
    provider: 'azure',
    service: 'sql',
    title: 'SQL Database Has Advanced Threat Protection Enabled',
    severity: 'MEDIUM',
    description: 'Checks that each SQL database has Advanced Threat Protection (threat detection) enabled, so SQL injection and anomalous access patterns can be detected.',
    remediation: 'Enable Microsoft Defender for SQL on the server level, which covers all databases.',
    tags: ['sql', 'threat-detection'],
  },

  // ── Newly ported Prowler checks (Tranche 2) ──
  {
    checkId: 'sqlserver_auditing_retention_90_days',
    provider: 'azure',
    service: 'sql',
    title: 'SQL Server Auditing Retention Exceeds 90 Days',
    severity: 'MEDIUM',
    description: 'Checks that the SQL Server blob auditing policy is enabled with a retention period greater than 90 days, so audit history covers a sufficient investigation window.',
    remediation: 'Enable auditing with a retention period greater than 90 days on all SQL Servers.',
    tags: ['sql', 'auditing', 'logging'],
  },
  {
    checkId: 'sqlserver_recommended_minimal_tls_version',
    provider: 'azure',
    service: 'sql',
    title: 'SQL Server Enforces Minimal TLS Version 1.2 or Higher',
    severity: 'MEDIUM',
    description: 'Checks that the SQL Server minimalTlsVersion is set to 1.2 or 1.3, rejecting connections that negotiate a deprecated, insecure TLS version.',
    remediation: 'Set the SQL Server minimal TLS version to 1.2 (or 1.3 where supported) and update client drivers as needed.',
    tags: ['sql', 'tls'],
  },
  {
    checkId: 'sqlserver_tde_encrypted_with_cmk',
    provider: 'azure',
    service: 'sql',
    title: 'SQL Server TDE Protector Uses a Customer-Managed Key',
    severity: 'CRITICAL',
    description: 'Checks that the SQL Server encryption protector server key type is AzureKeyVault (customer-managed key) and that all non-master databases have TDE enabled using that protector.',
    remediation: 'Configure a Key Vault-backed TDE protector (customer-managed key) on the SQL Server and confirm TDE is enabled on every database.',
    tags: ['sql', 'tde', 'cmk', 'encryption'],
  },
  {
    checkId: 'sqlserver_vulnerability_assessment_enabled',
    provider: 'azure',
    service: 'sql',
    title: 'SQL Server Has Vulnerability Assessment Enabled',
    severity: 'MEDIUM',
    description: 'Checks that the SQL Server has a vulnerability assessment configured with a storage container path for scan results.',
    remediation: 'Enable Vulnerability Assessment on the SQL Server and configure a storage account container to hold scan results.',
    tags: ['sql', 'vulnerability-assessment'],
  },
  {
    checkId: 'sqlserver_va_periodic_recurring_scans_enabled',
    provider: 'azure',
    service: 'sql',
    title: 'SQL Server Vulnerability Assessment Has Periodic Recurring Scans Enabled',
    severity: 'MEDIUM',
    description: 'Checks that a SQL Server with Vulnerability Assessment enabled also has periodic recurring scans turned on, so new vulnerabilities are detected automatically over time.',
    remediation: 'Enable periodic recurring scans in the SQL Server Vulnerability Assessment settings.',
    tags: ['sql', 'vulnerability-assessment'],
  },
  {
    checkId: 'sqlserver_va_emails_notifications_admins_enabled',
    provider: 'azure',
    service: 'sql',
    title: 'SQL Server Vulnerability Assessment Notifies Subscription Admins',
    severity: 'MEDIUM',
    description: 'Checks that a SQL Server with Vulnerability Assessment enabled has recurring-scan email notifications to subscription administrators turned on.',
    remediation: 'Enable "email subscription admins" in the SQL Server Vulnerability Assessment recurring-scan settings.',
    tags: ['sql', 'vulnerability-assessment', 'notifications'],
  },
  {
    checkId: 'sqlserver_va_scan_reports_configured',
    provider: 'azure',
    service: 'sql',
    title: 'SQL Server Vulnerability Assessment Has Scan Report Recipients Configured',
    severity: 'MEDIUM',
    description: 'Checks that a SQL Server with Vulnerability Assessment enabled has scan report recipients configured, either via subscription-admin notification or an explicit email list.',
    remediation: 'Configure scan report recipients (subscription admins and/or an explicit email list) in the SQL Server Vulnerability Assessment recurring-scan settings.',
    tags: ['sql', 'vulnerability-assessment', 'notifications'],
  },
];
