// Check logic derived from Prowler (Apache-2.0, https://github.com/prowler-cloud/prowler)
import { CheckMetadata } from '../../types';

export const storageChecks: CheckMetadata[] = [
  // ── Pre-existing checks (migrated from this.finding() to this.emit()) ──
  // No direct Prowler equivalent existed for these prior to Tranche 2, so
  // checkIds are invented in the `azure_storage_*` namespace.
  {
    checkId: 'azure_storage_public_blob_access_disabled',
    provider: 'azure',
    service: 'storage',
    title: 'Storage Account Disallows Public Blob Access',
    severity: 'HIGH',
    description: 'Checks that the storage account allowBlobPublicAccess setting is disabled, so container-level public access settings cannot expose blobs anonymously.',
    remediation: 'Set allowBlobPublicAccess=false at the account level. Individual container-level public access settings will be ignored once disabled.',
    tags: ['storage', 'public-access'],
  },
  {
    checkId: 'azure_storage_https_only_enforced',
    provider: 'azure',
    service: 'storage',
    title: 'Storage Account Enforces HTTPS-Only Traffic',
    severity: 'HIGH',
    description: 'Checks that the storage account enforces HTTPS-only access (Secure transfer required), preventing unencrypted data in transit.',
    remediation: 'Enable the "Secure transfer required" (enableHttpsTrafficOnly) setting on all storage accounts.',
    tags: ['storage', 'encryption-in-transit'],
  },
  {
    checkId: 'azure_storage_minimum_tls_version_12',
    provider: 'azure',
    service: 'storage',
    title: 'Storage Account Enforces Minimum TLS Version 1.2',
    severity: 'MEDIUM',
    description: 'Checks that the storage account minimum TLS version is set to TLS1_2. TLS 1.0/1.1 are deprecated and vulnerable to downgrade attacks.',
    remediation: 'Set minimumTlsVersion to TLS1_2 on all storage accounts.',
    tags: ['storage', 'tls'],
  },
  {
    checkId: 'azure_storage_infrastructure_encryption_enabled',
    provider: 'azure',
    service: 'storage',
    title: 'Storage Account Has Infrastructure (Double) Encryption Enabled',
    severity: 'LOW',
    description: 'Checks that the storage account has infrastructure (double) encryption enabled, layering a second independent encryption pass beneath the platform-managed encryption.',
    remediation: 'Enable infrastructure encryption when creating storage accounts. This cannot be changed after creation — recreate the account if required.',
    tags: ['storage', 'encryption-at-rest'],
  },
  {
    checkId: 'azure_storage_customer_managed_key_encryption',
    provider: 'azure',
    service: 'storage',
    title: 'Storage Account Uses Customer-Managed Keys',
    severity: 'LOW',
    description: 'Checks that the storage account encryption key source is Microsoft.Keyvault (customer-managed keys) rather than Microsoft-managed keys, giving the owner control over key rotation and revocation.',
    remediation: 'Configure customer-managed keys in Azure Key Vault for storage accounts holding sensitive data.',
    tags: ['storage', 'cmk'],
  },
  {
    checkId: 'azure_storage_blob_soft_delete_enabled',
    provider: 'azure',
    service: 'storage',
    title: 'Storage Account Has Blob Soft Delete Enabled',
    severity: 'MEDIUM',
    description: 'Checks that blob soft delete is enabled on the storage account, so accidental or malicious blob deletions can be recovered within the retention window.',
    remediation: 'Enable blob soft delete with a minimum retention of 7 days.',
    tags: ['storage', 'data-protection'],
  },
  {
    checkId: 'azure_storage_shared_key_access_disallowed',
    provider: 'azure',
    service: 'storage',
    title: 'Storage Account Disallows Shared Key Access',
    severity: 'MEDIUM',
    description: 'Checks that the storage account disallows authentication via account access keys (allowSharedKeyAccess=false), forcing clients onto Azure AD RBAC where access is scoped and audited.',
    remediation: 'Set allowSharedKeyAccess=false and migrate all access to Azure AD and SAS tokens with specific permissions.',
    tags: ['storage', 'authentication'],
  },
  {
    checkId: 'azure_storage_network_default_action_deny',
    provider: 'azure',
    service: 'storage',
    title: 'Storage Account Network Rules Default to Deny',
    severity: 'HIGH',
    description: 'Checks that the storage account network ACL default action is "Deny" rather than "Allow", so the account is not reachable from every IP address on the internet by default.',
    remediation: 'Set the storage account network ACL default action to "Deny" and add only required VNet rules or IP ranges. Use Private Endpoint for internal access.',
    tags: ['storage', 'network', 'public-access'],
  },
  {
    checkId: 'azure_storage_private_endpoint_configured',
    provider: 'azure',
    service: 'storage',
    title: 'Storage Account Has a Private Endpoint Configured',
    severity: 'MEDIUM',
    description: 'Checks that storage accounts with an unrestricted network default action have at least one approved Private Endpoint connection, so traffic can be routed off the public internet.',
    remediation: 'Create a Private Endpoint for the storage account in each VNet that needs access, and restrict the network ACL default action to Deny.',
    tags: ['storage', 'private-endpoint', 'network'],
  },

  // ── Newly ported Prowler checks (Tranche 2) ──
  {
    checkId: 'storage_account_public_network_access_disabled',
    provider: 'azure',
    service: 'storage',
    title: 'Storage Account Has Public Network Access Disabled',
    severity: 'HIGH',
    description: 'Checks that the storage account publicNetworkAccess property is set to "Disabled", overriding any container-level public access settings and forcing access through private endpoints or trusted services. Independent of the blob public-access setting.',
    remediation: 'Disable public network access on the storage account and reach it through Private Endpoints or trusted Azure services only. Validate client connectivity before disabling public access in production.',
    tags: ['storage', 'network', 'public-access'],
  },
  {
    checkId: 'storage_blob_versioning_is_enabled',
    provider: 'azure',
    service: 'storage',
    title: 'Storage Account Has Blob Versioning Enabled',
    severity: 'MEDIUM',
    description: 'Checks that blob versioning is enabled on the storage account, automatically retaining previous versions of blobs created by updates or deletes.',
    remediation: 'Enable blob versioning for accounts holding critical data. Pair with blob soft delete and lifecycle rules to retain and age off versions.',
    tags: ['storage', 'data-protection', 'versioning'],
  },
  {
    checkId: 'storage_cross_tenant_replication_disabled',
    provider: 'azure',
    service: 'storage',
    title: 'Storage Account Has Cross-Tenant Replication Disabled',
    severity: 'HIGH',
    description: 'Checks that the storage account disallows cross-tenant object replication (allowCrossTenantReplication=false), limiting replication policies to the same tenant.',
    remediation: 'Set allowCrossTenantReplication=false and keep replication within the same tenant. If cross-tenant transfer is required, use formal data-sharing controls with monitoring and time-bound approvals.',
    tags: ['storage', 'replication', 'data-protection'],
  },
  {
    checkId: 'storage_default_to_entra_authorization_enabled',
    provider: 'azure',
    service: 'storage',
    title: 'Storage Account Defaults to Microsoft Entra Authorization',
    severity: 'MEDIUM',
    description: 'Checks that "Default to Microsoft Entra authorization in the Azure portal" is enabled, so the portal uses Azure RBAC by default to access blobs, files, queues, and tables rather than account keys.',
    remediation: 'Enable this setting so the portal defaults to Microsoft Entra ID. Prefer managed identities and user-delegation SAS, and disable Shared Key use where feasible.',
    tags: ['storage', 'authentication', 'aad'],
  },
  {
    checkId: 'storage_ensure_azure_services_are_trusted_to_access_is_enabled',
    provider: 'azure',
    service: 'storage',
    title: 'Storage Account Allows Trusted Microsoft Services to Bypass Network Rules',
    severity: 'MEDIUM',
    description: 'Checks that the storage account network rule set bypass list includes "AzureServices", so trusted Microsoft platform services can reach the account even when firewalls restrict public access.',
    remediation: 'Enable the trusted-services exception (AzureServices) for storage accounts used by platform services. Keep networks otherwise restricted and prefer private endpoints.',
    tags: ['storage', 'network'],
  },
  {
    checkId: 'storage_ensure_file_shares_soft_delete_is_enabled',
    provider: 'azure',
    service: 'storage',
    title: 'Storage Account Has Soft Delete Enabled for File Shares',
    severity: 'MEDIUM',
    description: 'Checks that soft delete with a retention period is enabled for the storage account file service, so accidentally deleted file shares can be recovered.',
    remediation: 'Enable soft delete for all Azure file shares and choose a retention window aligned to RPO/RTO and data criticality (e.g. 7-90 days).',
    tags: ['storage', 'data-protection'],
  },
  {
    checkId: 'storage_geo_redundant_enabled',
    provider: 'azure',
    service: 'storage',
    title: 'Storage Account Uses Geo-Redundant Replication',
    severity: 'MEDIUM',
    description: 'Checks that the storage account replication SKU is one of Standard_GRS, Standard_GZRS, Standard_RAGRS, or Standard_RAGZRS, so data is copied to a paired secondary region.',
    remediation: 'Adopt GRS/GZRS for critical workloads (prefer Standard_GZRS where supported) to achieve cross-region resilience. Use RA-GRS/RA-GZRS if read continuity during an outage is required.',
    tags: ['storage', 'availability', 'replication'],
  },
  {
    checkId: 'storage_key_rotation_90_days',
    provider: 'azure',
    service: 'storage',
    title: 'Storage Account Has Access Key Expiration Set to 90 Days or Less',
    severity: 'MEDIUM',
    description: 'Checks that the storage account defines a key expiration period for access-key rotation, with a maximum of 90 days.',
    remediation: 'Enforce a key expiration period of 90 days or less and automate rotation. Prefer Microsoft Entra ID with managed identities over Shared Key.',
    tags: ['storage', 'key-rotation'],
  },
  {
    checkId: 'storage_smb_protocol_version_is_latest',
    provider: 'azure',
    service: 'storage',
    title: 'Storage Account Allows Only the Latest SMB Protocol Version',
    severity: 'MEDIUM',
    description: 'Checks that Azure file shares are configured to allow only the latest SMB protocol version (SMB 3.1.1), blocking legacy SMB versions at the storage account level.',
    remediation: 'Restrict SMB to the newest version (SMB 3.1.1) and disable older versions. Validate client compatibility before rollout.',
    tags: ['storage', 'network'],
  },
];
