// Check logic derived from Prowler (Apache-2.0, https://github.com/prowler-cloud/prowler)
import { CheckMetadata } from '../../types';

export const vmChecks: CheckMetadata[] = [
  // ── Pre-existing checks (no Prowler equivalent) — checkIds invented following
  // <service>_<resource>_<condition> convention ──────────────────────────────
  {
    checkId: 'vm_os_disk_encryption_not_enabled',
    provider: 'azure',
    service: 'vm',
    title: 'Virtual Machine OS Disk Not Encrypted',
    severity: 'HIGH',
    description: 'Checks that a virtual machine\'s OS disk is protected by Azure Disk Encryption, a disk encryption set, or encryption-at-host, rather than relying only on default platform-managed disk encryption.',
    remediation: 'Enable Azure Disk Encryption on VM disks or attach a disk encryption set backed by a customer-managed key in Key Vault.',
    tags: ['vm', 'encryption'],
  },
  {
    checkId: 'vm_public_ip_management_ports_exposed',
    provider: 'azure',
    service: 'vm',
    title: 'Virtual Machine Has Public IP With Management Ports Exposed',
    severity: 'CRITICAL',
    description: 'Checks that a virtual machine with a directly-assigned public IP does not have an NSG rule permitting inbound access to management ports (22, 3389, 5985, 5986) from any source address.',
    remediation: 'Remove the public IP or restrict NSG inbound rules to specific trusted IPs. Use Azure Bastion for RDP/SSH instead of exposing management ports.',
    tags: ['vm', 'public-ip', 'exposed-ports'],
  },
  {
    checkId: 'vm_public_ip_address_assigned',
    provider: 'azure',
    service: 'vm',
    title: 'Virtual Machine Has a Public IP Address',
    severity: 'MEDIUM',
    description: 'Checks whether a virtual machine has a directly-assigned public IP address, which increases attack surface even when current NSG rules are restrictive.',
    remediation: 'Remove the public IP and access the VM via Azure Bastion, VPN, or ExpressRoute.',
    tags: ['vm', 'public-ip'],
  },
  {
    checkId: 'vm_managed_identity_not_configured',
    provider: 'azure',
    service: 'vm',
    title: 'Virtual Machine Does Not Use Managed Identity',
    severity: 'MEDIUM',
    description: 'Checks that a virtual machine has a system-assigned or user-assigned managed identity configured, so applications on the VM can authenticate to Azure services without stored credentials.',
    remediation: 'Assign a system-assigned or user-assigned managed identity so applications authenticate to Azure services without credentials.',
    tags: ['vm', 'identity'],
  },
  {
    checkId: 'vm_eol_operating_system',
    provider: 'azure',
    service: 'vm',
    title: 'Virtual Machine Running End-of-Life Operating System',
    severity: 'HIGH',
    description: 'Checks the VM image reference against known end-of-life OS releases (Windows Server 2008/2012, Ubuntu 14/16/18, CentOS 6/7) that no longer receive security patches.',
    remediation: 'Migrate to a supported OS. For Windows 2008/2012 use Windows Server 2022. For Ubuntu 14/16/18 use Ubuntu 22.04 LTS or 24.04 LTS.',
    tags: ['vm', 'eol-os'],
  },
  {
    checkId: 'vmss_os_disk_encryption_not_enabled',
    provider: 'azure',
    service: 'vm',
    title: 'Virtual Machine Scale Set OS Disk Not Encrypted',
    severity: 'HIGH',
    description: 'Checks that a VM Scale Set\'s OS disk profile has a disk encryption set configured, so all scale-set instances run with customer-managed key encrypted disks.',
    remediation: 'Configure a disk encryption set with a customer-managed key on the VMSS OS disk profile.',
    tags: ['vmss', 'encryption'],
  },
  {
    checkId: 'vmss_eol_operating_system',
    provider: 'azure',
    service: 'vm',
    title: 'Virtual Machine Scale Set Running End-of-Life Operating System',
    severity: 'HIGH',
    description: 'Checks the VMSS image reference against known end-of-life OS releases (Windows Server 2008/2012, Ubuntu 14/16/18, CentOS 6/7), which put every instance in the scale set on an unsupported OS.',
    remediation: 'Update the VMSS image reference to a supported OS version and re-image all instances.',
    tags: ['vmss', 'eol-os'],
  },
  {
    checkId: 'vmss_managed_identity_not_configured',
    provider: 'azure',
    service: 'vm',
    title: 'Virtual Machine Scale Set Does Not Use Managed Identity',
    severity: 'MEDIUM',
    description: 'Checks that a VM Scale Set has a managed identity configured, so workloads on scale-set instances can authenticate to Azure services without stored credentials.',
    remediation: 'Assign a managed identity to the VMSS so all instances can authenticate to Azure services without credentials.',
    tags: ['vmss', 'identity'],
  },
  {
    checkId: 'vmss_overprovisioning_enabled',
    provider: 'azure',
    service: 'vm',
    title: 'Virtual Machine Scale Set Overprovisioning Enabled',
    severity: 'LOW',
    description: 'Checks whether a VM Scale Set has overprovisioning enabled, which temporarily creates more VM instances than requested, briefly widening attack surface and writing data to instances that get discarded.',
    remediation: 'Disable overprovisioning if workload data sensitivity requires it, or ensure ephemeral disks are used so discarded instances leave no data.',
    tags: ['vmss', 'configuration'],
  },

  // ── Ported from Prowler's `vm` service — checkIds verbatim ─────────────────
  {
    checkId: 'vm_backup_enabled',
    provider: 'azure',
    service: 'vm',
    title: 'Virtual Machine Is Protected by Azure Backup',
    severity: 'HIGH',
    description: 'Checks that each Azure VM is protected by Azure Backup by confirming it exists as a VM backup item in a Recovery Services vault. VMs absent from any vault item indicate no configured backup coverage.',
    remediation: 'Protect the VM with Azure Backup in a Recovery Services vault under a standardized policy: az backup protection enable-for-vm --resource-group <vault-resource-group> --vault-name <vault-name> --vm <vm-name> --vm-resource-group <vm-resource-group> --policy-name DefaultPolicy',
    tags: ['vm', 'backup', 'resilience'],
  },
  {
    checkId: 'vm_desired_sku_size',
    provider: 'azure',
    service: 'vm',
    title: 'Virtual Machine Uses an Organization-Approved SKU Size',
    severity: 'MEDIUM',
    description: 'Checks each virtual machine\'s SKU size against an organization allowlist of approved VM size SKUs. Instances using sizes outside the allowlist are flagged as non-standard.',
    remediation: 'Resize the VM to an approved SKU: az vm resize --resource-group <RESOURCE_GROUP> --name <VM_NAME> --size <desired-sku>. Enforce the allowlist with an Azure Policy assignment restricting allowed VM SKUs.',
    tags: ['vm', 'governance'],
  },
  {
    checkId: 'vm_ensure_attached_disks_encrypted_with_cmk',
    provider: 'azure',
    service: 'vm',
    title: 'Virtual Machine OS or Data Disk Is Encrypted With a Customer-Managed Key',
    severity: 'MEDIUM',
    description: 'Checks that managed disks currently attached to a VM (OS and data disks) use customer-managed key (CMK) encryption via a disk encryption set, rather than platform-managed keys.',
    remediation: 'Update the disk to use a disk encryption set backed by a customer-managed key: az disk update -g <RESOURCE_GROUP> -n <DISK_NAME> --encryption-type EncryptionAtRestWithCustomerKey --disk-encryption-set <DES_ID>',
    tags: ['vm', 'disk', 'encryption', 'cmk'],
  },
  {
    checkId: 'vm_ensure_unattached_disks_encrypted_with_cmk',
    provider: 'azure',
    service: 'vm',
    title: 'Unattached Disk Is Encrypted With a Customer-Managed Key',
    severity: 'MEDIUM',
    description: 'Checks that managed disks not currently attached to any VM use customer-managed key (CMK) encryption via a disk encryption set, rather than platform-managed keys.',
    remediation: 'Update the disk to use a disk encryption set backed by a customer-managed key: az disk update -g <RESOURCE_GROUP> -n <DISK_NAME> --encryption-type EncryptionAtRestWithCustomerKey --disk-encryption-set <DES_ID>. Consider deleting stale unattached disks to reduce exposure.',
    tags: ['vm', 'disk', 'encryption', 'cmk'],
  },
  {
    checkId: 'vm_ensure_using_approved_images',
    provider: 'azure',
    service: 'vm',
    title: 'Virtual Machine Uses an Approved Custom Machine Image',
    severity: 'HIGH',
    description: 'Checks that a VM was launched from an approved custom (golden) image — a subscription-scoped image reference ID — rather than an unmanaged marketplace, gallery, or community image source.',
    remediation: 'Standardize provisioning on golden images maintained in an Azure Compute Gallery or as managed images, hardened and scanned before publishing; enforce via policy that deployments use only approved image references.',
    tags: ['vm', 'image', 'software-supply-chain'],
  },
  {
    checkId: 'vm_ensure_using_managed_disks',
    provider: 'azure',
    service: 'vm',
    title: 'Virtual Machine Uses Managed Disks for OS and Data Disks',
    severity: 'HIGH',
    description: 'Checks that every OS and data disk attached to a VM is a managed disk rather than an unmanaged page-blob VHD in a storage account. Azure is retiring unmanaged disks on 2026-03-31.',
    remediation: 'Convert the VM to managed disks: az vm convert --resource-group <RESOURCE_GROUP> --name <VM_NAME>. If the VM is in an availability set, convert the set to Aligned first.',
    tags: ['vm', 'disk', 'resilience'],
  },
  {
    checkId: 'vm_jit_access_enabled',
    provider: 'azure',
    service: 'vm',
    title: 'Virtual Machine Has Just-in-Time (JIT) Access Enabled',
    severity: 'MEDIUM',
    description: 'Checks that a virtual machine is covered by a Microsoft Defender for Cloud Just-in-Time network access policy, which opens management ports only for approved, time-bound requests from specified source IPs.',
    remediation: 'Enable JIT network access for the VM in Microsoft Defender for Cloud: Workload protections > Just-in-time VM access > select the VM > Enable JIT on VMs, keeping the default managed ports and a short access window.',
    tags: ['vm', 'jit', 'internet-exposed'],
  },
  {
    checkId: 'vm_linux_enforce_ssh_authentication',
    provider: 'azure',
    service: 'vm',
    title: 'Linux Virtual Machine Has Password Authentication Disabled',
    severity: 'HIGH',
    description: 'Checks that a Linux VM has disablePasswordAuthentication set to true, so only SSH public-key authentication is permitted and interactive password logins are disallowed.',
    remediation: 'Set disablePasswordAuthentication to true in the VM\'s linuxConfiguration and ensure an SSH public key is configured for the admin account before removing password login.',
    tags: ['vm', 'linux', 'ssh', 'identity-access'],
  },
  {
    checkId: 'vm_scaleset_associated_with_load_balancer',
    provider: 'azure',
    service: 'vm',
    title: 'Virtual Machine Scale Set Is Associated With a Load Balancer Backend Pool',
    severity: 'MEDIUM',
    description: 'Checks that a VM Scale Set\'s network profile references at least one load balancer backend address pool, so traffic is health-probed and evenly distributed across instances.',
    remediation: 'Attach the scale set\'s NIC IP configuration to a Standard Load Balancer backend pool so traffic is distributed with health-based failover.',
    tags: ['vmss', 'load-balancer', 'resilience'],
  },
  {
    checkId: 'vm_scaleset_not_empty',
    provider: 'azure',
    service: 'vm',
    title: 'Virtual Machine Scale Set Has at Least One VM Instance',
    severity: 'MEDIUM',
    description: 'Checks that a VM Scale Set has one or more VM instances. A scale set with zero instances is orphaned, hides stale configuration/identities, and can reactivate with outdated images if capacity is restored.',
    remediation: 'Decommission empty scale sets that are no longer needed, or scale to at least one instance: az vmss scale --resource-group <resource-group> --name <scale-set-name> --new-capacity 1.',
    tags: ['vmss', 'governance', 'resilience'],
  },
  {
    checkId: 'vm_sufficient_daily_backup_retention_period',
    provider: 'azure',
    service: 'vm',
    title: 'Virtual Machine Has a Backup Policy With Sufficient Daily Retention',
    severity: 'MEDIUM',
    description: 'Checks that a VM protected by Azure Backup uses a policy whose daily retention period meets the configured minimum (default 7 days). VMs without backup, or with a shorter retention window, are flagged.',
    remediation: 'Apply or update the VM\'s backup policy so daily retention meets or exceeds the minimum required days, aligned to your RPO/RTO targets.',
    tags: ['vm', 'backup', 'resilience'],
  },
  {
    checkId: 'vm_trusted_launch_enabled',
    provider: 'azure',
    service: 'vm',
    title: 'Virtual Machine Has Trusted Launch With Secure Boot and vTPM Enabled',
    severity: 'MEDIUM',
    description: 'Checks that a Generation 2 VM has securityType set to TrustedLaunch with both secureBootEnabled and vTpmEnabled turned on, protecting the boot chain against bootkits/rootkits.',
    remediation: 'Enable Trusted Launch with Secure Boot and vTPM: az vm update --resource-group <RESOURCE_GROUP> --name <VM_NAME> --security-type TrustedLaunch --enable-secure-boot true --enable-vtpm true. Create a VM restore point before remediating an existing VM.',
    tags: ['vm', 'trusted-launch', 'node-security'],
  },
];
