// Check logic derived from Prowler (Apache-2.0, https://github.com/prowler-cloud/prowler)
import { CheckMetadata } from '../../types';

export const computeChecks: CheckMetadata[] = [
  // --- Rewritten from the pre-existing finding()-based scanner. These predate
  // Prowler-parity work and have no exact Prowler checkId equivalent (either the
  // resource scope or the pass/fail condition differs from Prowler's own compute
  // checks), so they keep product-invented checkIds rather than borrowing one.
  {
    checkId: 'compute_instance_public_ip_address',
    provider: 'gcp',
    service: 'compute',
    title: 'Compute Engine Instance Has a Public IP Address',
    severity: 'HIGH',
    description: 'Checks that Compute Engine VM instances do not have a public IP address assigned via an access config on any network interface.',
    remediation: 'Remove public IPs from Compute instances that do not need direct internet connectivity. Use Cloud NAT for outbound traffic and a load balancer or Identity-Aware Proxy for inbound access.',
    tags: ['compute', 'network', 'public-ip'],
  },
  {
    checkId: 'compute_instance_metadata_os_login_enabled',
    provider: 'gcp',
    service: 'compute',
    title: 'Compute Engine Instance Uses OS Login',
    severity: 'HIGH',
    description: 'Checks that the enable-oslogin instance metadata key is set to true, so SSH access is managed via IAM rather than project/instance metadata SSH keys.',
    remediation: 'Enable OS Login by setting the enable-oslogin=true metadata key. OS Login integrates SSH access with IAM and optionally enforces 2FA for SSH sessions.',
    tags: ['compute', 'ssh', 'os-login'],
  },
  {
    checkId: 'compute_instance_serial_port_metadata_disabled',
    provider: 'gcp',
    service: 'compute',
    title: 'Compute Engine Instance Serial Port Access Disabled',
    severity: 'HIGH',
    description: 'Checks that the serial-port-enable instance metadata key is not set to true. Serial port access allows interactive console sessions that bypass normal authentication.',
    remediation: 'Disable serial port access by setting serial-port-enable=false in instance metadata. Use OS Login or SSH keys for secure instance access instead.',
    tags: ['compute', 'serial-port'],
  },
  {
    checkId: 'compute_instance_disks_cmek_encrypted',
    provider: 'gcp',
    service: 'compute',
    title: 'Compute Engine Instance Disks Use Customer-Managed Encryption Keys',
    severity: 'LOW',
    description: 'Checks that all disks attached to a Compute Engine instance are encrypted with a customer-managed key (Cloud KMS) rather than only Google-managed encryption.',
    remediation: 'Encrypt Compute Engine disks with a customer-managed key from Cloud KMS. Note: disks must be recreated from snapshots to apply CMEK.',
    tags: ['compute', 'disk-encryption', 'cmek'],
  },
  {
    checkId: 'compute_instance_service_account_configured',
    provider: 'gcp',
    service: 'compute',
    title: 'Compute Engine Instance Has a Dedicated Service Account',
    severity: 'MEDIUM',
    description: 'Checks that a Compute Engine instance has a service account attached and is not left with no service account at all.',
    remediation: 'Attach a dedicated, least-privilege service account to the VM. Avoid attaching the default Compute Engine service account which has the Editor role.',
    tags: ['compute', 'service-account'],
  },
  {
    checkId: 'compute_instance_shielded_secure_boot_vtpm_enabled',
    provider: 'gcp',
    service: 'compute',
    title: 'Compute Engine Instance Has Secure Boot and vTPM Enabled',
    severity: 'MEDIUM',
    description: 'Checks that a Compute Engine instance has both Secure Boot and virtual TPM enabled under Shielded VM configuration.',
    remediation: 'Enable Shielded VM by setting enableSecureBoot=true and enableVtpm=true on the instance. Recreate the instance if the current machine type supports Shielded VM.',
    tags: ['compute', 'shielded-vm'],
  },
  {
    checkId: 'compute_firewall_open_ingress_from_internet',
    provider: 'gcp',
    service: 'compute',
    title: 'Firewall Rule Allows Unrestricted Inbound Traffic From the Internet',
    severity: 'CRITICAL',
    description: 'Checks VPC firewall ingress rules for an "allow all" rule (protocol "all", or tcp/udp with no port restriction) opened to 0.0.0.0/0 or ::/0.',
    remediation: 'Restrict the source range to specific IP ranges or remove the rule. Use Identity-Aware Proxy (IAP) for SSH/RDP access instead of opening firewall rules to the internet.',
    tags: ['compute', 'firewall', 'open-port', 'internet-exposed'],
  },
  {
    checkId: 'compute_firewall_ssh_exposed_generic',
    provider: 'gcp',
    service: 'compute',
    title: 'Firewall Rule Exposes SSH to the Internet',
    severity: 'CRITICAL',
    description: 'Checks VPC firewall ingress rules for TCP port 22 opened to 0.0.0.0/0 or ::/0, evaluated per matching port entry.',
    remediation: 'Remove the SSH firewall rule. Use Identity-Aware Proxy (IAP) Tunneling (gcloud compute ssh --tunnel-through-iap) which does not require a public IP or open firewall rule.',
    tags: ['compute', 'firewall', 'ssh', 'internet-exposed'],
  },
  {
    checkId: 'compute_firewall_rdp_exposed_generic',
    provider: 'gcp',
    service: 'compute',
    title: 'Firewall Rule Exposes RDP to the Internet',
    severity: 'CRITICAL',
    description: 'Checks VPC firewall ingress rules for TCP port 3389 opened to 0.0.0.0/0 or ::/0, evaluated per matching port entry.',
    remediation: 'Remove the RDP firewall rule. Use IAP Desktop for RDP access through Identity-Aware Proxy without exposing port 3389.',
    tags: ['compute', 'firewall', 'rdp', 'internet-exposed'],
  },
  {
    checkId: 'compute_firewall_sensitive_port_exposed',
    provider: 'gcp',
    service: 'compute',
    title: 'Firewall Rule Exposes a Sensitive Port to the Internet',
    severity: 'HIGH',
    description: 'Checks VPC firewall ingress rules for common database/administration ports (e.g. 3306, 5432, 6379, 27017) opened to 0.0.0.0/0 or ::/0.',
    remediation: 'Restrict the firewall rule to specific source IP ranges. Consider VPC Service Controls or Private Service Connect to avoid exposing sensitive ports.',
    tags: ['compute', 'firewall', 'sensitive-port', 'internet-exposed'],
  },
  {
    checkId: 'compute_firewall_default_rule_enabled',
    provider: 'gcp',
    service: 'compute',
    title: 'Default Firewall Rule Is Enabled',
    severity: 'HIGH',
    description: 'Checks that auto-created default-allow-ssh, default-allow-rdp, or default-allow-icmp firewall rules are not left enabled, as these are broad, project-wide, and un-scoped.',
    remediation: 'Disable the default rule and create specific firewall rules that allow only required traffic from known source IP ranges or via IAP.',
    tags: ['compute', 'firewall', 'default-rule'],
  },
  {
    checkId: 'compute_network_auto_mode_subnet_creation',
    provider: 'gcp',
    service: 'compute',
    title: 'VPC Network Does Not Use Auto-Mode Subnet Creation',
    severity: 'MEDIUM',
    description: 'Checks that a non-default VPC network does not use auto-mode, which automatically creates a subnet in every GCP region and results in unnecessarily broad network footprint.',
    remediation: 'Migrate to a custom-mode VPC where subnets are only created in regions where resources are intentionally deployed.',
    tags: ['compute', 'vpc', 'auto-mode'],
  },
  {
    checkId: 'compute_network_empty_vpc',
    provider: 'gcp',
    service: 'compute',
    title: 'VPC Network Has No Unused Empty Networks',
    severity: 'LOW',
    description: 'Checks that a non-default VPC network has at least one subnet; a network with zero subnets is unused network surface.',
    remediation: 'Delete unused VPC networks to reduce network surface area and avoid accidental resource creation in the wrong network.',
    tags: ['compute', 'vpc', 'hygiene'],
  },

  // --- Ported verbatim from Prowler's gcp/services/compute checks (checkId
  // preserved so compliance-framework mappings can be reused directly).
  {
    checkId: 'compute_firewall_rdp_access_from_the_internet_allowed',
    provider: 'gcp',
    service: 'compute',
    title: 'Firewall Rule Does Not Allow RDP From the Internet',
    severity: 'CRITICAL',
    description: 'Checks VPC firewall ingress rules for TCP port 3389 (RDP) opened to 0.0.0.0/0, including rules that allow all TCP ports or the "all" protocol.',
    remediation: 'Restrict RDP to trusted IP ranges or a hardened bastion/IAP proxy; prefer private access with no public IPs. Delete or scope down the offending firewall rule.',
    tags: ['compute', 'firewall', 'rdp', 'internet-exposed'],
  },
  {
    checkId: 'compute_firewall_ssh_access_from_the_internet_allowed',
    provider: 'gcp',
    service: 'compute',
    title: 'Firewall Rule Does Not Allow SSH From the Internet',
    severity: 'CRITICAL',
    description: 'Checks VPC firewall ingress rules for TCP port 22 (SSH) opened to 0.0.0.0/0, including rules that allow all TCP ports or the "all" protocol.',
    remediation: 'Restrict SSH to trusted sources; avoid 0.0.0.0/0. Prefer Identity-Aware Proxy (IAP) TCP forwarding or a bastion host instead of an open firewall rule.',
    tags: ['compute', 'firewall', 'ssh', 'internet-exposed'],
  },
  {
    checkId: 'compute_image_not_publicly_shared',
    provider: 'gcp',
    service: 'compute',
    title: 'Compute Engine Disk Image Is Not Publicly Shared',
    severity: 'MEDIUM',
    description: 'Checks that custom Compute Engine disk images do not grant IAM access to allAuthenticatedUsers, which exposes the image to any Google account holder.',
    remediation: 'Remove the allAuthenticatedUsers IAM binding from the disk image. Grant access only to specific users, groups, or service accounts that require it.',
    tags: ['compute', 'image', 'internet-exposed'],
  },
  {
    checkId: 'compute_instance_automatic_restart_enabled',
    provider: 'gcp',
    service: 'compute',
    title: 'Compute Engine Instance Has Automatic Restart Enabled',
    severity: 'MEDIUM',
    description: 'Checks that Compute Engine VM instances have Automatic Restart enabled so the instance recovers from host maintenance or unexpected failures without manual intervention.',
    remediation: 'Enable Automatic Restart under the instance scheduling policy (gcloud compute instances update --restart-on-failure). Preemptible and Spot VMs cannot support this and are excluded.',
    tags: ['compute', 'resilience'],
  },
  {
    checkId: 'compute_instance_block_project_wide_ssh_keys_disabled',
    provider: 'gcp',
    service: 'compute',
    title: 'Compute Engine Instance Blocks Project-Wide SSH Keys',
    severity: 'MEDIUM',
    description: 'Checks that the block-project-ssh-keys instance metadata key is set to true, so the instance only accepts instance-level or OS Login credentials rather than shared project-wide SSH keys.',
    remediation: 'Set block-project-ssh-keys=true on the instance metadata. Prefer OS Login or instance-specific keys over shared project-wide SSH keys.',
    tags: ['compute', 'ssh', 'identity-access'],
  },
  {
    checkId: 'compute_instance_confidential_computing_enabled',
    provider: 'gcp',
    service: 'compute',
    title: 'Compute Engine Instance Has Confidential Computing Enabled',
    severity: 'MEDIUM',
    description: 'Checks that a Compute Engine instance is configured as a Confidential VM, encrypting data in use with hardware-based memory protection.',
    remediation: 'Stop the instance, edit it to enable the Confidential VM service (requires a supported machine series such as N2D), then restart it.',
    tags: ['compute', 'encryption', 'confidential-computing'],
  },
  {
    checkId: 'compute_instance_default_service_account_in_use',
    provider: 'gcp',
    service: 'compute',
    title: 'Compute Engine Instance Does Not Use the Default Service Account',
    severity: 'MEDIUM',
    description: 'Checks that a Compute Engine instance is not configured to use the default Compute Engine service account, which typically holds the broad Editor role.',
    remediation: 'Create a dedicated service account scoped to the instance\'s workload and attach it in place of the default Compute Engine service account.',
    tags: ['compute', 'service-account', 'least-privilege'],
  },
  {
    checkId: 'compute_instance_default_service_account_in_use_with_full_api_access',
    provider: 'gcp',
    service: 'compute',
    title: 'Compute Engine Instance Does Not Use the Default Service Account With Full API Access',
    severity: 'HIGH',
    description: 'Checks that a Compute Engine instance is not using the default service account together with the cloud-platform OAuth scope, which grants full access to all enabled Cloud APIs.',
    remediation: 'Replace the default service account and cloud-platform scope with a dedicated service account granted only the specific IAM roles the workload requires.',
    tags: ['compute', 'service-account', 'least-privilege'],
  },
  {
    checkId: 'compute_instance_deletion_protection_enabled',
    provider: 'gcp',
    service: 'compute',
    title: 'Compute Engine Instance Has Deletion Protection Enabled',
    severity: 'MEDIUM',
    description: 'Checks that Compute Engine VM instances have deletion protection enabled to prevent accidental termination of production or critical workloads.',
    remediation: 'Enable deletion protection on the instance (gcloud compute instances update --deletion-protection) for any instance running a production or critical workload.',
    tags: ['compute', 'resilience'],
  },
  {
    checkId: 'compute_instance_disk_auto_delete_disabled',
    provider: 'gcp',
    service: 'compute',
    title: 'Compute Engine Instance Disks Have Auto-Delete Disabled',
    severity: 'MEDIUM',
    description: 'Checks that persistent disks attached to a Compute Engine instance have auto-delete disabled, preventing accidental data loss when the instance is terminated.',
    remediation: 'Disable auto-delete on attached persistent disks (gcloud compute instances set-disk-auto-delete --no-auto-delete) for any disk holding data that must survive instance deletion.',
    tags: ['compute', 'data-protection'],
  },
  {
    checkId: 'compute_instance_encryption_with_csek_enabled',
    provider: 'gcp',
    service: 'compute',
    title: 'Compute Engine Instance Disks Encrypted With Customer-Supplied Encryption Keys',
    severity: 'HIGH',
    description: 'Checks that every disk attached to a Compute Engine instance is encrypted with a Customer-Supplied Encryption Key (CSEK).',
    remediation: 'Recreate the instance\'s disks with a customer-supplied encryption key (--csek-key-file) so all attached disks are CSEK-encrypted.',
    tags: ['compute', 'encryption', 'csek'],
  },
  {
    checkId: 'compute_instance_group_autohealing_enabled',
    provider: 'gcp',
    service: 'compute',
    title: 'Managed Instance Group Has Autohealing Enabled',
    severity: 'HIGH',
    description: 'Checks that a Managed Instance Group (MIG) has an autohealing policy configured with a valid health check reference, so unhealthy instances are automatically recreated.',
    remediation: 'Configure an autohealing policy on the MIG with a valid health check (gcloud compute instance-groups managed update --health-check).',
    tags: ['compute', 'mig', 'resilience'],
  },
  {
    checkId: 'compute_instance_group_load_balancer_attached',
    provider: 'gcp',
    service: 'compute',
    title: 'Managed Instance Group Is Attached to a Load Balancer',
    severity: 'LOW',
    description: 'Checks that a Managed Instance Group (MIG) is registered as a backend for a load balancer via a backend service, so traffic is distributed across its instances.',
    remediation: 'Attach the MIG as a backend to a backend service used by a load balancer so traffic is distributed evenly across its instances.',
    tags: ['compute', 'mig', 'load-balancer'],
  },
  {
    checkId: 'compute_instance_group_multiple_zones',
    provider: 'gcp',
    service: 'compute',
    title: 'Managed Instance Group Spans Multiple Zones',
    severity: 'LOW',
    description: 'Checks that a Managed Instance Group (MIG) spans at least two zones, so the group tolerates a single-zone outage.',
    remediation: 'Convert a zonal MIG to a regional MIG, or configure the regional MIG\'s distribution policy to span at least two zones.',
    tags: ['compute', 'mig', 'high-availability'],
  },
  {
    checkId: 'compute_instance_ip_forwarding_is_enabled',
    provider: 'gcp',
    service: 'compute',
    title: 'Compute Engine Instance Has IP Forwarding Disabled',
    severity: 'MEDIUM',
    description: 'Checks that a Compute Engine instance does not have IP forwarding (canIpForward) enabled, which would let the instance route traffic on behalf of other addresses. GKE-managed instances are excluded.',
    remediation: 'Disable IP forwarding on the instance unless it is intentionally acting as a router or NAT gateway; recreate the instance without --can-ip-forward if not required.',
    tags: ['compute', 'network'],
  },
  {
    checkId: 'compute_instance_on_host_maintenance_migrate',
    provider: 'gcp',
    service: 'compute',
    title: 'Compute Engine Instance Has On-Host Maintenance Set to Migrate',
    severity: 'MEDIUM',
    description: 'Checks that a Compute Engine instance\'s host maintenance behavior is set to MIGRATE (live migration) rather than TERMINATE, minimizing downtime from Google-initiated maintenance. Preemptible and Spot VMs are excluded, as they must use TERMINATE.',
    remediation: 'Set the instance\'s scheduling.onHostMaintenance to MIGRATE (gcloud compute instances set-scheduling --maintenance-policy=MIGRATE) unless the instance is preemptible or Spot.',
    tags: ['compute', 'resilience'],
  },
  {
    checkId: 'compute_instance_preemptible_vm_disabled',
    provider: 'gcp',
    service: 'compute',
    title: 'Compute Engine Instance Is Not Preemptible or Spot',
    severity: 'MEDIUM',
    description: 'Checks that a Compute Engine instance is not configured as a preemptible or Spot VM, which Google can terminate at any time and are unsuitable for workloads requiring continuous availability.',
    remediation: 'Recreate the instance as a standard (non-preemptible, non-Spot) VM if it runs a workload that requires continuous availability.',
    tags: ['compute', 'resilience'],
  },
  {
    checkId: 'compute_instance_serial_ports_in_use',
    provider: 'gcp',
    service: 'compute',
    title: 'Compute Engine Instance Has Serial Port Access Disabled',
    severity: 'MEDIUM',
    description: 'Checks that the serial-port-enable instance metadata key is not set to enable interactive serial console access.',
    remediation: 'Set serial-port-enable=false (or remove the key) in instance metadata to disable serial console access.',
    tags: ['compute', 'serial-port'],
  },
  {
    checkId: 'compute_instance_shielded_vm_enabled',
    provider: 'gcp',
    service: 'compute',
    title: 'Compute Engine Instance Has vTPM and Integrity Monitoring Enabled',
    severity: 'MEDIUM',
    description: 'Checks that a Compute Engine instance has both virtual TPM and Integrity Monitoring enabled under Shielded VM configuration.',
    remediation: 'Enable Shielded VM vTPM and Integrity Monitoring on the instance (recreate if unsupported by the current image/machine type).',
    tags: ['compute', 'shielded-vm'],
  },
  {
    checkId: 'compute_instance_single_network_interface',
    provider: 'gcp',
    service: 'compute',
    title: 'Compute Engine Instance Has a Single Network Interface',
    severity: 'MEDIUM',
    description: 'Checks that a Compute Engine instance is configured with only one network interface to minimize network complexity and attack surface. GKE-managed instances with multiple interfaces are flagged for manual review instead of failing outright.',
    remediation: 'Reduce the instance to a single network interface unless multiple interfaces are a deliberate architectural requirement (e.g. a network appliance).',
    tags: ['compute', 'network'],
  },
  {
    checkId: 'compute_instance_suspended_without_persistent_disks',
    provider: 'gcp',
    service: 'compute',
    title: 'Suspended Compute Engine Instance Has No Persistent Disks Attached',
    severity: 'MEDIUM',
    description: 'Checks that a Compute Engine instance in SUSPENDED or SUSPENDING state does not still have persistent disks attached, which represent unused infrastructure that continues to incur storage costs.',
    remediation: 'Detach or delete persistent disks from suspended instances that are no longer needed, or resume/delete the instance.',
    tags: ['compute', 'cost', 'hygiene'],
  },
  {
    checkId: 'compute_loadbalancer_logging_enabled',
    provider: 'gcp',
    service: 'compute',
    title: 'HTTP(S) Load Balancer Has Logging Enabled',
    severity: 'HIGH',
    description: 'Checks that a global or regional HTTP(S) load balancer\'s backend service has request logging enabled.',
    remediation: 'Enable logging on the load balancer\'s backend service (logConfig.enable=true) to retain request-level visibility for investigations.',
    tags: ['compute', 'load-balancer', 'logging'],
  },
  {
    checkId: 'compute_network_default_in_use',
    provider: 'gcp',
    service: 'compute',
    title: 'Project Does Not Have a Default VPC Network',
    severity: 'MEDIUM',
    description: 'Checks that a project does not still have the auto-created "default" VPC network, which ships with permissive pre-populated firewall rules (SSH/RDP/ICMP from 0.0.0.0/0).',
    remediation: 'Delete the default VPC network and create custom VPCs with appropriately scoped subnets and firewall rules; migrate all resources off the default network first.',
    tags: ['compute', 'vpc', 'default-network'],
  },
  {
    checkId: 'compute_network_dns_logging_enabled',
    provider: 'gcp',
    service: 'compute',
    title: 'VPC Network Has Cloud DNS Logging Enabled',
    severity: 'MEDIUM',
    description: 'Checks that a VPC network is bound to a Cloud DNS server policy with logging enabled, capturing DNS query records for the network.',
    remediation: 'Create or update a Cloud DNS server policy for the network with --enable-logging, or attach the network to an existing policy that has logging enabled.',
    tags: ['compute', 'dns', 'logging'],
  },
  {
    checkId: 'compute_network_not_legacy',
    provider: 'gcp',
    service: 'compute',
    title: 'VPC Network Is Not Legacy',
    severity: 'MEDIUM',
    description: 'Checks that a VPC network does not use the legacy (non-subnetted) network mode, which predates GCP\'s regional subnet model and offers coarser access control.',
    remediation: 'Migrate legacy networks to an auto-mode or custom-mode subnetted VPC network; legacy networks cannot be converted in place and require a new network plus resource migration.',
    tags: ['compute', 'vpc', 'legacy'],
  },
  {
    checkId: 'compute_project_os_login_enabled',
    provider: 'gcp',
    service: 'compute',
    title: 'Project Has OS Login Enabled',
    severity: 'LOW',
    description: 'Checks that the enable-oslogin project-wide metadata key is set to true, so SSH access across the project is managed via IAM.',
    remediation: 'Set enable-oslogin=true in the project\'s common instance metadata (gcloud compute project-info add-metadata --metadata enable-oslogin=TRUE).',
    tags: ['compute', 'ssh', 'os-login'],
  },
  {
    checkId: 'compute_project_os_login_2fa_enabled',
    provider: 'gcp',
    service: 'compute',
    title: 'Project Has OS Login With 2FA Enabled',
    severity: 'HIGH',
    description: 'Checks that the enable-oslogin-2fa project-wide metadata key is set to true, enforcing two-factor authentication for SSH access via OS Login.',
    remediation: 'Set enable-oslogin-2fa=true in the project\'s common instance metadata to require 2FA for OS Login SSH sessions.',
    tags: ['compute', 'ssh', 'os-login', 'mfa'],
  },
  {
    checkId: 'compute_snapshot_not_outdated',
    provider: 'gcp',
    service: 'compute',
    title: 'Compute Engine Disk Snapshot Is Not Outdated',
    severity: 'LOW',
    description: 'Checks that a Compute Engine disk snapshot is not older than 90 days, helping control storage costs and limit exposure from stale data.',
    remediation: 'Delete outdated snapshots that are no longer required for recovery or compliance, or move them to a lifecycle-managed archival policy.',
    tags: ['compute', 'snapshot', 'hygiene'],
  },
  {
    checkId: 'compute_subnet_flow_logs_enabled',
    provider: 'gcp',
    service: 'compute',
    title: 'Subnet Has VPC Flow Logs Enabled',
    severity: 'MEDIUM',
    description: 'Checks that a VPC subnet has Flow Logs enabled, capturing network flow records for traffic visibility, forensics, and anomaly detection.',
    remediation: 'Enable VPC Flow Logs on the subnet (gcloud compute networks subnets update --enable-flow-logs).',
    tags: ['compute', 'network', 'logging'],
  },
];
