// Check logic derived from Prowler (Apache-2.0, https://github.com/prowler-cloud/prowler)
import { CheckMetadata } from '../../types';

export const iamChecks: CheckMetadata[] = [
  {
    checkId: 'iam_account_access_approval_enabled',
    provider: 'gcp',
    service: 'iam',
    title: 'Project Has Access Approval Enabled',
    severity: 'HIGH',
    description: 'Checks that the project has Access Approval configured, requiring explicit customer authorization before Google support or engineering personnel can access project data.',
    remediation: 'Enable Access Approval for the project (gcloud access-approval settings update --project=<PROJECT_ID> --enrolled-services=all) and, where feasible, at the organization level for consistency. Assign least-privilege approvers and monitor Access Transparency records.',
    tags: ['iam', 'access-approval', 'identity-access'],
  },
  {
    checkId: 'iam_organization_essential_contacts_configured',
    provider: 'gcp',
    service: 'iam',
    title: 'Organization Has Essential Contacts Configured',
    severity: 'MEDIUM',
    description: 'Checks that the organization has at least one Essential Contact configured for categories such as Security, Billing, Legal, Suspension, Technical, or Product Updates, so critical notices reach the right people.',
    remediation: 'Configure Essential Contacts at the organization level with group aliases for Security, Billing, Legal, Suspension, Technical, and Product Updates categories. Review contacts quarterly and restrict them to approved domains.',
    tags: ['iam', 'essential-contacts', 'resilience'],
  },
  {
    checkId: 'iam_cloud_asset_inventory_enabled',
    provider: 'gcp',
    service: 'iam',
    title: 'Project Has Cloud Asset Inventory API Enabled',
    severity: 'HIGH',
    description: 'Checks that the Cloud Asset Inventory API (cloudasset.googleapis.com) is enabled for the project, providing resource and IAM policy inventory with time-series metadata and change history.',
    remediation: 'Enable the Cloud Asset Inventory API (gcloud services enable cloudasset.googleapis.com --project <PROJECT_ID>) across all projects and, if applicable, at the organization level to maintain authoritative asset and IAM histories.',
    tags: ['iam', 'asset-inventory', 'forensics-ready'],
  },
  {
    checkId: 'iam_role_kms_enforce_separation_of_duties',
    provider: 'gcp',
    service: 'iam',
    title: 'KMS Roles Enforce Separation Of Duties',
    severity: 'MEDIUM',
    description: 'Checks that no project member is simultaneously granted roles/cloudkms.admin together with a CryptoKey Encrypter/Decrypter role, which would let the same principal both manage and use encryption keys.',
    remediation: 'Remove either the Cloud KMS Admin role or the CryptoKey Encrypter/Decrypter role from any principal that holds both, so key management and key usage stay in separate hands. Isolate key management in a dedicated project where possible.',
    tags: ['iam', 'separation-of-duties', 'encryption'],
  },
  {
    checkId: 'iam_role_sa_enforce_separation_of_duties',
    provider: 'gcp',
    service: 'iam',
    title: 'Service Account Roles Enforce Separation Of Duties',
    severity: 'MEDIUM',
    description: 'Checks that no project member is simultaneously granted both roles/iam.serviceAccountAdmin and roles/iam.serviceAccountUser, which would let the same principal both create/manage service accounts and use or impersonate them.',
    remediation: 'Remove either the Service Account Admin or Service Account User role from any principal that holds both at the project level. Grant these roles individually and scope them to specific service accounts rather than the whole project.',
    tags: ['iam', 'separation-of-duties'],
  },
  {
    checkId: 'iam_service_account_unused',
    provider: 'gcp',
    service: 'iam',
    title: 'Service Account Was Used Within The Configured Inactivity Window',
    severity: 'MEDIUM',
    description: 'Checks that enabled service accounts show recent API usage activity within a configurable inactivity window (default 180 days), flagging dormant but still-permissioned accounts.',
    remediation: 'Disable and, after confirming no dependency, delete service accounts with no recorded activity in the inactivity window. Revoke their role bindings and keys first, and prefer short-lived impersonation over standing accounts going forward.',
    tags: ['iam', 'service-account', 'unused-credentials'],
  },
  {
    checkId: 'iam_sa_user_managed_key_unused',
    provider: 'gcp',
    service: 'iam',
    title: 'User-Managed Service Account Key Was Used Within The Inactivity Window',
    severity: 'MEDIUM',
    description: 'Checks that user-managed service account keys show recorded usage activity within the configured inactivity window (default 180 days), flagging keys that exist but are never actually used.',
    remediation: 'Delete user-managed keys that show no usage in the inactivity window. Prefer Workload Identity Federation or service account impersonation over standing keys, and enforce iam.disableServiceAccountKeyCreation where keys are not required.',
    tags: ['iam', 'service-account-key', 'unused-credentials'],
  },
  {
    checkId: 'iam_no_service_roles_at_project_level',
    provider: 'gcp',
    service: 'iam',
    title: 'No IAM Members Hold Service-Account Impersonation Roles At Project Level',
    severity: 'MEDIUM',
    description: 'Checks that roles/iam.serviceAccountUser and roles/iam.serviceAccountTokenCreator are not bound at the project level, since a project-wide grant lets the holder attach or impersonate any service account in the project.',
    remediation: 'Remove project-level bindings for roles/iam.serviceAccountUser and roles/iam.serviceAccountTokenCreator. If a principal needs to use or impersonate a service account, grant the role on that specific service account resource instead.',
    tags: ['iam', 'privilege-escalation', 'service-account'],
  },
  {
    checkId: 'iam_sa_no_administrative_privileges',
    provider: 'gcp',
    service: 'iam',
    title: 'Service Account Has No Administrative Privileges',
    severity: 'HIGH',
    description: 'Checks that no service account is bound to roles/owner, roles/editor, or any role containing "admin" anywhere in the project IAM policy hierarchy.',
    remediation: 'Remove Owner, Editor, and any admin-containing role bindings from the service account. Replace them with narrowly scoped predefined or custom roles that grant only the permissions the workload actually needs.',
    tags: ['iam', 'service-account', 'least-privilege'],
  },
  {
    checkId: 'iam_sa_no_user_managed_keys',
    provider: 'gcp',
    service: 'iam',
    title: 'Service Account Has No User-Managed Keys',
    severity: 'MEDIUM',
    description: 'Checks that a service account has no keys of type USER_MANAGED — only Google-managed keys or no keys at all.',
    remediation: 'Delete all user-managed keys for the service account and migrate the workload to Workload Identity Federation or Application Default Credentials. If a key is unavoidable, store it in Secret Manager and rotate it aggressively.',
    tags: ['iam', 'service-account-key', 'secrets'],
  },
  // ── Below: added to close the gap between GcpIAMScanner's actual checks and
  // this registry (only iam_sa_no_user_managed_keys had a match before —
  // these 7 give the scanner's remaining finding() call sites a checkId).
  {
    checkId: 'iam_no_primitive_roles_at_project_level',
    provider: 'gcp',
    service: 'iam',
    title: 'No Primitive Roles Bound At Project Level',
    severity: 'HIGH',
    description: 'Checks that no member is bound to a primitive role (roles/owner, roles/editor, roles/viewer) at the project level. Primitive roles grant overly broad permissions across all GCP services.',
    remediation: 'Replace primitive role bindings with predefined or custom roles that follow least privilege. Identify the specific GCP services each principal needs and grant those service-specific roles instead.',
    tags: ['iam', 'least-privilege', 'primitive-role'],
  },
  {
    checkId: 'iam_no_public_access_bindings',
    provider: 'gcp',
    service: 'iam',
    title: 'Project IAM Policy Does Not Grant Public Access',
    severity: 'CRITICAL',
    description: 'Checks that no IAM binding in the project policy includes allUsers or allAuthenticatedUsers, which would make the associated resources accessible to the general public.',
    remediation: 'Remove allUsers and allAuthenticatedUsers from all IAM bindings. Grant access only to specific, named identities — service accounts, Google groups, or individual users.',
    tags: ['iam', 'public-access'],
  },
  {
    checkId: 'iam_owner_role_assignments_limited',
    provider: 'gcp',
    service: 'iam',
    title: 'Owner Role Assignments Are Limited',
    severity: 'HIGH',
    description: 'Checks that the project has at most 3 members with the Owner role. A compromised Owner account has unrestricted access to all GCP resources, data, and billing.',
    remediation: 'Reduce Owner role assignments to at most 3 break-glass accounts. Use predefined roles for day-to-day operations and enable Privileged Access Management (PAM) for just-in-time access.',
    tags: ['iam', 'privilege-escalation'],
  },
  {
    checkId: 'iam_sensitive_roles_not_granted_to_individual_users',
    provider: 'gcp',
    service: 'iam',
    title: 'Sensitive Roles Not Granted To Individual User Accounts',
    severity: 'MEDIUM',
    description: 'Checks that sensitive roles (roles/owner, roles/editor, roles/iam.securityAdmin, roles/resourcemanager.organizationAdmin) are not granted directly to individual user accounts, which are harder to manage than groups and bypass group-based access controls.',
    remediation: 'Grant sensitive roles to Google Groups rather than individual user accounts. This enables centralized access management and an audit trail at the group level.',
    tags: ['iam', 'access-management'],
  },
  {
    checkId: 'iam_service_account_count_reasonable',
    provider: 'gcp',
    service: 'iam',
    title: 'Service Account Count Is Reasonable',
    severity: 'LOW',
    description: 'Checks that a project does not have an unusually high number of service accounts (>50). A large number increases the attack surface and makes access auditing difficult.',
    remediation: 'Review and delete unused or orphaned service accounts. Prefer Workload Identity for GKE workloads over standing service account keys.',
    tags: ['iam', 'service-account'],
  },
  {
    checkId: 'iam_sa_key_rotation_90_days',
    provider: 'gcp',
    service: 'iam',
    title: 'Service Account Key Rotated Within 90 Days',
    severity: 'HIGH',
    description: 'Checks that user-managed service account keys have been rotated within the last 90 days. Stale keys represent credentials that may have been exfiltrated and are still valid.',
    remediation: 'Delete and regenerate the service account key. Implement a key rotation policy with a maximum age of 90 days, and use Secret Manager to distribute new keys to applications automatically.',
    tags: ['iam', 'key-rotation'],
  },
  {
    checkId: 'iam_default_compute_sa_no_editor_role',
    provider: 'gcp',
    service: 'iam',
    title: 'Default Compute Engine Service Account Does Not Hold Editor Role',
    severity: 'HIGH',
    description: 'Checks whether the project\'s default Compute Engine service account exists — by default it is granted the Editor role, giving all VM instances broad write access to GCP APIs.',
    remediation: 'Audit the default service account\'s IAM role and remove or downscope the Editor role. Create dedicated service accounts per VM workload with only the required permissions.',
    tags: ['iam', 'service-account', 'default-sa'],
  },
];
