// Check logic derived from Prowler (Apache-2.0, https://github.com/prowler-cloud/prowler)
import { CheckMetadata } from '../../types';

export const iamChecks: CheckMetadata[] = [
  {
    checkId: 'iam_account_access_approval_enabled',
    provider: 'gcp',
    service: 'iam',
    title: 'Project Has Access Approval Enabled',
    severity: 'HIGH',
    description: 'Checks that the project has Access Approval configured, requiring explicit customer authorization before Google support or engineering personnel can access project data.',
    remediation: 'Enable Access Approval for the project (gcloud access-approval settings update --project=<PROJECT_ID> --enrolled-services=all) and, where feasible, at the organization level for consistency. Assign least-privilege approvers and monitor Access Transparency records.',
    tags: ['iam', 'access-approval', 'identity-access'],
  },
  {
    checkId: 'iam_organization_essential_contacts_configured',
    provider: 'gcp',
    service: 'iam',
    title: 'Organization Has Essential Contacts Configured',
    severity: 'MEDIUM',
    description: 'Checks that the organization has at least one Essential Contact configured for categories such as Security, Billing, Legal, Suspension, Technical, or Product Updates, so critical notices reach the right people.',
    remediation: 'Configure Essential Contacts at the organization level with group aliases for Security, Billing, Legal, Suspension, Technical, and Product Updates categories. Review contacts quarterly and restrict them to approved domains.',
    tags: ['iam', 'essential-contacts', 'resilience'],
  },
  {
    checkId: 'iam_cloud_asset_inventory_enabled',
    provider: 'gcp',
    service: 'iam',
    title: 'Project Has Cloud Asset Inventory API Enabled',
    severity: 'HIGH',
    description: 'Checks that the Cloud Asset Inventory API (cloudasset.googleapis.com) is enabled for the project, providing resource and IAM policy inventory with time-series metadata and change history.',
    remediation: 'Enable the Cloud Asset Inventory API (gcloud services enable cloudasset.googleapis.com --project <PROJECT_ID>) across all projects and, if applicable, at the organization level to maintain authoritative asset and IAM histories.',
    tags: ['iam', 'asset-inventory', 'forensics-ready'],
  },
  {
    checkId: 'iam_role_kms_enforce_separation_of_duties',
    provider: 'gcp',
    service: 'iam',
    title: 'KMS Roles Enforce Separation Of Duties',
    severity: 'MEDIUM',
    description: 'Checks that no project member is simultaneously granted roles/cloudkms.admin together with a CryptoKey Encrypter/Decrypter role, which would let the same principal both manage and use encryption keys.',
    remediation: 'Remove either the Cloud KMS Admin role or the CryptoKey Encrypter/Decrypter role from any principal that holds both, so key management and key usage stay in separate hands. Isolate key management in a dedicated project where possible.',
    tags: ['iam', 'separation-of-duties', 'encryption'],
  },
  {
    checkId: 'iam_role_sa_enforce_separation_of_duties',
    provider: 'gcp',
    service: 'iam',
    title: 'Service Account Roles Enforce Separation Of Duties',
    severity: 'MEDIUM',
    description: 'Checks that no project member is simultaneously granted both roles/iam.serviceAccountAdmin and roles/iam.serviceAccountUser, which would let the same principal both create/manage service accounts and use or impersonate them.',
    remediation: 'Remove either the Service Account Admin or Service Account User role from any principal that holds both at the project level. Grant these roles individually and scope them to specific service accounts rather than the whole project.',
    tags: ['iam', 'separation-of-duties'],
  },
  {
    checkId: 'iam_service_account_unused',
    provider: 'gcp',
    service: 'iam',
    title: 'Service Account Was Used Within The Configured Inactivity Window',
    severity: 'MEDIUM',
    description: 'Checks that enabled service accounts show recent API usage activity within a configurable inactivity window (default 180 days), flagging dormant but still-permissioned accounts.',
    remediation: 'Disable and, after confirming no dependency, delete service accounts with no recorded activity in the inactivity window. Revoke their role bindings and keys first, and prefer short-lived impersonation over standing accounts going forward.',
    tags: ['iam', 'service-account', 'unused-credentials'],
  },
  {
    checkId: 'iam_sa_user_managed_key_unused',
    provider: 'gcp',
    service: 'iam',
    title: 'User-Managed Service Account Key Was Used Within The Inactivity Window',
    severity: 'MEDIUM',
    description: 'Checks that user-managed service account keys show recorded usage activity within the configured inactivity window (default 180 days), flagging keys that exist but are never actually used.',
    remediation: 'Delete user-managed keys that show no usage in the inactivity window. Prefer Workload Identity Federation or service account impersonation over standing keys, and enforce iam.disableServiceAccountKeyCreation where keys are not required.',
    tags: ['iam', 'service-account-key', 'unused-credentials'],
  },
  {
    checkId: 'iam_no_service_roles_at_project_level',
    provider: 'gcp',
    service: 'iam',
    title: 'No IAM Members Hold Service-Account Impersonation Roles At Project Level',
    severity: 'MEDIUM',
    description: 'Checks that roles/iam.serviceAccountUser and roles/iam.serviceAccountTokenCreator are not bound at the project level, since a project-wide grant lets the holder attach or impersonate any service account in the project.',
    remediation: 'Remove project-level bindings for roles/iam.serviceAccountUser and roles/iam.serviceAccountTokenCreator. If a principal needs to use or impersonate a service account, grant the role on that specific service account resource instead.',
    tags: ['iam', 'privilege-escalation', 'service-account'],
  },
  {
    checkId: 'iam_sa_no_administrative_privileges',
    provider: 'gcp',
    service: 'iam',
    title: 'Service Account Has No Administrative Privileges',
    severity: 'HIGH',
    description: 'Checks that no service account is bound to roles/owner, roles/editor, or any role containing "admin" anywhere in the project IAM policy hierarchy.',
    remediation: 'Remove Owner, Editor, and any admin-containing role bindings from the service account. Replace them with narrowly scoped predefined or custom roles that grant only the permissions the workload actually needs.',
    tags: ['iam', 'service-account', 'least-privilege'],
  },
  {
    checkId: 'iam_sa_no_user_managed_keys',
    provider: 'gcp',
    service: 'iam',
    title: 'Service Account Has No User-Managed Keys',
    severity: 'MEDIUM',
    description: 'Checks that a service account has no keys of type USER_MANAGED — only Google-managed keys or no keys at all.',
    remediation: 'Delete all user-managed keys for the service account and migrate the workload to Workload Identity Federation or Application Default Credentials. If a key is unavoidable, store it in Secret Manager and rotate it aggressively.',
    tags: ['iam', 'service-account-key', 'secrets'],
  },
];
