// Check logic derived from Prowler (Apache-2.0, https://github.com/prowler-cloud/prowler)
import { CheckMetadata } from '../../types';

export const loggingChecks: CheckMetadata[] = [
  {
    checkId: 'logging_log_metric_filter_and_alert_for_project_ownership_changes_enabled',
    provider: 'gcp',
    service: 'logging',
    title: 'Log Metric Filter For Project Ownership Changes Has An Associated Alert Policy',
    severity: 'MEDIUM',
    description: 'Checks that a log-based metric matching project ownership assignment/removal events (roles/owner additions or removals, ownership invites) exists and that a Cloud Monitoring alert policy is attached to it, so ownership changes actually generate a notification rather than just a silent metric.',
    remediation: 'Create a log-based metric with filter (protoPayload.serviceName="cloudresourcemanager.googleapis.com") AND (ProjectOwnership OR projectOwnerInvitee) OR (protoPayload.serviceData.policyDelta.bindingDeltas.action="ADD" AND protoPayload.serviceData.policyDelta.bindingDeltas.role="roles/owner") OR (protoPayload.serviceData.policyDelta.bindingDeltas.action="REMOVE" AND protoPayload.serviceData.policyDelta.bindingDeltas.role="roles/owner"), then create a Cloud Monitoring alert policy whose condition filter references that metric (metric.type="logging.googleapis.com/user/<metric-name>").',
    tags: ['logging', 'metrics', 'alerting', 'cis-2.4', 'identity-access'],
  },
  {
    checkId: 'logging_log_metric_filter_and_alert_for_audit_configuration_changes_enabled',
    provider: 'gcp',
    service: 'logging',
    title: 'Log Metric Filter For Audit Configuration Changes Has An Associated Alert Policy',
    severity: 'MEDIUM',
    description: 'Checks that a log-based metric matching audit configuration changes (SetIamPolicy calls that modify auditConfigDeltas) exists and that a Cloud Monitoring alert policy is attached to it, so tampering with audit logging coverage itself is detected rather than only recorded as a metric nobody watches.',
    remediation: 'Create a log-based metric with filter protoPayload.methodName="SetIamPolicy" AND protoPayload.serviceData.policyDelta.auditConfigDeltas:*, then create a Cloud Monitoring alert policy whose condition filter references that metric (metric.type="logging.googleapis.com/user/<metric-name>").',
    tags: ['logging', 'metrics', 'alerting', 'cis-2.5'],
  },
  {
    checkId: 'logging_log_metric_filter_and_alert_for_custom_role_changes_enabled',
    provider: 'gcp',
    service: 'logging',
    title: 'Log Metric Filter For Custom Role Changes Has An Associated Alert Policy',
    severity: 'MEDIUM',
    description: 'Checks that a log-based metric matching IAM custom role create/update/delete events exists and that a Cloud Monitoring alert policy is attached to it, so privilege-model changes are actively alerted on instead of only counted.',
    remediation: 'Create a log-based metric with filter resource.type="iam_role" AND (protoPayload.methodName="google.iam.admin.v1.CreateRole" OR protoPayload.methodName="google.iam.admin.v1.DeleteRole" OR protoPayload.methodName="google.iam.admin.v1.UpdateRole"), then create a Cloud Monitoring alert policy whose condition filter references that metric (metric.type="logging.googleapis.com/user/<metric-name>").',
    tags: ['logging', 'metrics', 'alerting', 'cis-2.6'],
  },
  {
    checkId: 'logging_log_metric_filter_and_alert_for_vpc_firewall_rule_changes_enabled',
    provider: 'gcp',
    service: 'logging',
    title: 'Log Metric Filter For VPC Firewall Rule Changes Has An Associated Alert Policy',
    severity: 'MEDIUM',
    description: 'Checks that a log-based metric matching VPC firewall rule insert/patch/delete events exists and that a Cloud Monitoring alert policy is attached to it, so unauthorized or accidental firewall changes trigger a notification instead of only incrementing a metric.',
    remediation: 'Create a log-based metric with filter resource.type="gce_firewall_rule" AND (protoPayload.methodName:"compute.firewalls.patch" OR protoPayload.methodName:"compute.firewalls.insert" OR protoPayload.methodName:"compute.firewalls.delete"), then create a Cloud Monitoring alert policy whose condition filter references that metric (metric.type="logging.googleapis.com/user/<metric-name>").',
    tags: ['logging', 'metrics', 'alerting', 'cis-2.7', 'network'],
  },
  {
    checkId: 'logging_log_metric_filter_and_alert_for_vpc_network_route_changes_enabled',
    provider: 'gcp',
    service: 'logging',
    title: 'Log Metric Filter For VPC Network Route Changes Has An Associated Alert Policy',
    severity: 'MEDIUM',
    description: 'Checks that a log-based metric matching VPC route insert/delete events exists and that a Cloud Monitoring alert policy is attached to it, so route changes that could redirect or blackhole traffic actually raise an alert.',
    remediation: 'Create a log-based metric with filter resource.type="gce_route" AND (protoPayload.methodName:"compute.routes.delete" OR protoPayload.methodName:"compute.routes.insert"), then create a Cloud Monitoring alert policy whose condition filter references that metric (metric.type="logging.googleapis.com/user/<metric-name>").',
    tags: ['logging', 'metrics', 'alerting', 'cis-2.8', 'network'],
  },
  {
    checkId: 'logging_log_metric_filter_and_alert_for_vpc_network_changes_enabled',
    provider: 'gcp',
    service: 'logging',
    title: 'Log Metric Filter For VPC Network Changes Has An Associated Alert Policy',
    severity: 'MEDIUM',
    description: 'Checks that a log-based metric matching VPC network create/patch/delete/peering events exists and that a Cloud Monitoring alert policy is attached to it, so network-topology changes are alerted on, not just tallied.',
    remediation: 'Create a log-based metric with filter resource.type="gce_network" AND (protoPayload.methodName:"compute.networks.insert" OR protoPayload.methodName:"compute.networks.patch" OR protoPayload.methodName:"compute.networks.delete" OR protoPayload.methodName:"compute.networks.removePeering" OR protoPayload.methodName:"compute.networks.addPeering"), then create a Cloud Monitoring alert policy whose condition filter references that metric (metric.type="logging.googleapis.com/user/<metric-name>").',
    tags: ['logging', 'metrics', 'alerting', 'cis-2.9', 'network'],
  },
  {
    checkId: 'logging_log_metric_filter_and_alert_for_bucket_permission_changes_enabled',
    provider: 'gcp',
    service: 'logging',
    title: 'Log Metric Filter For Cloud Storage IAM Permission Changes Has An Associated Alert Policy',
    severity: 'MEDIUM',
    description: 'Checks that a log-based metric matching Cloud Storage bucket IAM permission changes (storage.setIamPermissions) exists and that a Cloud Monitoring alert policy is attached to it, so bucket-access changes that could expose data are actively alerted.',
    remediation: 'Create a log-based metric with filter resource.type="gcs_bucket" AND protoPayload.methodName="storage.setIamPermissions", then create a Cloud Monitoring alert policy whose condition filter references that metric (metric.type="logging.googleapis.com/user/<metric-name>").',
    tags: ['logging', 'metrics', 'alerting', 'cis-2.10', 'identity-access', 'storage'],
  },
  {
    checkId: 'logging_log_metric_filter_and_alert_for_sql_instance_configuration_changes_enabled',
    provider: 'gcp',
    service: 'logging',
    title: 'Log Metric Filter For Cloud SQL Configuration Changes Has An Associated Alert Policy',
    severity: 'MEDIUM',
    description: 'Checks that a log-based metric matching Cloud SQL instance configuration update events exists and that a Cloud Monitoring alert policy is attached to it, so changes such as opening public access or relaxing TLS on a database instance are actively alerted.',
    remediation: 'Create a log-based metric with filter protoPayload.methodName="cloudsql.instances.update", then create a Cloud Monitoring alert policy whose condition filter references that metric (metric.type="logging.googleapis.com/user/<metric-name>").',
    tags: ['logging', 'metrics', 'alerting', 'cis-2.11', 'database'],
  },
  {
    checkId: 'logging_log_metric_filter_and_alert_for_compute_configuration_changes_enabled',
    provider: 'gcp',
    service: 'logging',
    title: 'Log Metric Filter For Compute Engine Configuration Changes Has An Associated Alert Policy',
    severity: 'MEDIUM',
    description: 'Checks that a log-based metric matching Compute Engine configuration change events (any compute.googleapis.com API activity) exists and that a Cloud Monitoring alert policy is attached to it, so unauthorized modifications to instances, disks, and networks are actively alerted.',
    remediation: 'Create a log-based metric with filter protoPayload.serviceName="compute.googleapis.com", then create a Cloud Monitoring alert policy whose condition filter references that metric (metric.type="logging.googleapis.com/user/<metric-name>").',
    tags: ['logging', 'metrics', 'alerting', 'compute'],
  },
  {
    checkId: 'logging_sink_created',
    provider: 'gcp',
    service: 'logging',
    title: 'Project Has At Least One Logging Sink Exporting All Log Entries',
    severity: 'MEDIUM',
    description: 'Checks that the project has at least one log sink (project-level or an org-level sink with includeChildren) exporting a full, unfiltered copy of all log entries to a durable destination for centralized retention and forensics.',
    remediation: 'Create a log sink with an empty inclusion filter so it exports all log entries (gcloud logging sinks create <name> <destination>), pointing at a Cloud Storage bucket, BigQuery dataset, or Pub/Sub topic outside the source project.',
    tags: ['logging', 'retention', 'compliance', 'forensics-ready'],
  },
];
