// Check logic derived from Prowler (Apache-2.0, https://github.com/prowler-cloud/prowler)
import { CheckMetadata } from '../../types';

export const sqlChecks: CheckMetadata[] = [
  {
    checkId: 'cloudsql_instance_public_ip',
    provider: 'gcp',
    service: 'sql',
    title: 'Cloud SQL Instance Does Not Have a Public IP',
    severity: 'HIGH',
    description: 'Checks that Cloud SQL instances do not have a public (PRIMARY) IP address assigned, which exposes the database endpoint to the internet.',
    remediation: 'Disable the public IP on the Cloud SQL instance and connect via Cloud SQL Auth Proxy, Private Service Connect, or a private IP within the VPC.',
    tags: ['cloudsql', 'network', 'public-ip'],
  },
  {
    checkId: 'cloudsql_instance_private_ip_assignment',
    provider: 'gcp',
    service: 'sql',
    title: 'Cloud SQL Instance Restricted to Private IP',
    severity: 'HIGH',
    description: 'Checks that every IP address assigned to a Cloud SQL instance is of type PRIVATE, i.e. the instance has no public-reachable address of any kind.',
    remediation: 'Remove all non-private IP assignments from the instance and configure Private Service Connect / VPC peering so the database is reachable only from within the VPC.',
    tags: ['cloudsql', 'network', 'private-ip'],
  },
  {
    checkId: 'cloudsql_instance_public_access',
    provider: 'gcp',
    service: 'sql',
    title: 'Cloud SQL Instance Not Open to All IP Addresses',
    severity: 'CRITICAL',
    description: 'Checks that Cloud SQL instances do not have an authorized network entry of 0.0.0.0/0, which allows connections from any internet host.',
    remediation: 'Remove the 0.0.0.0/0 authorized network entry. Restrict authorized networks to specific application server IPs, or rely exclusively on Cloud SQL Auth Proxy / Private IP.',
    tags: ['cloudsql', 'firewall', 'network'],
  },
  {
    checkId: 'cloudsql_instance_ssl_connections',
    provider: 'gcp',
    service: 'sql',
    title: 'Cloud SQL Instance Requires SSL for All Connections',
    severity: 'HIGH',
    description: 'Checks that Cloud SQL instances enforce SSL/TLS for every client connection rather than allowing a mix of encrypted and unencrypted traffic.',
    remediation: 'Set the SSL mode to ENCRYPTED_ONLY or TRUSTED_CLIENT_CERTIFICATE_REQUIRED (or requireSsl=true) and update client connection strings to use SSL certificates.',
    tags: ['cloudsql', 'encryption-in-transit', 'ssl'],
  },
  {
    checkId: 'cloudsql_instance_automated_backups',
    provider: 'gcp',
    service: 'sql',
    title: 'Cloud SQL Instance Has Automated Backups Enabled',
    severity: 'HIGH',
    description: 'Checks that Cloud SQL instances have automated backups configured, so data can be recovered after accidental deletion, corruption, or ransomware.',
    remediation: 'Enable automated backups on the Cloud SQL instance with a backup window during off-peak hours and a retention period of at least 7 days.',
    tags: ['cloudsql', 'backup'],
  },
  {
    checkId: 'cloudsql_instance_high_availability_enabled',
    provider: 'gcp',
    service: 'sql',
    title: 'Cloud SQL Instance Has High Availability Configured',
    severity: 'MEDIUM',
    description: 'Checks that Cloud SQL instances use REGIONAL availabilityType so a standby replica in another zone can take over automatically during a zone-level outage.',
    remediation: 'Set availabilityType to REGIONAL for production Cloud SQL instances to enable automatic failover to a standby instance in another zone.',
    tags: ['cloudsql', 'availability'],
  },
  {
    checkId: 'cloudsql_instance_cmek_encryption_enabled',
    provider: 'gcp',
    service: 'sql',
    title: 'Cloud SQL Instance Encrypted With a Customer-Managed Key',
    severity: 'MEDIUM',
    description: 'Checks that Cloud SQL instances use a customer-managed encryption key (CMEK) via Cloud KMS for at-rest encryption instead of the default Google-managed key.',
    remediation: 'Recreate or configure the Cloud SQL instance with a Cloud KMS customer-managed key so the organization retains control of key custody and revocation.',
    tags: ['cloudsql', 'encryption-at-rest', 'cmek', 'kms'],
  },
  {
    checkId: 'cloudsql_instance_postgres_log_connections_flag',
    provider: 'gcp',
    service: 'sql',
    title: 'Cloud SQL PostgreSQL Instance Logs Connections',
    severity: 'MEDIUM',
    description: 'Checks that Cloud SQL PostgreSQL instances have the log_connections database flag set to "on" so every connection attempt and authentication result is recorded.',
    remediation: 'Set the log_connections database flag to "on" to record all new client connections.',
    tags: ['cloudsql', 'logging', 'postgresql'],
  },
  {
    checkId: 'cloudsql_instance_postgres_log_disconnections_flag',
    provider: 'gcp',
    service: 'sql',
    title: 'Cloud SQL PostgreSQL Instance Logs Disconnections',
    severity: 'LOW',
    description: 'Checks that Cloud SQL PostgreSQL instances have the log_disconnections database flag set to "on" so session duration and disconnect events are captured.',
    remediation: 'Set the log_disconnections database flag to "on".',
    tags: ['cloudsql', 'logging', 'postgresql'],
  },
  {
    checkId: 'cloudsql_instance_postgres_enable_pgaudit_flag',
    provider: 'gcp',
    service: 'sql',
    title: 'Cloud SQL PostgreSQL Instance Has pgAudit Enabled',
    severity: 'HIGH',
    description: 'Checks that Cloud SQL PostgreSQL instances have the cloudsql.enable_pgaudit database flag set to "on" for granular audit trails of database activity.',
    remediation: 'Set the cloudsql.enable_pgaudit database flag to "on" to enable detailed audit logging of statements executed against the database.',
    tags: ['cloudsql', 'logging', 'postgresql', 'audit'],
  },
  {
    checkId: 'cloudsql_instance_postgres_log_error_verbosity_flag',
    provider: 'gcp',
    service: 'sql',
    title: 'Cloud SQL PostgreSQL Instance Uses Default Log Error Verbosity',
    severity: 'MEDIUM',
    description: 'Checks that Cloud SQL PostgreSQL instances have the log_error_verbosity database flag set to "default" rather than "terse" (hides forensic detail) or "verbose" (leaks internal metadata).',
    remediation: 'Set the log_error_verbosity database flag to "default".',
    tags: ['cloudsql', 'logging', 'postgresql'],
  },
  {
    checkId: 'cloudsql_instance_postgres_log_min_duration_statement_flag',
    provider: 'gcp',
    service: 'sql',
    title: 'Cloud SQL PostgreSQL Instance Disables Statement Duration Logging',
    severity: 'MEDIUM',
    description: 'Checks that Cloud SQL PostgreSQL instances have the log_min_duration_statement database flag set to "-1", since enabling duration-based statement logging can capture full SQL text (including literals) into log storage.',
    remediation: 'Set the log_min_duration_statement database flag to "-1" unless statement-duration logging is a deliberate, access-controlled requirement.',
    tags: ['cloudsql', 'logging', 'postgresql'],
  },
  {
    checkId: 'cloudsql_instance_postgres_log_min_error_statement_flag',
    provider: 'gcp',
    service: 'sql',
    title: 'Cloud SQL PostgreSQL Instance Logs Errors at the Correct Threshold',
    severity: 'MEDIUM',
    description: 'Checks that Cloud SQL PostgreSQL instances have the log_min_error_statement database flag set to "error", the recommended severity threshold for logging SQL text alongside error messages.',
    remediation: 'Set the log_min_error_statement database flag to "error".',
    tags: ['cloudsql', 'logging', 'postgresql'],
  },
  {
    checkId: 'cloudsql_instance_postgres_log_min_messages_flag',
    provider: 'gcp',
    service: 'sql',
    title: 'Cloud SQL PostgreSQL Instance Logs at a Sufficient Severity',
    severity: 'MEDIUM',
    description: 'Checks that Cloud SQL PostgreSQL instances have the log_min_messages database flag set to ERROR or higher; flags left unset or set to DEBUG*/INFO/NOTICE degrade audit log integrity.',
    remediation: 'Set the log_min_messages database flag to ERROR or a higher severity (e.g. WARNING, LOG).',
    tags: ['cloudsql', 'logging', 'postgresql'],
  },
  {
    checkId: 'cloudsql_instance_postgres_log_statement_flag',
    provider: 'gcp',
    service: 'sql',
    title: 'Cloud SQL PostgreSQL Instance Logs DDL Statements',
    severity: 'MEDIUM',
    description: 'Checks that Cloud SQL PostgreSQL instances have the log_statement database flag set to "ddl" so schema-changing statements are recorded without over-logging every statement.',
    remediation: 'Set the log_statement database flag to "ddl".',
    tags: ['cloudsql', 'logging', 'postgresql'],
  },
  {
    checkId: 'cloudsql_instance_mysql_local_infile_flag',
    provider: 'gcp',
    service: 'sql',
    title: 'Cloud SQL MySQL Instance Has local_infile Disabled',
    severity: 'HIGH',
    description: 'Checks that Cloud SQL MySQL instances have the local_infile database flag set to "off", preventing clients from loading local files via LOAD DATA LOCAL.',
    remediation: 'Set the local_infile database flag to "off" on the Cloud SQL MySQL instance.',
    tags: ['cloudsql', 'mysql', 'security-flag'],
  },
  {
    checkId: 'cloudsql_instance_mysql_skip_show_database_flag',
    provider: 'gcp',
    service: 'sql',
    title: 'Cloud SQL MySQL Instance Restricts SHOW DATABASES',
    severity: 'LOW',
    description: 'Checks that Cloud SQL MySQL instances have the skip_show_database database flag set to "on" so only users with the SHOW DATABASES privilege can enumerate database names.',
    remediation: 'Set the skip_show_database database flag to "on".',
    tags: ['cloudsql', 'mysql', 'security-flag'],
  },
  {
    checkId: 'cloudsql_instance_sqlserver_cross_db_ownership_chaining_flag',
    provider: 'gcp',
    service: 'sql',
    title: 'Cloud SQL SQL Server Instance Disables Cross-DB Ownership Chaining',
    severity: 'HIGH',
    description: 'Checks that Cloud SQL SQL Server instances have the "cross db ownership chaining" flag set to "off", preventing privilege escalation across database boundaries.',
    remediation: 'Set the "cross db ownership chaining" flag to "off".',
    tags: ['cloudsql', 'sqlserver', 'security-flag'],
  },
  {
    checkId: 'cloudsql_instance_sqlserver_contained_database_authentication_flag',
    provider: 'gcp',
    service: 'sql',
    title: 'Cloud SQL SQL Server Instance Disables Contained Database Authentication',
    severity: 'MEDIUM',
    description: 'Checks that Cloud SQL SQL Server instances have the "contained database authentication" flag set to "off", ensuring authentication stays at the server level under centralized policy.',
    remediation: 'Set the "contained database authentication" flag to "off" unless contained databases are specifically required.',
    tags: ['cloudsql', 'sqlserver', 'security-flag'],
  },
  {
    checkId: 'cloudsql_instance_sqlserver_external_scripts_enabled_flag',
    provider: 'gcp',
    service: 'sql',
    title: 'Cloud SQL SQL Server Instance Disables External Scripts',
    severity: 'HIGH',
    description: 'Checks that Cloud SQL SQL Server instances have the "external scripts enabled" flag set to "off", preventing invocation of language extensions (e.g. R/Python) that could enable arbitrary code execution.',
    remediation: 'Set the "external scripts enabled" flag to "off".',
    tags: ['cloudsql', 'sqlserver', 'security-flag'],
  },
  {
    checkId: 'cloudsql_instance_sqlserver_remote_access_flag',
    provider: 'gcp',
    service: 'sql',
    title: 'Cloud SQL SQL Server Instance Disables Remote Access',
    severity: 'MEDIUM',
    description: 'Checks that Cloud SQL SQL Server instances have the "remote access" flag set to "off", preventing remote procedure calls between servers that expand the instance\'s exposure.',
    remediation: 'Set the "remote access" flag to "off" unless cross-server RPCs are explicitly required.',
    tags: ['cloudsql', 'sqlserver', 'security-flag'],
  },
  {
    checkId: 'cloudsql_instance_sqlserver_trace_flag',
    provider: 'gcp',
    service: 'sql',
    title: 'Cloud SQL SQL Server Instance Enables Trace Flag 3625',
    severity: 'MEDIUM',
    description: 'Checks that Cloud SQL SQL Server instances have trace flag 3625 set to "on", which masks sensitive error detail (parameters, object names) from non-administrative users.',
    remediation: 'Set the "3625" trace flag to "on" to limit the detail exposed in error messages to non-admin users.',
    tags: ['cloudsql', 'sqlserver', 'security-flag'],
  },
  {
    checkId: 'cloudsql_instance_sqlserver_user_connections_flag',
    provider: 'gcp',
    service: 'sql',
    title: 'Cloud SQL SQL Server Instance Does Not Cap User Connections',
    severity: 'MEDIUM',
    description: 'Checks that Cloud SQL SQL Server instances have the "user connections" flag set to "0" (unlimited), avoiding an artificial cap that can exhaust available sessions.',
    remediation: 'Set the "user connections" flag to "0" to remove any artificial cap on concurrent user sessions.',
    tags: ['cloudsql', 'sqlserver', 'availability'],
  },
  {
    checkId: 'cloudsql_instance_sqlserver_user_options_flag',
    provider: 'gcp',
    service: 'sql',
    title: 'Cloud SQL SQL Server Instance Has No Global user options Override',
    severity: 'MEDIUM',
    description: 'Checks that Cloud SQL SQL Server instances do not have the "user options" flag configured, since a global override affects SET behavior for every session and can produce inconsistent results.',
    remediation: 'Clear the "user options" flag so session-level SET behaviors are not globally overridden.',
    tags: ['cloudsql', 'sqlserver', 'integrity'],
  },
  {
    checkId: 'cloudsql_instance_point_in_time_recovery_enabled',
    provider: 'gcp',
    service: 'sql',
    title: 'Cloud SQL Instance Has Point-in-Time Recovery Enabled',
    severity: 'MEDIUM',
    description: 'Checks that Cloud SQL instances with automated backups enabled also have point-in-time recovery (PITR) enabled, allowing restoration to any point within the retention window rather than only to daily snapshots.',
    remediation: 'Enable Point-in-Time Recovery on the Cloud SQL instance to allow restoration to any point within the retention window.',
    tags: ['cloudsql', 'backup', 'pitr'],
  },
];
