import { CheckMetadata } from '../../types';

// Titles must stay byte-identical to the pre-registry hardcoded titles:
// the scan worker dedupes OPEN findings on service:title:fingerprint, so a
// reworded title would re-open every existing finding as "new".
export const apigatewayChecks: CheckMetadata[] = [
  {
    checkId: 'apigateway_restapi_access_logging_enabled',
    provider: 'aws',
    service: 'apigateway',
    title: 'API Gateway Stage Access Logging Disabled',
    severity: 'HIGH',
    description: 'Checks that API Gateway REST API stages have access logging enabled; without logs, API abuse and unauthorized access cannot be detected or audited.',
    remediation: 'Enable access logging for the stage by setting a CloudWatch Logs or Kinesis ARN as the logging destination in API Gateway stage settings.',
    tags: ['apigateway', 'logging'],
  },
  {
    checkId: 'apigateway_restapi_logging_enabled',
    provider: 'aws',
    service: 'apigateway',
    title: 'API Gateway Stage Execution Logging Disabled',
    severity: 'MEDIUM',
    description: 'Checks that API Gateway stages have execution logging enabled so request/response details are captured for troubleshooting and security analysis.',
    remediation: 'Enable execution logging in the API Gateway console under Stages > Logs/Tracing. Set level to ERROR or INFO.',
    tags: ['apigateway', 'logging'],
  },
  {
    checkId: 'apigateway_restapi_waf_acl_attached',
    provider: 'aws',
    service: 'apigateway',
    title: 'API Gateway Stage Not Protected By WAF',
    severity: 'HIGH',
    description: 'Checks that API Gateway stages have a WAF WebACL associated; without WAF protection the API is exposed to web attacks (SQLi, XSS, bot traffic).',
    remediation: 'Associate a WAF WebACL with the API stage in the AWS WAF console or via: aws wafv2 associate-web-acl --web-acl-arn <acl-arn> --resource-arn <stage-arn>',
    tags: ['apigateway', 'waf'],
  },
  {
    checkId: 'apigateway_restapi_cache_encrypted',
    provider: 'aws',
    service: 'apigateway',
    title: 'API Gateway Stage Cache Not Encrypted',
    severity: 'MEDIUM',
    description: 'Checks that API Gateway stages with caching enabled encrypt cache data; sensitive API responses cached in plaintext can be exposed.',
    remediation: 'Enable cache encryption in API Gateway stage method settings.',
    tags: ['apigateway', 'encryption'],
  },
  {
    checkId: 'apigateway_restapi_stage_throttling_configured',
    provider: 'aws',
    service: 'apigateway',
    title: 'API Gateway Stage No Throttling Configured',
    severity: 'MEDIUM',
    description: 'Checks that API Gateway stages have throttling configured; without throttling, the API is vulnerable to abuse, DDoS, and unexpected cost spikes.',
    remediation: 'Configure throttling limits in API Gateway stage settings to limit requests per second.',
    tags: ['apigateway', 'throttling'],
  },
  {
    checkId: 'apigateway_restapi_authorizers_enabled',
    provider: 'aws',
    service: 'apigateway',
    title: 'API Gateway Method Has No Authorization',
    severity: 'HIGH',
    description: 'Checks that API Gateway REST API methods require authorization or an API key; methods with authorizationType=NONE and no API key are publicly invokable without authentication.',
    remediation: 'Add IAM, Cognito, or Lambda authorizer to these methods, or require an API key. Configure in API Gateway console under Resources > Method Request.',
    tags: ['apigateway', 'authentication', 'public-access'],
  },
  {
    checkId: 'apigateway_domain_name_pqc_tls_enabled',
    provider: 'aws',
    service: 'apigateway',
    title: 'API Gateway Custom Domain Name Not Using Post-Quantum TLS',
    severity: 'LOW',
    description: 'Checks that API Gateway custom domain names use a post-quantum TLS security policy such as SecurityPolicy_TLS13_1_2_PQ_2025_09 to protect against harvest-now, decrypt-later attacks.',
    remediation: 'Update the custom domain security policy to a post-quantum option (e.g., SecurityPolicy_TLS13_1_2_PQ_2025_09) via the console or AWS CLI.',
    tags: ['apigateway', 'encryption', 'post-quantum'],
  },
  {
    checkId: 'apigateway_restapi_client_certificate_enabled',
    provider: 'aws',
    service: 'apigateway',
    title: 'API Gateway Stage Client Certificate Not Enabled',
    severity: 'MEDIUM',
    description: 'Checks that API Gateway REST API stages have a client certificate configured for mutual TLS authentication to the backend; without it, the backend cannot verify requests originate from API Gateway.',
    remediation: 'Create a client certificate and attach it to the stage via the console (Stage Settings > Client Certificate) or AWS CLI.',
    tags: ['apigateway', 'encryption', 'mutual-tls'],
  },
  {
    checkId: 'apigateway_restapi_no_secrets_in_stage_variables',
    provider: 'aws',
    service: 'apigateway',
    title: 'API Gateway Stage Variables Contain Secrets',
    severity: 'HIGH',
    description: 'Checks that API Gateway REST API stage variables do not contain hardcoded secrets such as passwords, API keys, or tokens; such credentials are stored in plaintext and visible to anyone with read access.',
    remediation: 'Remove hardcoded credentials from stage variables and store them in AWS Secrets Manager or Parameter Store; reference them via Lambda authorizers or mapping templates.',
    tags: ['apigateway', 'secrets', 'credentials'],
  },
  {
    checkId: 'apigateway_restapi_public',
    provider: 'aws',
    service: 'apigateway',
    title: 'API Gateway REST API Endpoint Is Public',
    severity: 'MEDIUM',
    description: 'Checks that API Gateway REST APIs do not expose internet-accessible endpoints; public endpoints increase attack surface compared to private VPC-only endpoints.',
    remediation: 'Change the endpoint type to PRIVATE in the API settings, or restrict access via resource policies (e.g., aws:SourceVpc/aws:SourceVpce conditions).',
    tags: ['apigateway', 'network', 'public-access'],
  },
  {
    checkId: 'apigateway_restapi_public_with_authorizer',
    provider: 'aws',
    service: 'apigateway',
    title: 'API Gateway Public Endpoint Missing Authorizer',
    severity: 'HIGH',
    description: 'Checks that API Gateway REST APIs with public endpoints have an authorizer configured (Lambda, Cognito, or API key); without authentication, anonymous callers can invoke methods.',
    remediation: 'Attach an authorizer to the API or its methods via the console (Resources > Method Request > Authorization) or AWS CLI.',
    tags: ['apigateway', 'authentication', 'public-access'],
  },
  {
    checkId: 'apigateway_restapi_tracing_enabled',
    provider: 'aws',
    service: 'apigateway',
    title: 'API Gateway Stage X-Ray Tracing Not Enabled',
    severity: 'LOW',
    description: 'Checks that API Gateway REST API stages have AWS X-Ray active tracing enabled so distributed traces and latency/error visibility are captured.',
    remediation: 'Enable X-Ray tracing on the stage via the console (Logs/Tracing > X-Ray Tracing) or AWS CLI.',
    tags: ['apigateway', 'observability', 'tracing'],
  },
];
