// Check logic derived from Prowler (Apache-2.0, https://github.com/prowler-cloud/prowler)
import { CheckMetadata } from '../../types';

export const autoscalingChecks: CheckMetadata[] = [
  {
    checkId: 'autoscaling_find_secrets_ec2_launch_configuration',
    provider: 'aws',
    service: 'autoscaling',
    title: 'Auto Scaling Launch Configuration Secrets in User Data',
    severity: 'CRITICAL',
    description: 'Checks EC2 Auto Scaling launch configurations for secrets (passwords, tokens, API keys) embedded in User Data bootstrapping scripts.',
    remediation: 'Remove secrets from User Data. Fetch credentials at runtime from Secrets Manager or SSM Parameter Store using an instance role, rotate any exposed secrets, and prefer short-lived scoped credentials.',
    tags: ['autoscaling', 'secrets', 'user-data'],
  },
  {
    checkId: 'autoscaling_group_launch_configuration_no_public_ip',
    provider: 'aws',
    service: 'autoscaling',
    title: 'Auto Scaling Launch Configuration Assigns Public IP',
    severity: 'HIGH',
    description: 'Checks that launch configurations associated with Auto Scaling groups do not assign public IP addresses to instances.',
    remediation: 'Place instances in private subnets with AssociatePublicIpAddress=false; expose services through load balancers or private endpoints and use SSM, VPN or a bastion for admin access.',
    tags: ['autoscaling', 'public-access', 'network'],
  },
  {
    checkId: 'autoscaling_group_launch_configuration_requires_imdsv2',
    provider: 'aws',
    service: 'autoscaling',
    title: 'Auto Scaling Launch Configuration Missing IMDSv2 Enforcement',
    severity: 'HIGH',
    description: 'Checks that Auto Scaling launch configurations either require IMDSv2 (HttpTokens=required with metadata enabled) or disable the instance metadata service entirely.',
    remediation: 'Set HttpTokens=required on the launch configuration metadata options, or disable the metadata endpoint if not needed, to block SSRF-based credential theft.',
    tags: ['autoscaling', 'imdsv2', 'metadata', 'ssrf'],
  },
  {
    checkId: 'autoscaling_group_capacity_rebalance_enabled',
    provider: 'aws',
    service: 'autoscaling',
    title: 'Auto Scaling Group Capacity Rebalancing Disabled',
    severity: 'MEDIUM',
    description: 'Checks that load-balanced Auto Scaling groups have Capacity Rebalancing enabled so at-risk Spot instances are proactively replaced before interruption.',
    remediation: 'Enable Capacity Rebalancing on the Auto Scaling group, keep headroom below MaxSize, and use lifecycle hooks to drain instances so capacity is sustained during Spot interruptions.',
    tags: ['autoscaling', 'availability', 'spot'],
  },
  {
    checkId: 'autoscaling_group_elb_health_check_enabled',
    provider: 'aws',
    service: 'autoscaling',
    title: 'Auto Scaling Group Missing ELB Health Checks',
    severity: 'LOW',
    description: 'Checks that Auto Scaling groups associated with a load balancer use ELB health checks instead of EC2-only instance checks.',
    remediation: 'Set the health check type to ELB on load-balanced Auto Scaling groups and tune the health check grace period so unhealthy targets are replaced based on real client reachability.',
    tags: ['autoscaling', 'health-check', 'availability'],
  },
  {
    checkId: 'autoscaling_group_multiple_az',
    provider: 'aws',
    service: 'autoscaling',
    title: 'Auto Scaling Group Single Availability Zone',
    severity: 'MEDIUM',
    description: 'Checks that Auto Scaling groups span multiple Availability Zones instead of being confined to a single zone.',
    remediation: 'Configure the Auto Scaling group with subnets in at least two Availability Zones and distribute traffic with a load balancer so the workload survives a zonal outage.',
    tags: ['autoscaling', 'availability', 'multi-az'],
  },
  {
    checkId: 'autoscaling_group_multiple_instance_types',
    provider: 'aws',
    service: 'autoscaling',
    title: 'Auto Scaling Group Lacks Instance Type Diversity',
    severity: 'MEDIUM',
    description: 'Checks that Auto Scaling groups run multiple instance types in each Availability Zone and span more than one zone, avoiding single points of capacity failure.',
    remediation: 'Adopt a mixed instances strategy with diverse instance families and sizes per Availability Zone and distribute capacity across multiple zones to tolerate capacity shortages.',
    tags: ['autoscaling', 'availability', 'capacity'],
  },
  {
    checkId: 'autoscaling_group_using_ec2_launch_template',
    provider: 'aws',
    service: 'autoscaling',
    title: 'Auto Scaling Group Not Using Launch Template',
    severity: 'MEDIUM',
    description: 'Checks that Auto Scaling groups use an EC2 launch template (directly or via a mixed instances policy) instead of a legacy launch configuration.',
    remediation: 'Migrate the Auto Scaling group to a versioned EC2 launch template with hardened defaults (IMDSv2, encrypted storage, least-privilege roles) and manage changes under review.',
    tags: ['autoscaling', 'launch-template', 'configuration'],
  },
];
