// Check logic derived from Prowler (Apache-2.0, https://github.com/prowler-cloud/prowler)
import { CheckMetadata } from '../../types';

export const bedrockChecks: CheckMetadata[] = [
  {
    checkId: 'bedrock_agent_guardrail_enabled',
    provider: 'aws',
    service: 'bedrock',
    title: 'Bedrock Agent Without Guardrail',
    severity: 'HIGH',
    description: 'Checks that each Bedrock agent has a guardrail associated so agent sessions are protected against harmful content, prompt attacks and sensitive data exposure.',
    remediation: 'Create a Bedrock guardrail with appropriate content, prompt-attack and sensitive-information policies and associate it with the agent (guardrailConfiguration) so all agent sessions are filtered.',
    tags: ['bedrock', 'guardrail', 'agent', 'ai-safety'],
  },
  {
    checkId: 'bedrock_api_key_no_administrative_privileges',
    provider: 'aws',
    service: 'bedrock',
    title: 'Bedrock API Key User Has Excessive Privileges',
    severity: 'HIGH',
    description: 'Checks that IAM users holding Bedrock API keys (service-specific credentials for bedrock.amazonaws.com) do not have policies granting administrative access or full Bedrock service access.',
    remediation: 'Scope the IAM policies of users that own Bedrock API keys to the minimum required bedrock actions and resources; remove AdministratorAccess and wildcard bedrock:* grants from those users.',
    tags: ['bedrock', 'iam', 'api-key', 'least-privilege'],
  },
  {
    checkId: 'bedrock_api_key_no_long_term_credentials',
    provider: 'aws',
    service: 'bedrock',
    title: 'Bedrock Long-Term API Key Active',
    severity: 'HIGH',
    description: 'Checks for active long-term Bedrock API keys; AWS recommends short-term session-scoped keys (valid up to 12 hours) for any non-exploratory workload. Keys configured to never expire are reported as critical.',
    remediation: 'Delete active long-term Bedrock API keys and switch workloads to short-term Bedrock API keys or IAM role-based authentication; never configure keys without an expiration.',
    tags: ['bedrock', 'iam', 'api-key', 'credentials'],
  },
  {
    checkId: 'bedrock_full_access_policy_attached',
    provider: 'aws',
    service: 'bedrock',
    title: 'IAM Role Has AmazonBedrockFullAccess Attached',
    severity: 'HIGH',
    description: 'Checks that IAM roles (excluding service roles) do not have the AmazonBedrockFullAccess AWS-managed policy attached, which grants excessive Bedrock permissions.',
    remediation: 'Detach AmazonBedrockFullAccess from the role and replace it with a customer-managed policy granting only the specific bedrock actions and model resources the workload needs.',
    tags: ['bedrock', 'iam', 'least-privilege'],
  },
  {
    checkId: 'bedrock_guardrail_prompt_attack_filter_enabled',
    provider: 'aws',
    service: 'bedrock',
    title: 'Bedrock Guardrail Prompt Attack Filter Weak or Disabled',
    severity: 'HIGH',
    description: 'Checks that each Bedrock guardrail has the prompt attack (jailbreak/prompt injection) content filter configured with HIGH input strength.',
    remediation: 'Edit the guardrail content policy to enable the prompt attack filter and set its input strength to HIGH so prompt injection and jailbreak attempts are blocked.',
    tags: ['bedrock', 'guardrail', 'prompt-injection', 'ai-safety'],
  },
  {
    checkId: 'bedrock_guardrail_sensitive_information_filter_enabled',
    provider: 'aws',
    service: 'bedrock',
    title: 'Bedrock Guardrail Missing Sensitive Information Filter',
    severity: 'HIGH',
    description: 'Checks that each Bedrock guardrail has a sensitive information policy configured so PII and other sensitive data are blocked or masked in prompts and responses.',
    remediation: 'Add a sensitive information policy (PII entity types and/or regex patterns with block or mask behavior) to the guardrail so sensitive data is not exposed through model interactions.',
    tags: ['bedrock', 'guardrail', 'data-protection', 'pii'],
  },
  {
    checkId: 'bedrock_guardrails_configured',
    provider: 'aws',
    service: 'bedrock',
    title: 'No Bedrock Guardrails in Region',
    severity: 'MEDIUM',
    description: 'Checks that at least one Bedrock guardrail is configured in the region so model invocations and agents can be protected with content filtering policies.',
    remediation: 'Create at least one Bedrock guardrail with content, prompt-attack and sensitive-information policies and attach it to agents and model invocations in the region.',
    tags: ['bedrock', 'guardrail', 'ai-safety'],
  },
  {
    checkId: 'bedrock_model_invocation_logging_enabled',
    provider: 'aws',
    service: 'bedrock',
    title: 'Bedrock Model Invocation Logging Disabled',
    severity: 'MEDIUM',
    description: 'Checks that Bedrock model invocation logging is enabled in the region so prompts and responses are captured to CloudWatch Logs and/or S3 for monitoring and forensics.',
    remediation: 'Enable model invocation logging in the Bedrock settings for the region, delivering logs to a CloudWatch Log Group and/or S3 bucket with appropriate retention and access controls.',
    tags: ['bedrock', 'logging', 'audit'],
  },
  {
    checkId: 'bedrock_model_invocation_logs_encryption_enabled',
    provider: 'aws',
    service: 'bedrock',
    title: 'Bedrock Model Invocation Logs Unencrypted',
    severity: 'HIGH',
    description: 'Checks that the destinations for Bedrock model invocation logs are encrypted: the S3 bucket has server-side encryption and the CloudWatch Log Group is encrypted with a KMS key.',
    remediation: 'Enable server-side encryption on the S3 bucket receiving Bedrock invocation logs and associate a KMS key with the CloudWatch Log Group so logged prompts and responses are protected at rest.',
    tags: ['bedrock', 'encryption', 'kms', 'logging'],
  },
  {
    checkId: 'bedrock_prompt_encrypted_with_cmk',
    provider: 'aws',
    service: 'bedrock',
    title: 'Bedrock Prompt Not Encrypted With Customer-Managed Key',
    severity: 'MEDIUM',
    description: 'Checks that Bedrock Prompt Management prompts are encrypted at rest with a customer-managed KMS key instead of the default AWS-owned key.',
    remediation: 'Recreate or update the prompt with a customer-managed KMS key (customerEncryptionKeyArn) and restrict the key policy to the principals that need to use the prompt.',
    tags: ['bedrock', 'encryption', 'kms', 'prompt-management'],
  },
  {
    checkId: 'bedrock_vpc_endpoints_configured',
    provider: 'aws',
    service: 'bedrock',
    title: 'VPC Missing Bedrock Interface Endpoints',
    severity: 'MEDIUM',
    description: 'Checks that in-use VPCs in regions with Bedrock activity have interface VPC endpoints for all Bedrock services (control plane, runtime, agent, agent runtime, Mantle) so traffic stays on the AWS network.',
    remediation: 'Create interface VPC endpoints for bedrock, bedrock-runtime, bedrock-agent, bedrock-agent-runtime and bedrock-mantle in the VPC, and attach endpoint policies restricting access to required principals and models.',
    tags: ['bedrock', 'network', 'vpc-endpoint', 'private-connectivity'],
  },
];
