// Check logic derived from Prowler (Apache-2.0, https://github.com/prowler-cloud/prowler)
import { CheckMetadata } from '../../types';

// Titles must stay byte-identical to the pre-registry hardcoded titles:
// the scan worker dedupes OPEN findings on service:title:fingerprint, so a
// reworded title would re-open every existing finding as "new".
export const cloudfrontChecks: CheckMetadata[] = [
  {
    checkId: 'cloudfront_distributions_https_enabled',
    provider: 'aws',
    service: 'cloudfront',
    title: 'CloudFront Distribution Allows HTTP Traffic',
    severity: 'HIGH',
    description: 'Checks that CloudFront distributions do not allow HTTP traffic (ViewerProtocolPolicy: allow-all) on any cache behavior, so data in transit between viewers and CloudFront is encrypted.',
    remediation: 'Set ViewerProtocolPolicy to "redirect-to-https" or "https-only" on all cache behaviors in CloudFront distribution settings.',
    tags: ['cloudfront', 'https', 'encryption'],
  },
  {
    checkId: 'cloudfront_distributions_using_waf',
    provider: 'aws',
    service: 'cloudfront',
    title: 'CloudFront Distribution Not Protected By WAF',
    severity: 'HIGH',
    description: 'Checks that CloudFront distributions have a WAF WebACL attached; without WAF protection the distribution is exposed to web attacks (OWASP Top 10, bots, DDoS).',
    remediation: 'Associate a WAF WebACL (in us-east-1) with the CloudFront distribution via the WAF console or CloudFront settings.',
    tags: ['cloudfront', 'waf'],
  },
  {
    checkId: 'cloudfront_distributions_logging_enabled',
    provider: 'aws',
    service: 'cloudfront',
    title: 'CloudFront Distribution Access Logging Disabled',
    severity: 'MEDIUM',
    description: 'Checks that CloudFront distributions have access logging enabled so malicious traffic patterns and geographic abuse can be analyzed.',
    remediation: 'Enable access logging in CloudFront distribution settings. Specify an S3 bucket as the logging destination.',
    tags: ['cloudfront', 'logging'],
  },
  {
    checkId: 'cloudfront_distributions_using_deprecated_ssl_protocols',
    provider: 'aws',
    service: 'cloudfront',
    title: 'CloudFront Distribution Uses Weak TLS Protocol',
    severity: 'HIGH',
    description: 'Checks that CloudFront distributions do not allow weak minimum TLS protocol versions (< TLSv1.2), which are vulnerable to known attacks (BEAST, POODLE).',
    remediation: 'Update minimum TLS protocol to TLSv1.2_2021 in CloudFront viewer certificate settings.',
    tags: ['cloudfront', 'tls', 'encryption'],
  },
  {
    checkId: 'cloudfront_distributions_custom_ssl_certificate',
    provider: 'aws',
    service: 'cloudfront',
    title: 'CloudFront Distribution Using Default SSL Certificate',
    severity: 'LOW',
    description: 'Checks that CloudFront distributions use a custom ACM certificate instead of the default CloudFront SSL certificate, so users are not served the generic *.cloudfront.net domain.',
    remediation: 'Request a certificate in ACM (us-east-1) and configure it on the CloudFront distribution with a custom domain.',
    tags: ['cloudfront', 'certificate'],
  },
  {
    checkId: 'cloudfront_distributions_default_root_object',
    provider: 'aws',
    service: 'cloudfront',
    title: 'CloudFront Distribution Missing Default Root Object',
    severity: 'HIGH',
    description: 'Checks that CloudFront distributions have a default root object configured so requests for the root URL return a specific file instead of exposing origin listings or unintended content.',
    remediation: 'Set a default root object (e.g. index.html, without a leading slash) in the CloudFront distribution general settings.',
    tags: ['cloudfront', 'configuration'],
  },
  {
    checkId: 'cloudfront_distributions_field_level_encryption_enabled',
    provider: 'aws',
    service: 'cloudfront',
    title: 'CloudFront Distribution Field-Level Encryption Not Enabled',
    severity: 'LOW',
    description: 'Checks that the default cache behavior of CloudFront distributions has a field-level encryption configuration so sensitive request fields are encrypted at the edge before reaching the origin.',
    remediation: 'Create a field-level encryption configuration (public key + profile) and associate it with the default cache behavior of the distribution.',
    tags: ['cloudfront', 'encryption'],
  },
  {
    checkId: 'cloudfront_distributions_geo_restrictions_enabled',
    provider: 'aws',
    service: 'cloudfront',
    title: 'CloudFront Distribution Geo Restrictions Not Enabled',
    severity: 'LOW',
    description: 'Checks that CloudFront distributions restrict content delivery by country using a geo restriction allowlist or blocklist instead of serving content globally without limits.',
    remediation: 'Configure geographic restrictions (allow list or block list with at least one country) under the distribution security settings.',
    tags: ['cloudfront', 'geo-restriction', 'internet-exposed'],
  },
  {
    checkId: 'cloudfront_distributions_https_sni_enabled',
    provider: 'aws',
    service: 'cloudfront',
    title: 'CloudFront Distribution Not Using SNI For HTTPS',
    severity: 'LOW',
    description: 'Checks that CloudFront distributions with a custom SSL/TLS certificate serve HTTPS requests using Server Name Indication (sni-only) instead of a dedicated IP address.',
    remediation: 'Set the SSL support method (client support) to SNI only on the distribution viewer certificate settings.',
    tags: ['cloudfront', 'tls', 'sni'],
  },
  {
    checkId: 'cloudfront_distributions_multiple_origin_failover_configured',
    provider: 'aws',
    service: 'cloudfront',
    title: 'CloudFront Distribution Origin Failover Not Configured',
    severity: 'LOW',
    description: 'Checks that CloudFront distributions have an origin group with at least two origins so requests automatically fail over when the primary origin is unavailable.',
    remediation: 'Create an origin group with a primary and secondary origin, set failover status codes, and point the cache behavior at the origin group.',
    tags: ['cloudfront', 'resilience', 'failover'],
  },
  {
    checkId: 'cloudfront_distributions_origin_traffic_encrypted',
    provider: 'aws',
    service: 'cloudfront',
    title: 'CloudFront Distribution Origin Traffic Not Encrypted',
    severity: 'MEDIUM',
    description: 'Checks that traffic between CloudFront and its origins is encrypted: custom origins must use https-only (or match-viewer with an HTTPS-enforcing viewer policy), and S3 origins must not be paired with an allow-all viewer protocol policy.',
    remediation: 'Set the origin protocol policy to https-only on custom origins and use redirect-to-https or https-only as the viewer protocol policy.',
    tags: ['cloudfront', 'encryption', 'https'],
  },
  {
    checkId: 'cloudfront_distributions_pqc_tls_enabled',
    provider: 'aws',
    service: 'cloudfront',
    title: 'CloudFront Distribution Post-Quantum TLS Not Enabled',
    severity: 'LOW',
    description: 'Checks that CloudFront distributions enforce a TLS 1.3-only security policy (TLSv1.3_2025) so viewer connections use quantum-safe key exchange; distributions on the default CloudFront certificate are pinned to TLSv1 and cannot enable it.',
    remediation: 'Use a custom ACM certificate with SNI and set the security policy (MinimumProtocolVersion) to TLSv1.3_2025 on the distribution.',
    tags: ['cloudfront', 'tls', 'encryption', 'post-quantum'],
  },
  {
    checkId: 'cloudfront_distributions_s3_origin_access_control',
    provider: 'aws',
    service: 'cloudfront',
    title: 'CloudFront S3 Origin Without Origin Access Control',
    severity: 'MEDIUM',
    description: 'Checks that every S3 origin of a CloudFront distribution has an Origin Access Control (OAC) attached so bucket content can only be reached through CloudFront.',
    remediation: 'Create an Origin Access Control (S3 type, sigv4 signing) and attach it to each S3 origin, then restrict the bucket policy to the distribution.',
    tags: ['cloudfront', 's3', 'access-control'],
  },
  {
    checkId: 'cloudfront_distributions_s3_origin_non_existent_bucket',
    provider: 'aws',
    service: 'cloudfront',
    title: 'CloudFront S3 Origin Bucket Does Not Exist',
    severity: 'HIGH',
    description: 'Checks that S3 origins of CloudFront distributions reference existing buckets; a dangling origin allows bucket takeover where an attacker creates the missing bucket and serves malicious content through the distribution.',
    remediation: 'Remove or update the origin that references the missing bucket, or recreate the bucket under your ownership and lock it down with Origin Access Control.',
    tags: ['cloudfront', 's3', 'takeover', 'resilience'],
  },
];
