// Check logic derived from Prowler (Apache-2.0, https://github.com/prowler-cloud/prowler)
import { CheckMetadata } from '../../types';

// Titles must stay byte-identical to the pre-registry hardcoded titles:
// the scan worker dedupes OPEN findings on service:title:fingerprint, so a
// reworded title would re-open every existing finding as "new".
export const cloudtrailChecks: CheckMetadata[] = [
  {
    checkId: 'cloudtrail_trail_not_configured',
    provider: 'aws',
    service: 'cloudtrail',
    title: 'No CloudTrail Found',
    severity: 'MEDIUM',
    description: 'Checks that at least one CloudTrail trail is configured in the region.',
    remediation: 'Enable CloudTrail to log all API activity for auditing and compliance',
    tags: ['cloudtrail', 'logging', 'audit'],
  },
  {
    checkId: 'cloudtrail_trail_not_logging',
    provider: 'aws',
    service: 'cloudtrail',
    title: 'CloudTrail Not Logging',
    severity: 'HIGH',
    description: 'Checks that CloudTrail trails are actively logging events.',
    remediation: 'Enable logging for the trail to ensure all API calls are recorded.',
    tags: ['cloudtrail', 'logging', 'active-monitoring'],
  },
  {
    checkId: 'cloudtrail_multi_region_enabled',
    provider: 'aws',
    service: 'cloudtrail',
    title: 'Single Region CloudTrail',
    severity: 'HIGH',
    description: 'Checks that CloudTrail trails are multi-region so API activity in all regions is logged.',
    remediation: 'Enable multi-region logging for the trail.',
    tags: ['cloudtrail', 'multi-region'],
  },
  {
    checkId: 'cloudtrail_trail_s3_bucket_not_configured',
    provider: 'aws',
    service: 'cloudtrail',
    title: 'S3 Bucket Not Configured',
    severity: 'CRITICAL',
    description: 'Checks that CloudTrail trails deliver logs to an S3 bucket.',
    remediation: 'Configure an S3 bucket destination for the trail.',
    tags: ['cloudtrail', 's3', 'logging'],
  },
  {
    checkId: 'cloudtrail_log_file_validation_enabled',
    provider: 'aws',
    service: 'cloudtrail',
    title: 'Log File Validation Not Enabled',
    severity: 'MEDIUM',
    description: 'Checks that CloudTrail trails have log file validation enabled to detect unauthorized modifications.',
    remediation: 'Enable log file validation for the trail to detect unauthorized modifications.',
    tags: ['cloudtrail', 'integrity', 'logging'],
  },
  {
    checkId: 'cloudtrail_cloudwatch_logging_enabled',
    provider: 'aws',
    service: 'cloudtrail',
    title: 'CloudWatch Logs Not Configured',
    severity: 'MEDIUM',
    description: 'Checks that CloudTrail trails deliver logs to CloudWatch Logs for real-time monitoring.',
    remediation: 'Configure a CloudWatch Logs destination for the trail for real-time alerts.',
    tags: ['cloudtrail', 'cloudwatch', 'monitoring'],
  },
  {
    checkId: 'cloudtrail_kms_encryption_enabled',
    provider: 'aws',
    service: 'cloudtrail',
    title: 'S3 Logs Not KMS Encrypted',
    severity: 'MEDIUM',
    description: 'Checks that CloudTrail S3 log files are encrypted with a KMS key.',
    remediation: 'Enable KMS encryption for the S3 logs of the trail.',
    tags: ['cloudtrail', 'kms', 'encryption'],
  },
  {
    checkId: 'cloudtrail_multi_region_enabled_logging_management_events',
    provider: 'aws',
    service: 'cloudtrail',
    title: 'Management Events Not Logged',
    severity: 'HIGH',
    description: 'Checks that CloudTrail trails log management events.',
    remediation: 'Enable management event logging for the trail.',
    tags: ['cloudtrail', 'management-events'],
  },
  {
    checkId: 'cloudtrail_bedrock_logging_enabled',
    provider: 'aws',
    service: 'cloudtrail',
    title: 'Bedrock API Calls Not Logged By CloudTrail',
    severity: 'MEDIUM',
    description: 'Checks that at least one actively logging CloudTrail trail captures Amazon Bedrock API activity, either through management events or advanced event selectors targeting Bedrock resources.',
    remediation: 'Enable management events on an actively logging trail, or add advanced event selectors targeting Bedrock resource types (AWS::Bedrock::Model, AWS::Bedrock::Guardrail, etc.) for data-plane visibility.',
    tags: ['cloudtrail', 'bedrock', 'logging', 'gen-ai'],
  },
  {
    checkId: 'cloudtrail_bucket_requires_mfa_delete',
    provider: 'aws',
    service: 'cloudtrail',
    title: 'CloudTrail Bucket MFA Delete Not Enabled',
    severity: 'MEDIUM',
    description: 'Checks that the S3 bucket receiving logs from actively logging CloudTrail trails has MFA delete enabled, so log versions cannot be permanently deleted with credentials alone.',
    remediation: 'As the root user with MFA, run: aws s3api put-bucket-versioning --bucket <bucket> --versioning-configuration Status=Enabled,MFADelete=Enabled --mfa "<mfa-serial> <code>".',
    tags: ['cloudtrail', 's3', 'mfa', 'integrity'],
  },
  {
    checkId: 'cloudtrail_insights_exist',
    provider: 'aws',
    service: 'cloudtrail',
    title: 'CloudTrail Insights Not Enabled',
    severity: 'LOW',
    description: 'Checks that actively logging CloudTrail trails have Insights selectors enabled so anomalous API call and error rates are detected automatically.',
    remediation: 'Enable CloudTrail Insights on the trail with both ApiCallRateInsight and ApiErrorRateInsight insight types.',
    tags: ['cloudtrail', 'insights', 'anomaly-detection'],
  },
  {
    checkId: 'cloudtrail_logs_s3_bucket_access_logging_enabled',
    provider: 'aws',
    service: 'cloudtrail',
    title: 'CloudTrail Bucket Access Logging Not Enabled',
    severity: 'MEDIUM',
    description: 'Checks that the S3 bucket receiving CloudTrail logs has server access logging enabled, providing an independent audit trail of access to the log files themselves.',
    remediation: 'Enable S3 server access logging on the CloudTrail log bucket, delivering the access logs to a separate tightly-controlled bucket.',
    tags: ['cloudtrail', 's3', 'logging'],
  },
  {
    checkId: 'cloudtrail_logs_s3_bucket_is_not_publicly_accessible',
    provider: 'aws',
    service: 'cloudtrail',
    title: 'CloudTrail Bucket Publicly Accessible',
    severity: 'CRITICAL',
    description: 'Checks that the S3 bucket receiving CloudTrail logs has no ACL grant to the public AllUsers group, which would expose API activity history to anyone on the internet.',
    remediation: 'Remove public ACL grants from the CloudTrail log bucket (aws s3api put-bucket-acl --bucket <bucket> --acl private) and enable S3 Block Public Access.',
    tags: ['cloudtrail', 's3', 'public-access', 'internet-exposed'],
  },
  {
    checkId: 'cloudtrail_s3_dataevents_read_enabled',
    provider: 'aws',
    service: 'cloudtrail',
    title: 'S3 Object-Level Read Events Not Logged',
    severity: 'LOW',
    description: 'Checks that at least one CloudTrail trail records S3 object-level read data events (e.g. GetObject) for all buckets via classic or advanced event selectors.',
    remediation: 'Add a data event selector for all S3 objects with read (or all) events: aws cloudtrail put-event-selectors --trail-name <trail> --event-selectors \'[{"ReadWriteType":"ReadOnly","DataResources":[{"Type":"AWS::S3::Object","Values":["arn:aws:s3"]}]}]\'.',
    tags: ['cloudtrail', 's3', 'data-events', 'logging'],
  },
  {
    checkId: 'cloudtrail_s3_dataevents_write_enabled',
    provider: 'aws',
    service: 'cloudtrail',
    title: 'S3 Object-Level Write Events Not Logged',
    severity: 'LOW',
    description: 'Checks that at least one CloudTrail trail records S3 object-level write data events (e.g. PutObject, DeleteObject) for all buckets via classic or advanced event selectors.',
    remediation: 'Add a data event selector for all S3 objects with write (or all) events: aws cloudtrail put-event-selectors --trail-name <trail> --event-selectors \'[{"ReadWriteType":"WriteOnly","DataResources":[{"Type":"AWS::S3::Object","Values":["arn:aws:s3"]}]}]\'.',
    tags: ['cloudtrail', 's3', 'data-events', 'logging'],
  },
  {
    checkId: 'cloudtrail_threat_detection_llm_jacking',
    provider: 'aws',
    service: 'cloudtrail',
    title: 'Potential LLM Jacking Activity Detected',
    severity: 'CRITICAL',
    description: 'Analyzes recent CloudTrail events for identities performing a high diversity of Bedrock/LLM-related API calls (InvokeModel, model-access enumeration, etc.) within a 24-hour window, a pattern typical of stolen-credential LLM jacking attacks.',
    remediation: 'Investigate the flagged identity immediately: rotate or deactivate its credentials, review Bedrock usage and costs, and restrict bedrock:* actions via least-privilege policies or SCPs.',
    tags: ['cloudtrail', 'threat-detection', 'bedrock', 'gen-ai'],
  },
];
