import { CheckMetadata } from '../../types';

// Titles must stay byte-identical to the pre-registry hardcoded titles:
// the scan worker dedupes OPEN findings on service:title:fingerprint, so a
// reworded title would re-open every existing finding as "new".
export const cloudtrailChecks: CheckMetadata[] = [
  {
    checkId: 'cloudtrail_trail_not_configured',
    provider: 'aws',
    service: 'cloudtrail',
    title: 'No CloudTrail Found',
    severity: 'MEDIUM',
    description: 'Checks that at least one CloudTrail trail is configured in the region.',
    remediation: 'Enable CloudTrail to log all API activity for auditing and compliance',
    tags: ['cloudtrail', 'logging', 'audit'],
  },
  {
    checkId: 'cloudtrail_trail_not_logging',
    provider: 'aws',
    service: 'cloudtrail',
    title: 'CloudTrail Not Logging',
    severity: 'HIGH',
    description: 'Checks that CloudTrail trails are actively logging events.',
    remediation: 'Enable logging for the trail to ensure all API calls are recorded.',
    tags: ['cloudtrail', 'logging', 'active-monitoring'],
  },
  {
    checkId: 'cloudtrail_multi_region_enabled',
    provider: 'aws',
    service: 'cloudtrail',
    title: 'Single Region CloudTrail',
    severity: 'HIGH',
    description: 'Checks that CloudTrail trails are multi-region so API activity in all regions is logged.',
    remediation: 'Enable multi-region logging for the trail.',
    tags: ['cloudtrail', 'multi-region'],
  },
  {
    checkId: 'cloudtrail_trail_s3_bucket_not_configured',
    provider: 'aws',
    service: 'cloudtrail',
    title: 'S3 Bucket Not Configured',
    severity: 'CRITICAL',
    description: 'Checks that CloudTrail trails deliver logs to an S3 bucket.',
    remediation: 'Configure an S3 bucket destination for the trail.',
    tags: ['cloudtrail', 's3', 'logging'],
  },
  {
    checkId: 'cloudtrail_log_file_validation_enabled',
    provider: 'aws',
    service: 'cloudtrail',
    title: 'Log File Validation Not Enabled',
    severity: 'MEDIUM',
    description: 'Checks that CloudTrail trails have log file validation enabled to detect unauthorized modifications.',
    remediation: 'Enable log file validation for the trail to detect unauthorized modifications.',
    tags: ['cloudtrail', 'integrity', 'logging'],
  },
  {
    checkId: 'cloudtrail_cloudwatch_logging_enabled',
    provider: 'aws',
    service: 'cloudtrail',
    title: 'CloudWatch Logs Not Configured',
    severity: 'MEDIUM',
    description: 'Checks that CloudTrail trails deliver logs to CloudWatch Logs for real-time monitoring.',
    remediation: 'Configure a CloudWatch Logs destination for the trail for real-time alerts.',
    tags: ['cloudtrail', 'cloudwatch', 'monitoring'],
  },
  {
    checkId: 'cloudtrail_kms_encryption_enabled',
    provider: 'aws',
    service: 'cloudtrail',
    title: 'S3 Logs Not KMS Encrypted',
    severity: 'MEDIUM',
    description: 'Checks that CloudTrail S3 log files are encrypted with a KMS key.',
    remediation: 'Enable KMS encryption for the S3 logs of the trail.',
    tags: ['cloudtrail', 'kms', 'encryption'],
  },
  {
    checkId: 'cloudtrail_multi_region_enabled_logging_management_events',
    provider: 'aws',
    service: 'cloudtrail',
    title: 'Management Events Not Logged',
    severity: 'HIGH',
    description: 'Checks that CloudTrail trails log management events.',
    remediation: 'Enable management event logging for the trail.',
    tags: ['cloudtrail', 'management-events'],
  },
];
