import { CheckMetadata } from '../../types';

// Titles must stay byte-identical to the pre-registry hardcoded titles:
// the scan worker dedupes OPEN findings on service:title:fingerprint, so a
// reworded title would re-open every existing finding as "new".
export const cloudwatchChecks: CheckMetadata[] = [
  {
    checkId: 'cloudwatch_cloudtrail_log_group_not_configured',
    provider: 'aws',
    service: 'cloudwatch',
    title: 'CloudWatch Monitoring Not Configured',
    severity: 'CRITICAL',
    description: 'Checks that at least one CloudTrail trail delivers logs to CloudWatch Logs, without which the CIS monitoring requirements (4.1-4.15) cannot be verified.',
    remediation: 'Configure at least one CloudTrail trail to deliver logs to a CloudWatch Logs log group',
    tags: ['cloudwatch', 'cloudtrail', 'monitoring', 'cis'],
  },
  {
    checkId: 'cloudwatch_log_metric_filter_unauthorized_api_calls',
    provider: 'aws',
    service: 'cloudwatch',
    title: 'Unauthorized API Calls Not Monitored',
    severity: 'MEDIUM',
    description: 'Checks that a CloudWatch Logs metric filter and alarm exist for unauthorized API calls (CIS 4.1).',
    remediation: 'Create a CloudWatch Logs metric filter and alarm for Unauthorized API Calls Not Monitored per CIS AWS Foundations Benchmark CIS-4.1',
    tags: ['cloudwatch', 'monitoring', 'cis', 'cis-4.1'],
    compliance: {
      cis_2_0_aws: ['4.1'],
    },
  },
  {
    checkId: 'cloudwatch_log_metric_filter_sign_in_without_mfa',
    provider: 'aws',
    service: 'cloudwatch',
    title: 'Console Sign-In Without MFA Not Monitored',
    severity: 'MEDIUM',
    description: 'Checks that a CloudWatch Logs metric filter and alarm exist for console sign-in without MFA (CIS 4.2).',
    remediation: 'Create a CloudWatch Logs metric filter and alarm for Console Sign-In Without MFA Not Monitored per CIS AWS Foundations Benchmark CIS-4.2',
    tags: ['cloudwatch', 'monitoring', 'cis', 'cis-4.2'],
    compliance: {
      cis_2_0_aws: ['4.2'],
    },
  },
  {
    checkId: 'cloudwatch_log_metric_filter_root_usage',
    provider: 'aws',
    service: 'cloudwatch',
    title: 'Root Account Usage Not Monitored',
    severity: 'MEDIUM',
    description: 'Checks that a CloudWatch Logs metric filter and alarm exist for root account usage (CIS 4.3).',
    remediation: 'Create a CloudWatch Logs metric filter and alarm for Root Account Usage Not Monitored per CIS AWS Foundations Benchmark CIS-4.3',
    tags: ['cloudwatch', 'monitoring', 'cis', 'cis-4.3'],
    compliance: {
      cis_2_0_aws: ['4.3'],
    },
  },
  {
    checkId: 'cloudwatch_log_metric_filter_policy_changes',
    provider: 'aws',
    service: 'cloudwatch',
    title: 'IAM Policy Changes Not Monitored',
    severity: 'MEDIUM',
    description: 'Checks that a CloudWatch Logs metric filter and alarm exist for IAM policy changes (CIS 4.4).',
    remediation: 'Create a CloudWatch Logs metric filter and alarm for IAM Policy Changes Not Monitored per CIS AWS Foundations Benchmark CIS-4.4',
    tags: ['cloudwatch', 'monitoring', 'cis', 'cis-4.4'],
    compliance: {
      cis_2_0_aws: ['4.4'],
    },
  },
  {
    checkId: 'cloudwatch_log_metric_filter_and_alarm_for_cloudtrail_configuration_changes_enabled',
    provider: 'aws',
    service: 'cloudwatch',
    title: 'CloudTrail Config Changes Not Monitored',
    severity: 'MEDIUM',
    description: 'Checks that a CloudWatch Logs metric filter and alarm exist for CloudTrail configuration changes (CIS 4.5).',
    remediation: 'Create a CloudWatch Logs metric filter and alarm for CloudTrail Config Changes Not Monitored per CIS AWS Foundations Benchmark CIS-4.5',
    tags: ['cloudwatch', 'monitoring', 'cis', 'cis-4.5'],
    compliance: {
      cis_2_0_aws: ['4.5'],
    },
  },
  {
    checkId: 'cloudwatch_log_metric_filter_authentication_failures',
    provider: 'aws',
    service: 'cloudwatch',
    title: 'Console Authentication Failures Not Monitored',
    severity: 'MEDIUM',
    description: 'Checks that a CloudWatch Logs metric filter and alarm exist for console authentication failures (CIS 4.6).',
    remediation: 'Create a CloudWatch Logs metric filter and alarm for Console Authentication Failures Not Monitored per CIS AWS Foundations Benchmark CIS-4.6',
    tags: ['cloudwatch', 'monitoring', 'cis', 'cis-4.6'],
    compliance: {
      cis_2_0_aws: ['4.6'],
    },
  },
  {
    checkId: 'cloudwatch_log_metric_filter_disable_or_scheduled_deletion_of_kms_cmk',
    provider: 'aws',
    service: 'cloudwatch',
    title: 'CMK Deletion Not Monitored',
    severity: 'MEDIUM',
    description: 'Checks that a CloudWatch Logs metric filter and alarm exist for disabling or scheduled deletion of customer managed keys (CIS 4.7).',
    remediation: 'Create a CloudWatch Logs metric filter and alarm for CMK Deletion Not Monitored per CIS AWS Foundations Benchmark CIS-4.7',
    tags: ['cloudwatch', 'monitoring', 'cis', 'cis-4.7'],
    compliance: {
      cis_2_0_aws: ['4.7'],
    },
  },
  {
    checkId: 'cloudwatch_log_metric_filter_for_s3_bucket_policy_changes',
    provider: 'aws',
    service: 'cloudwatch',
    title: 'S3 Bucket Policy Changes Not Monitored',
    severity: 'MEDIUM',
    description: 'Checks that a CloudWatch Logs metric filter and alarm exist for S3 bucket policy changes (CIS 4.8).',
    remediation: 'Create a CloudWatch Logs metric filter and alarm for S3 Bucket Policy Changes Not Monitored per CIS AWS Foundations Benchmark CIS-4.8',
    tags: ['cloudwatch', 'monitoring', 'cis', 'cis-4.8'],
    compliance: {
      cis_2_0_aws: ['4.8'],
    },
  },
  {
    checkId: 'cloudwatch_log_metric_filter_and_alarm_for_aws_config_configuration_changes_enabled',
    provider: 'aws',
    service: 'cloudwatch',
    title: 'AWS Config Changes Not Monitored',
    severity: 'MEDIUM',
    description: 'Checks that a CloudWatch Logs metric filter and alarm exist for AWS Config configuration changes (CIS 4.9).',
    remediation: 'Create a CloudWatch Logs metric filter and alarm for AWS Config Changes Not Monitored per CIS AWS Foundations Benchmark CIS-4.9',
    tags: ['cloudwatch', 'monitoring', 'cis', 'cis-4.9'],
    compliance: {
      cis_2_0_aws: ['4.9'],
    },
  },
  {
    checkId: 'cloudwatch_log_metric_filter_security_group_changes',
    provider: 'aws',
    service: 'cloudwatch',
    title: 'Security Group Changes Not Monitored',
    severity: 'MEDIUM',
    description: 'Checks that a CloudWatch Logs metric filter and alarm exist for security group changes (CIS 4.10).',
    remediation: 'Create a CloudWatch Logs metric filter and alarm for Security Group Changes Not Monitored per CIS AWS Foundations Benchmark CIS-4.10',
    tags: ['cloudwatch', 'monitoring', 'cis', 'cis-4.10'],
    compliance: {
      cis_2_0_aws: ['4.10'],
    },
  },
  {
    checkId: 'cloudwatch_changes_to_network_acls_alarm_configured',
    provider: 'aws',
    service: 'cloudwatch',
    title: 'NACL Changes Not Monitored',
    severity: 'MEDIUM',
    description: 'Checks that a CloudWatch Logs metric filter and alarm exist for network ACL changes (CIS 4.11).',
    remediation: 'Create a CloudWatch Logs metric filter and alarm for NACL Changes Not Monitored per CIS AWS Foundations Benchmark CIS-4.11',
    tags: ['cloudwatch', 'monitoring', 'cis', 'cis-4.11'],
    compliance: {
      cis_2_0_aws: ['4.11'],
    },
  },
  {
    checkId: 'cloudwatch_changes_to_network_gateways_alarm_configured',
    provider: 'aws',
    service: 'cloudwatch',
    title: 'Network Gateway Changes Not Monitored',
    severity: 'MEDIUM',
    description: 'Checks that a CloudWatch Logs metric filter and alarm exist for network gateway changes (CIS 4.12).',
    remediation: 'Create a CloudWatch Logs metric filter and alarm for Network Gateway Changes Not Monitored per CIS AWS Foundations Benchmark CIS-4.12',
    tags: ['cloudwatch', 'monitoring', 'cis', 'cis-4.12'],
    compliance: {
      cis_2_0_aws: ['4.12'],
    },
  },
  {
    checkId: 'cloudwatch_changes_to_network_route_tables_alarm_configured',
    provider: 'aws',
    service: 'cloudwatch',
    title: 'Route Table Changes Not Monitored',
    severity: 'MEDIUM',
    description: 'Checks that a CloudWatch Logs metric filter and alarm exist for route table changes (CIS 4.13).',
    remediation: 'Create a CloudWatch Logs metric filter and alarm for Route Table Changes Not Monitored per CIS AWS Foundations Benchmark CIS-4.13',
    tags: ['cloudwatch', 'monitoring', 'cis', 'cis-4.13'],
    compliance: {
      cis_2_0_aws: ['4.13'],
    },
  },
  {
    checkId: 'cloudwatch_changes_to_vpcs_alarm_configured',
    provider: 'aws',
    service: 'cloudwatch',
    title: 'VPC Changes Not Monitored',
    severity: 'MEDIUM',
    description: 'Checks that a CloudWatch Logs metric filter and alarm exist for VPC changes (CIS 4.14).',
    remediation: 'Create a CloudWatch Logs metric filter and alarm for VPC Changes Not Monitored per CIS AWS Foundations Benchmark CIS-4.14',
    tags: ['cloudwatch', 'monitoring', 'cis', 'cis-4.14'],
    compliance: {
      cis_2_0_aws: ['4.14'],
    },
  },
  {
    checkId: 'cloudwatch_log_metric_filter_aws_organizations_changes',
    provider: 'aws',
    service: 'cloudwatch',
    title: 'AWS Organization Changes Not Monitored',
    severity: 'MEDIUM',
    description: 'Checks that a CloudWatch Logs metric filter and alarm exist for AWS Organizations changes (CIS 4.15).',
    remediation: 'Create a CloudWatch Logs metric filter and alarm for AWS Organization Changes Not Monitored per CIS AWS Foundations Benchmark CIS-4.15',
    tags: ['cloudwatch', 'monitoring', 'cis', 'cis-4.15'],
    compliance: {
      cis_2_0_aws: ['4.15'],
    },
  },
  {
    checkId: 'vpc_flow_logs_enabled',
    provider: 'aws',
    service: 'cloudwatch',
    title: 'VPC Flow Logs Not Enabled',
    severity: 'HIGH',
    description: 'Checks that VPC Flow Logs are enabled so network traffic information is captured for security analysis.',
    remediation: 'Enable VPC Flow Logs for all VPCs to capture network traffic information',
    tags: ['vpc', 'flow-logs', 'monitoring', 'cis-3.9'],
    compliance: {
      cis_2_0_aws: ['3.9'],
    },
  },
  {
    checkId: 'cloudwatch_s3_object_level_logging_disabled',
    provider: 'aws',
    service: 'cloudwatch',
    title: 'S3 Object Logging Not Enabled',
    severity: 'MEDIUM',
    description: 'Checks that CloudTrail S3 object-level logging (data events) is enabled for both read and write operations.',
    remediation: 'Enable S3 object-level logging (data events) in CloudTrail for read and write operations',
    tags: ['cloudtrail', 's3', 'logging', 'cis-3.10', 'cis-3.11'],
    compliance: {
      cis_2_0_aws: ['3.10', '3.11'],
    },
  },
  {
    checkId: 'config_recorder_all_regions_enabled',
    provider: 'aws',
    service: 'cloudwatch',
    title: 'AWS Config Not Enabled',
    severity: 'MEDIUM',
    description: 'Checks that AWS Config has a configuration recorder that is actively recording resource configurations.',
    remediation: 'Enable AWS Config to continuously monitor and record AWS resource configurations',
    tags: ['config', 'compliance', 'cis-3.3'],
    compliance: {
      cis_2_0_aws: ['3.3'],
    },
  },
];
