// Check logic derived from Prowler (Apache-2.0, https://github.com/prowler-cloud/prowler)
import { CheckMetadata } from '../../types';

export const codebuildChecks: CheckMetadata[] = [
  {
    checkId: 'codebuild_project_no_secrets_in_variables',
    provider: 'aws',
    service: 'codebuild',
    title: 'CodeBuild Project Plaintext Secrets in Environment Variables',
    severity: 'CRITICAL',
    description: 'Checks CodeBuild projects for PLAINTEXT environment variables that appear to contain secrets (keys, tokens, passwords) instead of secure references.',
    remediation: 'Move secrets to Secrets Manager or SSM Parameter Store and use SECRETS_MANAGER/PARAMETER_STORE environment variable types; rotate any exposed credentials and never embed them in build artifacts.',
    tags: ['codebuild', 'secrets', 'environment-variables'],
  },
  {
    checkId: 'codebuild_project_source_repo_url_no_sensitive_credentials',
    provider: 'aws',
    service: 'codebuild',
    title: 'CodeBuild Source Repository URL Embeds Credentials',
    severity: 'CRITICAL',
    description: 'Checks CodeBuild project primary and secondary Bitbucket source URLs for embedded credentials such as x-token-auth tokens or basic-auth user:password pairs.',
    remediation: 'Remove credentials from repository URLs and use OAuth/CodeStar Connections or tokens stored in Secrets Manager; scope tokens to needed repos, set short lifetimes and rotate regularly.',
    tags: ['codebuild', 'secrets', 'source-repository'],
  },
  {
    checkId: 'codebuild_project_not_publicly_accessible',
    provider: 'aws',
    service: 'codebuild',
    title: 'CodeBuild Project Publicly Accessible',
    severity: 'HIGH',
    description: 'Checks that CodeBuild project visibility is PRIVATE; public projects expose build results, logs and artifacts to anyone.',
    remediation: 'Set the project visibility to PRIVATE and share build results only with trusted principals via narrowly scoped policies; keep logs and artifacts private.',
    tags: ['codebuild', 'public-access', 'ci-cd'],
  },
  {
    checkId: 'codebuild_project_webhook_filters_use_anchored_patterns',
    provider: 'aws',
    service: 'codebuild',
    title: 'CodeBuild Webhook Filters Not Anchored',
    severity: 'HIGH',
    description: 'Checks that CodeBuild webhook filters of type ACTOR_ACCOUNT_ID, HEAD_REF or BASE_REF use regex patterns anchored with ^ and $, preventing substring-match bypass of trigger restrictions.',
    remediation: 'Anchor every webhook filter pattern with ^ and $ (for multiple values use ^value1$|^value2$) so only exact matches can trigger builds.',
    tags: ['codebuild', 'webhook', 'ci-cd', 'supply-chain'],
  },
  {
    checkId: 'codebuild_project_logging_enabled',
    provider: 'aws',
    service: 'codebuild',
    title: 'CodeBuild Project Logging Disabled',
    severity: 'MEDIUM',
    description: 'Checks that CodeBuild projects have at least one log destination (CloudWatch Logs or S3) enabled for build logs and events.',
    remediation: 'Enable CloudWatch Logs or S3 logging (preferably both) on the project, encrypt the logs, set retention, and restrict access on a least-privilege basis.',
    tags: ['codebuild', 'logging', 'audit'],
  },
  {
    checkId: 'codebuild_project_older_90_days',
    provider: 'aws',
    service: 'codebuild',
    title: 'CodeBuild Project Inactive Over 90 Days',
    severity: 'MEDIUM',
    description: 'Checks for CodeBuild projects that have never been built or have not been invoked in the last 90 days; dormant projects retain webhooks, credentials and roles that widen the attack surface.',
    remediation: 'Review projects idle for more than 90 days: delete or archive unneeded ones, revoke unused webhooks, tokens and service roles, and rotate any associated secrets.',
    tags: ['codebuild', 'hygiene', 'attack-surface'],
  },
  {
    checkId: 'codebuild_project_user_controlled_buildspec',
    provider: 'aws',
    service: 'codebuild',
    title: 'CodeBuild Project Uses User-Controlled Buildspec',
    severity: 'MEDIUM',
    description: 'Checks whether CodeBuild projects reference a buildspec YAML file from the source repository, letting repository contributors change what runs in CI.',
    remediation: 'Use a centrally managed buildspec that contributors cannot modify, protect branches with required reviews, and apply least privilege to the build role.',
    tags: ['codebuild', 'buildspec', 'supply-chain'],
  },
  {
    checkId: 'codebuild_report_group_export_encrypted',
    provider: 'aws',
    service: 'codebuild',
    title: 'CodeBuild Report Group Export Unencrypted',
    severity: 'MEDIUM',
    description: 'Checks that CodeBuild report groups exporting test results to S3 encrypt the exported data at rest with a KMS key.',
    remediation: 'Enable encryption on the report group S3 export using KMS (prefer customer-managed keys), restrict key usage to required principals and enforce encryption via bucket policy.',
    tags: ['codebuild', 'encryption', 'report-group'],
  },
  {
    checkId: 'codebuild_project_s3_logs_encrypted',
    provider: 'aws',
    service: 'codebuild',
    title: 'CodeBuild S3 Build Logs Unencrypted',
    severity: 'LOW',
    description: 'Checks that CodeBuild projects delivering build logs to S3 have encryption at rest enabled for those log objects.',
    remediation: 'Enable encryption for the project S3 logs (prefer SSE-KMS with customer-managed keys), enforce it via bucket policy, and restrict log access to least privilege.',
    tags: ['codebuild', 'encryption', 'logging'],
  },
];
