// Check logic derived from Prowler (Apache-2.0, https://github.com/prowler-cloud/prowler)
import { CheckMetadata } from '../../types';

export const cognitoChecks: CheckMetadata[] = [
  {
    checkId: 'cognito_user_pool_mfa_enabled',
    provider: 'aws',
    service: 'cognito',
    title: 'Cognito User Pool MFA Not Enforced',
    severity: 'MEDIUM',
    description: 'Checks that Cognito user pools have MFA set to ON so a second factor is required during authentication.',
    remediation: 'Set MFA to Required at the user pool level, preferring TOTP or other phishing-resistant methods over SMS, and require factor enrollment during onboarding.',
    tags: ['cognito', 'mfa', 'authentication'],
  },
  {
    checkId: 'cognito_user_pool_advanced_security_enabled',
    provider: 'aws',
    service: 'cognito',
    title: 'Cognito Advanced Security Not Enforced',
    severity: 'MEDIUM',
    description: 'Checks that Cognito user pool threat protection (advanced security) is in ENFORCED full-function mode rather than audit-only or disabled, so adaptive risk responses and compromised-credential checks apply during authentication.',
    remediation: 'Set threat protection to ENFORCED, require step-up MFA on risky events, block compromised credentials, and monitor the exported risk logs.',
    tags: ['cognito', 'threat-protection', 'authentication'],
  },
  {
    checkId: 'cognito_user_pool_blocks_compromised_credentials_sign_in_attempts',
    provider: 'aws',
    service: 'cognito',
    title: 'Compromised Credential Sign-Ins Not Blocked',
    severity: 'MEDIUM',
    description: 'Checks that Cognito user pool threat protection is ENFORCED and the compromised-credentials policy applies a BLOCK action to sign-in events.',
    remediation: 'Enable threat protection in ENFORCED mode and set the compromised-credentials response for sign-in events to BLOCK, combined with adaptive authentication and MFA.',
    tags: ['cognito', 'threat-protection', 'credentials'],
  },
  {
    checkId: 'cognito_user_pool_blocks_potential_malicious_sign_in_attempts',
    provider: 'aws',
    service: 'cognito',
    title: 'Risky Sign-In Attempts Not Blocked',
    severity: 'MEDIUM',
    description: 'Checks that Cognito user pool threat protection is ENFORCED with adaptive authentication set to BLOCK for low, medium and high account-takeover risk levels.',
    remediation: 'Enable threat protection in ENFORCED mode and configure adaptive authentication to BLOCK at all risk levels, require MFA, and monitor user event logs to tune responses.',
    tags: ['cognito', 'threat-protection', 'account-takeover'],
  },
  {
    checkId: 'cognito_user_pool_deletion_protection_enabled',
    provider: 'aws',
    service: 'cognito',
    title: 'Cognito User Pool Deletion Protection Disabled',
    severity: 'MEDIUM',
    description: 'Checks that Cognito user pools have deletion protection set to ACTIVE so the pool cannot be deleted accidentally or maliciously.',
    remediation: 'Enable deletion protection (ACTIVE) on production user pools, restrict delete permissions, and alert on protection status changes.',
    tags: ['cognito', 'deletion-protection', 'availability'],
  },
  {
    checkId: 'cognito_user_pool_password_policy_minimum_length_14',
    provider: 'aws',
    service: 'cognito',
    title: 'Cognito Password Minimum Length Below 14',
    severity: 'MEDIUM',
    description: 'Checks that Cognito user pool password policies require a minimum length of at least 14 characters.',
    remediation: 'Set the password policy minimum length to 14 or more, favor long passphrases, block common passwords, and pair with MFA.',
    tags: ['cognito', 'password-policy', 'authentication'],
  },
  {
    checkId: 'cognito_user_pool_temporary_password_expiration',
    provider: 'aws',
    service: 'cognito',
    title: 'Cognito Temporary Password Validity Over 7 Days',
    severity: 'MEDIUM',
    description: 'Checks that administrator-issued temporary passwords in Cognito user pools expire within 7 days or less.',
    remediation: 'Set the temporary password validity in the password policy to 7 days or fewer, require a change on first sign-in, and revoke unused temporary credentials promptly.',
    tags: ['cognito', 'password-policy', 'credentials'],
  },
  {
    checkId: 'cognito_user_pool_self_registration_disabled',
    provider: 'aws',
    service: 'cognito',
    title: 'Cognito Self-Registration Enabled',
    severity: 'MEDIUM',
    description: 'Checks that Cognito user pools allow only administrators to create accounts (AllowAdminCreateUserOnly), preventing unrestricted self-service sign-up.',
    remediation: 'Enforce admin-only user creation; if self sign-up is required, add verification, MFA and bot protections, restrict app clients, and apply least privilege to roles granted to new users.',
    tags: ['cognito', 'self-registration', 'access-control'],
  },
  {
    checkId: 'cognito_user_pool_client_prevent_user_existence_errors',
    provider: 'aws',
    service: 'cognito',
    title: 'Cognito Client Reveals User Existence',
    severity: 'MEDIUM',
    description: 'Checks that Cognito app clients have PreventUserExistenceErrors enabled so authentication, confirmation and recovery responses stay generic and do not disclose whether a username exists.',
    remediation: 'Set PreventUserExistenceErrors to ENABLED on all app clients and strengthen with MFA, rate limiting and anomalous login detection.',
    tags: ['cognito', 'information-disclosure', 'authentication'],
  },
  {
    checkId: 'cognito_user_pool_client_token_revocation_enabled',
    provider: 'aws',
    service: 'cognito',
    title: 'Cognito Client Token Revocation Disabled',
    severity: 'MEDIUM',
    description: 'Checks that Cognito app clients have token revocation enabled so refresh tokens and derived access/ID tokens can be invalidated to end user sessions.',
    remediation: 'Enable token revocation (EnableTokenRevocation) on all app clients, use refresh token rotation, shorten token lifetimes, and enforce sign-out to terminate sessions.',
    tags: ['cognito', 'tokens', 'session-management'],
  },
];
