// Check logic derived from Prowler (Apache-2.0, https://github.com/prowler-cloud/prowler)
import { CheckMetadata } from '../../types';

export const directoryserviceChecks: CheckMetadata[] = [
  {
    checkId: 'directoryservice_directory_log_forwarding_enabled',
    provider: 'aws',
    service: 'directoryservice',
    title: 'Directory Service Log Forwarding Disabled',
    severity: 'MEDIUM',
    description: 'Checks that the AWS Directory Service directory forwards its domain controller security logs to a CloudWatch Logs log group.',
    remediation: 'Create a log subscription for the directory so domain controller security events are forwarded to CloudWatch Logs, and configure retention and alerting on the log group.',
    tags: ['directoryservice', 'logging', 'audit'],
  },
  {
    checkId: 'directoryservice_directory_monitor_notifications',
    provider: 'aws',
    service: 'directoryservice',
    title: 'Directory Service SNS Notifications Disabled',
    severity: 'MEDIUM',
    description: 'Checks that the directory has an SNS topic registered for status notifications so operators are alerted when the directory health state changes.',
    remediation: 'Register an SNS topic for directory monitoring (RegisterEventTopic) and subscribe the operations team so directory status changes are acted on promptly.',
    tags: ['directoryservice', 'monitoring', 'notifications'],
  },
  {
    checkId: 'directoryservice_directory_snapshots_limit',
    provider: 'aws',
    service: 'directoryservice',
    title: 'Directory Service Snapshot Limit Nearly Reached',
    severity: 'LOW',
    description: 'Checks that the directory has not reached, and is not within 2 snapshots of, its manual snapshot limit, which would block taking new recovery snapshots.',
    remediation: 'Delete obsolete manual snapshots or request a manual snapshot limit increase so new snapshots can be taken before risky changes.',
    tags: ['directoryservice', 'snapshots', 'resilience'],
  },
  {
    checkId: 'directoryservice_ldap_certificate_expiration',
    provider: 'aws',
    service: 'directoryservice',
    title: 'Directory Service LDAP Certificate Expiring Soon',
    severity: 'MEDIUM',
    description: 'Checks that LDAPS and client certificates registered on the directory remain valid for more than 90 days.',
    remediation: 'Renew and register a replacement certificate before expiry, then deregister the expiring certificate to avoid LDAPS or smart card authentication outages.',
    tags: ['directoryservice', 'certificates', 'ldaps'],
  },
  {
    checkId: 'directoryservice_radius_server_security_protocol',
    provider: 'aws',
    service: 'directoryservice',
    title: 'Directory Service RADIUS Not Using MS-CHAPv2',
    severity: 'MEDIUM',
    description: 'Checks that the RADIUS server configured for the directory uses MS-CHAPv2; PAP, CHAP and MS-CHAPv1 transmit credentials with weak or no protection.',
    remediation: 'Reconfigure the directory RADIUS settings to use the MS-CHAPv2 authentication protocol on both the AWS side and the RADIUS server.',
    tags: ['directoryservice', 'radius', 'authentication'],
  },
  {
    checkId: 'directoryservice_supported_mfa_radius_enabled',
    provider: 'aws',
    service: 'directoryservice',
    title: 'Directory Service RADIUS MFA Disabled',
    severity: 'MEDIUM',
    description: 'Checks that RADIUS-based multi-factor authentication is enabled and in Completed state for the directory so user sign-ins require a second factor.',
    remediation: 'Configure a RADIUS MFA server for the directory (EnableRadius) and verify the RADIUS status reaches Completed.',
    tags: ['directoryservice', 'mfa', 'authentication'],
  },
];
