// Check logic derived from Prowler (Apache-2.0, https://github.com/prowler-cloud/prowler)
import { CheckMetadata } from '../../types';

export const dmsChecks: CheckMetadata[] = [
  {
    checkId: 'dms_instance_no_public_access',
    provider: 'aws',
    service: 'dms',
    title: 'DMS Replication Instance Publicly Exposed',
    severity: 'CRITICAL',
    description: 'Checks that DMS replication instances marked publicly accessible are not also reachable from the Internet through a security group open to 0.0.0.0/0 or ::/0.',
    remediation: 'Disable public accessibility on the replication instance (recreate it as private if needed) or remove security group ingress rules open to the Internet, connecting to sources and targets over VPC networking, VPN or Direct Connect.',
    tags: ['dms', 'public-access', 'network'],
  },
  {
    checkId: 'dms_endpoint_ssl_enabled',
    provider: 'aws',
    service: 'dms',
    title: 'DMS Endpoint SSL Disabled',
    severity: 'HIGH',
    description: 'Checks that DMS endpoints use an SSL mode other than none, so replication traffic between DMS and the database is encrypted in transit.',
    remediation: 'Set the endpoint SslMode to require, verify-ca or verify-full (per engine support) and provision the certificates needed for the chosen mode.',
    tags: ['dms', 'encryption-in-transit', 'ssl'],
  },
  {
    checkId: 'dms_endpoint_mongodb_authentication_enabled',
    provider: 'aws',
    service: 'dms',
    title: 'DMS MongoDB Endpoint Without Authentication',
    severity: 'MEDIUM',
    description: 'Checks that DMS endpoints for MongoDB have an authentication mechanism configured (AuthType not set to no).',
    remediation: 'Configure the MongoDB endpoint with password authentication and a least-privilege database user instead of anonymous access.',
    tags: ['dms', 'authentication', 'mongodb'],
  },
  {
    checkId: 'dms_endpoint_neptune_iam_authorization_enabled',
    provider: 'aws',
    service: 'dms',
    title: 'DMS Neptune Endpoint IAM Authorization Disabled',
    severity: 'MEDIUM',
    description: 'Checks that DMS endpoints targeting Amazon Neptune have IAM authorization enabled so access to the Neptune database is authenticated through IAM.',
    remediation: 'Enable IamAuthEnabled in the Neptune endpoint settings and attach an IAM role with least-privilege access to the Neptune cluster.',
    tags: ['dms', 'iam', 'neptune'],
  },
  {
    checkId: 'dms_endpoint_redis_in_transit_encryption_enabled',
    provider: 'aws',
    service: 'dms',
    title: 'DMS Redis Endpoint Not Encrypted in Transit',
    severity: 'MEDIUM',
    description: 'Checks that DMS endpoints for Redis OSS use TLS (SslSecurityProtocol set to ssl-encryption) so replicated data is encrypted in transit.',
    remediation: 'Set SslSecurityProtocol to ssl-encryption in the Redis endpoint settings and supply the CA certificate required to validate the TLS connection.',
    tags: ['dms', 'encryption-in-transit', 'redis'],
  },
  {
    checkId: 'dms_instance_minor_version_upgrade_enabled',
    provider: 'aws',
    service: 'dms',
    title: 'DMS Auto Minor Version Upgrade Disabled',
    severity: 'MEDIUM',
    description: 'Checks that DMS replication instances have automatic minor version upgrades enabled so engine security patches are applied during maintenance windows.',
    remediation: 'Enable AutoMinorVersionUpgrade on the replication instance so minor engine versions with security fixes are applied automatically.',
    tags: ['dms', 'patching', 'maintenance'],
  },
  {
    checkId: 'dms_instance_multi_az_enabled',
    provider: 'aws',
    service: 'dms',
    title: 'DMS Replication Instance Not Multi-AZ',
    severity: 'MEDIUM',
    description: 'Checks that DMS replication instances have Multi-AZ enabled, providing a synchronously replicated standby in another Availability Zone.',
    remediation: 'Enable Multi-AZ on replication instances supporting production migrations so replication survives the loss of a single Availability Zone.',
    tags: ['dms', 'multi-az', 'resilience'],
  },
  {
    checkId: 'dms_replication_task_source_logging_enabled',
    provider: 'aws',
    service: 'dms',
    title: 'DMS Task Source Logging Incomplete',
    severity: 'MEDIUM',
    description: 'Checks that DMS replication tasks have logging enabled with the SOURCE_CAPTURE and SOURCE_UNLOAD components at Default severity or higher.',
    remediation: 'Enable task logging and set the SOURCE_CAPTURE and SOURCE_UNLOAD log components to at least LOGGER_SEVERITY_DEFAULT in the replication task settings.',
    tags: ['dms', 'logging', 'audit'],
  },
  {
    checkId: 'dms_replication_task_target_logging_enabled',
    provider: 'aws',
    service: 'dms',
    title: 'DMS Task Target Logging Incomplete',
    severity: 'MEDIUM',
    description: 'Checks that DMS replication tasks have logging enabled with the TARGET_APPLY and TARGET_LOAD components at Default severity or higher.',
    remediation: 'Enable task logging and set the TARGET_APPLY and TARGET_LOAD log components to at least LOGGER_SEVERITY_DEFAULT in the replication task settings.',
    tags: ['dms', 'logging', 'audit'],
  },
];
