// Check logic derived from Prowler (Apache-2.0, https://github.com/prowler-cloud/prowler)
import { CheckMetadata } from '../../types';

export const documentdbChecks: CheckMetadata[] = [
  {
    checkId: 'documentdb_cluster_public_snapshot',
    provider: 'aws',
    service: 'documentdb',
    title: 'DocumentDB Cluster Snapshot Publicly Shared',
    severity: 'CRITICAL',
    description: 'Checks that DocumentDB manual cluster snapshots are not shared publicly; a public snapshot lets any AWS account restore and read the full database.',
    remediation: 'Remove the "all" attribute from the snapshot share list to make it private, share only with trusted accounts, and restrict IAM permissions that can modify snapshot visibility.',
    tags: ['documentdb', 'snapshot', 'public-access', 'data-exposure'],
  },
  {
    checkId: 'documentdb_cluster_storage_encrypted',
    provider: 'aws',
    service: 'documentdb',
    title: 'DocumentDB Cluster Storage Not Encrypted',
    severity: 'MEDIUM',
    description: 'Checks that the DocumentDB cluster has storage encryption at rest enabled.',
    remediation: 'Encryption cannot be enabled on an existing DocumentDB cluster; migrate by restoring an encrypted snapshot copy into a new cluster with StorageEncrypted enabled, preferring a customer-managed KMS key.',
    tags: ['documentdb', 'encryption', 'at-rest'],
  },
  {
    checkId: 'documentdb_cluster_backup_enabled',
    provider: 'aws',
    service: 'documentdb',
    title: 'DocumentDB Cluster Backup Retention Insufficient',
    severity: 'MEDIUM',
    description: 'Checks that the DocumentDB cluster has automated backups enabled with a retention period of at least 7 days.',
    remediation: 'Set the cluster backup retention period to at least 7 days (up to 35), test point-in-time restores regularly, and apply least privilege to backup and snapshot management.',
    tags: ['documentdb', 'backup', 'resilience'],
  },
  {
    checkId: 'documentdb_cluster_cloudwatch_log_export',
    provider: 'aws',
    service: 'documentdb',
    title: 'DocumentDB Cluster Log Exports Not Enabled',
    severity: 'MEDIUM',
    description: 'Checks that the DocumentDB cluster exports both audit and profiler logs to CloudWatch Logs.',
    remediation: 'Enable audit and profiler log exports on the cluster (audit also requires the audit_logs cluster parameter), set log retention, and centralize analysis and alerting.',
    tags: ['documentdb', 'logging', 'audit'],
  },
  {
    checkId: 'documentdb_cluster_deletion_protection',
    provider: 'aws',
    service: 'documentdb',
    title: 'DocumentDB Cluster Deletion Protection Disabled',
    severity: 'MEDIUM',
    description: 'Checks that the DocumentDB cluster has deletion protection enabled, blocking accidental or malicious cluster deletion.',
    remediation: 'Enable deletion protection on the cluster and require change control to toggle it; take a final snapshot before any planned decommissioning.',
    tags: ['documentdb', 'deletion-protection', 'resilience'],
  },
  {
    checkId: 'documentdb_cluster_multi_az_enabled',
    provider: 'aws',
    service: 'documentdb',
    title: 'DocumentDB Cluster Multi-AZ Disabled',
    severity: 'MEDIUM',
    description: 'Checks that the DocumentDB cluster is deployed across multiple Availability Zones for automatic failover.',
    remediation: 'Add replica instances in different Availability Zones so the cluster becomes Multi-AZ, set promotion priorities, and test failover regularly.',
    tags: ['documentdb', 'multi-az', 'high-availability'],
  },
];
