import { CheckMetadata } from '../../types';

// Titles must stay byte-identical to the pre-registry hardcoded titles:
// the scan worker dedupes OPEN findings on service:title:fingerprint, so a
// reworded title would re-open every existing finding as "new".
export const dynamodbChecks: CheckMetadata[] = [
  {
    checkId: 'dynamodb_tables_kms_cmk_encryption_enabled',
    provider: 'aws',
    service: 'dynamodb',
    title: 'DynamoDB Table Not Encrypted With CMK',
    severity: 'MEDIUM',
    description: 'Checks that DynamoDB tables are encrypted with a customer-managed KMS key rather than being unencrypted or using only AWS-owned keys, which cannot be audited or rotated by you.',
    remediation: 'Enable CMK encryption: aws dynamodb update-table --table-name <table-name> --sse-specification Enabled=true,SSEType=KMS,KMSMasterKeyId=<your-key-arn>',
    tags: ['dynamodb', 'encryption'],
  },
  {
    checkId: 'dynamodb_tables_pitr_enabled',
    provider: 'aws',
    service: 'dynamodb',
    title: 'DynamoDB Table Point-in-Time Recovery Disabled',
    severity: 'HIGH',
    description: 'Checks that DynamoDB tables have Point-in-Time Recovery (PITR) enabled so accidental deletes or corruption can be recovered within a 35-day window.',
    remediation: 'Enable PITR: aws dynamodb update-continuous-backups --table-name <table-name> --point-in-time-recovery-specification PointInTimeRecoveryEnabled=true',
    tags: ['dynamodb', 'backup', 'recovery'],
  },
  {
    checkId: 'dynamodb_table_deletion_protection_enabled',
    provider: 'aws',
    service: 'dynamodb',
    title: 'DynamoDB Table Deletion Protection Disabled',
    severity: 'MEDIUM',
    description: 'Checks that DynamoDB tables have deletion protection enabled so they cannot be deleted accidentally or by a compromised credential.',
    remediation: 'Enable deletion protection: aws dynamodb update-table --table-name <table-name> --deletion-protection-enabled',
    tags: ['dynamodb', 'availability'],
  },
  {
    checkId: 'dynamodb_table_replica_autoscaling_enabled',
    provider: 'aws',
    service: 'dynamodb',
    title: 'DynamoDB Global Table Replica Missing Auto Scaling',
    severity: 'LOW',
    description: 'Checks that DynamoDB global table replicas have autoscaling configured; without it, replicas can be throttled under load or over-provisioned (cost).',
    remediation: 'Enable autoscaling on each replica via the DynamoDB console under Additional settings > Auto scaling.',
    tags: ['dynamodb', 'availability', 'global-tables'],
  },
  {
    checkId: 'dynamodb_table_autoscaling_enabled',
    provider: 'aws',
    service: 'dynamodb',
    title: 'DynamoDB Table Auto Scaling Not Enabled',
    severity: 'MEDIUM',
    description: 'Checks that DynamoDB tables use on-demand capacity or, when in provisioned mode, have Application Auto Scaling registered for both read and write capacity so traffic spikes do not throttle requests.',
    remediation: 'Switch the table to on-demand capacity (aws dynamodb update-table --table-name <table-name> --billing-mode PAY_PER_REQUEST) or register Application Auto Scaling targets for both read and write capacity units.',
    tags: ['dynamodb', 'availability', 'autoscaling'],
  },
  {
    checkId: 'dynamodb_table_cross_account_access',
    provider: 'aws',
    service: 'dynamodb',
    title: 'DynamoDB Table Allows Cross-Account Access',
    severity: 'MEDIUM',
    description: 'Checks that DynamoDB table resource-based policies do not grant access to wildcard or foreign-account principals, which enables external reads, writes and capacity consumption.',
    remediation: 'Remove or scope the resource-based policy to same-account principals with conditions such as aws:PrincipalOrgID or aws:PrincipalArn; delete it entirely with: aws dynamodb delete-resource-policy --resource-arn <table-arn>',
    tags: ['dynamodb', 'access-control', 'public-access'],
  },
  {
    checkId: 'dynamodb_table_protected_by_backup_plan',
    provider: 'aws',
    service: 'dynamodb',
    title: 'DynamoDB Table Not In Backup Plan',
    severity: 'MEDIUM',
    description: 'Checks that DynamoDB tables are covered by an AWS Backup plan so scheduled backups and retention policies govern the table data.',
    remediation: 'Assign the table (directly, by tag, or via a resource-type wildcard) to an AWS Backup plan with an appropriate schedule, retention and vault, and test restores regularly.',
    tags: ['dynamodb', 'backup', 'recovery'],
  },
  {
    checkId: 'dynamodb_accelerator_cluster_encryption_enabled',
    provider: 'aws',
    service: 'dynamodb',
    title: 'DAX Cluster Encryption At Rest Disabled',
    severity: 'MEDIUM',
    description: 'Checks that DynamoDB Accelerator (DAX) clusters have server-side encryption at rest enabled so the on-disk cache, configuration and logs cannot be read from the underlying storage.',
    remediation: 'Recreate the cluster with encryption enabled (aws dax create-cluster ... --sse-specification Enabled=true), migrate the application endpoint, then delete the unencrypted cluster; encryption cannot be enabled in place.',
    tags: ['dynamodb', 'dax', 'encryption'],
  },
  {
    checkId: 'dynamodb_accelerator_cluster_in_transit_encryption_enabled',
    provider: 'aws',
    service: 'dynamodb',
    title: 'DAX Cluster In-Transit Encryption Disabled',
    severity: 'MEDIUM',
    description: 'Checks that DAX clusters enforce TLS endpoint encryption so client traffic to the cluster cannot be intercepted or tampered with.',
    remediation: 'Create a new cluster with --cluster-endpoint-encryption-type TLS, point the application at the new endpoint, then delete the non-TLS cluster; endpoint encryption cannot be changed in place.',
    tags: ['dynamodb', 'dax', 'encryption'],
  },
  {
    checkId: 'dynamodb_accelerator_cluster_multi_az',
    provider: 'aws',
    service: 'dynamodb',
    title: 'DAX Cluster Not Multi-AZ',
    severity: 'MEDIUM',
    description: 'Checks that DAX clusters have nodes in more than one Availability Zone; single-AZ clusters lose the cache entirely on an AZ outage, shifting full read load onto DynamoDB.',
    remediation: 'Increase the replication factor and spread nodes across AZs: aws dax increase-replication-factor --cluster-name <name> --new-replication-factor 2 --availability-zones <az-1> <az-2>',
    tags: ['dynamodb', 'dax', 'availability'],
  },
];
