import { CheckMetadata } from '../../types';

// Titles must stay byte-identical to the pre-registry hardcoded titles:
// the scan worker dedupes OPEN findings on service:title:fingerprint, so a
// reworded title would re-open every existing finding as "new".
export const ec2Checks: CheckMetadata[] = [
  {
    checkId: 'ec2_securitygroup_allow_ingress_from_internet_to_high_risk_tcp_ports',
    provider: 'aws',
    service: 'ec2',
    title: 'Overly Permissive Security Group Rule',
    severity: 'HIGH',
    description: 'Checks security groups for inbound rules that allow traffic from 0.0.0.0/0 (or ::/0) to high-risk ports or to all traffic.',
    remediation: 'Restrict inbound access to specific IPs or security groups instead of 0.0.0.0/0.',
    tags: ['ec2', 'security-group', 'network'],
  },
  {
    checkId: 'ec2_networkacl_allow_ingress_any_port',
    provider: 'aws',
    service: 'ec2',
    title: 'Overly Permissive Network ACL',
    severity: 'MEDIUM',
    description: 'Checks network ACLs for allow rules that permit traffic from 0.0.0.0/0 (or ::/0).',
    remediation: 'Review and restrict Network ACL rules to specific CIDR blocks.',
    tags: ['ec2', 'network-acl', 'network'],
  },
  {
    checkId: 'ec2_instance_public_ip_without_security_group',
    provider: 'aws',
    service: 'ec2',
    title: 'Instance Has Public IP Without Security Group',
    severity: 'HIGH',
    description: 'Checks for EC2 instances that have a public IP address but no security group attached.',
    remediation: 'Review and attach an appropriate security group to the instance.',
    tags: ['ec2', 'public-ip', 'network'],
  },
  {
    checkId: 'ec2_instance_imdsv2_enabled',
    provider: 'aws',
    service: 'ec2',
    title: 'IMDSv1 Enabled',
    severity: 'HIGH',
    description: 'Checks that EC2 instances enforce IMDSv2 (HttpTokens required) for instance metadata access.',
    remediation: 'Enable IMDSv2 on the instance to protect against SSRF attacks.',
    tags: ['ec2', 'metadata', 'imds'],
  },
  {
    checkId: 'ec2_instance_detailed_monitoring_enabled',
    provider: 'aws',
    service: 'ec2',
    title: 'Detailed Monitoring Not Enabled',
    severity: 'LOW',
    description: 'Checks that EC2 instances have detailed CloudWatch monitoring enabled.',
    remediation: 'Enable detailed monitoring for the instance.',
    tags: ['ec2', 'monitoring'],
  },
  {
    checkId: 'ec2_ebs_default_encryption',
    provider: 'aws',
    service: 'ec2',
    title: 'EBS Default Encryption Not Enabled',
    severity: 'MEDIUM',
    description: 'Checks that EBS default encryption is enabled for the region so new EBS volumes are automatically encrypted.',
    remediation: 'Enable EBS default encryption in the EC2 console (EC2 → Settings → Data protection) or via CLI: aws ec2 enable-ebs-encryption-by-default',
    tags: ['ec2', 'ebs', 'encryption', 'cis-2.2.1'],
    compliance: {
      cis_2_0_aws: ['2.2.1'],
    },
  },
  {
    checkId: 'ec2_instance_internet_reachable',
    provider: 'aws',
    service: 'ec2',
    title: 'Publicly Reachable EC2 Instance',
    severity: 'HIGH',
    description: 'Checks for EC2 instances that are truly reachable from the internet: public IP, subnet routed to an internet gateway, and security group rules open to 0.0.0.0/0.',
    remediation: 'Verify the instance needs to be publicly accessible. If not, remove the public IP or place it behind a load balancer. Restrict security group rules to specific CIDR ranges.',
    tags: ['ec2', 'network-reachability', 'public-exposure', 'internet-facing'],
  },
  {
    checkId: 'ec2_instance_port_ssh_exposed_to_internet',
    provider: 'aws',
    service: 'ec2',
    title: 'Sensitive Port 22 (SSH) Exposed to Internet',
    severity: 'CRITICAL',
    description: 'Checks for internet-reachable EC2 instances with SSH port 22 open to 0.0.0.0/0.',
    remediation: 'Restrict port 22 in the security group. Use a bastion host, VPN, or AWS Systems Manager Session Manager instead of direct SSH access.',
    tags: ['ec2', 'network-reachability', 'open-port', 'internet-facing', 'ssh'],
  },
  {
    checkId: 'ec2_instance_port_rdp_exposed_to_internet',
    provider: 'aws',
    service: 'ec2',
    title: 'Sensitive Port 3389 (RDP) Exposed to Internet',
    severity: 'CRITICAL',
    description: 'Checks for internet-reachable EC2 instances with RDP port 3389 open to 0.0.0.0/0.',
    remediation: 'Restrict port 3389 in the security group. Use a bastion host, VPN, or AWS Systems Manager Session Manager instead of direct RDP access.',
    tags: ['ec2', 'network-reachability', 'open-port', 'internet-facing', 'rdp'],
  },
  {
    checkId: 'ec2_instance_port_mysql_exposed_to_internet',
    provider: 'aws',
    service: 'ec2',
    title: 'Sensitive Port 3306 (MySQL) Exposed to Internet',
    severity: 'CRITICAL',
    description: 'Checks for internet-reachable EC2 instances with MySQL port 3306 open to 0.0.0.0/0.',
    remediation: 'Restrict port 3306 in the security group. Use a bastion host, VPN, or AWS Systems Manager Session Manager instead of direct MySQL access.',
    tags: ['ec2', 'network-reachability', 'open-port', 'internet-facing', 'mysql'],
  },
  {
    checkId: 'ec2_instance_port_postgresql_exposed_to_internet',
    provider: 'aws',
    service: 'ec2',
    title: 'Sensitive Port 5432 (PostgreSQL) Exposed to Internet',
    severity: 'CRITICAL',
    description: 'Checks for internet-reachable EC2 instances with PostgreSQL port 5432 open to 0.0.0.0/0.',
    remediation: 'Restrict port 5432 in the security group. Use a bastion host, VPN, or AWS Systems Manager Session Manager instead of direct PostgreSQL access.',
    tags: ['ec2', 'network-reachability', 'open-port', 'internet-facing', 'postgresql'],
  },
  {
    checkId: 'ec2_instance_port_sqlserver_exposed_to_internet',
    provider: 'aws',
    service: 'ec2',
    title: 'Sensitive Port 1433 (MSSQL) Exposed to Internet',
    severity: 'CRITICAL',
    description: 'Checks for internet-reachable EC2 instances with MSSQL port 1433 open to 0.0.0.0/0.',
    remediation: 'Restrict port 1433 in the security group. Use a bastion host, VPN, or AWS Systems Manager Session Manager instead of direct MSSQL access.',
    tags: ['ec2', 'network-reachability', 'open-port', 'internet-facing', 'mssql'],
  },
  {
    checkId: 'ec2_instance_port_mongodb_exposed_to_internet',
    provider: 'aws',
    service: 'ec2',
    title: 'Sensitive Port 27017 (MongoDB) Exposed to Internet',
    severity: 'CRITICAL',
    description: 'Checks for internet-reachable EC2 instances with MongoDB port 27017 open to 0.0.0.0/0.',
    remediation: 'Restrict port 27017 in the security group. Use a bastion host, VPN, or AWS Systems Manager Session Manager instead of direct MongoDB access.',
    tags: ['ec2', 'network-reachability', 'open-port', 'internet-facing', 'mongodb'],
  },
  {
    checkId: 'ec2_instance_port_redis_exposed_to_internet',
    provider: 'aws',
    service: 'ec2',
    title: 'Sensitive Port 6379 (Redis) Exposed to Internet',
    severity: 'CRITICAL',
    description: 'Checks for internet-reachable EC2 instances with Redis port 6379 open to 0.0.0.0/0.',
    remediation: 'Restrict port 6379 in the security group. Use a bastion host, VPN, or AWS Systems Manager Session Manager instead of direct Redis access.',
    tags: ['ec2', 'network-reachability', 'open-port', 'internet-facing', 'redis'],
  },
  {
    checkId: 'ec2_instance_port_elasticsearch_exposed_to_internet',
    provider: 'aws',
    service: 'ec2',
    title: 'Sensitive Port 9200 (Elasticsearch) Exposed to Internet',
    severity: 'CRITICAL',
    description: 'Checks for internet-reachable EC2 instances with Elasticsearch port 9200 open to 0.0.0.0/0.',
    remediation: 'Restrict port 9200 in the security group. Use a bastion host, VPN, or AWS Systems Manager Session Manager instead of direct Elasticsearch access.',
    tags: ['ec2', 'network-reachability', 'open-port', 'internet-facing', 'elasticsearch'],
  },
  {
    checkId: 'ec2_instance_port_kibana_exposed_to_internet',
    provider: 'aws',
    service: 'ec2',
    title: 'Sensitive Port 5601 (Kibana) Exposed to Internet',
    severity: 'CRITICAL',
    description: 'Checks for internet-reachable EC2 instances with Kibana port 5601 open to 0.0.0.0/0.',
    remediation: 'Restrict port 5601 in the security group. Use a bastion host, VPN, or AWS Systems Manager Session Manager instead of direct Kibana access.',
    tags: ['ec2', 'network-reachability', 'open-port', 'internet-facing', 'kibana'],
  },
  {
    checkId: 'ec2_instance_port_etcd_exposed_to_internet',
    provider: 'aws',
    service: 'ec2',
    title: 'Sensitive Port 2379 (etcd) Exposed to Internet',
    severity: 'CRITICAL',
    description: 'Checks for internet-reachable EC2 instances with etcd port 2379 open to 0.0.0.0/0.',
    remediation: 'Restrict port 2379 in the security group. Use a bastion host, VPN, or AWS Systems Manager Session Manager instead of direct etcd access.',
    tags: ['ec2', 'network-reachability', 'open-port', 'internet-facing', 'etcd'],
  },
  {
    checkId: 'ec2_instance_port_consul_exposed_to_internet',
    provider: 'aws',
    service: 'ec2',
    title: 'Sensitive Port 8500 (Consul) Exposed to Internet',
    severity: 'CRITICAL',
    description: 'Checks for internet-reachable EC2 instances with Consul port 8500 open to 0.0.0.0/0.',
    remediation: 'Restrict port 8500 in the security group. Use a bastion host, VPN, or AWS Systems Manager Session Manager instead of direct Consul access.',
    tags: ['ec2', 'network-reachability', 'open-port', 'internet-facing', 'consul'],
  },
  {
    checkId: 'ec2_instance_port_kubernetes_api_exposed_to_internet',
    provider: 'aws',
    service: 'ec2',
    title: 'Sensitive Port 6443 (Kubernetes API) Exposed to Internet',
    severity: 'CRITICAL',
    description: 'Checks for internet-reachable EC2 instances with Kubernetes API port 6443 open to 0.0.0.0/0.',
    remediation: 'Restrict port 6443 in the security group. Use a bastion host, VPN, or AWS Systems Manager Session Manager instead of direct Kubernetes API access.',
    tags: ['ec2', 'network-reachability', 'open-port', 'internet-facing', 'kubernetes api'],
  },
];
