import { CheckMetadata } from '../../types';

// Titles must stay byte-identical to the pre-registry hardcoded titles:
// the scan worker dedupes OPEN findings on service:title:fingerprint, so a
// reworded title would re-open every existing finding as "new".
export const ec2Checks: CheckMetadata[] = [
  {
    checkId: 'ec2_securitygroup_allow_ingress_from_internet_to_high_risk_tcp_ports',
    provider: 'aws',
    service: 'ec2',
    title: 'Overly Permissive Security Group Rule',
    severity: 'HIGH',
    description: 'Checks security groups for inbound rules that allow traffic from 0.0.0.0/0 (or ::/0) to high-risk ports or to all traffic.',
    remediation: 'Restrict inbound access to specific IPs or security groups instead of 0.0.0.0/0.',
    tags: ['ec2', 'security-group', 'network'],
  },
  {
    checkId: 'ec2_networkacl_allow_ingress_any_port',
    provider: 'aws',
    service: 'ec2',
    title: 'Overly Permissive Network ACL',
    severity: 'MEDIUM',
    description: 'Checks network ACLs for allow rules that permit traffic from 0.0.0.0/0 (or ::/0).',
    remediation: 'Review and restrict Network ACL rules to specific CIDR blocks.',
    tags: ['ec2', 'network-acl', 'network'],
  },
  {
    checkId: 'ec2_instance_public_ip_without_security_group',
    provider: 'aws',
    service: 'ec2',
    title: 'Instance Has Public IP Without Security Group',
    severity: 'HIGH',
    description: 'Checks for EC2 instances that have a public IP address but no security group attached.',
    remediation: 'Review and attach an appropriate security group to the instance.',
    tags: ['ec2', 'public-ip', 'network'],
  },
  {
    checkId: 'ec2_instance_imdsv2_enabled',
    provider: 'aws',
    service: 'ec2',
    title: 'IMDSv1 Enabled',
    severity: 'HIGH',
    description: 'Checks that EC2 instances enforce IMDSv2 (HttpTokens required) for instance metadata access.',
    remediation: 'Enable IMDSv2 on the instance to protect against SSRF attacks.',
    tags: ['ec2', 'metadata', 'imds'],
  },
  {
    checkId: 'ec2_instance_detailed_monitoring_enabled',
    provider: 'aws',
    service: 'ec2',
    title: 'Detailed Monitoring Not Enabled',
    severity: 'LOW',
    description: 'Checks that EC2 instances have detailed CloudWatch monitoring enabled.',
    remediation: 'Enable detailed monitoring for the instance.',
    tags: ['ec2', 'monitoring'],
  },
  {
    checkId: 'ec2_ebs_default_encryption',
    provider: 'aws',
    service: 'ec2',
    title: 'EBS Default Encryption Not Enabled',
    severity: 'MEDIUM',
    description: 'Checks that EBS default encryption is enabled for the region so new EBS volumes are automatically encrypted.',
    remediation: 'Enable EBS default encryption in the EC2 console (EC2 → Settings → Data protection) or via CLI: aws ec2 enable-ebs-encryption-by-default',
    tags: ['ec2', 'ebs', 'encryption', 'cis-2.2.1'],
    compliance: {
      cis_2_0_aws: ['2.2.1'],
    },
  },
  {
    checkId: 'ec2_instance_internet_reachable',
    provider: 'aws',
    service: 'ec2',
    title: 'Publicly Reachable EC2 Instance',
    severity: 'HIGH',
    description: 'Checks for EC2 instances that are truly reachable from the internet: public IP, subnet routed to an internet gateway, and security group rules open to 0.0.0.0/0.',
    remediation: 'Verify the instance needs to be publicly accessible. If not, remove the public IP or place it behind a load balancer. Restrict security group rules to specific CIDR ranges.',
    tags: ['ec2', 'network-reachability', 'public-exposure', 'internet-facing'],
  },
  {
    checkId: 'ec2_instance_port_ssh_exposed_to_internet',
    provider: 'aws',
    service: 'ec2',
    title: 'Sensitive Port 22 (SSH) Exposed to Internet',
    severity: 'CRITICAL',
    description: 'Checks for internet-reachable EC2 instances with SSH port 22 open to 0.0.0.0/0.',
    remediation: 'Restrict port 22 in the security group. Use a bastion host, VPN, or AWS Systems Manager Session Manager instead of direct SSH access.',
    tags: ['ec2', 'network-reachability', 'open-port', 'internet-facing', 'ssh'],
  },
  {
    checkId: 'ec2_instance_port_rdp_exposed_to_internet',
    provider: 'aws',
    service: 'ec2',
    title: 'Sensitive Port 3389 (RDP) Exposed to Internet',
    severity: 'CRITICAL',
    description: 'Checks for internet-reachable EC2 instances with RDP port 3389 open to 0.0.0.0/0.',
    remediation: 'Restrict port 3389 in the security group. Use a bastion host, VPN, or AWS Systems Manager Session Manager instead of direct RDP access.',
    tags: ['ec2', 'network-reachability', 'open-port', 'internet-facing', 'rdp'],
  },
  {
    checkId: 'ec2_instance_port_mysql_exposed_to_internet',
    provider: 'aws',
    service: 'ec2',
    title: 'Sensitive Port 3306 (MySQL) Exposed to Internet',
    severity: 'CRITICAL',
    description: 'Checks for internet-reachable EC2 instances with MySQL port 3306 open to 0.0.0.0/0.',
    remediation: 'Restrict port 3306 in the security group. Use a bastion host, VPN, or AWS Systems Manager Session Manager instead of direct MySQL access.',
    tags: ['ec2', 'network-reachability', 'open-port', 'internet-facing', 'mysql'],
  },
  {
    checkId: 'ec2_instance_port_postgresql_exposed_to_internet',
    provider: 'aws',
    service: 'ec2',
    title: 'Sensitive Port 5432 (PostgreSQL) Exposed to Internet',
    severity: 'CRITICAL',
    description: 'Checks for internet-reachable EC2 instances with PostgreSQL port 5432 open to 0.0.0.0/0.',
    remediation: 'Restrict port 5432 in the security group. Use a bastion host, VPN, or AWS Systems Manager Session Manager instead of direct PostgreSQL access.',
    tags: ['ec2', 'network-reachability', 'open-port', 'internet-facing', 'postgresql'],
  },
  {
    checkId: 'ec2_instance_port_sqlserver_exposed_to_internet',
    provider: 'aws',
    service: 'ec2',
    title: 'Sensitive Port 1433 (MSSQL) Exposed to Internet',
    severity: 'CRITICAL',
    description: 'Checks for internet-reachable EC2 instances with MSSQL port 1433 open to 0.0.0.0/0.',
    remediation: 'Restrict port 1433 in the security group. Use a bastion host, VPN, or AWS Systems Manager Session Manager instead of direct MSSQL access.',
    tags: ['ec2', 'network-reachability', 'open-port', 'internet-facing', 'mssql'],
  },
  {
    checkId: 'ec2_instance_port_mongodb_exposed_to_internet',
    provider: 'aws',
    service: 'ec2',
    title: 'Sensitive Port 27017 (MongoDB) Exposed to Internet',
    severity: 'CRITICAL',
    description: 'Checks for internet-reachable EC2 instances with MongoDB port 27017 open to 0.0.0.0/0.',
    remediation: 'Restrict port 27017 in the security group. Use a bastion host, VPN, or AWS Systems Manager Session Manager instead of direct MongoDB access.',
    tags: ['ec2', 'network-reachability', 'open-port', 'internet-facing', 'mongodb'],
  },
  {
    checkId: 'ec2_instance_port_redis_exposed_to_internet',
    provider: 'aws',
    service: 'ec2',
    title: 'Sensitive Port 6379 (Redis) Exposed to Internet',
    severity: 'CRITICAL',
    description: 'Checks for internet-reachable EC2 instances with Redis port 6379 open to 0.0.0.0/0.',
    remediation: 'Restrict port 6379 in the security group. Use a bastion host, VPN, or AWS Systems Manager Session Manager instead of direct Redis access.',
    tags: ['ec2', 'network-reachability', 'open-port', 'internet-facing', 'redis'],
  },
  {
    checkId: 'ec2_instance_port_elasticsearch_exposed_to_internet',
    provider: 'aws',
    service: 'ec2',
    title: 'Sensitive Port 9200 (Elasticsearch) Exposed to Internet',
    severity: 'CRITICAL',
    description: 'Checks for internet-reachable EC2 instances with Elasticsearch port 9200 open to 0.0.0.0/0.',
    remediation: 'Restrict port 9200 in the security group. Use a bastion host, VPN, or AWS Systems Manager Session Manager instead of direct Elasticsearch access.',
    tags: ['ec2', 'network-reachability', 'open-port', 'internet-facing', 'elasticsearch'],
  },
  {
    checkId: 'ec2_instance_port_kibana_exposed_to_internet',
    provider: 'aws',
    service: 'ec2',
    title: 'Sensitive Port 5601 (Kibana) Exposed to Internet',
    severity: 'CRITICAL',
    description: 'Checks for internet-reachable EC2 instances with Kibana port 5601 open to 0.0.0.0/0.',
    remediation: 'Restrict port 5601 in the security group. Use a bastion host, VPN, or AWS Systems Manager Session Manager instead of direct Kibana access.',
    tags: ['ec2', 'network-reachability', 'open-port', 'internet-facing', 'kibana'],
  },
  {
    checkId: 'ec2_instance_port_etcd_exposed_to_internet',
    provider: 'aws',
    service: 'ec2',
    title: 'Sensitive Port 2379 (etcd) Exposed to Internet',
    severity: 'CRITICAL',
    description: 'Checks for internet-reachable EC2 instances with etcd port 2379 open to 0.0.0.0/0.',
    remediation: 'Restrict port 2379 in the security group. Use a bastion host, VPN, or AWS Systems Manager Session Manager instead of direct etcd access.',
    tags: ['ec2', 'network-reachability', 'open-port', 'internet-facing', 'etcd'],
  },
  {
    checkId: 'ec2_instance_port_consul_exposed_to_internet',
    provider: 'aws',
    service: 'ec2',
    title: 'Sensitive Port 8500 (Consul) Exposed to Internet',
    severity: 'CRITICAL',
    description: 'Checks for internet-reachable EC2 instances with Consul port 8500 open to 0.0.0.0/0.',
    remediation: 'Restrict port 8500 in the security group. Use a bastion host, VPN, or AWS Systems Manager Session Manager instead of direct Consul access.',
    tags: ['ec2', 'network-reachability', 'open-port', 'internet-facing', 'consul'],
  },
  {
    checkId: 'ec2_instance_port_kubernetes_api_exposed_to_internet',
    provider: 'aws',
    service: 'ec2',
    title: 'Sensitive Port 6443 (Kubernetes API) Exposed to Internet',
    severity: 'CRITICAL',
    description: 'Checks for internet-reachable EC2 instances with Kubernetes API port 6443 open to 0.0.0.0/0.',
    remediation: 'Restrict port 6443 in the security group. Use a bastion host, VPN, or AWS Systems Manager Session Manager instead of direct Kubernetes API access.',
    tags: ['ec2', 'network-reachability', 'open-port', 'internet-facing', 'kubernetes api'],
  },
  // ─── Prowler-ported checks (logic derived from Prowler, Apache-2.0) ─────────
  {
    checkId: 'ec2_ami_account_block_public_access',
    provider: 'aws',
    service: 'ec2',
    title: 'AMI Block Public Access Not Enabled',
    severity: 'MEDIUM',
    description: 'Checks that AMI Block Public Access is enabled (block-new-sharing) for the account in the region so no AMI can be made public.',
    remediation: 'Enable AMI block public access: aws ec2 enable-image-block-public-access --image-block-public-access-state block-new-sharing, and add SCP guardrails so it cannot be disabled.',
    tags: ['ec2', 'ami', 'public-exposure', 'account-setting'],
  },
  {
    checkId: 'ec2_ami_public',
    provider: 'aws',
    service: 'ec2',
    title: 'Publicly Shared AMI',
    severity: 'CRITICAL',
    description: 'Checks that AMIs owned by the account are not publicly shared via launch permissions (Group=all).',
    remediation: 'Make the AMI private with modify-image-attribute, share only with specific accounts, and enable AMI block public access for the region.',
    tags: ['ec2', 'ami', 'public-exposure'],
  },
  {
    checkId: 'ec2_client_vpn_endpoint_connection_logging_enabled',
    provider: 'aws',
    service: 'ec2',
    title: 'Client VPN Connection Logging Not Enabled',
    severity: 'LOW',
    description: 'Checks that Client VPN endpoints log client connect and disconnect events to CloudWatch Logs.',
    remediation: 'Enable connection logging on the Client VPN endpoint with a CloudWatch log group so remote-access events leave an audit trail.',
    tags: ['ec2', 'vpn', 'logging'],
  },
  {
    checkId: 'ec2_confidential_workload_host_imdsv2_not_enforced',
    provider: 'aws',
    service: 'ec2',
    title: 'Confidential Workload Host Without IMDSv2 Enforced',
    severity: 'HIGH',
    description: 'Checks that instances hosting Nitro Enclave workloads (EnclaveOptions enabled) enforce IMDSv2 (HttpTokens=required) on the metadata service.',
    remediation: 'Enforce IMDSv2 on the enclave host with modify-instance-metadata-options --http-tokens required so host-side SSRF cannot lift the credentials the enclave depends on.',
    tags: ['ec2', 'enclave', 'imds', 'metadata'],
  },
  {
    checkId: 'ec2_confidential_workload_host_not_running',
    provider: 'aws',
    service: 'ec2',
    title: 'Nitro Enclave Parent Instance Not Running',
    severity: 'MEDIUM',
    description: 'Checks that enclave-enabled instances are not stopped, shutting down, or terminated, since enclaves are destroyed when their parent stops.',
    remediation: 'Start the parent instance and relaunch the enclave, or decommission downstream dependencies on enclave availability; prefer Auto Scaling lifecycle hooks that recreate enclaves.',
    tags: ['ec2', 'enclave', 'resilience'],
  },
  {
    checkId: 'ec2_confidential_workload_host_public_ip',
    provider: 'aws',
    service: 'ec2',
    title: 'Confidential Workload Host Internet-Exposed',
    severity: 'MEDIUM',
    description: 'Checks that enclave-enabled hosts have no public IPv4, no globally routable IPv6, and do not sit in a subnet routed to an internet gateway.',
    remediation: 'Place enclave hosts in private subnets only, remove public and Elastic IPs, and route required egress through a NAT gateway.',
    tags: ['ec2', 'enclave', 'public-exposure', 'network'],
  },
  {
    checkId: 'ec2_confidential_workload_host_unrestricted_ingress',
    provider: 'aws',
    service: 'ec2',
    title: 'Confidential Workload Host With Unrestricted Ingress',
    severity: 'HIGH',
    description: 'Checks that security groups attached to enclave-enabled hosts do not expose TCP/UDP ports outside the allow-list (22, 80, 443) to 0.0.0.0/0 or ::/0.',
    remediation: 'Restrict internet-facing ingress on enclave hosts to the minimum standard ports and use security-group-to-security-group references for internal services.',
    tags: ['ec2', 'enclave', 'security-group', 'network'],
  },
  {
    checkId: 'ec2_confidential_workload_host_vsock_proxy_exposed',
    provider: 'aws',
    service: 'ec2',
    title: 'Confidential Workload Host vsock-Proxy Ports Exposed',
    severity: 'MEDIUM',
    description: 'Checks that enclave-enabled hosts do not expose TCP ports commonly used by vsock-proxy bridges (5000, 8000-8090, 9000) to the internet. Heuristic control.',
    remediation: 'Restrict the vsock-proxy TCP ports to internal CIDRs or peer security groups; verify flagged ports against the actual proxy scheme before broad remediation.',
    tags: ['ec2', 'enclave', 'security-group', 'network'],
  },
  {
    checkId: 'ec2_ebs_snapshot_account_block_public_access',
    provider: 'aws',
    service: 'ec2',
    title: 'EBS Snapshot Block Public Access Not Fully Enabled',
    severity: 'HIGH',
    description: 'Checks that account-level Block Public Access for EBS snapshots is set to block-all-sharing in regions that have snapshots.',
    remediation: 'Run aws ec2 enable-snapshot-block-public-access --state block-all-sharing and review snapshots that were already shared publicly.',
    tags: ['ec2', 'ebs', 'snapshot', 'public-exposure', 'account-setting'],
  },
  {
    checkId: 'ec2_ebs_volume_protected_by_backup_plan',
    provider: 'aws',
    service: 'ec2',
    title: 'EBS Volume Not Protected by Backup Plan',
    severity: 'MEDIUM',
    description: 'Checks that each EBS volume is covered by an AWS Backup plan, either directly or through a wildcard resource selection.',
    remediation: 'Assign the volume to an AWS Backup plan aligned to your RPO/RTO, using tags or a wildcard selection for automatic coverage.',
    tags: ['ec2', 'ebs', 'backup', 'resilience'],
  },
  {
    checkId: 'ec2_ebs_volume_snapshots_exists',
    provider: 'aws',
    service: 'ec2',
    title: 'EBS Volume Without Snapshots',
    severity: 'HIGH',
    description: 'Checks that each EBS volume has at least one snapshot available for point-in-time recovery.',
    remediation: 'Create a snapshot of the volume and automate recurring snapshots with Data Lifecycle Manager or AWS Backup.',
    tags: ['ec2', 'ebs', 'snapshot', 'resilience'],
  },
  {
    checkId: 'ec2_elastic_ip_unassigned',
    provider: 'aws',
    service: 'ec2',
    title: 'Unassigned Elastic IP',
    severity: 'LOW',
    description: 'Checks for Elastic IP addresses that are allocated but not associated with any instance or network interface.',
    remediation: 'Associate the Elastic IP where required or release it: aws ec2 release-address --allocation-id <allocation-id>.',
    tags: ['ec2', 'elastic-ip', 'cost', 'hygiene'],
  },
  {
    checkId: 'ec2_instance_account_imdsv2_enabled',
    provider: 'aws',
    service: 'ec2',
    title: 'Account-Level IMDSv2 Default Not Enabled',
    severity: 'HIGH',
    description: 'Checks that the account-level EC2 instance metadata defaults require IMDSv2 (HttpTokens=required) so new instances disable IMDSv1 by default.',
    remediation: 'Run aws ec2 modify-instance-metadata-defaults --http-tokens required in each active region and add SCP/IAM guardrails.',
    tags: ['ec2', 'imds', 'metadata', 'account-setting'],
  },
  {
    checkId: 'ec2_instance_internet_facing_with_instance_profile',
    provider: 'aws',
    service: 'ec2',
    title: 'Internet-Facing Instance With Instance Profile',
    severity: 'HIGH',
    description: 'Checks for EC2 instances that have both a public IP address and an IAM instance profile attached, expanding the credential-theft blast radius.',
    remediation: 'Remove the public exposure or the instance profile; place workloads behind a load balancer, enforce IMDSv2, and apply least privilege to the role.',
    tags: ['ec2', 'public-exposure', 'iam', 'network'],
  },
  {
    checkId: 'ec2_instance_older_than_specific_days',
    provider: 'aws',
    service: 'ec2',
    title: 'Long-Running EC2 Instance',
    severity: 'MEDIUM',
    description: 'Checks for running EC2 instances launched more than 180 days ago, which tend to drift from patch and hardening baselines.',
    remediation: 'Rebuild long-lived instances from current hardened AMIs on a regular rotation, or retire them; use centralized patch management in the interim.',
    tags: ['ec2', 'patching', 'hygiene'],
  },
  {
    checkId: 'ec2_instance_paravirtual_type',
    provider: 'aws',
    service: 'ec2',
    title: 'Paravirtual Instance Type',
    severity: 'MEDIUM',
    description: 'Checks for EC2 instances using the legacy paravirtual virtualization type instead of HVM.',
    remediation: 'Migrate the workload to an HVM-based AMI on a current instance family, then terminate the paravirtual instance.',
    tags: ['ec2', 'virtualization', 'hygiene'],
  },
  {
    checkId: 'ec2_instance_port_cassandra_exposed_to_internet',
    provider: 'aws',
    service: 'ec2',
    title: 'Cassandra Ports Exposed to Internet',
    severity: 'CRITICAL',
    description: 'Checks for EC2 instances with Cassandra ports (7000, 7001, 7199, 9042, 9160) open to 0.0.0.0/0; severity scales with public IP and subnet exposure.',
    remediation: 'Remove the internet-open ingress for the Cassandra ports and allow only trusted CIDRs or peer security groups; keep nodes in private subnets.',
    tags: ['ec2', 'open-port', 'internet-facing', 'cassandra'],
  },
  {
    checkId: 'ec2_instance_port_cifs_exposed_to_internet',
    provider: 'aws',
    service: 'ec2',
    title: 'CIFS/SMB Ports Exposed to Internet',
    severity: 'CRITICAL',
    description: 'Checks for EC2 instances with CIFS/SMB ports (139, 445) open to 0.0.0.0/0; severity scales with public IP and subnet exposure.',
    remediation: 'Remove the internet-open ingress for ports 139 and 445; restrict SMB to trusted internal sources or replace it with SFTP.',
    tags: ['ec2', 'open-port', 'internet-facing', 'cifs'],
  },
  {
    checkId: 'ec2_instance_port_elasticsearch_kibana_exposed_to_internet',
    provider: 'aws',
    service: 'ec2',
    title: 'Elasticsearch/Kibana Ports Exposed to Internet',
    severity: 'CRITICAL',
    description: 'Checks for EC2 instances with Elasticsearch/Kibana ports (9200, 9300, 5601) open to 0.0.0.0/0; severity scales with public IP and subnet exposure.',
    remediation: 'Remove the internet-open ingress for ports 9200, 9300 and 5601; keep the cluster private and require authentication and TLS.',
    tags: ['ec2', 'open-port', 'internet-facing', 'elasticsearch', 'kibana'],
  },
  {
    checkId: 'ec2_instance_port_ftp_exposed_to_internet',
    provider: 'aws',
    service: 'ec2',
    title: 'FTP Ports Exposed to Internet',
    severity: 'CRITICAL',
    description: 'Checks for EC2 instances with FTP ports (20, 21) open to 0.0.0.0/0; severity scales with public IP and subnet exposure.',
    remediation: 'Remove the internet-open ingress for ports 20-21 and prefer SFTP/FTPS restricted to trusted sources.',
    tags: ['ec2', 'open-port', 'internet-facing', 'ftp'],
  },
  {
    checkId: 'ec2_instance_port_kafka_exposed_to_internet',
    provider: 'aws',
    service: 'ec2',
    title: 'Kafka Port Exposed to Internet',
    severity: 'CRITICAL',
    description: 'Checks for EC2 instances with Kafka port 9092 open to 0.0.0.0/0; severity scales with public IP and subnet exposure.',
    remediation: 'Remove the internet-open ingress for port 9092; keep brokers in private subnets with TLS and authenticated clients.',
    tags: ['ec2', 'open-port', 'internet-facing', 'kafka'],
  },
  {
    checkId: 'ec2_instance_port_kerberos_exposed_to_internet',
    provider: 'aws',
    service: 'ec2',
    title: 'Kerberos Ports Exposed to Internet',
    severity: 'CRITICAL',
    description: 'Checks for EC2 instances with Kerberos ports (88, 464, 749, 750) open to 0.0.0.0/0; severity scales with public IP and subnet exposure.',
    remediation: 'Remove the internet-open ingress for the Kerberos ports; keep KDCs in private subnets reachable only via VPN or peering.',
    tags: ['ec2', 'open-port', 'internet-facing', 'kerberos'],
  },
  {
    checkId: 'ec2_instance_port_ldap_exposed_to_internet',
    provider: 'aws',
    service: 'ec2',
    title: 'LDAP Ports Exposed to Internet',
    severity: 'CRITICAL',
    description: 'Checks for EC2 instances with LDAP/LDAPS ports (389, 636) open to 0.0.0.0/0; severity scales with public IP and subnet exposure.',
    remediation: 'Remove the internet-open ingress for ports 389 and 636; allowlist trusted CIDRs, require LDAPS and disable insecure binds.',
    tags: ['ec2', 'open-port', 'internet-facing', 'ldap'],
  },
  {
    checkId: 'ec2_instance_port_memcached_exposed_to_internet',
    provider: 'aws',
    service: 'ec2',
    title: 'Memcached Port Exposed to Internet',
    severity: 'CRITICAL',
    description: 'Checks for EC2 instances with Memcached port 11211 open to 0.0.0.0/0; severity scales with public IP and subnet exposure.',
    remediation: 'Remove the internet-open ingress for port 11211 and restrict Memcached to internal clients only.',
    tags: ['ec2', 'open-port', 'internet-facing', 'memcached'],
  },
  {
    checkId: 'ec2_instance_port_oracle_exposed_to_internet',
    provider: 'aws',
    service: 'ec2',
    title: 'Oracle Ports Exposed to Internet',
    severity: 'CRITICAL',
    description: 'Checks for EC2 instances with Oracle ports (1521, 2483, 2484) open to 0.0.0.0/0; severity scales with public IP and subnet exposure.',
    remediation: 'Remove the internet-open ingress for the Oracle listener ports and allow only trusted CIDRs or peer security groups.',
    tags: ['ec2', 'open-port', 'internet-facing', 'oracle'],
  },
  {
    checkId: 'ec2_instance_port_telnet_exposed_to_internet',
    provider: 'aws',
    service: 'ec2',
    title: 'Telnet Port Exposed to Internet',
    severity: 'CRITICAL',
    description: 'Checks for EC2 instances with Telnet port 23 open to 0.0.0.0/0; severity scales with public IP and subnet exposure.',
    remediation: 'Remove the internet-open ingress for port 23 and replace Telnet with SSH or Session Manager.',
    tags: ['ec2', 'open-port', 'internet-facing', 'telnet'],
  },
  {
    checkId: 'ec2_instance_profile_attached',
    provider: 'aws',
    service: 'ec2',
    title: 'Instance Profile Not Attached',
    severity: 'MEDIUM',
    description: 'Checks that EC2 instances have an IAM instance profile attached so workloads use role credentials instead of static keys.',
    remediation: 'Attach a least-privilege IAM instance profile to the instance via Actions > Security > Modify IAM role.',
    tags: ['ec2', 'iam', 'identity'],
  },
  {
    checkId: 'ec2_instance_public_ip',
    provider: 'aws',
    service: 'ec2',
    title: 'Instance With Public IP',
    severity: 'MEDIUM',
    description: 'Checks for EC2 instances with a public IPv4 address, which makes them directly reachable and scannable from the internet.',
    remediation: 'Remove the public IP: disassociate any Elastic IP or relaunch without auto-assign public IP; expose the workload via a load balancer instead.',
    tags: ['ec2', 'public-ip', 'public-exposure', 'network'],
  },
  {
    checkId: 'ec2_instance_secrets_user_data',
    provider: 'aws',
    service: 'ec2',
    title: 'Secrets in Instance User Data',
    severity: 'HIGH',
    description: 'Checks EC2 instance User Data for credential-like content such as access keys, private keys and secret assignments.',
    remediation: 'Remove secrets from User Data, fetch them at runtime from Secrets Manager or SSM Parameter Store via the instance role, and rotate any exposed credentials.',
    tags: ['ec2', 'secrets', 'user-data'],
  },
  {
    checkId: 'ec2_instance_stopped_older_than_specific_days',
    provider: 'aws',
    service: 'ec2',
    title: 'Long-Stopped EC2 Instance',
    severity: 'LOW',
    description: 'Checks for EC2 instances that have been in the stopped state for more than 30 days while still retaining volumes, credentials and network configuration.',
    remediation: 'Terminate long-stopped instances that are no longer needed, or start and patch them and return them to an actively managed lifecycle.',
    tags: ['ec2', 'hygiene', 'cost'],
  },
  {
    checkId: 'ec2_instance_uses_single_eni',
    provider: 'aws',
    service: 'ec2',
    title: 'Instance With Multiple ENIs',
    severity: 'LOW',
    description: 'Checks that EC2 instances use only one elastic network interface; dual-homed hosts can bypass segmentation between subnets.',
    remediation: 'Detach secondary network interfaces unless multi-homing is formally approved; use gateways or load balancers instead of dual-homed hosts.',
    tags: ['ec2', 'eni', 'network', 'segmentation'],
  },
  {
    checkId: 'ec2_instance_with_outdated_ami',
    provider: 'aws',
    service: 'ec2',
    title: 'Instance Using Deprecated AMI',
    severity: 'MEDIUM',
    description: 'Checks for EC2 instances launched from Amazon-owned AMIs whose deprecation time has passed.',
    remediation: 'Rebuild the instance from a current, non-deprecated AMI and update launch templates or Auto Scaling groups that reference the old image.',
    tags: ['ec2', 'ami', 'patching'],
  },
  {
    checkId: 'ec2_launch_template_imdsv2_required',
    provider: 'aws',
    service: 'ec2',
    title: 'Launch Template Without IMDSv2 Required',
    severity: 'HIGH',
    description: 'Checks that EC2 launch templates have at least one version with IMDSv2 required (or the metadata service disabled) so launched instances block IMDSv1.',
    remediation: 'Create a new launch template version with MetadataOptions HttpTokens=required and set it as the default version.',
    tags: ['ec2', 'launch-template', 'imds', 'metadata'],
  },
  {
    checkId: 'ec2_launch_template_no_public_ip',
    provider: 'aws',
    service: 'ec2',
    title: 'Launch Template Assigns Public IP',
    severity: 'HIGH',
    description: 'Checks that launch template versions neither auto-assign public IP addresses nor reference network interfaces that already have public IPs.',
    remediation: 'Create a new launch template version with AssociatePublicIpAddress=false and no public-IP network interfaces, and set it as the default version.',
    tags: ['ec2', 'launch-template', 'public-exposure', 'network'],
  },
  {
    checkId: 'ec2_launch_template_no_secrets',
    provider: 'aws',
    service: 'ec2',
    title: 'Secrets in Launch Template User Data',
    severity: 'HIGH',
    description: 'Checks the User Data of every launch template version for credential-like content such as access keys, private keys and secret assignments.',
    remediation: 'Create a clean template version without secrets, delete the affected versions, rotate exposed credentials, and fetch secrets at runtime from Secrets Manager or SSM Parameter Store.',
    tags: ['ec2', 'launch-template', 'secrets', 'user-data'],
  },
  {
    checkId: 'ec2_networkacl_allow_ingress_tcp_port_22',
    provider: 'aws',
    service: 'ec2',
    title: 'Network ACL Allows SSH Port 22 From Internet',
    severity: 'MEDIUM',
    description: 'Checks network ACLs for entries that end up allowing ingress from 0.0.0.0/0 (or ::/0) to TCP port 22 at the subnet boundary.',
    remediation: 'Remove or deny the allow entry for TCP port 22 from 0.0.0.0/0 in the network ACL; restrict SSH to trusted sources or use Session Manager.',
    tags: ['ec2', 'network-acl', 'ssh', 'network'],
  },
  {
    checkId: 'ec2_networkacl_allow_ingress_tcp_port_3389',
    provider: 'aws',
    service: 'ec2',
    title: 'Network ACL Allows RDP Port 3389 From Internet',
    severity: 'MEDIUM',
    description: 'Checks network ACLs for entries that end up allowing ingress from 0.0.0.0/0 (or ::/0) to TCP port 3389 at the subnet boundary.',
    remediation: 'Remove or deny the allow entry for TCP port 3389 from 0.0.0.0/0 in the network ACL; restrict RDP to admin ranges or use Session Manager.',
    tags: ['ec2', 'network-acl', 'rdp', 'network'],
  },
  {
    checkId: 'ec2_networkacl_unused',
    provider: 'aws',
    service: 'ec2',
    title: 'Unused Network ACL',
    severity: 'LOW',
    description: 'Checks for non-default network ACLs that are not associated with any subnet.',
    remediation: 'Delete the unused network ACL or associate it with the intended subnets; tag retained ACLs with owner and purpose.',
    tags: ['ec2', 'network-acl', 'hygiene'],
  },
  {
    checkId: 'ec2_securitygroup_allow_ingress_from_internet_to_all_ports',
    provider: 'aws',
    service: 'ec2',
    title: 'Security Group Open to Internet on All Ports',
    severity: 'CRITICAL',
    description: 'Checks in-use security groups for ingress rules that allow all ports and protocols from 0.0.0.0/0 or ::/0.',
    remediation: 'Delete the all-traffic ingress rule and allow only the specific ports and trusted sources the workload needs.',
    tags: ['ec2', 'security-group', 'internet-facing', 'network'],
  },
  {
    checkId: 'ec2_securitygroup_allow_ingress_from_internet_to_any_port',
    provider: 'aws',
    service: 'ec2',
    title: 'Security Group Open to Internet on Any Port',
    severity: 'HIGH',
    description: 'Checks in-use security groups with any internet-open ingress that are attached to network interfaces other than approved public-facing types (API Gateway managed, VPC endpoints, ELB-owned).',
    remediation: 'Remove the 0.0.0.0/0 and ::/0 ingress rules, or move public exposure behind a load balancer, API gateway or WAF.',
    tags: ['ec2', 'security-group', 'internet-facing', 'network'],
  },
  {
    checkId: 'ec2_securitygroup_allow_ingress_from_internet_to_any_port_from_ip',
    provider: 'aws',
    service: 'ec2',
    title: 'Security Group Allows Ingress From Specific Public IP',
    severity: 'MEDIUM',
    description: 'Checks in-use security groups for ingress rules sourced from specific globally routable IP addresses (wildcards excluded), which often become stale personal or third-party allowlists.',
    remediation: 'Remove stale public-IP allowlist rules; use VPN, Session Manager or PrivateLink for individual and third-party access instead.',
    tags: ['ec2', 'security-group', 'network', 'hygiene'],
  },
  {
    checkId: 'ec2_securitygroup_allow_ingress_from_internet_to_tcp_port_22',
    provider: 'aws',
    service: 'ec2',
    title: 'Security Group Allows SSH Port 22 From Internet',
    severity: 'HIGH',
    description: 'Checks in-use security groups for ingress rules that allow TCP port 22 from 0.0.0.0/0 or ::/0.',
    remediation: 'Remove the internet-open rule for port 22; allow only trusted IPs or use a bastion, VPN or Session Manager.',
    tags: ['ec2', 'security-group', 'internet-facing', 'ssh'],
  },
  {
    checkId: 'ec2_securitygroup_allow_ingress_from_internet_to_tcp_port_3389',
    provider: 'aws',
    service: 'ec2',
    title: 'Security Group Allows RDP Port 3389 From Internet',
    severity: 'HIGH',
    description: 'Checks in-use security groups for ingress rules that allow TCP port 3389 from 0.0.0.0/0 or ::/0.',
    remediation: 'Remove the internet-open rule for port 3389; allow only admin ranges or use a bastion, VPN or Session Manager.',
    tags: ['ec2', 'security-group', 'internet-facing', 'rdp'],
  },
  {
    checkId: 'ec2_securitygroup_allow_ingress_from_internet_to_tcp_port_cassandra_7199_9160_8888',
    provider: 'aws',
    service: 'ec2',
    title: 'Security Group Allows Cassandra Ports From Internet',
    severity: 'HIGH',
    description: 'Checks in-use security groups for ingress rules that allow Cassandra TCP ports 7199, 9160 or 8888 from 0.0.0.0/0 or ::/0.',
    remediation: 'Remove the internet-open rules for the Cassandra ports and allow only trusted CIDRs or peer security groups.',
    tags: ['ec2', 'security-group', 'internet-facing', 'cassandra'],
  },
  {
    checkId: 'ec2_securitygroup_allow_ingress_from_internet_to_tcp_port_elasticsearch_kibana_9200_9300_5601',
    provider: 'aws',
    service: 'ec2',
    title: 'Security Group Allows Elasticsearch/Kibana Ports From Internet',
    severity: 'HIGH',
    description: 'Checks in-use security groups for ingress rules that allow Elasticsearch/Kibana TCP ports 9200, 9300 or 5601 from 0.0.0.0/0 or ::/0.',
    remediation: 'Remove the internet-open rules for ports 9200, 9300 and 5601 and keep the cluster reachable only from trusted networks.',
    tags: ['ec2', 'security-group', 'internet-facing', 'elasticsearch', 'kibana'],
  },
  {
    checkId: 'ec2_securitygroup_allow_ingress_from_internet_to_tcp_port_ftp_20_21',
    provider: 'aws',
    service: 'ec2',
    title: 'Security Group Allows FTP Ports From Internet',
    severity: 'HIGH',
    description: 'Checks in-use security groups for ingress rules that allow FTP TCP ports 20 or 21 from 0.0.0.0/0 or ::/0.',
    remediation: 'Remove the internet-open rules for ports 20-21 and prefer SFTP/FTPS restricted to trusted sources.',
    tags: ['ec2', 'security-group', 'internet-facing', 'ftp'],
  },
  {
    checkId: 'ec2_securitygroup_allow_ingress_from_internet_to_tcp_port_kafka_9092',
    provider: 'aws',
    service: 'ec2',
    title: 'Security Group Allows Kafka Port From Internet',
    severity: 'HIGH',
    description: 'Checks in-use security groups for ingress rules that allow Kafka TCP port 9092 from 0.0.0.0/0 or ::/0.',
    remediation: 'Remove the internet-open rule for port 9092 and restrict broker access to trusted networks with TLS and client authentication.',
    tags: ['ec2', 'security-group', 'internet-facing', 'kafka'],
  },
  {
    checkId: 'ec2_securitygroup_allow_ingress_from_internet_to_tcp_port_memcached_11211',
    provider: 'aws',
    service: 'ec2',
    title: 'Security Group Allows Memcached Port From Internet',
    severity: 'HIGH',
    description: 'Checks in-use security groups for ingress rules that allow Memcached TCP port 11211 from 0.0.0.0/0 or ::/0.',
    remediation: 'Remove the internet-open rule for port 11211 and restrict Memcached to internal clients only.',
    tags: ['ec2', 'security-group', 'internet-facing', 'memcached'],
  },
  {
    checkId: 'ec2_securitygroup_allow_ingress_from_internet_to_tcp_port_mongodb_27017_27018',
    provider: 'aws',
    service: 'ec2',
    title: 'Security Group Allows MongoDB Ports From Internet',
    severity: 'HIGH',
    description: 'Checks in-use security groups for ingress rules that allow MongoDB TCP ports 27017 or 27018 from 0.0.0.0/0 or ::/0.',
    remediation: 'Remove the internet-open rules for ports 27017-27018 and restrict database access to application security groups.',
    tags: ['ec2', 'security-group', 'internet-facing', 'mongodb'],
  },
  {
    checkId: 'ec2_securitygroup_allow_ingress_from_internet_to_tcp_port_mysql_3306',
    provider: 'aws',
    service: 'ec2',
    title: 'Security Group Allows MySQL Port From Internet',
    severity: 'HIGH',
    description: 'Checks in-use security groups for ingress rules that allow MySQL TCP port 3306 from 0.0.0.0/0 or ::/0.',
    remediation: 'Remove the internet-open rule for port 3306 and restrict database access to application security groups.',
    tags: ['ec2', 'security-group', 'internet-facing', 'mysql'],
  },
  {
    checkId: 'ec2_securitygroup_allow_ingress_from_internet_to_tcp_port_oracle_1521_2483',
    provider: 'aws',
    service: 'ec2',
    title: 'Security Group Allows Oracle Ports From Internet',
    severity: 'HIGH',
    description: 'Checks in-use security groups for ingress rules that allow Oracle TCP ports 1521 or 2483 from 0.0.0.0/0 or ::/0.',
    remediation: 'Remove the internet-open rules for the Oracle listener ports and restrict database access to application security groups.',
    tags: ['ec2', 'security-group', 'internet-facing', 'oracle'],
  },
  {
    checkId: 'ec2_securitygroup_allow_ingress_from_internet_to_tcp_port_postgres_5432',
    provider: 'aws',
    service: 'ec2',
    title: 'Security Group Allows PostgreSQL Port From Internet',
    severity: 'HIGH',
    description: 'Checks in-use security groups for ingress rules that allow PostgreSQL TCP port 5432 from 0.0.0.0/0 or ::/0.',
    remediation: 'Remove the internet-open rule for port 5432 and restrict database access to application security groups.',
    tags: ['ec2', 'security-group', 'internet-facing', 'postgresql'],
  },
  {
    checkId: 'ec2_securitygroup_allow_ingress_from_internet_to_tcp_port_redis_6379',
    provider: 'aws',
    service: 'ec2',
    title: 'Security Group Allows Redis Port From Internet',
    severity: 'HIGH',
    description: 'Checks in-use security groups for ingress rules that allow Redis TCP port 6379 from 0.0.0.0/0 or ::/0.',
    remediation: 'Remove the internet-open rule for port 6379 and restrict Redis to internal clients with authentication enabled.',
    tags: ['ec2', 'security-group', 'internet-facing', 'redis'],
  },
  {
    checkId: 'ec2_securitygroup_allow_ingress_from_internet_to_tcp_port_sql_server_1433_1434',
    provider: 'aws',
    service: 'ec2',
    title: 'Security Group Allows SQL Server Ports From Internet',
    severity: 'HIGH',
    description: 'Checks in-use security groups for ingress rules that allow SQL Server TCP ports 1433 or 1434 from 0.0.0.0/0 or ::/0.',
    remediation: 'Remove the internet-open rules for ports 1433-1434 and restrict database access to application security groups.',
    tags: ['ec2', 'security-group', 'internet-facing', 'sqlserver'],
  },
  {
    checkId: 'ec2_securitygroup_allow_ingress_from_internet_to_tcp_port_telnet_23',
    provider: 'aws',
    service: 'ec2',
    title: 'Security Group Allows Telnet Port From Internet',
    severity: 'HIGH',
    description: 'Checks in-use security groups for ingress rules that allow Telnet TCP port 23 from 0.0.0.0/0 or ::/0.',
    remediation: 'Remove the internet-open rule for port 23 and replace Telnet with SSH or Session Manager.',
    tags: ['ec2', 'security-group', 'internet-facing', 'telnet'],
  },
  {
    checkId: 'ec2_securitygroup_allow_wide_open_public_ipv4',
    provider: 'aws',
    service: 'ec2',
    title: 'Security Group With Wide-Open Public IPv4 Range',
    severity: 'HIGH',
    description: 'Checks in-use security groups for ingress or egress rules with public (non-RFC1918) IPv4 CIDR ranges wider than /24.',
    remediation: 'Replace wide public CIDRs with specific /24-or-narrower ranges or private RFC1918 networks; restrict and log egress by default.',
    tags: ['ec2', 'security-group', 'network'],
  },
  {
    checkId: 'ec2_securitygroup_from_launch_wizard',
    provider: 'aws',
    service: 'ec2',
    title: 'Security Group Created by Launch Wizard',
    severity: 'MEDIUM',
    description: 'Checks for security groups named launch-wizard-*, which are auto-generated by the EC2 Launch Wizard and often overly permissive.',
    remediation: 'Replace launch-wizard groups with curated baseline security groups managed via IaC, then delete the auto-generated groups.',
    tags: ['ec2', 'security-group', 'hygiene'],
  },
  {
    checkId: 'ec2_securitygroup_not_used',
    provider: 'aws',
    service: 'ec2',
    title: 'Unused Security Group',
    severity: 'LOW',
    description: 'Checks for non-default security groups with no attached network interfaces and no references from other security groups.',
    remediation: 'Delete unused security groups to prevent stale, potentially permissive groups from being attached later without review.',
    tags: ['ec2', 'security-group', 'hygiene'],
  },
  {
    checkId: 'ec2_securitygroup_with_many_ingress_egress_rules',
    provider: 'aws',
    service: 'ec2',
    title: 'Security Group With Excessive Rules',
    severity: 'MEDIUM',
    description: 'Checks for security groups with more than 50 inbound or 50 outbound rules, where rule sprawl can hide overly permissive entries.',
    remediation: 'Split the group into role-specific security groups, prefer SG-to-SG references over broad CIDRs, and remove stale rules.',
    tags: ['ec2', 'security-group', 'hygiene'],
  },
  {
    checkId: 'ec2_transitgateway_auto_accept_vpc_attachments',
    provider: 'aws',
    service: 'ec2',
    title: 'Transit Gateway Auto-Accepts Shared VPC Attachments',
    severity: 'HIGH',
    description: 'Checks that Transit Gateways do not automatically accept cross-account shared VPC attachments (AutoAcceptSharedAttachments=enable).',
    remediation: 'Disable auto-accept with modify-transit-gateway --options AutoAcceptSharedAttachments=disable and require explicit approval for every attachment.',
    tags: ['ec2', 'transit-gateway', 'network', 'trust-boundary'],
  },
];
