import { CheckMetadata } from '../../types';

// Titles must stay byte-identical to the pre-registry hardcoded titles:
// the scan worker dedupes OPEN findings on service:title:fingerprint, so a
// reworded title would re-open every existing finding as "new".
export const ecsChecks: CheckMetadata[] = [
  {
    checkId: 'ecs_task_definition_host_network_mode',
    provider: 'aws',
    service: 'ecs',
    title: 'ECS Task Definition Uses Host Network Mode',
    severity: 'HIGH',
    description: 'Checks that ECS task definitions do not use "host" network mode, where containers share the host\'s network namespace, bypassing VPC isolation and allowing access to all host network interfaces.',
    remediation: 'Change network mode to "awsvpc" for better isolation. Each task gets its own ENI and security group.',
    tags: ['ecs', 'network', 'isolation'],
  },
  {
    checkId: 'ecs_task_definitions_no_privileged_containers',
    provider: 'aws',
    service: 'ecs',
    title: 'ECS Container Running in Privileged Mode',
    severity: 'CRITICAL',
    description: 'Checks that ECS containers do not run with privileged=true; privileged containers have full access to the host kernel and all devices — equivalent to root on the host.',
    remediation: 'Remove "privileged: true" from the container definition. Use specific Linux capabilities instead if needed.',
    tags: ['ecs', 'container', 'privilege'],
  },
  {
    checkId: 'ecs_container_non_root_user',
    provider: 'aws',
    service: 'ecs',
    title: 'ECS Container Running as Root User',
    severity: 'HIGH',
    description: 'Checks that ECS containers do not run as the root user; if the container is compromised, the attacker has root privileges inside the container.',
    remediation: 'Set a non-root user in the Dockerfile (USER 1000) or in the task definition user field.',
    tags: ['ecs', 'container', 'privilege'],
  },
  {
    checkId: 'ecs_task_definitions_no_environment_secrets',
    provider: 'aws',
    service: 'ecs',
    title: 'ECS Container Has Secrets in Plaintext Environment Variables',
    severity: 'HIGH',
    description: 'Checks that ECS containers do not pass secret-like values as plaintext environment variables, which are visible in task metadata, logs, and to anyone with DescribeTaskDefinition permission.',
    remediation: 'Replace plaintext env vars with ECS secrets integration: use "secrets" field referencing SSM Parameter Store SecureString or Secrets Manager ARNs. Example: { "name": "DB_PASSWORD", "valueFrom": "arn:aws:ssm:region:account:parameter/db-password" }',
    tags: ['ecs', 'container', 'secrets'],
  },
  {
    checkId: 'ecs_task_definitions_containers_readonly_access',
    provider: 'aws',
    service: 'ecs',
    title: 'ECS Container Root Filesystem Not Read-Only',
    severity: 'MEDIUM',
    description: 'Checks that ECS containers have readonlyRootFilesystem enabled; a writable root filesystem allows attackers to modify container files and install persistence tools.',
    remediation: 'Enable read-only root filesystem in the container definition: "readonlyRootFilesystem": true. Mount writable volumes only for directories that genuinely need write access (e.g. /tmp).',
    tags: ['ecs', 'container', 'filesystem'],
  },
  {
    checkId: 'ecs_container_resource_limits_configured',
    provider: 'aws',
    service: 'ecs',
    title: 'ECS Container Has No Resource Limits',
    severity: 'LOW',
    description: 'Checks that ECS containers have CPU or memory limits configured; without limits, a compromised or buggy container can consume all host resources (noisy neighbor / DoS).',
    remediation: 'Set CPU and memory limits on the container definition to prevent resource exhaustion.',
    tags: ['ecs', 'container', 'resources'],
  },
  {
    checkId: 'ecs_service_deployment_circuit_breaker_enabled',
    provider: 'aws',
    service: 'ecs',
    title: 'ECS Service Deployment Circuit Breaker Disabled',
    severity: 'LOW',
    description: 'Checks that ECS services have a deployment circuit breaker enabled; without it, failed deployments keep retrying indefinitely instead of rolling back automatically.',
    remediation: 'Enable deployment circuit breaker with rollback: set deploymentCircuitBreaker.enable=true and rollback=true in service configuration.',
    tags: ['ecs', 'service', 'deployment'],
  },
  {
    checkId: 'ecs_cluster_container_insights_enabled',
    provider: 'aws',
    service: 'ecs',
    title: 'ECS Cluster Container Insights Disabled',
    severity: 'MEDIUM',
    description: 'Checks that ECS clusters have CloudWatch Container Insights set to enabled or enhanced; without it, cluster, service, and task telemetry is not collected, delaying detection of failures and abuse.',
    remediation: 'Enable Container Insights on the cluster: aws ecs update-cluster-settings --cluster <cluster> --settings name=containerInsights,value=enabled (prefer "enhanced" for deeper visibility).',
    tags: ['ecs', 'monitoring', 'logging'],
  },
  {
    checkId: 'ecs_service_fargate_latest_platform_version',
    provider: 'aws',
    service: 'ecs',
    title: 'ECS Fargate Service Platform Version Outdated',
    severity: 'MEDIUM',
    description: 'Checks that ECS Fargate services run on the latest Fargate platform version (LATEST, or 1.4.0 for Linux / 1.0.0 for Windows); outdated platform versions miss kernel and runtime security patches.',
    remediation: 'Update the service to the latest platform version: aws ecs update-service --cluster <cluster> --service <service> --platform-version LATEST',
    tags: ['ecs', 'service', 'patching'],
  },
  {
    checkId: 'ecs_service_no_assign_public_ip',
    provider: 'aws',
    service: 'ecs',
    title: 'ECS Service Assigns Public IP Automatically',
    severity: 'HIGH',
    description: 'Checks that ECS services do not automatically assign public IPs to their tasks; publicly addressed tasks are directly reachable from the internet for scanning, brute force, and exploitation.',
    remediation: 'Set assignPublicIp=DISABLED in the service network configuration, run tasks in private subnets, and expose them through a load balancer or private endpoint instead.',
    tags: ['ecs', 'service', 'network', 'internet-exposed'],
  },
  {
    checkId: 'ecs_task_definitions_host_namespace_not_shared',
    provider: 'aws',
    service: 'ecs',
    title: 'ECS Task Definition Shares Host Process Namespace',
    severity: 'HIGH',
    description: 'Checks that ECS task definitions do not use pidMode "host"; sharing the host process namespace lets containers enumerate, signal, and ptrace host processes, enabling privilege escalation.',
    remediation: 'Register a new task definition revision with pidMode set to "task" (or unset for per-container namespaces) and deregister the host-PID revision.',
    tags: ['ecs', 'container', 'isolation'],
  },
  {
    checkId: 'ecs_task_definitions_host_networking_mode_users',
    provider: 'aws',
    service: 'ecs',
    title: 'ECS Host Network Mode Container Running As Root',
    severity: 'HIGH',
    description: 'Checks that ECS task definitions using host network mode do not run non-privileged containers as root or with no user set; root containers on the host network can bind low ports, sniff traffic, and impersonate host services.',
    remediation: 'Switch the task definition to awsvpc network mode, or set a non-root user (e.g. 1000) on every non-privileged container that must keep host networking.',
    tags: ['ecs', 'container', 'network', 'privilege'],
  },
  {
    checkId: 'ecs_task_definitions_logging_block_mode',
    provider: 'aws',
    service: 'ecs',
    title: 'ECS Container Logging In Blocking Mode',
    severity: 'LOW',
    description: 'Checks that ECS containers with a log driver use non-blocking log delivery; in blocking mode a stalled log destination blocks writes to stdout/stderr and can make the container unresponsive.',
    remediation: 'Set "mode": "non-blocking" with an appropriate max-buffer-size in the logConfiguration options of each container and register a new task definition revision.',
    tags: ['ecs', 'container', 'logging', 'resilience'],
  },
  {
    checkId: 'ecs_task_definitions_logging_enabled',
    provider: 'aws',
    service: 'ecs',
    title: 'ECS Container Logging Not Configured',
    severity: 'HIGH',
    description: 'Checks that every container in an ECS task definition has a logConfiguration with a log driver; without container logs, intrusions and tampering go undetected and forensics is impossible.',
    remediation: 'Add a logConfiguration with a log driver (e.g. awslogs with a CloudWatch Logs group) to every container and register a new task definition revision.',
    tags: ['ecs', 'container', 'logging'],
  },
  {
    checkId: 'ecs_task_set_no_assign_public_ip',
    provider: 'aws',
    service: 'ecs',
    title: 'ECS Task Set Assigns Public IP Automatically',
    severity: 'HIGH',
    description: 'Checks that ECS task sets do not automatically assign public IPs to their tasks; publicly addressed tasks are directly reachable from the internet.',
    remediation: 'Recreate the task set (redeploy the service) with assignPublicIp=DISABLED in its network configuration and place tasks in private subnets behind a load balancer.',
    tags: ['ecs', 'network', 'internet-exposed'],
  },
];
