import { CheckMetadata } from '../../types';

// Titles must stay byte-identical to the pre-registry hardcoded titles:
// the scan worker dedupes OPEN findings on service:title:fingerprint, so a
// reworded title would re-open every existing finding as "new".
export const ecsChecks: CheckMetadata[] = [
  {
    checkId: 'ecs_task_definition_host_network_mode',
    provider: 'aws',
    service: 'ecs',
    title: 'ECS Task Definition Uses Host Network Mode',
    severity: 'HIGH',
    description: 'Checks that ECS task definitions do not use "host" network mode, where containers share the host\'s network namespace, bypassing VPC isolation and allowing access to all host network interfaces.',
    remediation: 'Change network mode to "awsvpc" for better isolation. Each task gets its own ENI and security group.',
    tags: ['ecs', 'network', 'isolation'],
  },
  {
    checkId: 'ecs_task_definitions_no_privileged_containers',
    provider: 'aws',
    service: 'ecs',
    title: 'ECS Container Running in Privileged Mode',
    severity: 'CRITICAL',
    description: 'Checks that ECS containers do not run with privileged=true; privileged containers have full access to the host kernel and all devices — equivalent to root on the host.',
    remediation: 'Remove "privileged: true" from the container definition. Use specific Linux capabilities instead if needed.',
    tags: ['ecs', 'container', 'privilege'],
  },
  {
    checkId: 'ecs_container_non_root_user',
    provider: 'aws',
    service: 'ecs',
    title: 'ECS Container Running as Root User',
    severity: 'HIGH',
    description: 'Checks that ECS containers do not run as the root user; if the container is compromised, the attacker has root privileges inside the container.',
    remediation: 'Set a non-root user in the Dockerfile (USER 1000) or in the task definition user field.',
    tags: ['ecs', 'container', 'privilege'],
  },
  {
    checkId: 'ecs_task_definitions_no_environment_secrets',
    provider: 'aws',
    service: 'ecs',
    title: 'ECS Container Has Secrets in Plaintext Environment Variables',
    severity: 'HIGH',
    description: 'Checks that ECS containers do not pass secret-like values as plaintext environment variables, which are visible in task metadata, logs, and to anyone with DescribeTaskDefinition permission.',
    remediation: 'Replace plaintext env vars with ECS secrets integration: use "secrets" field referencing SSM Parameter Store SecureString or Secrets Manager ARNs. Example: { "name": "DB_PASSWORD", "valueFrom": "arn:aws:ssm:region:account:parameter/db-password" }',
    tags: ['ecs', 'container', 'secrets'],
  },
  {
    checkId: 'ecs_task_definitions_containers_readonly_access',
    provider: 'aws',
    service: 'ecs',
    title: 'ECS Container Root Filesystem Not Read-Only',
    severity: 'MEDIUM',
    description: 'Checks that ECS containers have readonlyRootFilesystem enabled; a writable root filesystem allows attackers to modify container files and install persistence tools.',
    remediation: 'Enable read-only root filesystem in the container definition: "readonlyRootFilesystem": true. Mount writable volumes only for directories that genuinely need write access (e.g. /tmp).',
    tags: ['ecs', 'container', 'filesystem'],
  },
  {
    checkId: 'ecs_container_resource_limits_configured',
    provider: 'aws',
    service: 'ecs',
    title: 'ECS Container Has No Resource Limits',
    severity: 'LOW',
    description: 'Checks that ECS containers have CPU or memory limits configured; without limits, a compromised or buggy container can consume all host resources (noisy neighbor / DoS).',
    remediation: 'Set CPU and memory limits on the container definition to prevent resource exhaustion.',
    tags: ['ecs', 'container', 'resources'],
  },
  {
    checkId: 'ecs_service_deployment_circuit_breaker_enabled',
    provider: 'aws',
    service: 'ecs',
    title: 'ECS Service Deployment Circuit Breaker Disabled',
    severity: 'LOW',
    description: 'Checks that ECS services have a deployment circuit breaker enabled; without it, failed deployments keep retrying indefinitely instead of rolling back automatically.',
    remediation: 'Enable deployment circuit breaker with rollback: set deploymentCircuitBreaker.enable=true and rollback=true in service configuration.',
    tags: ['ecs', 'service', 'deployment'],
  },
];
