// Check logic derived from Prowler (Apache-2.0, https://github.com/prowler-cloud/prowler)
import { CheckMetadata } from '../../types';

export const efsChecks: CheckMetadata[] = [
  {
    checkId: 'efs_encryption_at_rest_enabled',
    provider: 'aws',
    service: 'efs',
    title: 'EFS Not Encrypted At Rest',
    severity: 'MEDIUM',
    description: 'Checks that EFS file systems have encryption at rest enabled using AWS KMS to protect file data and metadata.',
    remediation: 'Create a new encrypted file system, preferably with a customer-managed KMS key, and migrate the data; encryption cannot be enabled on an existing unencrypted file system. Enforce creation-time encryption via IAM or SCP policies.',
    tags: ['efs', 'encryption', 'kms'],
    compliance: {
      cis_2_0_aws: ['2.4.1'],
    },
  },
  {
    checkId: 'efs_not_publicly_accessible',
    provider: 'aws',
    service: 'efs',
    title: 'EFS Policy Allows Broad Access',
    severity: 'MEDIUM',
    description: 'Checks EFS file system policies for wildcard principals or missing elasticfilesystem:AccessedViaMountTarget condition; an absent policy leaves the file system open to any client within the VPC.',
    remediation: 'Attach a least-privilege file system policy without wildcard principals, require the elasticfilesystem:AccessedViaMountTarget=true condition, and constrain access with aws:SourceVpc or aws:SourceAccount.',
    tags: ['efs', 'public-access', 'resource-policy'],
  },
  {
    checkId: 'efs_have_backup_enabled',
    provider: 'aws',
    service: 'efs',
    title: 'EFS Backups Not Enabled',
    severity: 'MEDIUM',
    description: 'Checks that EFS file systems have automatic backups enabled via the file system backup policy.',
    remediation: 'Set the file system backup policy to ENABLED, use tiered retention with immutable vaults and cross-Region copies, and regularly test restores.',
    tags: ['efs', 'backup', 'data-protection'],
  },
  {
    checkId: 'efs_mount_target_not_publicly_accessible',
    provider: 'aws',
    service: 'efs',
    title: 'EFS Mount Target In Public Subnet',
    severity: 'MEDIUM',
    description: 'Checks that EFS mount targets are not placed in subnets that auto-assign public IPv4 addresses (MapPublicIpOnLaunch=true).',
    remediation: 'Place mount targets in private subnets that do not auto-assign public IPs and restrict NFS access via security groups to known sources.',
    tags: ['efs', 'public-access', 'network'],
  },
  {
    checkId: 'efs_multi_az_enabled',
    provider: 'aws',
    service: 'efs',
    title: 'EFS Not Multi-AZ Resilient',
    severity: 'MEDIUM',
    description: 'Checks that EFS file systems are Regional (not One Zone) with mount targets in more than one Availability Zone for fault tolerance.',
    remediation: 'Use Regional EFS and create mount targets in each required Availability Zone; avoid One Zone storage for critical data.',
    tags: ['efs', 'availability', 'resilience'],
  },
  {
    checkId: 'efs_access_point_enforce_root_directory',
    provider: 'aws',
    service: 'efs',
    title: 'EFS Access Point Exposes Root Directory',
    severity: 'MEDIUM',
    description: 'Checks that EFS access points enforce a scoped root directory; access points whose Path is "/" mount the entire file system instead of a dedicated subdirectory.',
    remediation: 'Set each access point root directory Path to a dedicated subdirectory, using per-application access points with enforced POSIX permissions.',
    tags: ['efs', 'access-point', 'least-privilege'],
  },
  {
    checkId: 'efs_access_point_enforce_user_identity',
    provider: 'aws',
    service: 'efs',
    title: 'EFS Access Point Missing POSIX User',
    severity: 'MEDIUM',
    description: 'Checks that EFS access points define a POSIX user identity (uid/gid) so client access is mapped to a controlled, least-privilege identity.',
    remediation: 'Configure a least-privilege POSIX uid/gid (avoid 0) on every access point and use IAM to require access point usage.',
    tags: ['efs', 'access-point', 'identity'],
  },
];
