// Check logic derived from Prowler (Apache-2.0, https://github.com/prowler-cloud/prowler)
import { CheckMetadata } from '../../types';

export const eksChecks: CheckMetadata[] = [
  {
    checkId: 'eks_cluster_not_publicly_accessible',
    provider: 'aws',
    service: 'eks',
    title: 'EKS Cluster Endpoint Publicly Accessible',
    severity: 'HIGH',
    description: 'Checks that the EKS cluster API server endpoint is not open to the Internet from 0.0.0.0/0.',
    remediation: 'Prefer private endpoint access. If a public endpoint is required, restrict it to trusted admin CIDR ranges (not 0.0.0.0/0) and reach the API via VPN, Direct Connect or bastion hosts.',
    tags: ['eks', 'public-access', 'network'],
  },
  {
    checkId: 'eks_cluster_private_nodes_enabled',
    provider: 'aws',
    service: 'eks',
    title: 'EKS Private Endpoint Access Disabled',
    severity: 'HIGH',
    description: 'Checks that the EKS cluster has private endpoint access enabled so Kubernetes API traffic can use a VPC-resolved private endpoint.',
    remediation: 'Enable private endpoint access on the cluster and disable or tightly restrict the public endpoint; administer the cluster from private networks.',
    tags: ['eks', 'private-endpoint', 'network'],
  },
  {
    checkId: 'eks_cluster_network_policy_enabled',
    provider: 'aws',
    service: 'eks',
    title: 'EKS Cluster Security Group Missing',
    severity: 'HIGH',
    description: 'Checks that the EKS cluster has a cluster security group assigned, supporting pod-level network isolation via Kubernetes NetworkPolicy.',
    remediation: 'Ensure the cluster has a cluster security group and enforce least-privilege NetworkPolicy with default-deny ingress and egress, explicitly allowing only required flows.',
    tags: ['eks', 'network-policy', 'segmentation'],
  },
  {
    checkId: 'eks_cluster_uses_a_supported_version',
    provider: 'aws',
    service: 'eks',
    title: 'EKS Running Unsupported Kubernetes Version',
    severity: 'HIGH',
    description: 'Checks that the EKS cluster runs a supported Kubernetes version (1.28 or later); older versions no longer receive security patches.',
    remediation: 'Upgrade the cluster to a supported Kubernetes minor version, upgrading node groups and add-ons together with the control plane and testing workloads for API deprecations.',
    tags: ['eks', 'patching', 'kubernetes-version'],
  },
  {
    checkId: 'eks_cluster_deletion_protection_enabled',
    provider: 'aws',
    service: 'eks',
    title: 'EKS Deletion Protection Disabled',
    severity: 'HIGH',
    description: 'Checks that EKS clusters have deletion protection enabled, blocking cluster removal until protection is explicitly disabled.',
    remediation: 'Enable deletion protection (deletionProtection=true) on critical clusters and restrict delete/disable permissions to narrowly scoped roles under change control.',
    tags: ['eks', 'deletion-protection', 'resilience'],
  },
  {
    checkId: 'eks_control_plane_logging_all_types_enabled',
    provider: 'aws',
    service: 'eks',
    title: 'EKS Control Plane Logging Incomplete',
    severity: 'MEDIUM',
    description: 'Checks that all EKS control plane log types (api, audit, authenticator, controllerManager, scheduler) are enabled.',
    remediation: 'Enable all five control plane log types on the cluster, set log retention and alerts, and centralize analysis for detection and forensics.',
    tags: ['eks', 'logging', 'audit'],
  },
  {
    checkId: 'eks_cluster_kms_cmk_encryption_in_secrets_enabled',
    provider: 'aws',
    service: 'eks',
    title: 'EKS Secrets Not KMS Encrypted',
    severity: 'MEDIUM',
    description: 'Checks that the EKS cluster uses AWS KMS envelope encryption so Kubernetes Secrets are stored in etcd as ciphertext at rest.',
    remediation: 'Enable cluster-level secrets encryption with AWS KMS, preferring a customer-managed key, and apply least privilege to key policies and cluster RBAC.',
    tags: ['eks', 'encryption', 'kms', 'secrets'],
  },
];
