// Check logic derived from Prowler (Apache-2.0, https://github.com/prowler-cloud/prowler)
import { CheckMetadata } from '../../types';

// Titles must stay byte-identical to the pre-registry hardcoded titles:
// the scan worker dedupes OPEN findings on service:title:fingerprint, so a
// reworded title would re-open every existing finding as "new".
export const elbChecks: CheckMetadata[] = [
  {
    checkId: 'elbv2_logging_enabled',
    provider: 'aws',
    service: 'elb',
    title: 'Load Balancer Access Logging Disabled',
    severity: 'HIGH',
    description: 'Checks that load balancers have access logs enabled. Access logs are required for security analysis, compliance (PCI 10.2), and incident response.',
    remediation: 'Enable access logs on the load balancer: aws elbv2 modify-load-balancer-attributes --load-balancer-arn <lb-arn> --attributes Key=access_logs.s3.enabled,Value=true Key=access_logs.s3.bucket,Value=<your-log-bucket>',
    tags: ['elb', 'logging'],
  },
  {
    checkId: 'elbv2_deletion_protection',
    provider: 'aws',
    service: 'elb',
    title: 'Load Balancer Deletion Protection Disabled',
    severity: 'MEDIUM',
    description: 'Checks that load balancers have deletion protection enabled to prevent accidental or malicious deletion of a production load balancer.',
    remediation: 'Enable deletion protection: aws elbv2 modify-load-balancer-attributes --load-balancer-arn <lb-arn> --attributes Key=deletion_protection.enabled,Value=true',
    tags: ['elb', 'availability'],
  },
  {
    checkId: 'elbv2_ssl_listeners',
    provider: 'aws',
    service: 'elb',
    title: 'Load Balancer HTTP Listener Without HTTPS Redirect',
    severity: 'HIGH',
    description: 'Checks that HTTP listeners on internet-facing load balancers redirect traffic to HTTPS so data in transit is encrypted.',
    remediation: 'Add a redirect action to the HTTP listener: aws elbv2 modify-listener --listener-arn <listener-arn> --default-actions Type=redirect,RedirectConfig=\'{Protocol=HTTPS,Port=443,StatusCode=HTTP_301}\'',
    tags: ['elb', 'encryption', 'https'],
  },
  {
    checkId: 'elbv2_insecure_ssl_ciphers',
    provider: 'aws',
    service: 'elb',
    title: 'Load Balancer Uses Weak TLS Policy',
    severity: 'HIGH',
    description: 'Checks that HTTPS listeners do not use SSL policies that support weak ciphers or TLS versions below 1.2.',
    remediation: 'Update to a modern TLS policy: aws elbv2 modify-listener --listener-arn <listener-arn> --ssl-policy ELBSecurityPolicy-TLS13-1-2-2021-06',
    tags: ['elb', 'tls', 'encryption'],
  },
  {
    checkId: 'elb_target_group_insecure_backend_protocol',
    provider: 'aws',
    service: 'elb',
    title: 'Target Group Uses Unencrypted Backend Protocol',
    severity: 'MEDIUM',
    description: 'Checks that target groups do not forward traffic to backends using unencrypted HTTP or TCP; such traffic between the load balancer and the targets is unencrypted even if the listener uses TLS.',
    remediation: 'Switch the target group to HTTPS (or TLS) and configure the targets to terminate TLS, then update via: aws elbv2 modify-target-group --target-group-arn <target-group-arn> --protocol HTTPS',
    tags: ['elb', 'encryption', 'backend-tls'],
  },
  {
    checkId: 'elb_connection_draining_enabled',
    provider: 'aws',
    service: 'elb',
    title: 'Classic Load Balancer Connection Draining Disabled',
    severity: 'MEDIUM',
    description: 'Checks that Classic Load Balancers have connection draining enabled so deregistering or unhealthy instances finish in-flight requests before being removed from service.',
    remediation: 'Enable connection draining: aws elb modify-load-balancer-attributes --load-balancer-name <lb-name> --load-balancer-attributes \'{"ConnectionDraining":{"Enabled":true}}\'',
    tags: ['elb', 'classic', 'availability'],
  },
  {
    checkId: 'elb_cross_zone_load_balancing_enabled',
    provider: 'aws',
    service: 'elb',
    title: 'Classic Load Balancer Cross-Zone Load Balancing Disabled',
    severity: 'MEDIUM',
    description: 'Checks that Classic Load Balancers have cross-zone load balancing enabled so traffic is distributed across registered instances in all enabled availability zones instead of concentrating in one zone.',
    remediation: 'Enable cross-zone load balancing: aws elb modify-load-balancer-attributes --load-balancer-name <lb-name> --load-balancer-attributes \'{"CrossZoneLoadBalancing":{"Enabled":true}}\'',
    tags: ['elb', 'classic', 'availability'],
  },
  {
    checkId: 'elb_desync_mitigation_mode',
    provider: 'aws',
    service: 'elb',
    title: 'Classic Load Balancer Desync Mitigation Mode Not Strict',
    severity: 'MEDIUM',
    description: 'Checks that Classic Load Balancers have the desync mitigation mode set to defensive or strictest to protect against HTTP request smuggling attacks.',
    remediation: 'Set a strict desync mitigation mode: aws elb modify-load-balancer-attributes --load-balancer-name <lb-name> --load-balancer-attributes \'{"AdditionalAttributes":[{"Key":"elb.http.desyncmitigationmode","Value":"defensive"}]}\'',
    tags: ['elb', 'classic', 'desync'],
  },
  {
    checkId: 'elb_insecure_ssl_ciphers',
    provider: 'aws',
    service: 'elb',
    title: 'Classic Load Balancer Uses Insecure SSL Ciphers',
    severity: 'MEDIUM',
    description: 'Checks that Classic Load Balancer HTTPS listeners use the ELBSecurityPolicy-TLS-1-2-2017-01 security policy so legacy TLS versions and weak cipher suites cannot be negotiated.',
    remediation: 'Apply the TLS 1.2-only policy to the HTTPS listener: aws elb set-load-balancer-policies-of-listener --load-balancer-name <lb-name> --load-balancer-port <port> --policy-names ELBSecurityPolicy-TLS-1-2-2017-01',
    tags: ['elb', 'classic', 'tls', 'encryption'],
  },
  {
    checkId: 'elb_internet_facing',
    provider: 'aws',
    service: 'elb',
    title: 'Classic Load Balancer Is Internet-Facing',
    severity: 'MEDIUM',
    description: 'Checks that Classic Load Balancers are not internet-facing; a public scheme exposes the backends to the internet through a public DNS name.',
    remediation: 'If public access is not required, recreate the load balancer with an internal scheme. Otherwise restrict its security groups to trusted CIDRs and enforce TLS on all listeners.',
    tags: ['elb', 'classic', 'network-exposure'],
  },
  {
    checkId: 'elb_is_in_multiple_az',
    provider: 'aws',
    service: 'elb',
    title: 'Classic Load Balancer Not in Multiple Availability Zones',
    severity: 'MEDIUM',
    description: 'Checks that Classic Load Balancers are enabled in at least two availability zones so a zone outage does not take the load balancer offline.',
    remediation: 'Attach a subnet in a second availability zone: aws elb attach-load-balancer-to-subnets --load-balancer-name <lb-name> --subnets <subnet-in-another-az>',
    tags: ['elb', 'classic', 'availability'],
  },
  {
    checkId: 'elb_logging_enabled',
    provider: 'aws',
    service: 'elb',
    title: 'Classic Load Balancer Access Logging Disabled',
    severity: 'MEDIUM',
    description: 'Checks that Classic Load Balancers have access logs delivered to S3; without them edge traffic is invisible to security analysis, forensics and incident response.',
    remediation: 'Enable access logs: aws elb modify-load-balancer-attributes --load-balancer-name <lb-name> --load-balancer-attributes AccessLog={Enabled=true,S3BucketName=<your-log-bucket>}',
    tags: ['elb', 'classic', 'logging'],
  },
  {
    checkId: 'elb_ssl_listeners',
    provider: 'aws',
    service: 'elb',
    title: 'Classic Load Balancer Has Unencrypted Listeners',
    severity: 'MEDIUM',
    description: 'Checks that Classic Load Balancers only use HTTPS or SSL listeners; HTTP or TCP listeners carry client traffic in plaintext.',
    remediation: 'Replace plaintext listeners with HTTPS/SSL listeners backed by an ACM certificate, then remove the old ones: aws elb delete-load-balancer-listeners --load-balancer-name <lb-name> --load-balancer-ports <port>',
    tags: ['elb', 'classic', 'encryption'],
  },
  {
    checkId: 'elb_ssl_listeners_use_acm_certificate',
    provider: 'aws',
    service: 'elb',
    title: 'Classic Load Balancer Certificate Not ACM-Issued',
    severity: 'MEDIUM',
    description: 'Checks that Classic Load Balancer HTTPS/SSL listeners use Amazon-issued ACM certificates so validation, rotation and renewal are managed by AWS.',
    remediation: 'Attach an Amazon-issued ACM certificate to the listener: aws elb set-load-balancer-listener-ssl-certificate --load-balancer-name <lb-name> --load-balancer-port <port> --ssl-certificate-id <acm-certificate-arn>',
    tags: ['elb', 'classic', 'encryption', 'acm'],
  },
  {
    checkId: 'elbv2_alb_drop_invalid_header_fields_enabled',
    provider: 'aws',
    service: 'elb',
    title: 'ALB Not Dropping Invalid HTTP Header Fields',
    severity: 'MEDIUM',
    description: 'Checks that Application Load Balancers are configured to drop invalid HTTP header fields; forwarding non-RFC-compliant headers to targets enables HTTP desync (request smuggling) attacks.',
    remediation: 'Enable dropping of invalid header fields: aws elbv2 modify-load-balancer-attributes --load-balancer-arn <lb-arn> --attributes Key=routing.http.drop_invalid_header_fields.enabled,Value=true',
    tags: ['elb', 'desync'],
  },
  {
    checkId: 'elbv2_cross_zone_load_balancing_enabled',
    provider: 'aws',
    service: 'elb',
    title: 'Load Balancer Cross-Zone Load Balancing Disabled',
    severity: 'MEDIUM',
    description: 'Checks that Network and Gateway Load Balancers have cross-zone load balancing enabled so each node distributes traffic to targets in all enabled availability zones.',
    remediation: 'Enable cross-zone load balancing: aws elbv2 modify-load-balancer-attributes --load-balancer-arn <lb-arn> --attributes Key=load_balancing.cross_zone.enabled,Value=true',
    tags: ['elb', 'availability'],
  },
  {
    checkId: 'elbv2_desync_mitigation_mode',
    provider: 'aws',
    service: 'elb',
    title: 'ALB Desync Mitigation Mode Not Strict',
    severity: 'MEDIUM',
    description: 'Checks that Application Load Balancers have the desync mitigation mode set to defensive or strictest, or at least drop invalid header fields, to protect against HTTP request smuggling.',
    remediation: 'Set a strict desync mitigation mode: aws elbv2 modify-load-balancer-attributes --load-balancer-arn <lb-arn> --attributes Key=routing.http.desync_mitigation_mode,Value=strictest',
    tags: ['elb', 'desync'],
  },
  {
    checkId: 'elbv2_internet_facing',
    provider: 'aws',
    service: 'elb',
    title: 'Internet-Facing Load Balancer Open to the World',
    severity: 'MEDIUM',
    description: 'Checks that internet-facing load balancers do not have security groups allowing inbound TCP from 0.0.0.0/0 or ::/0, which makes them reachable from anywhere on the internet.',
    remediation: 'Restrict the security group inbound rules to trusted CIDRs or upstream services, or recreate the load balancer with an internal scheme if public access is not required.',
    tags: ['elb', 'network-exposure'],
  },
  {
    checkId: 'elbv2_is_in_multiple_az',
    provider: 'aws',
    service: 'elb',
    title: 'Load Balancer Not in Multiple Availability Zones',
    severity: 'MEDIUM',
    description: 'Checks that Application, Network and Gateway Load Balancers are enabled in at least two availability zones so a zone outage does not take the load balancer offline.',
    remediation: 'Add a subnet in a second availability zone: aws elbv2 set-subnets --load-balancer-arn <lb-arn> --subnets <subnet-in-az-a> <subnet-in-az-b>',
    tags: ['elb', 'availability'],
  },
  {
    checkId: 'elbv2_listener_pqc_tls_enabled',
    provider: 'aws',
    service: 'elb',
    title: 'Load Balancer Listener Without Post-Quantum TLS Policy',
    severity: 'LOW',
    description: 'Checks that HTTPS/TLS listeners use a post-quantum TLS security policy (hybrid ML-KEM + ECDHE key exchange) to reduce harvest-now-decrypt-later exposure of recorded traffic.',
    remediation: 'Switch the listener to a post-quantum TLS policy: aws elbv2 modify-listener --listener-arn <listener-arn> --ssl-policy ELBSecurityPolicy-TLS13-1-2-PQ-2025-09',
    tags: ['elb', 'tls', 'encryption'],
  },
  {
    checkId: 'elbv2_listeners_underneath',
    provider: 'aws',
    service: 'elb',
    title: 'Load Balancer Has No Listeners',
    severity: 'MEDIUM',
    description: 'Checks that every load balancer has at least one listener; without one it cannot accept connections and services behind its DNS endpoint are unreachable.',
    remediation: 'Add a listener (prefer HTTPS on 443): aws elbv2 create-listener --load-balancer-arn <lb-arn> --protocol HTTPS --port 443 --certificates CertificateArn=<acm-cert-arn> --default-actions Type=forward,TargetGroupArn=<target-group-arn>',
    tags: ['elb', 'availability'],
  },
  {
    checkId: 'elbv2_nlb_tls_termination_enabled',
    provider: 'aws',
    service: 'elb',
    title: 'NLB TLS Termination Not Enabled',
    severity: 'MEDIUM',
    description: 'Checks that Network Load Balancers have at least one TLS listener so client encryption is terminated centrally with consistent cipher policies instead of being left to backend targets.',
    remediation: 'Add a TLS listener: aws elbv2 create-listener --load-balancer-arn <lb-arn> --protocol TLS --port 443 --ssl-policy ELBSecurityPolicy-TLS13-1-2-2021-06 --certificates CertificateArn=<acm-cert-arn> --default-actions Type=forward,TargetGroupArn=<target-group-arn>',
    tags: ['elb', 'tls', 'encryption'],
  },
  {
    checkId: 'elbv2_waf_acl_attached',
    provider: 'aws',
    service: 'elb',
    title: 'ALB Without WAF Web ACL',
    severity: 'MEDIUM',
    description: 'Checks that Application Load Balancers have an AWS WAF web ACL attached so Layer 7 traffic is filtered before reaching the targets.',
    remediation: 'Associate a WAFv2 web ACL with the load balancer: aws wafv2 associate-web-acl --web-acl-arn <web-acl-arn> --resource-arn <lb-arn>',
    tags: ['elb', 'waf'],
  },
];
