// Check logic derived from Prowler (Apache-2.0, https://github.com/prowler-cloud/prowler)
import { CheckMetadata } from '../../types';

export const glueChecks: CheckMetadata[] = [
  {
    checkId: 'glue_etl_jobs_no_secrets_in_arguments',
    provider: 'aws',
    service: 'glue',
    title: 'Glue Job Has Secrets In Arguments',
    severity: 'CRITICAL',
    description: 'Checks Glue ETL job default arguments for values that resemble secrets (keys, tokens, passwords) stored inline instead of being sourced from Secrets Manager or Parameter Store.',
    remediation: 'Store secrets in AWS Secrets Manager or SSM Parameter Store and reference them by name or ARN in job arguments; rotate any exposed credentials and avoid logging argument values.',
    tags: ['glue', 'secrets', 'credentials'],
  },
  {
    checkId: 'glue_data_catalogs_not_publicly_accessible',
    provider: 'aws',
    service: 'glue',
    title: 'Glue Data Catalog Publicly Accessible',
    severity: 'HIGH',
    description: 'Checks the Glue Data Catalog resource policy for configurations such as a wildcard principal without restrictive conditions that expose the catalog publicly.',
    remediation: 'Remove wildcard principals from the catalog resource policy, grant only required actions to explicit principals, and limit scope with precise ARNs and conditions.',
    tags: ['glue', 'public-access', 'resource-policy'],
  },
  {
    checkId: 'glue_database_connections_ssl_enabled',
    provider: 'aws',
    service: 'glue',
    title: 'Glue Connection SSL Not Enforced',
    severity: 'HIGH',
    description: 'Checks that Glue connections enforce TLS/SSL for JDBC traffic to external data stores via the JDBC_ENFORCE_SSL property.',
    remediation: 'Set JDBC_ENFORCE_SSL to true on Glue connections, require encryption on target databases, validate certificates, and prefer private connectivity.',
    tags: ['glue', 'encryption-in-transit', 'ssl'],
  },
  {
    checkId: 'glue_etl_jobs_amazon_s3_encryption_enabled',
    provider: 'aws',
    service: 'glue',
    title: 'Glue Job S3 Encryption Disabled',
    severity: 'HIGH',
    description: 'Checks that Glue ETL jobs encrypt S3 outputs at rest (SSE-S3 or SSE-KMS) through an attached security configuration or job arguments.',
    remediation: 'Attach a Glue security configuration with S3 encryption enabled (prefer SSE-KMS with customer-managed keys) and enforce encrypted writes with bucket policies.',
    tags: ['glue', 'encryption', 's3'],
  },
  {
    checkId: 'glue_data_catalogs_connection_passwords_encryption_enabled',
    provider: 'aws',
    service: 'glue',
    title: 'Glue Connection Passwords Not Encrypted',
    severity: 'HIGH',
    description: 'Checks that the Glue Data Catalog encrypts connection passwords stored in connection properties with a KMS key.',
    remediation: 'Enable connection password encryption in the Data Catalog settings with a customer-managed KMS key and apply least privilege to the key and Glue roles.',
    tags: ['glue', 'encryption', 'credentials', 'kms'],
  },
  {
    checkId: 'glue_data_catalogs_metadata_encryption_enabled',
    provider: 'aws',
    service: 'glue',
    title: 'Glue Catalog Metadata Not Encrypted',
    severity: 'MEDIUM',
    description: 'Checks that Glue Data Catalog metadata is encrypted at rest with SSE-KMS in the catalog encryption settings.',
    remediation: 'Enable metadata encryption with SSE-KMS in the Data Catalog settings, preferably with a customer-managed KMS key, and restrict who can change the settings.',
    tags: ['glue', 'encryption', 'kms'],
  },
  {
    checkId: 'glue_etl_jobs_cloudwatch_logs_encryption_enabled',
    provider: 'aws',
    service: 'glue',
    title: 'Glue Job CloudWatch Logs Not Encrypted',
    severity: 'MEDIUM',
    description: 'Checks that Glue ETL jobs use a security configuration with CloudWatch Logs encryption (SSE-KMS) enabled.',
    remediation: 'Attach a security configuration with CloudWatch Logs encryption using a customer-managed KMS key and require all jobs to use an approved configuration.',
    tags: ['glue', 'encryption', 'logging', 'kms'],
  },
  {
    checkId: 'glue_etl_jobs_job_bookmark_encryption_enabled',
    provider: 'aws',
    service: 'glue',
    title: 'Glue Job Bookmark Encryption Disabled',
    severity: 'MEDIUM',
    description: 'Checks that Glue ETL jobs use a security configuration with job bookmark encryption (e.g. CSE-KMS) enabled to protect bookmark state.',
    remediation: 'Attach a security configuration to every job with job bookmark encryption enabled using customer-managed KMS keys, alongside S3 and CloudWatch Logs encryption.',
    tags: ['glue', 'encryption', 'kms'],
  },
  {
    checkId: 'glue_etl_jobs_logging_enabled',
    provider: 'aws',
    service: 'glue',
    title: 'Glue Job Continuous Logging Disabled',
    severity: 'MEDIUM',
    description: 'Checks that Glue ETL jobs send runtime events to CloudWatch Logs via the --enable-continuous-cloudwatch-log job argument.',
    remediation: 'Enable continuous CloudWatch logging on all Glue jobs, centralize logs with retention and KMS encryption, and alert on anomalies and failures.',
    tags: ['glue', 'logging', 'audit'],
  },
  {
    checkId: 'glue_ml_transform_encrypted_at_rest',
    provider: 'aws',
    service: 'glue',
    title: 'Glue ML Transform Not Encrypted',
    severity: 'MEDIUM',
    description: 'Checks that Glue ML transforms encrypt user data at rest with a KMS key.',
    remediation: 'Enable KMS-backed encryption at rest for ML transforms, prefer customer-managed keys, and apply least-privilege key policies with rotation.',
    tags: ['glue', 'encryption', 'kms', 'ml'],
  },
  {
    checkId: 'glue_catalog_connection_no_secrets',
    provider: 'aws',
    service: 'glue',
    title: 'Glue Connection Has Secrets In Properties',
    severity: 'HIGH',
    description: 'Checks Glue Data Catalog connection properties for values that resemble secrets (passwords, keys, tokens) stored inline instead of being sourced from Secrets Manager or Parameter Store.',
    remediation: 'Store credentials in AWS Secrets Manager or SSM Parameter Store and reference them (e.g. via SECRET_ID) in connection properties; rotate any exposed credentials.',
    tags: ['glue', 'secrets', 'credentials'],
  },
  {
    checkId: 'glue_development_endpoints_s3_encryption_enabled',
    provider: 'aws',
    service: 'glue',
    title: 'Glue Dev Endpoint S3 Encryption Disabled',
    severity: 'MEDIUM',
    description: 'Checks that Glue development endpoints use a security configuration with S3 encryption enabled so ETL outputs, temp data and scripts are encrypted at rest.',
    remediation: 'Create a Glue security configuration with S3 encryption enabled (prefer SSE-KMS with a customer-managed key) and recreate the development endpoint with that configuration attached.',
    tags: ['glue', 'encryption', 's3', 'dev-endpoint'],
  },
  {
    checkId: 'glue_development_endpoints_cloudwatch_logs_encryption_enabled',
    provider: 'aws',
    service: 'glue',
    title: 'Glue Dev Endpoint CloudWatch Logs Not Encrypted',
    severity: 'MEDIUM',
    description: 'Checks that Glue development endpoints use a security configuration with CloudWatch Logs encryption (SSE-KMS) enabled.',
    remediation: 'Create a Glue security configuration with CloudWatch Logs encryption using a customer-managed KMS key and recreate the development endpoint with that configuration attached.',
    tags: ['glue', 'encryption', 'logging', 'kms', 'dev-endpoint'],
  },
  {
    checkId: 'glue_development_endpoints_job_bookmark_encryption_enabled',
    provider: 'aws',
    service: 'glue',
    title: 'Glue Dev Endpoint Bookmark Encryption Disabled',
    severity: 'MEDIUM',
    description: 'Checks that Glue development endpoints use a security configuration with job bookmark encryption (e.g. CSE-KMS) enabled to protect bookmark state stored in S3.',
    remediation: 'Create a Glue security configuration with job bookmark encryption enabled using a customer-managed KMS key and recreate the development endpoint with that configuration attached.',
    tags: ['glue', 'encryption', 'kms', 'dev-endpoint'],
  },
];
