import { CheckMetadata } from '../../types';

// Titles must stay byte-identical to the pre-registry hardcoded titles:
// the scan worker dedupes OPEN findings on service:title:fingerprint, so a
// reworded title would re-open every existing finding as "new".
export const iamChecks: CheckMetadata[] = [
  {
    checkId: 'iam_user_mfa_enabled_console_access',
    provider: 'aws',
    service: 'iam',
    title: 'MFA Not Verified for User',
    severity: 'HIGH',
    description: 'Checks that IAM users with console access have at least one MFA device configured.',
    remediation: 'Enable MFA for the user using an authenticator app or hardware token.',
    tags: ['iam', 'mfa', 'multi-factor-auth', 'cis-1.10'],
    compliance: {
      cis_2_0_aws: ['1.10'],
    },
  },
  {
    checkId: 'iam_rotate_access_key_90_days',
    provider: 'aws',
    service: 'iam',
    title: 'Old Access Key',
    severity: 'MEDIUM',
    description: 'Checks that IAM user access keys are rotated at least every 90 days.',
    remediation: 'Rotate access keys that are older than 90 days.',
    tags: ['iam', 'access-keys', 'rotation'],
  },
  {
    checkId: 'iam_user_accesskey_never_used',
    provider: 'aws',
    service: 'iam',
    title: 'Unused Access Key',
    severity: 'LOW',
    description: 'Checks for IAM user access keys that have never been used.',
    remediation: 'Delete access keys that have never been used.',
    tags: ['iam', 'access-keys', 'cleanup'],
  },
  {
    checkId: 'iam_user_accesskey_unused',
    provider: 'aws',
    service: 'iam',
    title: 'Inactive Access Key',
    severity: 'LOW',
    description: 'Checks for IAM user access keys that have not been used for more than 90 days.',
    remediation: 'Delete or review access keys that have been inactive for more than 90 days.',
    tags: ['iam', 'access-keys', 'inactive'],
  },
  {
    checkId: 'iam_user_multiple_access_keys',
    provider: 'aws',
    service: 'iam',
    title: 'Multiple Access Keys',
    severity: 'MEDIUM',
    description: 'Checks that IAM users do not have more access keys than necessary (maximum 2).',
    remediation: 'Review and delete unnecessary access keys for the user.',
    tags: ['iam', 'access-keys', 'best-practices'],
  },
  {
    checkId: 'iam_user_console_access_mfa_unverified',
    provider: 'aws',
    service: 'iam',
    title: 'Console Access Without MFA',
    severity: 'HIGH',
    description: 'Checks IAM users with console access whose MFA status could not be verified.',
    remediation: 'Verify MFA is enabled for the user or disable console access.',
    tags: ['iam', 'console', 'mfa'],
  },
  {
    checkId: 'iam_user_never_logged_in',
    provider: 'aws',
    service: 'iam',
    title: 'User Never Logged In',
    severity: 'LOW',
    description: 'Checks for IAM users that have never logged in with their password.',
    remediation: 'Delete the user if no longer needed, or investigate setup.',
    tags: ['iam', 'user-management', 'cleanup'],
  },
  {
    checkId: 'iam_user_console_access_unused',
    provider: 'aws',
    service: 'iam',
    title: 'Inactive User',
    severity: 'LOW',
    description: 'Checks for IAM users that have not logged in for more than 90 days.',
    remediation: 'Review and remove inactive users that are no longer needed.',
    tags: ['iam', 'user-management', 'inactive'],
  },
  {
    checkId: 'iam_user_overly_permissive_policy',
    provider: 'aws',
    service: 'iam',
    title: 'Overly Permissive Policy',
    severity: 'HIGH',
    description: 'Checks for IAM users with attached policies (such as PowerUser or Admin policies) that may grant excessive permissions.',
    remediation: 'Review and replace overly permissive policies with least-privilege policies.',
    tags: ['iam', 'permissions', 'least-privilege'],
  },
  {
    checkId: 'iam_user_no_policies_attached',
    provider: 'aws',
    service: 'iam',
    title: 'No Policies Attached',
    severity: 'INFO',
    description: 'Checks for IAM users with no attached policies, which cannot perform any actions.',
    remediation: 'Attach appropriate policies to the user based on job requirements.',
    tags: ['iam', 'permissions', 'setup'],
  },
  {
    checkId: 'iam_no_root_access_key',
    provider: 'aws',
    service: 'iam',
    title: 'Root Access Key Exists',
    severity: 'CRITICAL',
    description: 'Checks that the root account has no active access keys.',
    remediation: 'Delete all root account access keys immediately. Use IAM users or roles for programmatic access.',
    tags: ['iam', 'root', 'access-keys', 'cis-1.4'],
    compliance: {
      cis_2_0_aws: ['1.4'],
    },
  },
  {
    checkId: 'iam_root_mfa_enabled',
    provider: 'aws',
    service: 'iam',
    title: 'Root Account MFA Not Enabled',
    severity: 'CRITICAL',
    description: 'Checks that multi-factor authentication (MFA) is enabled for the root account.',
    remediation: 'Enable MFA for the root account immediately using a hardware or virtual MFA device.',
    tags: ['iam', 'root', 'mfa', 'cis-1.5'],
    compliance: {
      cis_2_0_aws: ['1.5'],
    },
  },
  {
    checkId: 'iam_root_account_security_unverified',
    provider: 'aws',
    service: 'iam',
    title: 'Root Account Security',
    severity: 'CRITICAL',
    description: 'Emitted when root account security cannot be programmatically verified via the credential report; manual verification is required.',
    remediation: 'Review root account security at: https://console.aws.amazon.com/iam/home#/security_credentials',
    tags: ['iam', 'root', 'critical'],
  },
  {
    checkId: 'iam_password_policy_minimum_length_14',
    provider: 'aws',
    service: 'iam',
    title: 'Password Policy Minimum Length',
    severity: 'MEDIUM',
    description: 'Checks that the IAM account password policy requires a minimum length of at least 14 characters.',
    remediation: 'Update the IAM account password policy to require a minimum of 14 characters.',
    tags: ['iam', 'password-policy', 'cis-1.8'],
    compliance: {
      cis_2_0_aws: ['1.8'],
    },
  },
  {
    checkId: 'iam_password_policy_reuse_24',
    provider: 'aws',
    service: 'iam',
    title: 'Password Policy Reuse Prevention',
    severity: 'MEDIUM',
    description: 'Checks that the IAM account password policy prevents reuse of the last 24 passwords.',
    remediation: 'Update the IAM account password policy to prevent reuse of the last 24 passwords.',
    tags: ['iam', 'password-policy', 'cis-1.9'],
    compliance: {
      cis_2_0_aws: ['1.9'],
    },
  },
  {
    checkId: 'iam_password_policy_not_configured',
    provider: 'aws',
    service: 'iam',
    title: 'Password Policy Review Required',
    severity: 'HIGH',
    description: 'Checks that an IAM account password policy is configured and can be retrieved.',
    remediation: 'Create an IAM password policy enforcing minimum length of 14, complexity, and reuse prevention of 24.',
    tags: ['iam', 'password-policy', 'cis-1.8', 'cis-1.9'],
    compliance: {
      cis_2_0_aws: ['1.8', '1.9'],
    },
  },
  {
    checkId: 'accessanalyzer_enabled',
    provider: 'aws',
    service: 'iam',
    title: 'IAM Access Analyzer Not Enabled',
    severity: 'MEDIUM',
    description: 'Checks that IAM Access Analyzer is enabled for the account to identify resources shared with external entities.',
    remediation: 'Enable IAM Access Analyzer in the IAM console or via CLI: aws accessanalyzer create-analyzer --analyzer-name MyAnalyzer --type ACCOUNT',
    tags: ['iam', 'access-analyzer', 'cis-1.20'],
    compliance: {
      cis_2_0_aws: ['1.20'],
    },
  },
  {
    checkId: 'iam_support_role_created',
    provider: 'aws',
    service: 'iam',
    title: 'IAM Support Role Not Configured',
    severity: 'LOW',
    description: 'Checks that an IAM role with the AWSSupportAccess managed policy exists to manage AWS support cases.',
    remediation: 'Create an IAM role with the AWSSupportAccess managed policy and assign it to authorized users.',
    tags: ['iam', 'support-role', 'cis-1.17'],
    compliance: {
      cis_2_0_aws: ['1.17'],
    },
  },
  {
    checkId: 'iam_virtual_mfa_device_unassigned',
    provider: 'aws',
    service: 'iam',
    title: 'Orphaned Virtual MFA Device',
    severity: 'LOW',
    description: 'Checks for virtual MFA devices that are not assigned to any IAM user.',
    remediation: 'Delete unassigned virtual MFA devices to reduce clutter and prevent reuse.',
    tags: ['iam', 'mfa', 'cleanup'],
  },
  {
    checkId: 'iam_role_has_inline_policies',
    provider: 'aws',
    service: 'iam',
    title: 'IAM Role Has Inline Policies',
    severity: 'LOW',
    description: 'Checks for IAM roles with inline policies, which are harder to audit and reuse than managed policies.',
    remediation: 'Convert inline policies on roles to managed policies for better auditability and reuse.',
    tags: ['iam', 'roles', 'inline-policy', 'best-practices'],
  },
  {
    checkId: 'iam_customer_attached_policy_no_administrative_privileges',
    provider: 'aws',
    service: 'iam',
    title: 'Customer Managed Policy Allows Full Admin (*:*)',
    severity: 'CRITICAL',
    description: 'Checks for attached customer-managed policies that grant Allow on Action="*" and Resource="*".',
    remediation: 'Replace full-admin policies with least-privilege policies scoped to required actions and resources.',
    tags: ['iam', 'policies', 'wildcard', 'least-privilege', 'cis-1.16'],
    compliance: {
      cis_2_0_aws: ['1.16'],
    },
  },
];
