import { CheckMetadata } from '../../types';

// Titles must stay byte-identical to the pre-registry hardcoded titles:
// the scan worker dedupes OPEN findings on service:title:fingerprint, so a
// reworded title would re-open every existing finding as "new".
export const iamChecks: CheckMetadata[] = [
  {
    checkId: 'iam_user_mfa_enabled_console_access',
    provider: 'aws',
    service: 'iam',
    title: 'MFA Not Verified for User',
    severity: 'HIGH',
    description: 'Checks that IAM users with console access have at least one MFA device configured.',
    remediation: 'Enable MFA for the user using an authenticator app or hardware token.',
    tags: ['iam', 'mfa', 'multi-factor-auth', 'cis-1.10'],
    compliance: {
      cis_2_0_aws: ['1.10'],
    },
  },
  {
    checkId: 'iam_rotate_access_key_90_days',
    provider: 'aws',
    service: 'iam',
    title: 'Old Access Key',
    severity: 'MEDIUM',
    description: 'Checks that IAM user access keys are rotated at least every 90 days.',
    remediation: 'Rotate access keys that are older than 90 days.',
    tags: ['iam', 'access-keys', 'rotation'],
  },
  {
    checkId: 'iam_user_accesskey_never_used',
    provider: 'aws',
    service: 'iam',
    title: 'Unused Access Key',
    severity: 'LOW',
    description: 'Checks for IAM user access keys that have never been used.',
    remediation: 'Delete access keys that have never been used.',
    tags: ['iam', 'access-keys', 'cleanup'],
  },
  {
    checkId: 'iam_user_accesskey_unused',
    provider: 'aws',
    service: 'iam',
    title: 'Inactive Access Key',
    severity: 'LOW',
    description: 'Checks for IAM user access keys that have not been used for more than 90 days.',
    remediation: 'Delete or review access keys that have been inactive for more than 90 days.',
    tags: ['iam', 'access-keys', 'inactive'],
  },
  {
    checkId: 'iam_user_multiple_access_keys',
    provider: 'aws',
    service: 'iam',
    title: 'Multiple Access Keys',
    severity: 'MEDIUM',
    description: 'Checks that IAM users do not have more access keys than necessary (maximum 2).',
    remediation: 'Review and delete unnecessary access keys for the user.',
    tags: ['iam', 'access-keys', 'best-practices'],
  },
  {
    checkId: 'iam_user_console_access_mfa_unverified',
    provider: 'aws',
    service: 'iam',
    title: 'Console Access Without MFA',
    severity: 'HIGH',
    description: 'Checks IAM users with console access whose MFA status could not be verified.',
    remediation: 'Verify MFA is enabled for the user or disable console access.',
    tags: ['iam', 'console', 'mfa'],
  },
  {
    checkId: 'iam_user_never_logged_in',
    provider: 'aws',
    service: 'iam',
    title: 'User Never Logged In',
    severity: 'LOW',
    description: 'Checks for IAM users that have never logged in with their password.',
    remediation: 'Delete the user if no longer needed, or investigate setup.',
    tags: ['iam', 'user-management', 'cleanup'],
  },
  {
    checkId: 'iam_user_console_access_unused',
    provider: 'aws',
    service: 'iam',
    title: 'Inactive User',
    severity: 'LOW',
    description: 'Checks for IAM users that have not logged in for more than 90 days.',
    remediation: 'Review and remove inactive users that are no longer needed.',
    tags: ['iam', 'user-management', 'inactive'],
  },
  {
    checkId: 'iam_user_overly_permissive_policy',
    provider: 'aws',
    service: 'iam',
    title: 'Overly Permissive Policy',
    severity: 'HIGH',
    description: 'Checks for IAM users with attached policies (such as PowerUser or Admin policies) that may grant excessive permissions.',
    remediation: 'Review and replace overly permissive policies with least-privilege policies.',
    tags: ['iam', 'permissions', 'least-privilege'],
  },
  {
    checkId: 'iam_user_no_policies_attached',
    provider: 'aws',
    service: 'iam',
    title: 'No Policies Attached',
    severity: 'INFO',
    description: 'Checks for IAM users with no attached policies, which cannot perform any actions.',
    remediation: 'Attach appropriate policies to the user based on job requirements.',
    tags: ['iam', 'permissions', 'setup'],
  },
  {
    checkId: 'iam_no_root_access_key',
    provider: 'aws',
    service: 'iam',
    title: 'Root Access Key Exists',
    severity: 'CRITICAL',
    description: 'Checks that the root account has no active access keys.',
    remediation: 'Delete all root account access keys immediately. Use IAM users or roles for programmatic access.',
    tags: ['iam', 'root', 'access-keys', 'cis-1.4'],
    compliance: {
      cis_2_0_aws: ['1.4'],
    },
  },
  {
    checkId: 'iam_root_mfa_enabled',
    provider: 'aws',
    service: 'iam',
    title: 'Root Account MFA Not Enabled',
    severity: 'CRITICAL',
    description: 'Checks that multi-factor authentication (MFA) is enabled for the root account.',
    remediation: 'Enable MFA for the root account immediately using a hardware or virtual MFA device.',
    tags: ['iam', 'root', 'mfa', 'cis-1.5'],
    compliance: {
      cis_2_0_aws: ['1.5'],
    },
  },
  {
    checkId: 'iam_root_account_security_unverified',
    provider: 'aws',
    service: 'iam',
    title: 'Root Account Security',
    severity: 'CRITICAL',
    description: 'Emitted when root account security cannot be programmatically verified via the credential report; manual verification is required.',
    remediation: 'Review root account security at: https://console.aws.amazon.com/iam/home#/security_credentials',
    tags: ['iam', 'root', 'critical'],
  },
  {
    checkId: 'iam_password_policy_minimum_length_14',
    provider: 'aws',
    service: 'iam',
    title: 'Password Policy Minimum Length',
    severity: 'MEDIUM',
    description: 'Checks that the IAM account password policy requires a minimum length of at least 14 characters.',
    remediation: 'Update the IAM account password policy to require a minimum of 14 characters.',
    tags: ['iam', 'password-policy', 'cis-1.8'],
    compliance: {
      cis_2_0_aws: ['1.8'],
    },
  },
  {
    checkId: 'iam_password_policy_reuse_24',
    provider: 'aws',
    service: 'iam',
    title: 'Password Policy Reuse Prevention',
    severity: 'MEDIUM',
    description: 'Checks that the IAM account password policy prevents reuse of the last 24 passwords.',
    remediation: 'Update the IAM account password policy to prevent reuse of the last 24 passwords.',
    tags: ['iam', 'password-policy', 'cis-1.9'],
    compliance: {
      cis_2_0_aws: ['1.9'],
    },
  },
  {
    checkId: 'iam_password_policy_not_configured',
    provider: 'aws',
    service: 'iam',
    title: 'Password Policy Review Required',
    severity: 'HIGH',
    description: 'Checks that an IAM account password policy is configured and can be retrieved.',
    remediation: 'Create an IAM password policy enforcing minimum length of 14, complexity, and reuse prevention of 24.',
    tags: ['iam', 'password-policy', 'cis-1.8', 'cis-1.9'],
    compliance: {
      cis_2_0_aws: ['1.8', '1.9'],
    },
  },
  {
    checkId: 'accessanalyzer_enabled',
    provider: 'aws',
    service: 'iam',
    title: 'IAM Access Analyzer Not Enabled',
    severity: 'MEDIUM',
    description: 'Checks that IAM Access Analyzer is enabled for the account to identify resources shared with external entities.',
    remediation: 'Enable IAM Access Analyzer in the IAM console or via CLI: aws accessanalyzer create-analyzer --analyzer-name MyAnalyzer --type ACCOUNT',
    tags: ['iam', 'access-analyzer', 'cis-1.20'],
    compliance: {
      cis_2_0_aws: ['1.20'],
    },
  },
  {
    checkId: 'iam_support_role_created',
    provider: 'aws',
    service: 'iam',
    title: 'IAM Support Role Not Configured',
    severity: 'LOW',
    description: 'Checks that an IAM role with the AWSSupportAccess managed policy exists to manage AWS support cases.',
    remediation: 'Create an IAM role with the AWSSupportAccess managed policy and assign it to authorized users.',
    tags: ['iam', 'support-role', 'cis-1.17'],
    compliance: {
      cis_2_0_aws: ['1.17'],
    },
  },
  {
    checkId: 'iam_virtual_mfa_device_unassigned',
    provider: 'aws',
    service: 'iam',
    title: 'Orphaned Virtual MFA Device',
    severity: 'LOW',
    description: 'Checks for virtual MFA devices that are not assigned to any IAM user.',
    remediation: 'Delete unassigned virtual MFA devices to reduce clutter and prevent reuse.',
    tags: ['iam', 'mfa', 'cleanup'],
  },
  {
    checkId: 'iam_role_has_inline_policies',
    provider: 'aws',
    service: 'iam',
    title: 'IAM Role Has Inline Policies',
    severity: 'LOW',
    description: 'Checks for IAM roles with inline policies, which are harder to audit and reuse than managed policies.',
    remediation: 'Convert inline policies on roles to managed policies for better auditability and reuse.',
    tags: ['iam', 'roles', 'inline-policy', 'best-practices'],
  },
  {
    checkId: 'iam_customer_attached_policy_no_administrative_privileges',
    provider: 'aws',
    service: 'iam',
    title: 'Customer Managed Policy Allows Full Admin (*:*)',
    severity: 'CRITICAL',
    description: 'Checks for attached customer-managed policies that grant Allow on Action="*" and Resource="*".',
    remediation: 'Replace full-admin policies with least-privilege policies scoped to required actions and resources.',
    tags: ['iam', 'policies', 'wildcard', 'least-privilege', 'cis-1.16'],
    compliance: {
      cis_2_0_aws: ['1.16'],
    },
  },
  {
    checkId: 'iam_customer_unused_policy_administrative_privileges',
    provider: 'aws',
    service: 'iam',
    title: 'Unused Customer Managed Policy Grants Full Admin (*:*)',
    severity: 'HIGH',
    description: 'Checks for customer-managed policies that grant Allow on Action="*" and Resource="*" but are not attached to any user, group, or role — dead-weight full-admin permission sets that expand blast radius the moment they get attached, whether deliberately or by accident.',
    remediation: 'Delete the unused policy if it is no longer needed, or replace it with a least-privilege policy scoped to required actions and resources before attaching it to anything.',
    tags: ['iam', 'policies', 'wildcard', 'least-privilege', 'unused'],
  },
  {
    checkId: 'iam_administrator_access_with_mfa',
    provider: 'aws',
    service: 'iam',
    title: 'Administrator Access Without MFA',
    severity: 'HIGH',
    description: 'Checks that all IAM group members with AdministratorAccess policy have MFA enabled.',
    remediation: 'Require MFA for all users with AdministratorAccess, or move them to a group with MFA-enforcing policies.',
    tags: ['iam', 'mfa', 'admin', 'cis-1.10'],
    compliance: { cis_2_0_aws: ['1.10'] },
  },
  {
    checkId: 'iam_avoid_root_usage',
    provider: 'aws',
    service: 'iam',
    title: 'Root Account Used Recently',
    severity: 'HIGH',
    description: 'Checks that the AWS root user has not been used in the last day for console or API access.',
    remediation: 'Avoid using root account; disable root access keys and require MFA for emergency access only.',
    tags: ['iam', 'root', 'cis-1.1'],
    compliance: { cis_2_0_aws: ['1.1'] },
  },
  {
    checkId: 'iam_aws_attached_policy_no_administrative_privileges',
    provider: 'aws',
    service: 'iam',
    title: 'AWS Managed Policy Allows Full Admin (*:*)',
    severity: 'CRITICAL',
    description: 'Checks that attached AWS-managed policies do not grant Action="*" on Resource="*".',
    remediation: 'Detach overly permissive AWS managed policies and use least-privilege alternatives.',
    tags: ['iam', 'policies', 'wildcard', 'cis-1.16'],
    compliance: { cis_2_0_aws: ['1.16'] },
  },
  {
    checkId: 'iam_check_saml_providers_sts',
    provider: 'aws',
    service: 'iam',
    title: 'SAML Provider Not Configured',
    severity: 'LOW',
    description: 'Checks that at least one IAM SAML provider exists for federated role assumption.',
    remediation: 'Create an IAM SAML provider to enable federated access via sts:AssumeRoleWithSAML.',
    tags: ['iam', 'federation', 'saml'],
  },
  {
    checkId: 'iam_customer_unattached_policy_no_administrative_privileges',
    provider: 'aws',
    service: 'iam',
    title: 'Unattached Customer Policy Allows Full Admin (*:*)',
    severity: 'MEDIUM',
    description: 'Checks that unattached customer-managed policies do not grant Action="*" on Resource="*".',
    remediation: 'Remove or redesign policies to enforce least privilege.',
    tags: ['iam', 'policies', 'wildcard', 'cis-1.16'],
    compliance: { cis_2_0_aws: ['1.16'] },
  },
  {
    checkId: 'iam_group_administrator_access_policy',
    provider: 'aws',
    service: 'iam',
    title: 'Group Has AdministratorAccess Policy',
    severity: 'HIGH',
    description: 'Checks that IAM groups do not have the AdministratorAccess policy attached.',
    remediation: 'Detach AdministratorAccess from groups and use least-privilege policies instead.',
    tags: ['iam', 'groups', 'admin', 'cis-1.16'],
    compliance: { cis_2_0_aws: ['1.16'] },
  },
  {
    checkId: 'iam_inline_policy_allows_privilege_escalation',
    provider: 'aws',
    service: 'iam',
    title: 'Inline Policy Allows Privilege Escalation',
    severity: 'HIGH',
    description: 'Checks that inline policies do not allow actions that lead to privilege escalation.',
    remediation: 'Remove or restrict privilege-escalation actions from inline policies.',
    tags: ['iam', 'policies', 'privilege-escalation', 'inline'],
  },
  {
    checkId: 'iam_inline_policy_no_administrative_privileges',
    provider: 'aws',
    service: 'iam',
    title: 'Inline Policy Allows Full Admin (*:*)',
    severity: 'CRITICAL',
    description: 'Checks that inline policies do not grant Action="*" on Resource="*".',
    remediation: 'Replace inline policies granting full admin access with least-privilege policies.',
    tags: ['iam', 'policies', 'wildcard', 'inline', 'cis-1.16'],
    compliance: { cis_2_0_aws: ['1.16'] },
  },
  {
    checkId: 'iam_inline_policy_no_full_access_to_cloudtrail',
    provider: 'aws',
    service: 'iam',
    title: 'Inline Policy Allows Full CloudTrail Access',
    severity: 'HIGH',
    description: 'Checks that inline policies do not allow cloudtrail:* on all resources.',
    remediation: 'Scope CloudTrail permissions to specific actions and resources.',
    tags: ['iam', 'policies', 'cloudtrail', 'inline', 'cis-1.16'],
    compliance: { cis_2_0_aws: ['1.16'] },
  },
  {
    checkId: 'iam_inline_policy_no_full_access_to_kms',
    provider: 'aws',
    service: 'iam',
    title: 'Inline Policy Allows Full KMS Access',
    severity: 'MEDIUM',
    description: 'Checks that inline policies do not allow kms:* on all resources.',
    remediation: 'Restrict KMS permissions to specific actions and key ARNs.',
    tags: ['iam', 'policies', 'kms', 'inline'],
  },
  {
    checkId: 'iam_inline_policy_no_wildcard_marketplace_subscribe',
    provider: 'aws',
    service: 'iam',
    title: 'Inline Policy Allows Marketplace Subscribe on All Resources',
    severity: 'MEDIUM',
    description: 'Checks that inline policies do not allow aws-marketplace:Subscribe on all resources.',
    remediation: 'Scope marketplace subscribe permissions to specific product ARNs.',
    tags: ['iam', 'policies', 'marketplace', 'inline', 'gen-ai'],
  },
  {
    checkId: 'iam_no_custom_policy_permissive_role_assumption',
    provider: 'aws',
    service: 'iam',
    title: 'Custom Policy Allows Permissive Role Assumption',
    severity: 'HIGH',
    description: 'Checks that custom policies do not allow sts:AssumeRole on wildcard resources.',
    remediation: 'Restrict AssumeRole permissions to specific role ARNs.',
    tags: ['iam', 'policies', 'sts', 'privilege-escalation', 'cis-1.16'],
    compliance: { cis_2_0_aws: ['1.16'] },
  },
  {
    checkId: 'iam_no_expired_server_certificates_stored',
    provider: 'aws',
    service: 'iam',
    title: 'Expired Server Certificate Stored',
    severity: 'HIGH',
    description: 'Checks that no expired TLS certificates are stored in IAM.',
    remediation: 'Delete expired server certificates from IAM.',
    tags: ['iam', 'certificates', 'encryption', 'cis-1.6'],
    compliance: { cis_2_0_aws: ['1.6'] },
  },
  {
    checkId: 'iam_password_policy_expires_passwords_within_90_days_or_less',
    provider: 'aws',
    service: 'iam',
    title: 'Password Policy Does Not Expire Passwords Within 90 Days',
    severity: 'MEDIUM',
    description: 'Checks that the password policy enforces password expiration within 90 days.',
    remediation: 'Update password policy to set MaxPasswordAge to 90 days or less.',
    tags: ['iam', 'password-policy', 'cis-1.11'],
    compliance: { cis_2_0_aws: ['1.11'] },
  },
  {
    checkId: 'iam_password_policy_lowercase',
    provider: 'aws',
    service: 'iam',
    title: 'Password Policy Does Not Require Lowercase',
    severity: 'LOW',
    description: 'Checks that the password policy requires at least one lowercase letter.',
    remediation: 'Update password policy to require lowercase characters.',
    tags: ['iam', 'password-policy', 'cis-1.14'],
    compliance: { cis_2_0_aws: ['1.14'] },
  },
  {
    checkId: 'iam_password_policy_number',
    provider: 'aws',
    service: 'iam',
    title: 'Password Policy Does Not Require Numbers',
    severity: 'MEDIUM',
    description: 'Checks that the password policy requires at least one numeric character.',
    remediation: 'Update password policy to require numbers.',
    tags: ['iam', 'password-policy', 'cis-1.12'],
    compliance: { cis_2_0_aws: ['1.12'] },
  },
  {
    checkId: 'iam_password_policy_symbol',
    provider: 'aws',
    service: 'iam',
    title: 'Password Policy Does Not Require Symbols',
    severity: 'MEDIUM',
    description: 'Checks that the password policy requires at least one non-alphanumeric character.',
    remediation: 'Update password policy to require symbols.',
    tags: ['iam', 'password-policy', 'cis-1.13'],
    compliance: { cis_2_0_aws: ['1.13'] },
  },
  {
    checkId: 'iam_password_policy_uppercase',
    provider: 'aws',
    service: 'iam',
    title: 'Password Policy Does Not Require Uppercase',
    severity: 'MEDIUM',
    description: 'Checks that the password policy requires at least one uppercase letter.',
    remediation: 'Update password policy to require uppercase characters.',
    tags: ['iam', 'password-policy', 'cis-1.15'],
    compliance: { cis_2_0_aws: ['1.15'] },
  },
  {
    checkId: 'iam_policy_allows_privilege_escalation',
    provider: 'aws',
    service: 'iam',
    title: 'Custom Managed Policy Allows Privilege Escalation',
    severity: 'HIGH',
    description: 'Checks that customer-managed policies do not allow actions that lead to privilege escalation.',
    remediation: 'Remove or restrict privilege-escalation actions from policies.',
    tags: ['iam', 'policies', 'privilege-escalation', 'cis-1.16'],
    compliance: { cis_2_0_aws: ['1.16'] },
  },
  {
    checkId: 'iam_policy_attached_only_to_group_or_roles',
    provider: 'aws',
    service: 'iam',
    title: 'User Has Direct Policy Attachments',
    severity: 'LOW',
    description: 'Checks that IAM users do not have inline or attached policies directly.',
    remediation: 'Move user policies to groups or roles instead of attaching directly to users.',
    tags: ['iam', 'users', 'policies', 'cis-1.16'],
    compliance: { cis_2_0_aws: ['1.16'] },
  },
  {
    checkId: 'iam_policy_cloudshell_admin_not_attached',
    provider: 'aws',
    service: 'iam',
    title: 'AWSCloudShellFullAccess Policy Attached',
    severity: 'MEDIUM',
    description: 'Checks that no IAM users, groups, or roles have the AWSCloudShellFullAccess policy.',
    remediation: 'Detach AWSCloudShellFullAccess and use least-privilege policies instead.',
    tags: ['iam', 'policies', 'cloudshell'],
  },
  {
    checkId: 'iam_policy_no_full_access_to_cloudtrail',
    provider: 'aws',
    service: 'iam',
    title: 'Custom Managed Policy Allows Full CloudTrail Access',
    severity: 'MEDIUM',
    description: 'Checks that customer-managed policies do not allow cloudtrail:* on all resources.',
    remediation: 'Scope CloudTrail permissions to specific actions and resources.',
    tags: ['iam', 'policies', 'cloudtrail', 'cis-1.16'],
    compliance: { cis_2_0_aws: ['1.16'] },
  },
  {
    checkId: 'iam_policy_no_full_access_to_kms',
    provider: 'aws',
    service: 'iam',
    title: 'Custom Managed Policy Allows Full KMS Access',
    severity: 'MEDIUM',
    description: 'Checks that customer-managed policies do not allow kms:* on all resources.',
    remediation: 'Restrict KMS permissions to specific actions and key ARNs.',
    tags: ['iam', 'policies', 'kms', 'cis-1.16'],
    compliance: { cis_2_0_aws: ['1.16'] },
  },
  {
    checkId: 'iam_policy_no_wildcard_marketplace_subscribe',
    provider: 'aws',
    service: 'iam',
    title: 'Custom Managed Policy Allows Marketplace Subscribe on All Resources',
    severity: 'MEDIUM',
    description: 'Checks that customer-managed policies do not allow aws-marketplace:Subscribe on all resources.',
    remediation: 'Scope marketplace subscribe permissions to specific product ARNs.',
    tags: ['iam', 'policies', 'marketplace', 'gen-ai', 'cis-1.16'],
    compliance: { cis_2_0_aws: ['1.16'] },
  },
  {
    checkId: 'iam_role_access_not_stale_to_bedrock',
    provider: 'aws',
    service: 'iam',
    title: 'Role Has Stale Bedrock Access',
    severity: 'MEDIUM',
    description: 'Checks that IAM roles with Bedrock permissions have used them recently (within 60 days).',
    remediation: 'Remove stale Bedrock permissions from roles with no recent access.',
    tags: ['iam', 'bedrock', 'access-advisor', 'gen-ai'],
  },
  {
    checkId: 'iam_role_administratoraccess_policy',
    provider: 'aws',
    service: 'iam',
    title: 'Role Has AdministratorAccess Policy',
    severity: 'HIGH',
    description: 'Checks that IAM roles do not have the AdministratorAccess policy attached.',
    remediation: 'Detach AdministratorAccess from roles and use least-privilege policies instead.',
    tags: ['iam', 'roles', 'admin', 'cis-1.16'],
    compliance: { cis_2_0_aws: ['1.16'] },
  },
  {
    checkId: 'iam_role_cross_account_readonlyaccess_policy',
    provider: 'aws',
    service: 'iam',
    title: 'Role Grants Cross-Account ReadOnlyAccess',
    severity: 'HIGH',
    description: 'Checks that roles trusting external principals do not have ReadOnlyAccess policy.',
    remediation: 'Detach ReadOnlyAccess and restrict cross-account permissions to specific resources.',
    tags: ['iam', 'roles', 'cross-account', 'trust-boundaries'],
  },
  {
    checkId: 'iam_role_cross_service_confused_deputy_prevention',
    provider: 'aws',
    service: 'iam',
    title: 'Service Role Missing Confused Deputy Prevention',
    severity: 'HIGH',
    description: 'Checks that service roles restrict AWS service principals using aws:SourceArn or aws:SourceAccount.',
    remediation: 'Add condition keys to trust policies to prevent cross-service confused deputy attacks.',
    tags: ['iam', 'roles', 'trust-boundaries', 'confused-deputy'],
  },
  {
    checkId: 'iam_root_credentials_management_enabled',
    provider: 'aws',
    service: 'iam',
    title: 'AWS Organization Root Credentials Management Not Enabled',
    severity: 'HIGH',
    description: 'Checks that AWS Organizations has centralized root credentials management enabled.',
    remediation: 'Enable root credentials management in AWS Organizations.',
    tags: ['iam', 'root', 'organizations'],
  },
  {
    checkId: 'iam_root_hardware_mfa_enabled',
    provider: 'aws',
    service: 'iam',
    title: 'Root Account MFA Not Enabled',
    severity: 'HIGH',
    description: 'Checks that the root account has at least one MFA method enabled — virtual/authenticator app, SMS, a hardware security key, or a TOTP token all satisfy this control. Only the complete absence of MFA is reported.',
    remediation: 'Enable MFA for the root account using any supported method (virtual authenticator app, hardware security key, or TOTP token).',
    tags: ['iam', 'root', 'mfa', 'cis-1.7'],
    compliance: { cis_2_0_aws: ['1.7'] },
  },
  {
    checkId: 'iam_securityaudit_role_created',
    provider: 'aws',
    service: 'iam',
    title: 'SecurityAudit Role Not Configured',
    severity: 'LOW',
    description: 'Checks that at least one IAM role has the SecurityAudit managed policy attached.',
    remediation: 'Create an IAM role with the SecurityAudit policy for security team read-only access.',
    tags: ['iam', 'roles', 'audit', 'cis-1.19'],
    compliance: { cis_2_0_aws: ['1.19'] },
  },
  {
    checkId: 'iam_user_access_not_stale_to_bedrock',
    provider: 'aws',
    service: 'iam',
    title: 'User Has Stale Bedrock Access',
    severity: 'MEDIUM',
    description: 'Checks that IAM users with Bedrock permissions have used them recently (within 60 days).',
    remediation: 'Remove stale Bedrock permissions from users with no recent access.',
    tags: ['iam', 'bedrock', 'access-advisor', 'gen-ai'],
  },
  {
    checkId: 'iam_user_access_not_stale_to_sagemaker',
    provider: 'aws',
    service: 'iam',
    title: 'User Has Stale SageMaker Access',
    severity: 'MEDIUM',
    description: 'Checks that IAM users with SageMaker permissions have used them recently (within 90 days).',
    remediation: 'Remove stale SageMaker permissions from users with no recent access.',
    tags: ['iam', 'sagemaker', 'access-advisor'],
  },
  {
    checkId: 'iam_user_hardware_mfa_enabled',
    provider: 'aws',
    service: 'iam',
    title: 'User MFA Not Enabled',
    severity: 'HIGH',
    description: 'Checks that the IAM user has at least one MFA method enabled — virtual/authenticator app, SMS, a hardware security key, or a TOTP token all satisfy this control. Only the complete absence of MFA is reported.',
    remediation: 'Enable MFA for this user using any supported method (virtual authenticator app, hardware security key, or TOTP token).',
    tags: ['iam', 'users', 'mfa', 'cis-1.10'],
    compliance: { cis_2_0_aws: ['1.10'] },
  },
  {
    checkId: 'iam_user_no_setup_initial_access_key',
    provider: 'aws',
    service: 'iam',
    title: 'User Has Never-Used Active Access Key',
    severity: 'MEDIUM',
    description: 'Checks that IAM users with console access do not have active access keys that have never been used.',
    remediation: 'Delete unused access keys or reduce provisioning of initial keys.',
    tags: ['iam', 'users', 'access-keys', 'cis-1.3'],
    compliance: { cis_2_0_aws: ['1.3'] },
  },
  {
    checkId: 'iam_user_two_active_access_key',
    provider: 'aws',
    service: 'iam',
    title: 'User Has Multiple Active Access Keys',
    severity: 'MEDIUM',
    description: 'Checks that IAM users have at most one active access key.',
    remediation: 'Deactivate or delete excess access keys, keeping only one active per user.',
    tags: ['iam', 'users', 'access-keys', 'cis-1.2'],
    compliance: { cis_2_0_aws: ['1.2'] },
  },
  {
    checkId: 'iam_user_with_temporary_credentials',
    provider: 'aws',
    service: 'iam',
    title: 'User Uses Long-Lived Credentials',
    severity: 'HIGH',
    description: 'Checks that IAM users do not use long-lived access keys to access services other than IAM/STS.',
    remediation: 'Migrate to temporary credentials via IAM roles and federation.',
    tags: ['iam', 'users', 'credentials', 'cis-1.18'],
    compliance: { cis_2_0_aws: ['1.18'] },
  },
  {
    checkId: 'iam_user_access_inventory',
    provider: 'aws',
    service: 'iam',
    title: 'IAM User Access Inventory',
    severity: 'MEDIUM', // baseline; actual severity is per-user (HIGH when open-ended, MEDIUM with any hygiene issue, INFO when clean)
    description: 'One consolidated record per IAM user covering effective permissions (groups, attached/inline policies), assumable roles, and access hygiene (MFA, password age, access key age) — flags open-ended (admin-equivalent) access and stale credentials.',
    remediation: 'Remove admin-equivalent policies/roles the user does not need, enable MFA, rotate the password, and deactivate access keys unused for 30+ days.',
    tags: ['iam', 'users', 'access-review', 'mfa', 'least-privilege'],
  },
];
