// Check logic derived from Prowler (Apache-2.0, https://github.com/prowler-cloud/prowler)
import { CheckMetadata } from '../../types';

export const kafkaChecks: CheckMetadata[] = [
  {
    checkId: 'kafka_cluster_is_public',
    provider: 'aws',
    service: 'kafka',
    title: 'MSK Cluster Publicly Accessible',
    severity: 'CRITICAL',
    description: 'Checks that the MSK cluster does not have public access enabled; brokers reachable from the Internet expose the Kafka surface to unauthorized clients.',
    remediation: 'Disable public access (set connectivity PublicAccess type to DISABLED) so brokers are reachable only from within the VPC; use VPC peering, Transit Gateway or PrivateLink for cross-network access.',
    tags: ['kafka', 'msk', 'public-access', 'network'],
  },
  {
    checkId: 'kafka_cluster_unrestricted_access_disabled',
    provider: 'aws',
    service: 'kafka',
    title: 'MSK Cluster Allows Unauthenticated Access',
    severity: 'CRITICAL',
    description: 'Checks that the MSK cluster does not permit unauthenticated client access, which would let any network-reachable client read and write topics.',
    remediation: 'Disable unauthenticated access on the cluster and require IAM, SASL/SCRAM or mutual TLS client authentication, combined with Kafka ACLs for least-privilege topic access.',
    tags: ['kafka', 'msk', 'authentication', 'access-control'],
  },
  {
    checkId: 'kafka_cluster_in_transit_encryption_enabled',
    provider: 'aws',
    service: 'kafka',
    title: 'MSK Cluster In-Transit Encryption Disabled',
    severity: 'HIGH',
    description: 'Checks that the MSK cluster enforces TLS encryption both between clients and brokers and for in-cluster broker traffic.',
    remediation: 'Set client-broker encryption to TLS (not PLAINTEXT or TLS_PLAINTEXT) and enable in-cluster encryption so all data moving to and between brokers is encrypted.',
    tags: ['kafka', 'msk', 'encryption', 'in-transit'],
  },
  {
    checkId: 'kafka_cluster_mutual_tls_authentication_enabled',
    provider: 'aws',
    service: 'kafka',
    title: 'MSK Cluster Mutual TLS Authentication Disabled',
    severity: 'HIGH',
    description: 'Checks that the MSK cluster has mutual TLS client authentication enabled so clients must present trusted certificates to connect.',
    remediation: 'Enable TLS client authentication on the cluster with an ACM Private CA, distribute client certificates, and pair certificate identity with Kafka ACLs.',
    tags: ['kafka', 'msk', 'authentication', 'tls'],
  },
  {
    checkId: 'kafka_cluster_encryption_at_rest_uses_cmk',
    provider: 'aws',
    service: 'kafka',
    title: 'MSK Cluster Not Encrypted With Customer Managed Key',
    severity: 'MEDIUM',
    description: 'Checks that the MSK cluster encrypts broker data volumes at rest with a customer-managed KMS key rather than an AWS-managed key.',
    remediation: 'Configure encryption at rest with a customer-managed KMS key (CMK) so you control key policy, rotation and revocation; apply least privilege to key grants.',
    tags: ['kafka', 'msk', 'encryption', 'kms'],
  },
  {
    checkId: 'kafka_cluster_enhanced_monitoring_enabled',
    provider: 'aws',
    service: 'kafka',
    title: 'MSK Cluster Enhanced Monitoring Disabled',
    severity: 'MEDIUM',
    description: 'Checks that the MSK cluster has enhanced monitoring enabled (beyond the DEFAULT level) for broker, topic or partition level metrics.',
    remediation: 'Raise the cluster monitoring level to PER_BROKER, PER_TOPIC_PER_BROKER or PER_TOPIC_PER_PARTITION and alert on anomalous broker and topic activity.',
    tags: ['kafka', 'msk', 'monitoring', 'observability'],
  },
  {
    checkId: 'kafka_cluster_uses_latest_version',
    provider: 'aws',
    service: 'kafka',
    title: 'MSK Cluster Not Running Latest Kafka Version',
    severity: 'MEDIUM',
    description: 'Checks that the MSK cluster runs the latest Kafka version supported by MSK, ensuring current security fixes and patches are applied.',
    remediation: 'Upgrade the cluster to the latest MSK-supported Kafka version during a maintenance window, validating client compatibility in staging first.',
    tags: ['kafka', 'msk', 'patching', 'version'],
  },
];
