import { CheckMetadata } from '../../types';

// Titles must stay byte-identical to the pre-registry hardcoded titles:
// the scan worker dedupes OPEN findings on service:title:fingerprint, so a
// reworded title would re-open every existing finding as "new".
export const kmsChecks: CheckMetadata[] = [
  {
    checkId: 'kms_cmk_not_deleted_unintentionally',
    provider: 'aws',
    service: 'kms',
    title: 'KMS Key Pending Deletion',
    severity: 'MEDIUM',
    description: 'Checks for KMS keys scheduled for deletion; deletion is irreversible and data encrypted under the key becomes unrecoverable.',
    remediation: "Cancel deletion or let the key expire if it's no longer needed",
    tags: ['kms', 'key-management'],
  },
  {
    checkId: 'kms_cmk_are_used',
    provider: 'aws',
    service: 'kms',
    title: 'KMS Key Disabled',
    severity: 'MEDIUM',
    description: 'Checks for KMS keys that are disabled; disabled keys cannot be used and may indicate stale key management.',
    remediation: "Enable the KMS key if it's still needed, or schedule it for deletion if not.",
    tags: ['kms', 'key-management'],
  },
  {
    checkId: 'kms_cmk_rotation_enabled',
    provider: 'aws',
    service: 'kms',
    title: 'KMS Key Rotation Not Enabled',
    severity: 'MEDIUM',
    description: 'Checks that customer-managed KMS keys have automatic key rotation enabled.',
    remediation: 'Enable automatic key rotation for the customer-managed KMS key.',
    tags: ['kms', 'key-rotation', 'compliance'],
  },
  {
    checkId: 'kms_cmk_not_multi_region',
    provider: 'aws',
    service: 'kms',
    title: 'KMS Key Is Multi-Region',
    severity: 'MEDIUM',
    description: 'Checks for enabled customer-managed KMS keys with the multi-Region property; shared key material across regions widens the blast radius of a key compromise.',
    remediation: 'Use single-region keys unless cross-region key material replication is a documented requirement; migrate data to a new single-region key and retire the multi-region key.',
    tags: ['kms', 'encryption', 'multi-region'],
  },
  {
    checkId: 'kms_key_not_publicly_accessible',
    provider: 'aws',
    service: 'kms',
    title: 'KMS Key Publicly Accessible',
    severity: 'CRITICAL',
    description: 'Checks that customer-managed KMS key policies do not allow wildcard principals without restrictive conditions, which would make the key usable by any AWS account.',
    remediation: 'Remove statements with Principal "*" from the key policy, or constrain them with restrictive conditions, and grant access only to specific accounts and roles.',
    tags: ['kms', 'identity-access', 'public-access'],
  },
  {
    checkId: 'kms_key_enclave_attestation_not_enforced',
    provider: 'aws',
    service: 'kms',
    title: 'KMS Enclave Key Attestation Not Enforced',
    severity: 'HIGH',
    description: 'Checks that every sensitive Allow statement (kms:Decrypt, GenerateDataKey*, DeriveSharedSecret, GenerateRandom, kms:*) in Nitro Enclave key policies carries a kms:RecipientAttestation:* condition binding usage to a measured enclave image.',
    remediation: 'Add a kms:RecipientAttestation:* condition (for example PCR0 bound to the enclave image measurement) to every sensitive Allow statement in the key policy.',
    tags: ['kms', 'nitro-enclave', 'attestation', 'trust-boundaries'],
  },
  {
    checkId: 'kms_key_enclave_attestation_bypassable_path',
    provider: 'aws',
    service: 'kms',
    title: 'KMS Enclave Key Attestation Bypassable',
    severity: 'HIGH',
    description: 'Checks Nitro Enclave key policies for authorization paths that bypass attestation: sensitive Allow statements without a kms:RecipientAttestation:* condition and without a paired Deny that fires when attestation is absent.',
    remediation: 'Add attestation conditions to the bypassing Allow statement, or add a Deny statement with a Null kms:RecipientAttestation condition so unattested calls fail closed; split admin actions from data-plane actions in root delegations.',
    tags: ['kms', 'nitro-enclave', 'attestation', 'trust-boundaries'],
  },
  {
    checkId: 'kms_key_enclave_attestation_no_deployment_binding',
    provider: 'aws',
    service: 'kms',
    title: 'KMS Enclave Key Attestation Without Deployment Binding',
    severity: 'INFO',
    description: 'Checks that enclave key attestation conditions bind a deployment context (PCR3 parent IAM role, PCR4 instance ID, PCR8 signing certificate, or an account-level condition); image-only PCR0/1/2 bindings accept the same image running anywhere.',
    remediation: 'Pair image PCR bindings with PCR3 (parent IAM role) and PCR8 (EIF signing certificate), PCR4 (instance ID), or an account/org condition so the key policy binds where the enclave runs, not just what it runs.',
    tags: ['kms', 'nitro-enclave', 'attestation', 'hardening'],
  },
];
