import { CheckMetadata } from '../../types';

// Titles must stay byte-identical to the pre-registry hardcoded titles:
// the scan worker dedupes OPEN findings on service:title:fingerprint, so a
// reworded title would re-open every existing finding as "new".
export const lambdaChecks: CheckMetadata[] = [
  {
    checkId: 'awslambda_function_using_supported_runtimes',
    provider: 'aws',
    service: 'lambda',
    title: 'Lambda EOL Runtime',
    severity: 'CRITICAL',
    description: 'Checks for Lambda functions using end-of-life runtimes that no longer receive security patches.',
    remediation: 'Upgrade the function to a supported runtime immediately. EOL runtimes have known unpatched vulnerabilities.',
    tags: ['lambda', 'runtime', 'eol', 'cis'],
  },
  {
    checkId: 'lambda_function_deprecated_runtime',
    provider: 'aws',
    service: 'lambda',
    title: 'Lambda Deprecated Runtime',
    severity: 'HIGH',
    description: 'Checks for Lambda functions using deprecated runtimes that will reach end-of-life soon.',
    remediation: 'Upgrade the function to a current runtime (e.g. nodejs20.x, python3.12, java21, dotnet8).',
    tags: ['lambda', 'runtime', 'deprecated'],
  },
  {
    checkId: 'awslambda_function_no_secrets_in_variables',
    provider: 'aws',
    service: 'lambda',
    title: 'Lambda Sensitive Environment Variable',
    severity: 'HIGH',
    description: 'Checks Lambda environment variables for names that suggest hardcoded secrets or credentials.',
    remediation: 'Move secret values to AWS Secrets Manager or SSM Parameter Store and reference them at runtime.',
    tags: ['lambda', 'secrets', 'environment-variables', 'hardcoded-credentials'],
  },
  {
    checkId: 'awslambda_function_not_publicly_accessible',
    provider: 'aws',
    service: 'lambda',
    title: 'Lambda Public Function',
    severity: 'HIGH',
    description: 'Checks Lambda resource-based policies for statements that allow public invocation from any principal ("*").',
    remediation: 'Remove or restrict the resource-based policy to only allow specific AWS accounts, services, or principals.',
    tags: ['lambda', 'public-access', 'policy'],
  },
  {
    checkId: 'awslambda_function_no_dead_letter_queue',
    provider: 'aws',
    service: 'lambda',
    title: 'Lambda No Dead Letter Queue',
    severity: 'LOW',
    description: 'Checks that Lambda functions have a dead-letter queue configured so failed async invocations are not silently dropped.',
    remediation: 'Configure an SQS queue or SNS topic as the dead-letter queue to capture and reprocess failed invocations.',
    tags: ['lambda', 'reliability', 'dlq'],
  },
  {
    checkId: 'awslambda_function_inside_vpc',
    provider: 'aws',
    service: 'lambda',
    title: 'Lambda Sensitive Function Not in VPC',
    severity: 'MEDIUM',
    description: 'Checks that Lambda functions that appear to handle sensitive operations are configured to run inside a VPC.',
    remediation: 'Configure VPC settings for the function to restrict network access to private subnets.',
    tags: ['lambda', 'vpc', 'network-isolation'],
  },
  {
    checkId: 'lambda_function_code_signing_enabled',
    provider: 'aws',
    service: 'lambda',
    title: 'Lambda No Code Signing',
    severity: 'LOW',
    description: 'Checks that Lambda functions have code signing configured so only verified code can be deployed.',
    remediation: 'Enable code signing using AWS Signer to ensure only trusted code is deployed.',
    tags: ['lambda', 'code-signing', 'integrity'],
  },
  {
    checkId: 'lambda_function_package_too_large',
    provider: 'aws',
    service: 'lambda',
    title: 'Lambda Package Too Large for Analysis',
    severity: 'INFO',
    description: 'Reports Lambda deployment packages that exceed the size limit for dependency vulnerability analysis and were skipped.',
    remediation: 'Consider breaking the function into smaller deployment packages or using Lambda layers to reduce package size.',
    tags: ['lambda', 'package-size'],
  },
  {
    // Severity is per-vulnerability (mapped from OSV/CVSS) — every emit passes
    // a severity override; MEDIUM here is the mapper's fallback default.
    checkId: 'lambda_function_vulnerable_dependency',
    provider: 'aws',
    service: 'lambda',
    title: 'Lambda Vulnerable Dependency',
    severity: 'MEDIUM',
    description: 'Checks Lambda deployment package dependencies against the OSV database for known vulnerabilities.',
    remediation: 'Update the vulnerable package to a patched version listed in the advisory.',
    tags: ['lambda', 'vulnerable-dependency', 'cve'],
  },
  {
    checkId: 'lambda_function_no_reserved_concurrency',
    provider: 'aws',
    service: 'lambda',
    title: 'Lambda Sensitive Function Has No Reserved Concurrency',
    severity: 'LOW',
    description: 'Checks that Lambda functions performing sensitive or expensive operations have a reserved concurrency limit to bound their blast radius.',
    remediation: 'Set a reserved concurrency limit: aws lambda put-function-concurrency --reserved-concurrent-executions <N>.',
    tags: ['lambda', 'concurrency', 'reliability'],
  },
  {
    checkId: 'lambda_function_alias_points_to_latest',
    provider: 'aws',
    service: 'lambda',
    title: 'Lambda Alias Points to $LATEST',
    severity: 'LOW',
    description: 'Checks that Lambda aliases point to a numbered version rather than $LATEST so deployments are immutable and rollback is possible.',
    remediation: 'Publish a numbered version and update each alias to point at it: aws lambda update-alias --function-version <N>.',
    tags: ['lambda', 'alias', 'release-management'],
  },
  {
    checkId: 'awslambda_function_env_vars_not_encrypted_with_cmk',
    provider: 'aws',
    service: 'lambda',
    title: 'Lambda Env Vars Not Encrypted With CMK',
    severity: 'MEDIUM',
    description: 'Checks that Lambda functions with environment variables encrypt them with a customer-managed KMS key instead of the default AWS-managed key.',
    remediation: 'Associate a customer-managed KMS key: aws lambda update-function-configuration --kms-key-arn <cmk-arn>, and grant the execution role decrypt access on the key.',
    tags: ['lambda', 'encryption', 'kms', 'environment-variables'],
  },
  {
    checkId: 'awslambda_function_invoke_api_operations_cloudtrail_logging_enabled',
    provider: 'aws',
    service: 'lambda',
    title: 'Lambda Invoke Not Logged by CloudTrail',
    severity: 'LOW',
    description: 'Checks that Lambda function Invoke API calls are recorded as CloudTrail data events by at least one trail.',
    remediation: 'Add a CloudTrail data event selector for AWS::Lambda::Function covering the function (or all functions) so Invoke calls are audited.',
    tags: ['lambda', 'cloudtrail', 'logging'],
  },
  {
    checkId: 'awslambda_function_no_secrets_in_code',
    provider: 'aws',
    service: 'lambda',
    title: 'Lambda Secrets in Function Code',
    severity: 'CRITICAL',
    description: 'Scans text files in Lambda deployment packages for credential patterns such as API keys, passwords, tokens and private keys.',
    remediation: 'Remove hardcoded values from the code, rotate the exposed credentials, and load secrets at runtime from AWS Secrets Manager or SSM Parameter Store.',
    tags: ['lambda', 'secrets', 'hardcoded-credentials'],
  },
  {
    checkId: 'awslambda_function_url_cors_policy',
    provider: 'aws',
    service: 'lambda',
    title: 'Lambda Function URL Wildcard CORS',
    severity: 'MEDIUM',
    description: 'Checks that Lambda function URL CORS policies do not allow the wildcard origin ("*").',
    remediation: 'Restrict AllowOrigins to trusted domains: aws lambda update-function-url-config --cors AllowOrigins=https://<trusted-domain>.',
    tags: ['lambda', 'function-url', 'cors', 'internet-exposed'],
  },
  {
    checkId: 'awslambda_function_url_public',
    provider: 'aws',
    service: 'lambda',
    title: 'Lambda Function URL Publicly Accessible',
    severity: 'HIGH',
    description: 'Checks that Lambda function URLs require AWS IAM authentication rather than allowing unauthenticated public invocation.',
    remediation: 'Set the function URL auth type to AWS_IAM: aws lambda update-function-url-config --auth-type AWS_IAM, and grant lambda:InvokeFunctionUrl only to required principals.',
    tags: ['lambda', 'function-url', 'public-access', 'internet-exposed'],
  },
  {
    checkId: 'awslambda_function_vpc_multi_az',
    provider: 'aws',
    service: 'lambda',
    title: 'Lambda Function Not Multi-AZ',
    severity: 'MEDIUM',
    description: 'Checks that VPC-attached Lambda functions use subnets spanning at least two Availability Zones for fault tolerance.',
    remediation: 'Configure the function VPC settings with subnets from at least two different Availability Zones via update-function-configuration --vpc-config.',
    tags: ['lambda', 'vpc', 'resilience', 'multi-az'],
  },
  {
    checkId: 'awslambda_function_using_cross_account_layers',
    provider: 'aws',
    service: 'lambda',
    title: 'Lambda Cross-Account Layer In Use',
    severity: 'HIGH',
    description: 'Checks that Lambda functions only use layers published by the audited account, since external layers are an uncontrolled supply-chain dependency.',
    remediation: 'Republish required layer content in your own account, pin functions to the account-owned layer ARN, and remove cross-account layer references.',
    tags: ['lambda', 'layers', 'supply-chain'],
  },
];
