import { CheckMetadata } from '../../types';

// Titles must stay byte-identical to the pre-registry hardcoded titles:
// the scan worker dedupes OPEN findings on service:title:fingerprint, so a
// reworded title would re-open every existing finding as "new".
export const lambdaChecks: CheckMetadata[] = [
  {
    checkId: 'awslambda_function_using_supported_runtimes',
    provider: 'aws',
    service: 'lambda',
    title: 'Lambda EOL Runtime',
    severity: 'CRITICAL',
    description: 'Checks for Lambda functions using end-of-life runtimes that no longer receive security patches.',
    remediation: 'Upgrade the function to a supported runtime immediately. EOL runtimes have known unpatched vulnerabilities.',
    tags: ['lambda', 'runtime', 'eol', 'cis'],
  },
  {
    checkId: 'lambda_function_deprecated_runtime',
    provider: 'aws',
    service: 'lambda',
    title: 'Lambda Deprecated Runtime',
    severity: 'HIGH',
    description: 'Checks for Lambda functions using deprecated runtimes that will reach end-of-life soon.',
    remediation: 'Upgrade the function to a current runtime (e.g. nodejs20.x, python3.12, java21, dotnet8).',
    tags: ['lambda', 'runtime', 'deprecated'],
  },
  {
    checkId: 'awslambda_function_no_secrets_in_variables',
    provider: 'aws',
    service: 'lambda',
    title: 'Lambda Sensitive Environment Variable',
    severity: 'HIGH',
    description: 'Checks Lambda environment variables for names that suggest hardcoded secrets or credentials.',
    remediation: 'Move secret values to AWS Secrets Manager or SSM Parameter Store and reference them at runtime.',
    tags: ['lambda', 'secrets', 'environment-variables', 'hardcoded-credentials'],
  },
  {
    checkId: 'awslambda_function_not_publicly_accessible',
    provider: 'aws',
    service: 'lambda',
    title: 'Lambda Public Function',
    severity: 'HIGH',
    description: 'Checks Lambda resource-based policies for statements that allow public invocation from any principal ("*").',
    remediation: 'Remove or restrict the resource-based policy to only allow specific AWS accounts, services, or principals.',
    tags: ['lambda', 'public-access', 'policy'],
  },
  {
    checkId: 'awslambda_function_no_dead_letter_queue',
    provider: 'aws',
    service: 'lambda',
    title: 'Lambda No Dead Letter Queue',
    severity: 'LOW',
    description: 'Checks that Lambda functions have a dead-letter queue configured so failed async invocations are not silently dropped.',
    remediation: 'Configure an SQS queue or SNS topic as the dead-letter queue to capture and reprocess failed invocations.',
    tags: ['lambda', 'reliability', 'dlq'],
  },
  {
    checkId: 'awslambda_function_inside_vpc',
    provider: 'aws',
    service: 'lambda',
    title: 'Lambda Sensitive Function Not in VPC',
    severity: 'MEDIUM',
    description: 'Checks that Lambda functions that appear to handle sensitive operations are configured to run inside a VPC.',
    remediation: 'Configure VPC settings for the function to restrict network access to private subnets.',
    tags: ['lambda', 'vpc', 'network-isolation'],
  },
  {
    checkId: 'lambda_function_code_signing_enabled',
    provider: 'aws',
    service: 'lambda',
    title: 'Lambda No Code Signing',
    severity: 'LOW',
    description: 'Checks that Lambda functions have code signing configured so only verified code can be deployed.',
    remediation: 'Enable code signing using AWS Signer to ensure only trusted code is deployed.',
    tags: ['lambda', 'code-signing', 'integrity'],
  },
  {
    checkId: 'lambda_function_package_too_large',
    provider: 'aws',
    service: 'lambda',
    title: 'Lambda Package Too Large for Analysis',
    severity: 'INFO',
    description: 'Reports Lambda deployment packages that exceed the size limit for dependency vulnerability analysis and were skipped.',
    remediation: 'Consider breaking the function into smaller deployment packages or using Lambda layers to reduce package size.',
    tags: ['lambda', 'package-size'],
  },
  {
    // Severity is per-vulnerability (mapped from OSV/CVSS) — every emit passes
    // a severity override; MEDIUM here is the mapper's fallback default.
    checkId: 'lambda_function_vulnerable_dependency',
    provider: 'aws',
    service: 'lambda',
    title: 'Lambda Vulnerable Dependency',
    severity: 'MEDIUM',
    description: 'Checks Lambda deployment package dependencies against the OSV database for known vulnerabilities.',
    remediation: 'Update the vulnerable package to a patched version listed in the advisory.',
    tags: ['lambda', 'vulnerable-dependency', 'cve'],
  },
  {
    checkId: 'lambda_function_no_reserved_concurrency',
    provider: 'aws',
    service: 'lambda',
    title: 'Lambda Sensitive Function Has No Reserved Concurrency',
    severity: 'LOW',
    description: 'Checks that Lambda functions performing sensitive or expensive operations have a reserved concurrency limit to bound their blast radius.',
    remediation: 'Set a reserved concurrency limit: aws lambda put-function-concurrency --reserved-concurrent-executions <N>.',
    tags: ['lambda', 'concurrency', 'reliability'],
  },
  {
    checkId: 'lambda_function_alias_points_to_latest',
    provider: 'aws',
    service: 'lambda',
    title: 'Lambda Alias Points to $LATEST',
    severity: 'LOW',
    description: 'Checks that Lambda aliases point to a numbered version rather than $LATEST so deployments are immutable and rollback is possible.',
    remediation: 'Publish a numbered version and update each alias to point at it: aws lambda update-alias --function-version <N>.',
    tags: ['lambda', 'alias', 'release-management'],
  },
];
