// Check logic derived from Prowler (Apache-2.0, https://github.com/prowler-cloud/prowler)
import { CheckMetadata } from '../../types';

export const neptuneChecks: CheckMetadata[] = [
  {
    checkId: 'neptune_cluster_public_snapshot',
    provider: 'aws',
    service: 'neptune',
    title: 'Neptune Cluster Snapshot Publicly Shared',
    severity: 'CRITICAL',
    description: 'Checks that Neptune DB cluster snapshots are not shared publicly; a public snapshot lets any AWS account restore and read the full graph database.',
    remediation: 'Remove the "all" attribute from the snapshot share list to make it private, share only with trusted accounts, and restrict IAM permissions that can modify snapshot visibility.',
    tags: ['neptune', 'snapshot', 'public-access', 'data-exposure'],
  },
  {
    checkId: 'neptune_cluster_storage_encrypted',
    provider: 'aws',
    service: 'neptune',
    title: 'Neptune Cluster Storage Not Encrypted',
    severity: 'HIGH',
    description: 'Checks that the Neptune cluster has storage encryption at rest enabled.',
    remediation: 'Storage encryption cannot be enabled on an existing Neptune cluster; create an encrypted snapshot copy and restore into a new cluster with StorageEncrypted enabled, preferring a customer-managed KMS key.',
    tags: ['neptune', 'encryption', 'at-rest'],
  },
  {
    checkId: 'neptune_cluster_backup_enabled',
    provider: 'aws',
    service: 'neptune',
    title: 'Neptune Cluster Backup Retention Insufficient',
    severity: 'MEDIUM',
    description: 'Checks that the Neptune cluster has automated backups enabled with a retention period of at least 7 days.',
    remediation: 'Set the cluster backup retention period to at least 7 days (up to 35), test point-in-time restores regularly, and apply least privilege to backup and snapshot management.',
    tags: ['neptune', 'backup', 'resilience'],
  },
  {
    checkId: 'neptune_cluster_deletion_protection',
    provider: 'aws',
    service: 'neptune',
    title: 'Neptune Cluster Deletion Protection Disabled',
    severity: 'MEDIUM',
    description: 'Checks that the Neptune cluster has deletion protection enabled, blocking accidental or malicious cluster deletion.',
    remediation: 'Enable deletion protection on the cluster and require change control to toggle it; take a final snapshot before any planned decommissioning.',
    tags: ['neptune', 'deletion-protection', 'resilience'],
  },
  {
    checkId: 'neptune_cluster_iam_authentication_enabled',
    provider: 'aws',
    service: 'neptune',
    title: 'Neptune Cluster IAM Authentication Disabled',
    severity: 'MEDIUM',
    description: 'Checks that the Neptune cluster has IAM database authentication enabled so access uses short-lived signed credentials instead of static secrets.',
    remediation: 'Enable IAM database authentication on the cluster and grant connect permissions through narrowly scoped IAM policies.',
    tags: ['neptune', 'iam', 'authentication'],
  },
  {
    checkId: 'neptune_cluster_integration_cloudwatch_logs',
    provider: 'aws',
    service: 'neptune',
    title: 'Neptune Cluster Audit Logging Disabled',
    severity: 'MEDIUM',
    description: 'Checks that the Neptune cluster exports audit logs to CloudWatch Logs for query and access visibility.',
    remediation: 'Enable the audit log export in EnabledCloudwatchLogsExports on the cluster, set retention on the log group, and centralize analysis and alerting.',
    tags: ['neptune', 'logging', 'audit'],
  },
  {
    checkId: 'neptune_cluster_multi_az',
    provider: 'aws',
    service: 'neptune',
    title: 'Neptune Cluster Multi-AZ Disabled',
    severity: 'MEDIUM',
    description: 'Checks that the Neptune cluster is deployed across multiple Availability Zones for automatic failover.',
    remediation: 'Add read replicas in different Availability Zones so the cluster becomes Multi-AZ, set promotion priorities, and test failover regularly.',
    tags: ['neptune', 'multi-az', 'high-availability'],
  },
  {
    checkId: 'neptune_cluster_snapshot_encrypted',
    provider: 'aws',
    service: 'neptune',
    title: 'Neptune Cluster Snapshot Not Encrypted',
    severity: 'MEDIUM',
    description: 'Checks that Neptune DB cluster snapshots are encrypted at rest.',
    remediation: 'Copy the unencrypted snapshot specifying a KMS key to produce an encrypted copy, delete the unencrypted original, and ensure the source cluster is encrypted so future snapshots inherit encryption.',
    tags: ['neptune', 'snapshot', 'encryption', 'at-rest'],
  },
  {
    checkId: 'neptune_cluster_uses_public_subnet',
    provider: 'aws',
    service: 'neptune',
    title: 'Neptune Cluster Deployed in Public Subnet',
    severity: 'MEDIUM',
    description: 'Checks that the Neptune cluster DB subnet group contains no public subnets (subnets whose route table has a default route to an Internet gateway).',
    remediation: 'Move the cluster to a DB subnet group composed only of private subnets without Internet gateway routes, and reach it through VPC-internal networking.',
    tags: ['neptune', 'network', 'public-subnet'],
  },
  {
    checkId: 'neptune_cluster_copy_tags_to_snapshots',
    provider: 'aws',
    service: 'neptune',
    title: 'Neptune Cluster Tags Not Copied to Snapshots',
    severity: 'LOW',
    description: 'Checks that the Neptune cluster is configured to copy its tags to snapshots so tag-based access controls, retention and cost tracking keep applying to backup data.',
    remediation: 'Enable tag copying: aws neptune modify-db-cluster --db-cluster-identifier <cluster-id> --copy-tags-to-snapshot --apply-immediately. Standardize the tag taxonomy and automate tagging checks in provisioning.',
    tags: ['neptune', 'snapshot', 'governance'],
  },
];
