// Check logic derived from Prowler (Apache-2.0, https://github.com/prowler-cloud/prowler)
import { CheckMetadata } from '../../types';

export const networkfirewallChecks: CheckMetadata[] = [
  {
    checkId: 'networkfirewall_logging_enabled',
    provider: 'aws',
    service: 'networkfirewall',
    title: 'Network Firewall Logging Disabled',
    severity: 'HIGH',
    description: 'Checks that the Network Firewall has at least one logging destination (alert, flow or TLS logs) configured, so traffic and alert events are captured.',
    remediation: 'Configure a logging destination (S3, CloudWatch Logs or Kinesis Data Firehose) for alert and flow logs on the firewall and centralize log analysis for detection and forensics.',
    tags: ['networkfirewall', 'logging', 'audit'],
  },
  {
    checkId: 'networkfirewall_multi_az',
    provider: 'aws',
    service: 'networkfirewall',
    title: 'Network Firewall Not Multi-AZ',
    severity: 'HIGH',
    description: 'Checks that the Network Firewall is deployed with subnet mappings in more than one Availability Zone for fault tolerance.',
    remediation: 'Add firewall subnet mappings in at least two Availability Zones so inspection capacity survives the loss of a single AZ.',
    tags: ['networkfirewall', 'multi-az', 'resilience'],
  },
  {
    checkId: 'networkfirewall_policy_default_action_full_packets',
    provider: 'aws',
    service: 'networkfirewall',
    title: 'Network Firewall Allows Full Packets by Default',
    severity: 'HIGH',
    description: 'Checks that the firewall policy default stateless action for full packets is drop or forward to the stateful engine, so unmatched traffic is not silently passed.',
    remediation: 'Set the stateless default action for full packets to aws:drop or aws:forward_to_sfe in the firewall policy so traffic that matches no stateless rule is dropped or inspected statefully.',
    tags: ['networkfirewall', 'firewall-policy', 'network'],
  },
  {
    checkId: 'networkfirewall_policy_default_action_fragmented_packets',
    provider: 'aws',
    service: 'networkfirewall',
    title: 'Network Firewall Allows Fragmented Packets by Default',
    severity: 'HIGH',
    description: 'Checks that the firewall policy default stateless action for fragmented packets is drop or forward to the stateful engine, preventing fragment-based evasion of inspection.',
    remediation: 'Set the stateless fragment default action to aws:drop or aws:forward_to_sfe in the firewall policy so fragmented packets are dropped or fully inspected.',
    tags: ['networkfirewall', 'firewall-policy', 'network'],
  },
  {
    checkId: 'networkfirewall_policy_rule_group_associated',
    provider: 'aws',
    service: 'networkfirewall',
    title: 'Network Firewall Policy Has No Rule Groups',
    severity: 'HIGH',
    description: 'Checks that the firewall policy has at least one stateless or stateful rule group associated; a policy without rule groups performs no traffic filtering.',
    remediation: 'Associate at least one stateless or stateful rule group with the firewall policy and define least-privilege rules for the traffic the firewall must inspect.',
    tags: ['networkfirewall', 'firewall-policy', 'network'],
  },
  {
    checkId: 'networkfirewall_deletion_protection',
    provider: 'aws',
    service: 'networkfirewall',
    title: 'Network Firewall Deletion Protection Disabled',
    severity: 'MEDIUM',
    description: 'Checks that the Network Firewall has deletion protection enabled, blocking accidental or malicious removal of the firewall.',
    remediation: 'Enable DeleteProtection on the firewall and restrict permissions to disable it to narrowly scoped roles under change control.',
    tags: ['networkfirewall', 'deletion-protection', 'resilience'],
  },
  {
    checkId: 'networkfirewall_in_all_vpc',
    provider: 'aws',
    service: 'networkfirewall',
    title: 'VPC Without Network Firewall',
    severity: 'MEDIUM',
    description: 'Checks that each in-use VPC (one with network interfaces) has an AWS Network Firewall deployed to inspect and filter its traffic.',
    remediation: 'Deploy AWS Network Firewall (or an equivalent inspection layer) in VPCs carrying workloads, routing traffic through firewall subnets in each Availability Zone.',
    tags: ['networkfirewall', 'vpc', 'network'],
  },
];
