// Check logic derived from Prowler (Apache-2.0, https://github.com/prowler-cloud/prowler)
import { CheckMetadata } from '../../types';

export const opensearchChecks: CheckMetadata[] = [
  {
    checkId: 'opensearch_service_domains_not_publicly_accessible',
    provider: 'aws',
    service: 'opensearch',
    title: 'OpenSearch Domain Publicly Accessible',
    severity: 'CRITICAL',
    description: 'Checks OpenSearch domains for public exposure via their resource-based access policy; domains inside a VPC are treated as privately reachable, while overly permissive policies allowing broad unauthenticated access are flagged.',
    remediation: 'Place domains in a VPC and restrict reachability with security groups; use narrow resource policies without Principal "*", and require authenticated access via fine-grained access control.',
    tags: ['opensearch', 'public-access', 'resource-policy'],
  },
  {
    checkId: 'opensearch_service_domains_encryption_at_rest_enabled',
    provider: 'aws',
    service: 'opensearch',
    title: 'OpenSearch Encryption At Rest Disabled',
    severity: 'CRITICAL',
    description: 'Checks that OpenSearch domains have encryption at rest enabled using AWS KMS (AES-256) for stored data, including indexes, swap files and automated snapshots.',
    remediation: 'Enable encryption at rest with AWS KMS, preferably a customer-managed key with automatic rotation, and apply least-privilege key policies.',
    tags: ['opensearch', 'encryption', 'kms'],
  },
  {
    checkId: 'opensearch_service_domains_https_communications_enforced',
    provider: 'aws',
    service: 'opensearch',
    title: 'OpenSearch HTTPS Not Enforced',
    severity: 'HIGH',
    description: 'Checks that OpenSearch domains require HTTPS for all traffic; without enforcement, unencrypted HTTP connections are accepted.',
    remediation: 'Enable "Require HTTPS for all traffic" on the domain, prefer TLS 1.2+, and block plain HTTP via network controls.',
    tags: ['opensearch', 'https', 'encryption-in-transit'],
  },
  {
    checkId: 'opensearch_service_domains_node_to_node_encryption_enabled',
    provider: 'aws',
    service: 'opensearch',
    title: 'OpenSearch Node-to-Node Encryption Disabled',
    severity: 'HIGH',
    description: 'Checks that OpenSearch domains have node-to-node encryption enabled so traffic between cluster nodes is protected with TLS.',
    remediation: 'Enable node-to-node encryption on the domain; combine with HTTPS enforcement for clients and restricted network exposure.',
    tags: ['opensearch', 'encryption-in-transit', 'cluster'],
  },
  {
    checkId: 'opensearch_service_domains_access_control_enabled',
    provider: 'aws',
    service: 'opensearch',
    title: 'OpenSearch Fine-Grained Access Control Disabled',
    severity: 'HIGH',
    description: 'Checks that OpenSearch domains have fine-grained access control enabled in advanced security options, providing role-based authorization at index, document and field level.',
    remediation: 'Enable fine-grained access control, define granular role-based permissions mapped to federated identities, and apply deny-by-default least privilege.',
    tags: ['opensearch', 'access-control', 'authorization'],
  },
  {
    checkId: 'opensearch_service_domains_audit_logging_enabled',
    provider: 'aws',
    service: 'opensearch',
    title: 'OpenSearch Audit Logging Disabled',
    severity: 'HIGH',
    description: 'Checks that OpenSearch domains have audit logs (AUDIT_LOGS) enabled and published to CloudWatch Logs.',
    remediation: 'Enable AUDIT_LOGS publishing to a centralized, durable log store; tune categories to record auth failures and sensitive index operations, with retention and alerting.',
    tags: ['opensearch', 'logging', 'audit'],
  },
  {
    checkId: 'opensearch_service_domains_updated_to_the_latest_service_software_version',
    provider: 'aws',
    service: 'opensearch',
    title: 'OpenSearch Service Software Update Pending',
    severity: 'HIGH',
    description: 'Checks OpenSearch domains for pending service software updates (internal platform updates, distinct from engine version upgrades).',
    remediation: 'Apply the latest service software update promptly, scheduling during the domain off-peak window or enabling automatic updates.',
    tags: ['opensearch', 'patching', 'service-software'],
  },
  {
    checkId: 'opensearch_service_domains_internal_user_database_enabled',
    provider: 'aws',
    service: 'opensearch',
    title: 'OpenSearch Internal User Database Enabled',
    severity: 'MEDIUM',
    description: 'Checks whether OpenSearch domains rely on the internal user database (built-in HTTP basic users) instead of external identity providers.',
    remediation: 'Prefer federated authentication (IAM, SAML or Amazon Cognito) and disable the internal user database; centralize credential rotation and enforce MFA.',
    tags: ['opensearch', 'authentication', 'identity'],
  },
  {
    checkId: 'opensearch_service_domains_use_cognito_authentication_for_kibana',
    provider: 'aws',
    service: 'opensearch',
    title: 'OpenSearch Dashboards Without SSO Authentication',
    severity: 'MEDIUM',
    description: 'Checks that OpenSearch domains use Amazon Cognito or SAML to authenticate access to OpenSearch Dashboards/Kibana.',
    remediation: 'Enable Cognito or SAML authentication for Dashboards, prefer SSO with MFA, and restrict access via VPC or private endpoints.',
    tags: ['opensearch', 'authentication', 'dashboards'],
  },
  {
    checkId: 'opensearch_service_domains_fault_tolerant_data_nodes',
    provider: 'aws',
    service: 'opensearch',
    title: 'OpenSearch Data Nodes Not Fault Tolerant',
    severity: 'MEDIUM',
    description: 'Checks that OpenSearch domains have at least 3 data nodes with Zone Awareness enabled to distribute data across Availability Zones.',
    remediation: 'Configure the domain with 3 or more data nodes and enable Zone Awareness; prefer Multi-AZ with Standby and set index replicas of at least 1.',
    tags: ['opensearch', 'availability', 'resilience'],
  },
  {
    checkId: 'opensearch_service_domains_fault_tolerant_master_nodes',
    provider: 'aws',
    service: 'opensearch',
    title: 'OpenSearch Master Nodes Not Fault Tolerant',
    severity: 'MEDIUM',
    description: 'Checks that OpenSearch domains have dedicated master nodes enabled with a count of at least 3 for stable cluster coordination and quorum.',
    remediation: 'Enable dedicated master nodes with at least 3 (an odd number) and distribute them across Availability Zones using Multi-AZ with Standby.',
    tags: ['opensearch', 'availability', 'cluster'],
  },
  {
    checkId: 'opensearch_service_domains_cloudwatch_logging_enabled',
    provider: 'aws',
    service: 'opensearch',
    title: 'OpenSearch Slow Logs Not Published to CloudWatch',
    severity: 'LOW',
    description: 'Checks that OpenSearch domains publish both search slow logs (SEARCH_SLOW_LOGS) and index slow logs (INDEX_SLOW_LOGS) to CloudWatch Logs for visibility into expensive queries and indexing hotspots.',
    remediation: 'Enable SEARCH_SLOW_LOGS and INDEX_SLOW_LOGS publishing to CloudWatch log groups on the domain, set meaningful thresholds and retention, and alert on anomalies.',
    tags: ['opensearch', 'logging', 'monitoring'],
  },
];
