import { CheckMetadata } from '../../types';

// Titles must stay byte-identical to the pre-registry hardcoded titles:
// the scan worker dedupes OPEN findings on service:title:fingerprint, so a
// reworded title would re-open every existing finding as "new".
export const rdsChecks: CheckMetadata[] = [
  {
    checkId: 'rds_instance_storage_encrypted',
    provider: 'aws',
    service: 'rds',
    title: 'RDS Not Encrypted',
    severity: 'HIGH',
    description: 'Checks that RDS database instances have storage encryption at rest enabled.',
    remediation: 'Enable storage encryption at rest for the database instance.',
    tags: ['rds', 'encryption', 'data-protection'],
  },
  {
    checkId: 'rds_instance_backup_enabled',
    provider: 'aws',
    service: 'rds',
    title: 'Short Backup Retention',
    severity: 'MEDIUM',
    description: 'Checks that RDS database instances have an automated backup retention period of at least 7 days.',
    remediation: 'Increase the automated backup retention period to at least 7 days.',
    tags: ['rds', 'backup', 'disaster-recovery'],
  },
  {
    checkId: 'rds_instance_no_public_access',
    provider: 'aws',
    service: 'rds',
    title: 'Database Publicly Accessible',
    severity: 'CRITICAL',
    description: 'Checks that RDS database instances are not publicly accessible from the internet.',
    remediation: 'Disable public accessibility on the database instance and use VPC endpoints or private subnets for access.',
    tags: ['rds', 'public-access', 'network'],
  },
  {
    checkId: 'rds_instance_deletion_protection',
    provider: 'aws',
    service: 'rds',
    title: 'Deletion Protection Not Enabled',
    severity: 'MEDIUM',
    description: 'Checks that RDS database instances have deletion protection enabled.',
    remediation: 'Enable deletion protection for the database instance.',
    tags: ['rds', 'data-protection', 'disaster-recovery'],
  },
  {
    checkId: 'rds_instance_multi_az',
    provider: 'aws',
    service: 'rds',
    title: 'Multi-AZ Not Enabled',
    severity: 'MEDIUM',
    description: 'Checks that RDS database instances are deployed across multiple availability zones.',
    remediation: 'Enable Multi-AZ deployment for the database instance for high availability.',
    tags: ['rds', 'high-availability', 'disaster-recovery'],
  },
  {
    checkId: 'rds_instance_copy_tags_to_snapshots',
    provider: 'aws',
    service: 'rds',
    title: 'Copy Tags to Snapshot Not Enabled',
    severity: 'LOW',
    description: 'Checks that RDS database instances copy tags to their snapshots.',
    remediation: 'Enable copy tags to snapshot for the database instance.',
    tags: ['rds', 'backup', 'tagging'],
  },
  {
    checkId: 'rds_cluster_storage_encrypted',
    provider: 'aws',
    service: 'rds',
    title: 'RDS Cluster Not Encrypted',
    severity: 'HIGH',
    description: 'Checks that RDS database clusters have storage encryption at rest enabled.',
    remediation: 'Enable storage encryption at rest for the database cluster.',
    tags: ['rds', 'encryption', 'data-protection'],
  },
  {
    checkId: 'rds_cluster_backup_retention',
    provider: 'aws',
    service: 'rds',
    title: 'Short Cluster Backup Retention',
    severity: 'MEDIUM',
    description: 'Checks that RDS database clusters have an automated backup retention period of at least 7 days.',
    remediation: 'Increase the automated backup retention period to at least 7 days.',
    tags: ['rds', 'backup', 'disaster-recovery'],
  },
];
