// Check logic derived from Prowler (Apache-2.0, https://github.com/prowler-cloud/prowler)
import { CheckMetadata } from '../../types';

// Titles must stay byte-identical to the pre-registry hardcoded titles:
// the scan worker dedupes OPEN findings on service:title:fingerprint, so a
// reworded title would re-open every existing finding as "new".
export const rdsChecks: CheckMetadata[] = [
  {
    checkId: 'rds_instance_storage_encrypted',
    provider: 'aws',
    service: 'rds',
    title: 'RDS Not Encrypted',
    severity: 'HIGH',
    description: 'Checks that RDS database instances have storage encryption at rest enabled.',
    remediation: 'Enable storage encryption at rest for the database instance.',
    tags: ['rds', 'encryption', 'data-protection'],
  },
  {
    checkId: 'rds_instance_backup_enabled',
    provider: 'aws',
    service: 'rds',
    title: 'Short Backup Retention',
    severity: 'MEDIUM',
    description: 'Checks that RDS database instances have an automated backup retention period of at least 7 days.',
    remediation: 'Increase the automated backup retention period to at least 7 days.',
    tags: ['rds', 'backup', 'disaster-recovery'],
  },
  {
    checkId: 'rds_instance_no_public_access',
    provider: 'aws',
    service: 'rds',
    title: 'Database Publicly Accessible',
    severity: 'CRITICAL',
    description: 'Checks that RDS database instances are not publicly accessible from the internet.',
    remediation: 'Disable public accessibility on the database instance and use VPC endpoints or private subnets for access.',
    tags: ['rds', 'public-access', 'network'],
  },
  {
    checkId: 'rds_instance_deletion_protection',
    provider: 'aws',
    service: 'rds',
    title: 'Deletion Protection Not Enabled',
    severity: 'MEDIUM',
    description: 'Checks that RDS database instances have deletion protection enabled.',
    remediation: 'Enable deletion protection for the database instance.',
    tags: ['rds', 'data-protection', 'disaster-recovery'],
  },
  {
    checkId: 'rds_instance_multi_az',
    provider: 'aws',
    service: 'rds',
    title: 'Multi-AZ Not Enabled',
    severity: 'MEDIUM',
    description: 'Checks that RDS database instances are deployed across multiple availability zones.',
    remediation: 'Enable Multi-AZ deployment for the database instance for high availability.',
    tags: ['rds', 'high-availability', 'disaster-recovery'],
  },
  {
    checkId: 'rds_instance_copy_tags_to_snapshots',
    provider: 'aws',
    service: 'rds',
    title: 'Copy Tags to Snapshot Not Enabled',
    severity: 'LOW',
    description: 'Checks that RDS database instances copy tags to their snapshots.',
    remediation: 'Enable copy tags to snapshot for the database instance.',
    tags: ['rds', 'backup', 'tagging'],
  },
  {
    checkId: 'rds_cluster_storage_encrypted',
    provider: 'aws',
    service: 'rds',
    title: 'RDS Cluster Not Encrypted',
    severity: 'HIGH',
    description: 'Checks that RDS database clusters have storage encryption at rest enabled.',
    remediation: 'Enable storage encryption at rest for the database cluster.',
    tags: ['rds', 'encryption', 'data-protection'],
  },
  {
    checkId: 'rds_cluster_backup_retention',
    provider: 'aws',
    service: 'rds',
    title: 'Short Cluster Backup Retention',
    severity: 'MEDIUM',
    description: 'Checks that RDS database clusters have an automated backup retention period of at least 7 days.',
    remediation: 'Increase the automated backup retention period to at least 7 days.',
    tags: ['rds', 'backup', 'disaster-recovery'],
  },
  {
    checkId: 'rds_cluster_backtrack_enabled',
    provider: 'aws',
    service: 'rds',
    title: 'Aurora MySQL Backtrack Not Enabled',
    severity: 'LOW',
    description: 'Checks that Aurora MySQL database clusters have Backtrack enabled with a non-zero backtrack window so recent changes can be rewound without a full restore.',
    remediation: 'Enable Backtrack on the Aurora MySQL cluster with a backtrack window that meets your recovery objectives (e.g. 3600 seconds).',
    tags: ['rds', 'backup', 'disaster-recovery'],
  },
  {
    checkId: 'rds_cluster_copy_tags_to_snapshots',
    provider: 'aws',
    service: 'rds',
    title: 'Cluster Copy Tags to Snapshot Not Enabled',
    severity: 'LOW',
    description: 'Checks that RDS database clusters copy tags to their snapshots.',
    remediation: 'Enable copy tags to snapshot on the database cluster so snapshots inherit ownership and lifecycle tags.',
    tags: ['rds', 'backup', 'tagging'],
  },
  {
    checkId: 'rds_cluster_critical_event_subscription',
    provider: 'aws',
    service: 'rds',
    title: 'Cluster Critical Event Subscription Missing',
    severity: 'MEDIUM',
    description: 'Checks that an enabled RDS event subscription for DB clusters covers the maintenance and failure event categories.',
    remediation: 'Create an enabled RDS event subscription with source type db-cluster covering the maintenance and failure event categories, delivered to a monitored SNS topic.',
    tags: ['rds', 'logging', 'monitoring'],
  },
  {
    checkId: 'rds_cluster_default_admin',
    provider: 'aws',
    service: 'rds',
    title: 'Cluster Default Master Username',
    severity: 'MEDIUM',
    description: 'Checks that RDS database clusters do not use a well-known default master username such as admin or postgres.',
    remediation: 'Recreate the cluster with a custom, non-default master username and migrate workloads to it.',
    tags: ['rds', 'identity', 'configuration'],
  },
  {
    checkId: 'rds_cluster_deletion_protection',
    provider: 'aws',
    service: 'rds',
    title: 'Cluster Deletion Protection Not Enabled',
    severity: 'MEDIUM',
    description: 'Checks that RDS database clusters have deletion protection enabled.',
    remediation: 'Enable deletion protection for the database cluster.',
    tags: ['rds', 'data-protection', 'disaster-recovery'],
  },
  {
    checkId: 'rds_cluster_iam_authentication_enabled',
    provider: 'aws',
    service: 'rds',
    title: 'Cluster IAM Authentication Not Enabled',
    severity: 'MEDIUM',
    description: 'Checks that RDS database clusters on supported engines have IAM database authentication enabled.',
    remediation: 'Enable IAM database authentication on the cluster and grant scoped rds-db:connect permissions instead of static database passwords.',
    tags: ['rds', 'identity', 'authentication'],
  },
  {
    checkId: 'rds_cluster_integration_cloudwatch_logs',
    provider: 'aws',
    service: 'rds',
    title: 'Cluster CloudWatch Log Export Not Enabled',
    severity: 'MEDIUM',
    description: 'Checks that RDS database clusters on supported engines export database logs to CloudWatch Logs.',
    remediation: 'Enable at least one supported log export (e.g. error, audit, postgresql) on the cluster so logs ship to CloudWatch Logs.',
    tags: ['rds', 'logging', 'monitoring'],
  },
  {
    checkId: 'rds_cluster_minor_version_upgrade_enabled',
    provider: 'aws',
    service: 'rds',
    title: 'Cluster Auto Minor Version Upgrade Not Enabled',
    severity: 'MEDIUM',
    description: 'Checks that Multi-AZ RDS database clusters have automatic minor version upgrades enabled.',
    remediation: 'Enable auto minor version upgrade on the cluster so security patches are applied during maintenance windows.',
    tags: ['rds', 'patching', 'vulnerability-management'],
  },
  {
    checkId: 'rds_cluster_multi_az',
    provider: 'aws',
    service: 'rds',
    title: 'Cluster Multi-AZ Not Enabled',
    severity: 'MEDIUM',
    description: 'Checks that RDS database clusters are deployed across multiple availability zones.',
    remediation: 'Enable Multi-AZ deployment for the database cluster for high availability.',
    tags: ['rds', 'high-availability', 'disaster-recovery'],
  },
  {
    checkId: 'rds_cluster_non_default_port',
    provider: 'aws',
    service: 'rds',
    title: 'Cluster Default Port In Use',
    severity: 'LOW',
    description: 'Checks that RDS database clusters do not listen on the default port of their database engine.',
    remediation: 'Change the cluster port to a non-default value and update application connection strings and security group rules.',
    tags: ['rds', 'network', 'configuration'],
  },
  {
    checkId: 'rds_cluster_protected_by_backup_plan',
    provider: 'aws',
    service: 'rds',
    title: 'Cluster Not in Backup Plan',
    severity: 'HIGH',
    description: 'Checks that RDS database clusters are protected by an AWS Backup plan.',
    remediation: 'Assign the database cluster to an AWS Backup plan, directly, by tag, or via a resource wildcard selection.',
    tags: ['rds', 'backup', 'disaster-recovery'],
  },
  {
    checkId: 'rds_instance_certificate_expiration',
    provider: 'aws',
    service: 'rds',
    title: 'Database Certificate Expiring',
    severity: 'HIGH',
    description: 'Checks that the CA certificate attached to RDS database instances has more than 3 months of validity remaining.',
    remediation: 'Rotate the instance CA certificate to a current authority (e.g. rds-ca-rsa2048-g1) before it expires and update client trust stores.',
    tags: ['rds', 'encryption', 'certificates'],
  },
  {
    checkId: 'rds_instance_critical_event_subscription',
    provider: 'aws',
    service: 'rds',
    title: 'Instance Critical Event Subscription Missing',
    severity: 'MEDIUM',
    description: 'Checks that an enabled RDS event subscription for DB instances covers the maintenance, configuration change and failure event categories.',
    remediation: 'Create an enabled RDS event subscription with source type db-instance covering the maintenance, configuration change and failure event categories, delivered to a monitored SNS topic.',
    tags: ['rds', 'logging', 'monitoring'],
  },
  {
    checkId: 'rds_instance_default_admin',
    provider: 'aws',
    service: 'rds',
    title: 'Default Master Username',
    severity: 'MEDIUM',
    description: 'Checks that RDS database instances do not use a well-known default master username such as admin or postgres.',
    remediation: 'Recreate the database with a custom, non-default master username and migrate workloads to it.',
    tags: ['rds', 'identity', 'configuration'],
  },
  {
    checkId: 'rds_instance_deprecated_engine_version',
    provider: 'aws',
    service: 'rds',
    title: 'Deprecated Engine Version',
    severity: 'HIGH',
    description: 'Checks that RDS database instances run an engine version that is still available in the region and not deprecated.',
    remediation: 'Upgrade the database instance to a currently supported engine version, testing the upgrade in non-production first.',
    tags: ['rds', 'patching', 'vulnerability-management'],
  },
  {
    checkId: 'rds_instance_enhanced_monitoring_enabled',
    provider: 'aws',
    service: 'rds',
    title: 'Enhanced Monitoring Not Enabled',
    severity: 'LOW',
    description: 'Checks that RDS database instances have enhanced monitoring enabled for OS-level metrics.',
    remediation: 'Enable enhanced monitoring with a non-zero monitoring interval and a monitoring IAM role on the database instance.',
    tags: ['rds', 'logging', 'monitoring'],
  },
  {
    checkId: 'rds_instance_event_subscription_parameter_groups',
    provider: 'aws',
    service: 'rds',
    title: 'Parameter Group Event Subscription Missing',
    severity: 'LOW',
    description: 'Checks that an enabled RDS event subscription for DB parameter groups covers configuration change events.',
    remediation: 'Create an enabled RDS event subscription with source type db-parameter-group covering the configuration change event category, delivered to a monitored SNS topic.',
    tags: ['rds', 'logging', 'monitoring'],
  },
  {
    checkId: 'rds_instance_event_subscription_security_groups',
    provider: 'aws',
    service: 'rds',
    title: 'Security Group Event Subscription Missing',
    severity: 'MEDIUM',
    description: 'Checks that an enabled RDS event subscription for DB security groups covers configuration change and failure events.',
    remediation: 'Create an enabled RDS event subscription with source type db-security-group covering the configuration change and failure event categories, delivered to a monitored SNS topic.',
    tags: ['rds', 'logging', 'monitoring'],
  },
  {
    checkId: 'rds_instance_extended_support',
    provider: 'aws',
    service: 'rds',
    title: 'RDS Extended Support Enrolled',
    severity: 'MEDIUM',
    description: 'Checks that RDS database instances are not enrolled in RDS Extended Support, which incurs additional charges after standard support ends.',
    remediation: 'Upgrade the instance to an engine version under standard support, and disable the engine lifecycle Extended Support option for new instances where that is your policy.',
    tags: ['rds', 'patching', 'cost'],
  },
  {
    checkId: 'rds_instance_iam_authentication_enabled',
    provider: 'aws',
    service: 'rds',
    title: 'IAM Authentication Not Enabled',
    severity: 'MEDIUM',
    description: 'Checks that RDS database instances on supported engines have IAM database authentication enabled.',
    remediation: 'Enable IAM database authentication on the instance (or its cluster) and grant scoped rds-db:connect permissions instead of static database passwords.',
    tags: ['rds', 'identity', 'authentication'],
  },
  {
    checkId: 'rds_instance_inside_vpc',
    provider: 'aws',
    service: 'rds',
    title: 'Database Not in VPC',
    severity: 'HIGH',
    description: 'Checks that RDS database instances are deployed inside a VPC.',
    remediation: 'Move the database instance into a VPC by assigning a DB subnet group, preferably with private subnets across multiple availability zones.',
    tags: ['rds', 'network', 'data-protection'],
  },
  {
    checkId: 'rds_instance_integration_cloudwatch_logs',
    provider: 'aws',
    service: 'rds',
    title: 'CloudWatch Log Export Not Enabled',
    severity: 'MEDIUM',
    description: 'Checks that RDS database instances export database logs to CloudWatch Logs.',
    remediation: 'Enable at least one supported log export (e.g. error, general, slowquery, audit) on the database instance so logs ship to CloudWatch Logs.',
    tags: ['rds', 'logging', 'monitoring'],
  },
  {
    checkId: 'rds_instance_minor_version_upgrade_enabled',
    provider: 'aws',
    service: 'rds',
    title: 'Auto Minor Version Upgrade Not Enabled',
    severity: 'MEDIUM',
    description: 'Checks that RDS database instances have automatic minor version upgrades enabled.',
    remediation: 'Enable auto minor version upgrade on the database instance so security patches are applied during maintenance windows.',
    tags: ['rds', 'patching', 'vulnerability-management'],
  },
  {
    checkId: 'rds_instance_non_default_port',
    provider: 'aws',
    service: 'rds',
    title: 'Default Port In Use',
    severity: 'LOW',
    description: 'Checks that RDS database instances do not listen on the default port of their database engine.',
    remediation: 'Change the instance port to a non-default value and update application connection strings and security group rules.',
    tags: ['rds', 'network', 'configuration'],
  },
  {
    checkId: 'rds_instance_protected_by_backup_plan',
    provider: 'aws',
    service: 'rds',
    title: 'Database Not in Backup Plan',
    severity: 'HIGH',
    description: 'Checks that non-Aurora RDS database instances are protected by an AWS Backup plan.',
    remediation: 'Assign the database instance to an AWS Backup plan, directly, by tag, or via a resource wildcard selection.',
    tags: ['rds', 'backup', 'disaster-recovery'],
  },
  {
    checkId: 'rds_instance_transport_encrypted',
    provider: 'aws',
    service: 'rds',
    title: 'Transport Encryption Not Enforced',
    severity: 'HIGH',
    description: 'Checks that RDS database instances and clusters enforce SSL/TLS for client connections via the rds.force_ssl or require_secure_transport parameters.',
    remediation: 'Set rds.force_ssl=1 (PostgreSQL/SQL Server) or require_secure_transport=1/ON (MySQL/MariaDB) in the attached parameter group and reboot if the parameter is static.',
    tags: ['rds', 'encryption', 'network'],
  },
  {
    checkId: 'rds_snapshots_encrypted',
    provider: 'aws',
    service: 'rds',
    title: 'Snapshot Not Encrypted',
    severity: 'HIGH',
    description: 'Checks that RDS database and cluster snapshots are encrypted at rest.',
    remediation: 'Copy the unencrypted snapshot with a KMS key to create an encrypted copy, then delete the unencrypted original.',
    tags: ['rds', 'encryption', 'backup'],
  },
  {
    checkId: 'rds_snapshots_public_access',
    provider: 'aws',
    service: 'rds',
    title: 'Public Database Snapshot',
    severity: 'CRITICAL',
    description: 'Checks that RDS database and cluster snapshots are not publicly shared with all AWS accounts.',
    remediation: 'Remove the "all" value from the snapshot restore attribute so it is no longer public, and share only with specific account IDs if needed.',
    tags: ['rds', 'public-access', 'data-protection'],
  },
];
