// Check logic derived from Prowler (Apache-2.0, https://github.com/prowler-cloud/prowler)
import { CheckMetadata } from '../../types';

// Titles must stay byte-identical to the pre-registry hardcoded titles:
// the scan worker dedupes OPEN findings on service:title:fingerprint, so a
// reworded title would re-open every existing finding as "new".
export const redshiftChecks: CheckMetadata[] = [
  {
    checkId: 'redshift_cluster_public_access',
    provider: 'aws',
    service: 'redshift',
    title: 'Redshift Cluster Publicly Accessible',
    severity: 'CRITICAL',
    description: 'Checks that Redshift clusters are not configured as publicly accessible; a public endpoint can be reached from the internet, exposing it to brute force and vulnerability exploits.',
    remediation: 'Disable public accessibility: aws redshift modify-cluster --cluster-identifier <cluster-id> --no-publicly-accessible. Access the cluster via a VPC bastion or VPN only.',
    tags: ['redshift', 'network', 'public-access'],
  },
  {
    checkId: 'redshift_cluster_encrypted_at_rest',
    provider: 'aws',
    service: 'redshift',
    title: 'Redshift Cluster Not Encrypted',
    severity: 'HIGH',
    description: 'Checks that Redshift clusters have encryption at rest enabled so data stored on cluster nodes, backups, and snapshots is encrypted.',
    remediation: 'Enable encryption by restoring the cluster from a snapshot with encryption enabled, or create a new encrypted cluster and migrate data.',
    tags: ['redshift', 'encryption'],
  },
  {
    checkId: 'redshift_cluster_audit_logging',
    provider: 'aws',
    service: 'redshift',
    title: 'Redshift Cluster Audit Logging Disabled',
    severity: 'HIGH',
    description: 'Checks that Redshift clusters have audit logging enabled so connection attempts, user activity, and queries are logged for security review.',
    remediation: 'Enable audit logging: aws redshift enable-logging --cluster-identifier <cluster-id> --bucket-name <s3-bucket> --s3-key-prefix redshift-logs/',
    tags: ['redshift', 'logging', 'audit'],
  },
  {
    checkId: 'redshift_cluster_non_default_username',
    provider: 'aws',
    service: 'redshift',
    title: 'Redshift Cluster Uses Default Admin Username',
    severity: 'MEDIUM',
    description: 'Checks that Redshift clusters do not use well-known default admin usernames (awsuser, admin, master, redshift, root), which make brute force attacks easier.',
    remediation: 'Create a new admin user with a non-default username, grant necessary permissions, then remove the default admin user.',
    tags: ['redshift', 'authentication'],
  },
  {
    checkId: 'redshift_cluster_in_vpc',
    provider: 'aws',
    service: 'redshift',
    title: 'Redshift Cluster Not in VPC',
    severity: 'HIGH',
    description: 'Checks that Redshift clusters run inside a VPC; clusters outside VPC lack network isolation and cannot use VPC security groups or endpoints.',
    remediation: 'Migrate the cluster to a VPC. Create a new cluster in a VPC subnet group and restore from snapshot.',
    tags: ['redshift', 'network'],
  },
  {
    checkId: 'redshift_cluster_automated_snapshot',
    provider: 'aws',
    service: 'redshift',
    title: 'Redshift Cluster Automated Snapshots Disabled',
    severity: 'HIGH',
    description: 'Checks that Redshift clusters have automated snapshot retention enabled so data can be recovered from automated backups after accidental deletion or corruption.',
    remediation: 'Enable automated snapshots: aws redshift modify-cluster --cluster-identifier <cluster-id> --automated-snapshot-retention-period 7',
    tags: ['redshift', 'backup'],
  },
  {
    checkId: 'redshift_cluster_enhanced_vpc_routing',
    provider: 'aws',
    service: 'redshift',
    title: 'Redshift Cluster Enhanced VPC Routing Disabled',
    severity: 'MEDIUM',
    description: 'Checks that Redshift clusters have Enhanced VPC Routing enabled so COPY and UNLOAD traffic stays within the VPC instead of traveling over the internet.',
    remediation: 'Enable enhanced VPC routing: aws redshift modify-cluster --cluster-identifier <cluster-id> --enhanced-vpc-routing',
    tags: ['redshift', 'network'],
  },
  {
    checkId: 'redshift_cluster_automatic_upgrades',
    provider: 'aws',
    service: 'redshift',
    title: 'Redshift Cluster Version Upgrades Disabled',
    severity: 'MEDIUM',
    description: 'Checks that Redshift clusters allow automatic version upgrades so engine patches are applied during the maintenance window instead of leaving clusters on vulnerable versions.',
    remediation: 'Enable version upgrades: aws redshift modify-cluster --cluster-identifier <cluster-id> --allow-version-upgrade',
    tags: ['redshift', 'patching'],
  },
  {
    checkId: 'redshift_cluster_in_transit_encryption_enabled',
    provider: 'aws',
    service: 'redshift',
    title: 'Redshift Cluster In-Transit Encryption Disabled',
    severity: 'HIGH',
    description: 'Checks that Redshift clusters require TLS for client connections via the require_ssl parameter in the cluster parameter group.',
    remediation: 'Set require_ssl to true: aws redshift modify-cluster-parameter-group --parameter-group-name <group> --parameters ParameterName=require_ssl,ParameterValue=true, then reboot the cluster to apply.',
    tags: ['redshift', 'encryption', 'in-transit'],
  },
  {
    checkId: 'redshift_cluster_multi_az_enabled',
    provider: 'aws',
    service: 'redshift',
    title: 'Redshift Cluster Multi-AZ Disabled',
    severity: 'MEDIUM',
    description: 'Checks that provisioned Redshift clusters have Multi-AZ enabled so compute spans two Availability Zones and survives an AZ failure.',
    remediation: 'Enable Multi-AZ: aws redshift modify-cluster --cluster-identifier <cluster-id> --multi-az (supported on provisioned RA3 clusters).',
    tags: ['redshift', 'availability', 'resilience'],
  },
  {
    checkId: 'redshift_cluster_non_default_database_name',
    provider: 'aws',
    service: 'redshift',
    title: 'Redshift Cluster Uses Default Database Name',
    severity: 'LOW',
    description: 'Checks that Redshift clusters do not use the default database name "dev", which is predictable and aids enumeration and mis-scoped policies.',
    remediation: 'Create a new cluster with a non-default database name, migrate workloads, and retire the cluster using the default "dev" database name.',
    tags: ['redshift', 'configuration'],
  },
];
