// Check logic derived from Prowler (Apache-2.0, https://github.com/prowler-cloud/prowler)
import { CheckMetadata } from '../../types';

// Titles must stay byte-identical to the pre-registry hardcoded titles:
// the scan worker dedupes OPEN findings on service:title:fingerprint, so a
// reworded title would re-open every existing finding as "new".
export const s3Checks: CheckMetadata[] = [
  {
    checkId: 's3_bucket_default_encryption',
    provider: 'aws',
    service: 's3',
    title: 'S3 Bucket Not Encrypted',
    severity: 'HIGH',
    description: 'Checks that S3 buckets have default server-side encryption enabled.',
    remediation: 'Enable SSE-S3 or SSE-KMS default encryption on the bucket.',
    tags: ['s3', 'encryption'],
    compliance: {
      cis_2_0_aws: ['2.1.1'],
      nist_800_53_r5: ['SC-28'],
    },
  },
  {
    checkId: 's3_bucket_kms_encryption',
    provider: 'aws',
    service: 's3',
    title: 'Using SSE-S3 Instead of KMS',
    severity: 'MEDIUM',
    description: 'Checks that S3 buckets use KMS (SSE-KMS) rather than SSE-S3 for default encryption, for stronger key management.',
    remediation: 'Configure the bucket default encryption to use aws:kms with a customer-managed key.',
    tags: ['s3', 'encryption', 'kms'],
  },
  {
    checkId: 's3_bucket_object_versioning',
    provider: 'aws',
    service: 's3',
    title: 'S3 Versioning Not Enabled',
    severity: 'MEDIUM',
    description: 'Checks that S3 buckets have object versioning enabled to protect against accidental deletion and overwrite.',
    remediation: 'Enable versioning on the bucket.',
    tags: ['s3', 'versioning', 'data-protection'],
  },
  {
    checkId: 's3_bucket_level_public_access_block',
    provider: 'aws',
    service: 's3',
    title: 'Public Access Not Fully Blocked',
    severity: 'CRITICAL',
    description: 'Checks that all four S3 Block Public Access settings are enabled at the bucket level.',
    remediation: 'Enable BlockPublicAcls, BlockPublicPolicy, IgnorePublicAcls and RestrictPublicBuckets on the bucket.',
    tags: ['s3', 'public-access', 'security'],
    compliance: {
      cis_2_0_aws: ['2.1.4'],
      nist_800_53_r5: ['AC-3', 'AC-6'],
    },
  },
  {
    checkId: 's3_bucket_public_access',
    provider: 'aws',
    service: 's3',
    title: 'Bucket Has Public ACL Grants',
    severity: 'CRITICAL',
    description: 'Checks S3 bucket ACLs for grants to AllUsers or AuthenticatedUsers, which allow unauthenticated or any-AWS-account access.',
    remediation: 'Remove public ACL grants from the bucket and prefer bucket policies with explicit principals.',
    tags: ['s3', 'acl', 'public-access'],
    compliance: {
      cis_2_0_aws: ['2.1.4'],
    },
  },
  {
    checkId: 's3_bucket_server_access_logging_enabled',
    provider: 'aws',
    service: 's3',
    title: 'S3 Access Logging Not Enabled',
    severity: 'MEDIUM',
    description: 'Checks that S3 buckets have server access logging enabled so all requests are auditable.',
    remediation: 'Enable server access logging on the bucket, targeting a dedicated logging bucket.',
    tags: ['s3', 'logging', 'audit'],
  },
  {
    checkId: 's3_bucket_no_mfa_delete',
    provider: 'aws',
    service: 's3',
    title: 'S3 MFA Delete Not Enabled',
    severity: 'MEDIUM',
    description: 'Checks that versioned S3 buckets have MFA Delete enabled so versions cannot be permanently deleted without MFA.',
    remediation: 'Enable MFA Delete on the bucket using root credentials: aws s3api put-bucket-versioning --versioning-configuration MFADelete=Enabled,Status=Enabled --mfa "<mfa-device-arn> <totp>".',
    tags: ['s3', 'mfa-delete', 'versioning', 'cis-2.1.2'],
    compliance: {
      cis_2_0_aws: ['2.1.2'],
    },
  },
  {
    checkId: 's3_bucket_secure_transport_policy',
    provider: 'aws',
    service: 's3',
    title: 'S3 HTTPS Not Enforced',
    severity: 'MEDIUM',
    description: 'Checks that the bucket policy denies plain-HTTP requests via the aws:SecureTransport condition, enforcing encryption in transit.',
    remediation: 'Add a bucket policy Deny statement with Condition { "Bool": { "aws:SecureTransport": "false" } }.',
    tags: ['s3', 'https', 'encryption-in-transit', 'cis-2.1.1'],
    compliance: {
      cis_2_0_aws: ['2.1.1'],
      nist_800_53_r5: ['SC-8'],
    },
  },
  {
    checkId: 's3_access_point_public_access_block',
    provider: 'aws',
    service: 's3',
    title: 'Access Point Public Access Not Blocked',
    severity: 'CRITICAL',
    description: 'Checks that S3 access points have all four Block Public Access settings enabled so ACLs and policies cannot expose objects through the access point.',
    remediation: 'Recreate the access point with BlockPublicAcls, IgnorePublicAcls, BlockPublicPolicy and RestrictPublicBuckets enabled; the settings cannot be changed after creation.',
    tags: ['s3', 'access-point', 'public-access'],
  },
  {
    checkId: 's3_account_level_public_access_blocks',
    provider: 'aws',
    service: 's3',
    title: 'Account-Level Public Access Not Blocked',
    severity: 'HIGH',
    description: 'Checks that account-level S3 Block Public Access has IgnorePublicAcls and RestrictPublicBuckets enabled to centrally neutralize public ACLs and public bucket policies.',
    remediation: 'Enable account-level Block Public Access: aws s3control put-public-access-block --account-id <account-id> --public-access-block-configuration BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true.',
    tags: ['s3', 'public-access', 'account'],
  },
  {
    checkId: 's3_bucket_acl_prohibited',
    provider: 'aws',
    service: 's3',
    title: 'Bucket ACLs Not Disabled',
    severity: 'MEDIUM',
    description: 'Checks that buckets set Object Ownership to BucketOwnerEnforced, which disables bucket and object ACLs in favor of centralized policy-based access control.',
    remediation: 'Set Object Ownership to BucketOwnerEnforced on the bucket after migrating any ACL-based grants into bucket policies.',
    tags: ['s3', 'acl', 'object-ownership'],
  },
  {
    checkId: 's3_bucket_cross_account_access',
    provider: 'aws',
    service: 's3',
    title: 'Bucket Policy Allows Cross-Account Access',
    severity: 'HIGH',
    description: 'Checks bucket policies for Allow statements granting access to principals outside the bucket owner account (other account IDs or a wildcard principal) without restrictive conditions.',
    remediation: 'Limit the bucket policy Principal to the owning account or explicitly trusted accounts, and scope any external access with conditions such as aws:PrincipalOrgID.',
    tags: ['s3', 'policy', 'cross-account'],
  },
  {
    checkId: 's3_bucket_cross_region_replication',
    provider: 'aws',
    service: 's3',
    title: 'Cross-Region Replication Not Configured',
    severity: 'LOW',
    description: 'Checks that versioned buckets have an enabled replication rule targeting a bucket in a different AWS region for resilience against regional outages.',
    remediation: 'Enable versioning and add an enabled replication rule whose destination bucket is in a different region, using a least-privilege replication role.',
    tags: ['s3', 'replication', 'resilience'],
  },
  {
    checkId: 's3_bucket_event_notifications_enabled',
    provider: 'aws',
    service: 's3',
    title: 'Event Notifications Not Enabled',
    severity: 'LOW',
    description: 'Checks that buckets have an event notification configuration (SNS, SQS, Lambda or EventBridge) so object and bucket changes are observable.',
    remediation: 'Configure event notifications on the bucket, e.g. enable EventBridge delivery: aws s3api put-bucket-notification-configuration --bucket <bucket> --notification-configuration \'{"EventBridgeConfiguration": {}}\'.',
    tags: ['s3', 'notifications', 'monitoring'],
  },
  {
    checkId: 's3_bucket_lifecycle_enabled',
    provider: 'aws',
    service: 's3',
    title: 'Lifecycle Configuration Not Enabled',
    severity: 'LOW',
    description: 'Checks that buckets have at least one enabled lifecycle rule to automate object expiration and transitions, controlling cost and data retention.',
    remediation: 'Add an enabled lifecycle rule to the bucket, e.g. abort incomplete multipart uploads after 7 days and expire or transition aged objects per data classification.',
    tags: ['s3', 'lifecycle', 'data-retention'],
  },
  {
    checkId: 's3_bucket_object_lock',
    provider: 'aws',
    service: 's3',
    title: 'Object Lock Not Enabled',
    severity: 'LOW',
    description: 'Checks that buckets have Object Lock enabled so object versions are protected by WORM retention against deletion and tampering.',
    remediation: 'Enable Object Lock on the bucket with a default retention (GOVERNANCE or COMPLIANCE mode); versioning is required and existing buckets may need Object Lock enabled via support or recreation.',
    tags: ['s3', 'object-lock', 'data-protection'],
  },
  {
    checkId: 's3_bucket_object_public',
    provider: 'aws',
    service: 's3',
    title: 'Public Objects Detected in Bucket',
    severity: 'LOW',
    description: 'Spot-checks a small, deterministic sample of objects per bucket and flags any whose ACL grants access to AllUsers or AuthenticatedUsers; a pass does not guarantee no public objects outside the sample.',
    remediation: 'Make the flagged objects private (aws s3api put-object-acl --key <key> --acl private) and set Object Ownership to BucketOwnerEnforced to prevent public object ACLs entirely.',
    tags: ['s3', 'acl', 'public-access', 'objects'],
  },
  {
    checkId: 's3_bucket_policy_public_write_access',
    provider: 'aws',
    service: 's3',
    title: 'Bucket Policy Allows Public Write',
    severity: 'CRITICAL',
    description: 'Checks bucket policies for statements granting write actions (s3:PutObject, s3:DeleteObject or wildcards) to all principals when RestrictPublicBuckets is not enforced at the account or bucket level.',
    remediation: 'Remove public write statements from the bucket policy and enable RestrictPublicBuckets in the bucket Block Public Access settings.',
    tags: ['s3', 'policy', 'public-access'],
  },
  {
    checkId: 's3_bucket_public_list_acl',
    provider: 'aws',
    service: 's3',
    title: 'Bucket Publicly Listable via ACL',
    severity: 'CRITICAL',
    description: 'Checks bucket ACLs for READ, READ_ACP or FULL_CONTROL grants to AllUsers or AuthenticatedUsers when Block Public Access does not neutralize public ACLs at the account or bucket level.',
    remediation: 'Remove the public ACL grant and enable IgnorePublicAcls and RestrictPublicBuckets on the bucket or account Block Public Access settings.',
    tags: ['s3', 'acl', 'public-access'],
  },
  {
    checkId: 's3_bucket_public_write_acl',
    provider: 'aws',
    service: 's3',
    title: 'Bucket Publicly Writable via ACL',
    severity: 'CRITICAL',
    description: 'Checks bucket ACLs for WRITE, WRITE_ACP or FULL_CONTROL grants to AllUsers or AuthenticatedUsers when Block Public Access does not neutralize public ACLs at the account or bucket level.',
    remediation: 'Remove the public ACL grant (aws s3api put-bucket-acl --acl private) and enable IgnorePublicAcls and RestrictPublicBuckets on the bucket or account Block Public Access settings.',
    tags: ['s3', 'acl', 'public-access'],
  },
  {
    checkId: 's3_bucket_shadow_resource_vulnerability',
    provider: 'aws',
    service: 's3',
    title: 'Shadow Resource Bucket Detected',
    severity: 'HIGH',
    description: 'Checks predictable AWS service bucket names (Glue, SageMaker, EMR, CodeStar) tied to this account for buckets pre-claimed or owned by another account (Bucket Monopoly attack).',
    remediation: 'Pre-claim the predictable service bucket names in every region you use so they are owned by your account, and avoid relying on service default bucket names where possible.',
    tags: ['s3', 'shadow-resource', 'trust-boundaries'],
  },
  {
    checkId: 's3_multi_region_access_point_public_access_block',
    provider: 'aws',
    service: 's3',
    title: 'Multi-Region Access Point Public Access Not Blocked',
    severity: 'HIGH',
    description: 'Checks that S3 Multi-Region Access Points have all four Block Public Access settings enabled so the global endpoint cannot expose the linked buckets.',
    remediation: 'Recreate the Multi-Region Access Point with all Block Public Access settings enabled; MRAP public access settings are immutable after creation.',
    tags: ['s3', 'access-point', 'public-access', 'multi-region'],
  },
];
