import { CheckMetadata } from '../../types';

// Titles must stay byte-identical to the pre-registry hardcoded titles:
// the scan worker dedupes OPEN findings on service:title:fingerprint, so a
// reworded title would re-open every existing finding as "new".
export const s3Checks: CheckMetadata[] = [
  {
    checkId: 's3_bucket_default_encryption',
    provider: 'aws',
    service: 's3',
    title: 'S3 Bucket Not Encrypted',
    severity: 'HIGH',
    description: 'Checks that S3 buckets have default server-side encryption enabled.',
    remediation: 'Enable SSE-S3 or SSE-KMS default encryption on the bucket.',
    tags: ['s3', 'encryption'],
    compliance: {
      cis_2_0_aws: ['2.1.1'],
      nist_800_53_r5: ['SC-28'],
    },
  },
  {
    checkId: 's3_bucket_kms_encryption',
    provider: 'aws',
    service: 's3',
    title: 'Using SSE-S3 Instead of KMS',
    severity: 'MEDIUM',
    description: 'Checks that S3 buckets use KMS (SSE-KMS) rather than SSE-S3 for default encryption, for stronger key management.',
    remediation: 'Configure the bucket default encryption to use aws:kms with a customer-managed key.',
    tags: ['s3', 'encryption', 'kms'],
  },
  {
    checkId: 's3_bucket_object_versioning',
    provider: 'aws',
    service: 's3',
    title: 'S3 Versioning Not Enabled',
    severity: 'MEDIUM',
    description: 'Checks that S3 buckets have object versioning enabled to protect against accidental deletion and overwrite.',
    remediation: 'Enable versioning on the bucket.',
    tags: ['s3', 'versioning', 'data-protection'],
  },
  {
    checkId: 's3_bucket_level_public_access_block',
    provider: 'aws',
    service: 's3',
    title: 'Public Access Not Fully Blocked',
    severity: 'CRITICAL',
    description: 'Checks that all four S3 Block Public Access settings are enabled at the bucket level.',
    remediation: 'Enable BlockPublicAcls, BlockPublicPolicy, IgnorePublicAcls and RestrictPublicBuckets on the bucket.',
    tags: ['s3', 'public-access', 'security'],
    compliance: {
      cis_2_0_aws: ['2.1.4'],
      nist_800_53_r5: ['AC-3', 'AC-6'],
    },
  },
  {
    checkId: 's3_bucket_public_access',
    provider: 'aws',
    service: 's3',
    title: 'Bucket Has Public ACL Grants',
    severity: 'CRITICAL',
    description: 'Checks S3 bucket ACLs for grants to AllUsers or AuthenticatedUsers, which allow unauthenticated or any-AWS-account access.',
    remediation: 'Remove public ACL grants from the bucket and prefer bucket policies with explicit principals.',
    tags: ['s3', 'acl', 'public-access'],
    compliance: {
      cis_2_0_aws: ['2.1.4'],
    },
  },
  {
    checkId: 's3_bucket_server_access_logging_enabled',
    provider: 'aws',
    service: 's3',
    title: 'S3 Access Logging Not Enabled',
    severity: 'MEDIUM',
    description: 'Checks that S3 buckets have server access logging enabled so all requests are auditable.',
    remediation: 'Enable server access logging on the bucket, targeting a dedicated logging bucket.',
    tags: ['s3', 'logging', 'audit'],
  },
  {
    checkId: 's3_bucket_no_mfa_delete',
    provider: 'aws',
    service: 's3',
    title: 'S3 MFA Delete Not Enabled',
    severity: 'MEDIUM',
    description: 'Checks that versioned S3 buckets have MFA Delete enabled so versions cannot be permanently deleted without MFA.',
    remediation: 'Enable MFA Delete on the bucket using root credentials: aws s3api put-bucket-versioning --versioning-configuration MFADelete=Enabled,Status=Enabled --mfa "<mfa-device-arn> <totp>".',
    tags: ['s3', 'mfa-delete', 'versioning', 'cis-2.1.2'],
    compliance: {
      cis_2_0_aws: ['2.1.2'],
    },
  },
  {
    checkId: 's3_bucket_secure_transport_policy',
    provider: 'aws',
    service: 's3',
    title: 'S3 HTTPS Not Enforced',
    severity: 'MEDIUM',
    description: 'Checks that the bucket policy denies plain-HTTP requests via the aws:SecureTransport condition, enforcing encryption in transit.',
    remediation: 'Add a bucket policy Deny statement with Condition { "Bool": { "aws:SecureTransport": "false" } }.',
    tags: ['s3', 'https', 'encryption-in-transit', 'cis-2.1.1'],
    compliance: {
      cis_2_0_aws: ['2.1.1'],
      nist_800_53_r5: ['SC-8'],
    },
  },
];
