// Check logic derived from Prowler (Apache-2.0, https://github.com/prowler-cloud/prowler)
import { CheckMetadata } from '../../types';

export const sagemakerChecks: CheckMetadata[] = [
  {
    checkId: 'sagemaker_notebook_instance_encryption_enabled',
    provider: 'aws',
    service: 'sagemaker',
    title: 'SageMaker Notebook Storage Not KMS Encrypted',
    severity: 'HIGH',
    description: 'Checks that SageMaker notebook instances encrypt their attached storage volumes with a KMS key so notebooks, datasets and cached credentials are protected at rest.',
    remediation: 'Recreate the notebook instance with a KMS key specified (KmsKeyId); existing instances cannot be encrypted in place. Prefer a customer-managed key with a least-privilege key policy.',
    tags: ['sagemaker', 'encryption', 'kms', 'notebook'],
  },
  {
    checkId: 'sagemaker_notebook_instance_root_access_disabled',
    provider: 'aws',
    service: 'sagemaker',
    title: 'SageMaker Notebook Root Access Enabled',
    severity: 'MEDIUM',
    description: 'Checks that SageMaker notebook instances have root access disabled so notebook users cannot escalate to root and tamper with the underlying instance.',
    remediation: 'Update the notebook instance with RootAccess=Disabled (the instance must be stopped first) so users operate without root privileges.',
    tags: ['sagemaker', 'notebook', 'least-privilege'],
  },
  {
    checkId: 'sagemaker_notebook_instance_vpc_settings_configured',
    provider: 'aws',
    service: 'sagemaker',
    title: 'SageMaker Notebook Not Deployed in a VPC',
    severity: 'HIGH',
    description: 'Checks that SageMaker notebook instances are launched into a VPC subnet so network access is governed by security groups and VPC controls.',
    remediation: 'Recreate the notebook instance with a subnet and security groups in your VPC; connectivity settings cannot be changed on an existing instance.',
    tags: ['sagemaker', 'notebook', 'network', 'vpc'],
  },
  {
    checkId: 'sagemaker_notebook_instance_without_direct_internet_access_configured',
    provider: 'aws',
    service: 'sagemaker',
    title: 'SageMaker Notebook Direct Internet Access Enabled',
    severity: 'HIGH',
    description: 'Checks that SageMaker notebook instances have direct internet access disabled so all traffic flows through the VPC (NAT, proxy or VPC endpoints) instead of a SageMaker-managed internet path.',
    remediation: 'Recreate the notebook instance with DirectInternetAccess=Disabled and a VPC subnet; provide outbound access, if needed, via NAT gateway or interface VPC endpoints.',
    tags: ['sagemaker', 'notebook', 'network', 'internet-exposure'],
  },
  {
    checkId: 'sagemaker_notebook_instance_no_secrets',
    provider: 'aws',
    service: 'sagemaker',
    title: 'SageMaker Notebook Lifecycle Script Contains Secrets',
    severity: 'HIGH',
    description: 'Checks the OnCreate and OnStart lifecycle configuration scripts of SageMaker notebook instances for hardcoded secrets such as AWS keys, passwords, tokens and private keys.',
    remediation: 'Remove hardcoded credentials from lifecycle configuration scripts, rotate any exposed secrets, and retrieve secrets at runtime from AWS Secrets Manager or SSM Parameter Store via the instance IAM role.',
    tags: ['sagemaker', 'notebook', 'secrets', 'credentials'],
  },
  {
    checkId: 'sagemaker_models_network_isolation_enabled',
    provider: 'aws',
    service: 'sagemaker',
    title: 'SageMaker Model Network Isolation Disabled',
    severity: 'HIGH',
    description: 'Checks that SageMaker models have network isolation enabled so model containers cannot make outbound network calls, including to external endpoints.',
    remediation: 'Recreate the model with EnableNetworkIsolation=true so inference containers run without network access; combine with a VPC configuration for controlled data access.',
    tags: ['sagemaker', 'model', 'network', 'isolation'],
  },
  {
    checkId: 'sagemaker_models_vpc_settings_configured',
    provider: 'aws',
    service: 'sagemaker',
    title: 'SageMaker Model Without VPC Configuration',
    severity: 'MEDIUM',
    description: 'Checks that SageMaker models are configured with VPC subnets so model containers communicate through your VPC under security group control.',
    remediation: 'Recreate the model with a VpcConfig (subnets and security groups) so its containers run inside your VPC instead of the SageMaker shared network.',
    tags: ['sagemaker', 'model', 'network', 'vpc'],
  },
  {
    checkId: 'sagemaker_training_jobs_intercontainer_encryption_enabled',
    provider: 'aws',
    service: 'sagemaker',
    title: 'SageMaker Training Job Inter-Container Traffic Unencrypted',
    severity: 'MEDIUM',
    description: 'Checks that SageMaker training jobs enable inter-container traffic encryption so data exchanged between distributed training nodes is protected in transit.',
    remediation: 'Launch training jobs with EnableInterContainerTrafficEncryption=true; note this can increase training time for distributed deep learning jobs.',
    tags: ['sagemaker', 'training', 'encryption', 'in-transit'],
  },
  {
    checkId: 'sagemaker_training_jobs_network_isolation_enabled',
    provider: 'aws',
    service: 'sagemaker',
    title: 'SageMaker Training Job Network Isolation Disabled',
    severity: 'HIGH',
    description: 'Checks that SageMaker training jobs run with network isolation enabled so training containers cannot make outbound network calls and exfiltrate training data.',
    remediation: 'Launch training jobs with EnableNetworkIsolation=true so containers are cut off from the network; SageMaker still handles S3 data staging outside the container.',
    tags: ['sagemaker', 'training', 'network', 'isolation'],
  },
  {
    checkId: 'sagemaker_training_jobs_volume_and_output_encryption_enabled',
    provider: 'aws',
    service: 'sagemaker',
    title: 'SageMaker Training Job Volume Not KMS Encrypted',
    severity: 'HIGH',
    description: 'Checks that SageMaker training jobs specify a KMS key for the attached ML storage volume so training data and artifacts on the volume are encrypted at rest.',
    remediation: 'Launch training jobs with ResourceConfig.VolumeKmsKeyId set to a KMS key (prefer a customer-managed key) so storage volumes and outputs are encrypted.',
    tags: ['sagemaker', 'training', 'encryption', 'kms'],
  },
  {
    checkId: 'sagemaker_training_jobs_vpc_settings_configured',
    provider: 'aws',
    service: 'sagemaker',
    title: 'SageMaker Training Job Without VPC Configuration',
    severity: 'HIGH',
    description: 'Checks that SageMaker training jobs are configured with VPC subnets so training traffic flows through your VPC under security group control.',
    remediation: 'Launch training jobs with a VpcConfig (subnets and security groups), using S3 VPC endpoints for data access so traffic stays on the AWS network.',
    tags: ['sagemaker', 'training', 'network', 'vpc'],
  },
  {
    checkId: 'sagemaker_domain_sso_configured',
    provider: 'aws',
    service: 'sagemaker',
    title: 'SageMaker Domain Not Using SSO Authentication',
    severity: 'MEDIUM',
    description: 'Checks that SageMaker domains use IAM Identity Center (SSO) authentication associated with an Identity Center instance instead of IAM mode, providing centralized identity and session management.',
    remediation: 'Create the domain with AuthMode=SSO and associate it with an IAM Identity Center instance; auth mode cannot be changed on an existing domain, so plan a migration for IAM-mode domains.',
    tags: ['sagemaker', 'domain', 'sso', 'identity'],
  },
  {
    checkId: 'sagemaker_endpoint_config_prod_variant_instances',
    provider: 'aws',
    service: 'sagemaker',
    title: 'SageMaker Endpoint Variant Running a Single Instance',
    severity: 'MEDIUM',
    description: 'Checks that every production variant of a SageMaker endpoint configuration has at least two initial instances so inference endpoints remain available across Availability Zones.',
    remediation: 'Update the endpoint configuration so each production variant has InitialInstanceCount of at least 2; SageMaker then spreads instances across Availability Zones for resilience.',
    tags: ['sagemaker', 'endpoint', 'availability', 'resilience'],
  },
];
