// Check logic derived from Prowler (Apache-2.0, https://github.com/prowler-cloud/prowler)
import { CheckMetadata } from '../../types';

export const sesChecks: CheckMetadata[] = [
  {
    checkId: 'ses_identity_dkim_enabled',
    provider: 'aws',
    service: 'ses',
    title: 'SES Identity DKIM Signing Not Enabled',
    severity: 'MEDIUM',
    description: 'Checks that SES email identities have DKIM signing enabled and successfully verified so receiving mail servers can validate that messages were authorized by the domain owner.',
    remediation: 'Enable DKIM signing for the identity and complete verification by publishing the DKIM CNAME/TXT records generated by SES in DNS; monitor for verification failures.',
    tags: ['ses', 'dkim', 'email-authentication'],
  },
  {
    checkId: 'ses_identity_not_publicly_accessible',
    provider: 'aws',
    service: 'ses',
    title: 'SES Identity Policy Allows Public Access',
    severity: 'HIGH',
    description: 'Checks that SES identity authorization policies do not grant access to all principals, which would let any AWS account send email as the identity.',
    remediation: 'Rewrite the identity authorization policy to name specific trusted principals or add restrictive conditions (aws:SourceAccount, aws:PrincipalOrgID); remove Principal "*" grants.',
    tags: ['ses', 'public-access', 'resource-policy'],
  },
];
