// Check logic derived from Prowler (Apache-2.0, https://github.com/prowler-cloud/prowler)
import { CheckMetadata } from '../../types';

export const shieldChecks: CheckMetadata[] = [
  {
    checkId: 'shield_advanced_protection_in_associated_elastic_ips',
    provider: 'aws',
    service: 'shield',
    title: 'Elastic IP Without Shield Advanced Protection',
    severity: 'MEDIUM',
    description: 'Checks that Elastic IP addresses in accounts subscribed to AWS Shield Advanced are registered as Shield-protected resources against DDoS attacks.',
    remediation: 'Add the Elastic IP allocation as a protected resource in AWS Shield Advanced so network- and transport-layer DDoS mitigations and cost protection apply to it.',
    tags: ['shield', 'ddos', 'elastic-ip', 'resilience'],
  },
  {
    checkId: 'shield_advanced_protection_in_classic_load_balancers',
    provider: 'aws',
    service: 'shield',
    title: 'Classic Load Balancer Without Shield Advanced Protection',
    severity: 'MEDIUM',
    description: 'Checks that Classic Load Balancers in accounts subscribed to AWS Shield Advanced are registered as Shield-protected resources against DDoS attacks.',
    remediation: 'Add the Classic Load Balancer as a protected resource in AWS Shield Advanced, or migrate to an Application Load Balancer and protect that instead.',
    tags: ['shield', 'ddos', 'elb', 'resilience'],
  },
  {
    checkId: 'shield_advanced_protection_in_cloudfront_distributions',
    provider: 'aws',
    service: 'shield',
    title: 'CloudFront Distribution Without Shield Advanced Protection',
    severity: 'MEDIUM',
    description: 'Checks that CloudFront distributions in accounts subscribed to AWS Shield Advanced are registered as Shield-protected resources against DDoS attacks.',
    remediation: 'Add the CloudFront distribution as a protected resource in AWS Shield Advanced and associate an AWS WAF web ACL to enable layer-7 DDoS mitigation.',
    tags: ['shield', 'ddos', 'cloudfront', 'resilience'],
  },
  {
    checkId: 'shield_advanced_protection_in_global_accelerators',
    provider: 'aws',
    service: 'shield',
    title: 'Global Accelerator Without Shield Advanced Protection',
    severity: 'MEDIUM',
    description: 'Checks that Global Accelerator accelerators in accounts subscribed to AWS Shield Advanced are registered as Shield-protected resources against DDoS attacks.',
    remediation: 'Add the Global Accelerator accelerator as a protected resource in AWS Shield Advanced so its anycast entry points receive advanced DDoS mitigation.',
    tags: ['shield', 'ddos', 'global-accelerator', 'resilience'],
  },
  {
    checkId: 'shield_advanced_protection_in_internet_facing_load_balancers',
    provider: 'aws',
    service: 'shield',
    title: 'Internet-Facing ALB Without Shield Advanced Protection',
    severity: 'MEDIUM',
    description: 'Checks that internet-facing Application Load Balancers in accounts subscribed to AWS Shield Advanced are registered as Shield-protected resources against DDoS attacks.',
    remediation: 'Add the internet-facing Application Load Balancer as a protected resource in AWS Shield Advanced and pair it with an AWS WAF web ACL for layer-7 defense.',
    tags: ['shield', 'ddos', 'alb', 'internet-exposed', 'resilience'],
  },
  {
    checkId: 'shield_advanced_protection_in_route53_hosted_zones',
    provider: 'aws',
    service: 'shield',
    title: 'Route 53 Hosted Zone Without Shield Advanced Protection',
    severity: 'MEDIUM',
    description: 'Checks that Route 53 hosted zones in accounts subscribed to AWS Shield Advanced are registered as Shield-protected resources against DNS-layer DDoS attacks.',
    remediation: 'Add the Route 53 hosted zone as a protected resource in AWS Shield Advanced so DNS query floods against the zone are mitigated.',
    tags: ['shield', 'ddos', 'route53', 'dns', 'resilience'],
  },
];
