import { CheckMetadata } from '../../types';

// Titles must stay byte-identical to the pre-registry hardcoded titles:
// the scan worker dedupes OPEN findings on service:title:fingerprint, so a
// reworded title would re-open every existing finding as "new".
export const threatdetectionChecks: CheckMetadata[] = [
  {
    // Severity is HIGH for StopLogging/UpdateTrail; the emit call overrides to
    // CRITICAL for DeleteTrail events.
    checkId: 'threatdetection_cloudtrail_logging_tampering',
    provider: 'aws',
    service: 'threatdetection',
    title: 'Threat: CloudTrail Logging Disabled or Modified',
    severity: 'HIGH',
    description: 'Detects CloudTrail StopLogging, DeleteTrail or UpdateTrail events, which may indicate an attacker disabling audit logging to cover their tracks.',
    remediation: 'Re-enable CloudTrail logging immediately (aws cloudtrail start-logging --name <trail>). Investigate who performed this action and revoke access if unauthorized.',
    tags: ['threat', 'cloudtrail', 'defense-evasion'],
  },
  {
    checkId: 'threatdetection_root_account_activity',
    provider: 'aws',
    service: 'threatdetection',
    title: 'Threat: Root Account API Activity',
    severity: 'CRITICAL',
    description: 'Detects API calls made with the AWS root account, which should never be used for daily operations.',
    remediation: 'Immediately rotate root account credentials. Enable MFA on root. Delete root access keys if any exist. Use IAM roles for all operations.',
    tags: ['threat', 'root', 'unauthorized-access'],
  },
  {
    checkId: 'threatdetection_console_login_without_mfa',
    provider: 'aws',
    service: 'threatdetection',
    title: 'Threat: Console Login Without MFA',
    severity: 'HIGH',
    description: 'Detects successful AWS console logins performed without MFA, a credential compromise risk.',
    remediation: "Enforce MFA for all IAM users via IAM policy condition aws:MultiFactorAuthPresent. Temporarily disable the user's console access until MFA is configured.",
    tags: ['threat', 'mfa', 'unauthorized-access'],
  },
  {
    checkId: 'threatdetection_brute_force_login_attempts',
    provider: 'aws',
    service: 'threatdetection',
    title: 'Threat: Brute Force Login Attempt',
    severity: 'HIGH',
    description: 'Detects repeated failed console login attempts from a single IP address, indicating a brute-force or credential stuffing attack.',
    remediation: 'Block the source IP at the network/WAF level. Enable account lockout policies. Review whether any login succeeded.',
    tags: ['threat', 'brute-force', 'unauthorized-access'],
  },
  {
    checkId: 'threatdetection_admin_policy_attached_to_user',
    provider: 'aws',
    service: 'threatdetection',
    title: 'Threat: Admin Policy Attached to User',
    severity: 'CRITICAL',
    description: 'Detects AttachUserPolicy events granting the AdministratorAccess managed policy, which may indicate persistence or privilege escalation.',
    remediation: 'Immediately detach the AdministratorAccess policy from the user (aws iam detach-user-policy --policy-arn arn:aws:iam::aws:policy/AdministratorAccess). Investigate whether this was authorized.',
    tags: ['threat', 'persistence', 'admin'],
  },
  {
    checkId: 'threatdetection_new_iam_user_created',
    provider: 'aws',
    service: 'threatdetection',
    title: 'Threat: New IAM User Created',
    severity: 'MEDIUM',
    description: 'Detects CreateUser events. New IAM users created outside authorized onboarding may indicate persistence.',
    remediation: 'Verify the user was created as part of an authorized onboarding process. If unauthorized, delete it immediately: aws iam delete-user --user-name <name>.',
    tags: ['threat', 'persistence', 'iam'],
  },
  {
    checkId: 'threatdetection_new_access_key_created',
    provider: 'aws',
    service: 'threatdetection',
    title: 'Threat: New Access Key Created',
    severity: 'HIGH',
    description: 'Detects CreateAccessKey events. New access keys created by unexpected actors may indicate credential persistence.',
    remediation: 'Verify the key creation was authorized. If not, deactivate it immediately: aws iam update-access-key --access-key-id <key-id> --status Inactive.',
    tags: ['threat', 'persistence', 'access-key'],
  },
  {
    checkId: 'cloudtrail_threat_detection_privilege_escalation',
    provider: 'aws',
    service: 'threatdetection',
    title: 'Threat: IAM Policy Privilege Escalation',
    severity: 'CRITICAL',
    description: 'Detects PutUserPolicy/PutRolePolicy/PutGroupPolicy events attaching inline policies with wildcard permissions, which grant unrestricted AWS access.',
    remediation: 'Delete the wildcard inline policy immediately and replace it with least-privilege managed policies.',
    tags: ['threat', 'privilege-escalation', 'iam'],
  },
  {
    checkId: 'threatdetection_iam_enumeration',
    provider: 'aws',
    service: 'threatdetection',
    title: 'Threat: IAM Enumeration Detected',
    severity: 'HIGH',
    description: 'Detects GetAccountAuthorizationDetails calls, which dump the entire IAM configuration — a common reconnaissance technique.',
    remediation: 'Review whether the caller should have iam:GetAccountAuthorizationDetails permission. Restrict this permission to only security/audit roles.',
    tags: ['threat', 'reconnaissance', 'iam'],
  },
  {
    checkId: 'cloudtrail_threat_detection_enumeration',
    provider: 'aws',
    service: 'threatdetection',
    title: 'Threat: Infrastructure Enumeration Detected',
    severity: 'MEDIUM',
    description: 'Detects actors calling many different discovery (Describe*/List*) APIs in a short window, a pattern of automated reconnaissance of the AWS environment.',
    remediation: 'Investigate whether the actor is a legitimate automation tool or compromised credential. Apply least-privilege — restrict discovery APIs to only needed services.',
    tags: ['threat', 'reconnaissance', 'enumeration'],
  },
  {
    checkId: 'threatdetection_mass_ec2_termination',
    provider: 'aws',
    service: 'threatdetection',
    title: 'Threat: Mass EC2 Instance Termination',
    severity: 'CRITICAL',
    description: 'Detects repeated TerminateInstances calls by a single actor, which may indicate ransomware, sabotage or a compromised credential.',
    remediation: 'Immediately revoke the actor credentials. Restore instances from snapshots/AMIs. Enable EC2 termination protection on critical instances.',
    tags: ['threat', 'impact', 'deletion'],
  },
  {
    checkId: 'threatdetection_ebs_snapshot_made_public',
    provider: 'aws',
    service: 'threatdetection',
    title: 'Threat: EBS Snapshot Made Public',
    severity: 'CRITICAL',
    description: 'Detects ModifySnapshotAttribute events that make an EBS snapshot publicly accessible, exposing all volume data to any AWS account.',
    remediation: 'Immediately make the snapshot private: aws ec2 modify-snapshot-attribute --snapshot-id <id> --attribute createVolumePermission --operation-type remove --group-names all.',
    tags: ['threat', 'exfiltration', 'snapshot'],
  },
  {
    checkId: 'threatdetection_rds_snapshot_made_public',
    provider: 'aws',
    service: 'threatdetection',
    title: 'Threat: RDS Snapshot Made Public',
    severity: 'CRITICAL',
    description: 'Detects ModifyDBSnapshotAttribute events that make an RDS snapshot publicly restorable, exposing the database contents to any AWS account.',
    remediation: 'Make the snapshot private: aws rds modify-db-snapshot-attribute --db-snapshot-identifier <id> --attribute-name restore --values-to-remove all.',
    tags: ['threat', 'exfiltration', 'rds'],
  },
  {
    checkId: 'threatdetection_high_compute_instance_launch',
    provider: 'aws',
    service: 'threatdetection',
    title: 'Threat: High-Compute Instance Launch (Crypto Mining Indicator)',
    severity: 'HIGH',
    description: 'Detects RunInstances events launching high-compute/GPU instance types, which often indicate crypto-mining when launched by unexpected identities.',
    remediation: 'If unauthorized, immediately terminate the instance(s) and revoke the actor credentials. Enable AWS Cost Anomaly Detection to catch unexpected compute spend.',
    tags: ['threat', 'crypto-mining', 'impact'],
  },
  {
    checkId: 'threatdetection_config_recorder_stopped',
    provider: 'aws',
    service: 'threatdetection',
    title: 'Threat: AWS Config Recorder Stopped',
    severity: 'HIGH',
    description: 'Detects StopConfigurationRecorder, DeleteConfigurationRecorder and DeleteDeliveryChannel events. Disabling AWS Config stops configuration change tracking — a common defense evasion technique.',
    remediation: 'Re-enable AWS Config recording immediately. Investigate whether this was authorized.',
    tags: ['threat', 'defense-evasion', 'config'],
  },
  // ── GuardDuty posture checks (ported from Prowler guardduty service) ──────
  // Check logic derived from Prowler (Apache-2.0, https://github.com/prowler-cloud/prowler)
  {
    checkId: 'guardduty_is_enabled',
    provider: 'aws',
    service: 'threatdetection',
    title: 'GuardDuty Not Enabled or Suspended',
    severity: 'HIGH',
    description: 'Checks that a GuardDuty detector exists in the region, is configured and has status ENABLED rather than suspended.',
    remediation: 'Enable GuardDuty in the region (aws guardduty create-detector --enable). If a detector exists but is suspended, re-enable it from the GuardDuty settings.',
    tags: ['guardduty', 'threat-detection', 'monitoring'],
  },
  {
    checkId: 'guardduty_centrally_managed',
    provider: 'aws',
    service: 'threatdetection',
    title: 'GuardDuty Not Centrally Managed',
    severity: 'MEDIUM',
    description: 'Checks that the GuardDuty detector is managed by an administrator account, or is itself the administrator account with member accounts.',
    remediation: 'Designate a GuardDuty delegated administrator for the organization and associate all member accounts so findings are centrally aggregated and managed.',
    tags: ['guardduty', 'organizations', 'governance'],
  },
  {
    checkId: 'guardduty_delegated_admin_enabled_all_regions',
    provider: 'aws',
    service: 'threatdetection',
    title: 'GuardDuty Delegated Admin Not Configured',
    severity: 'HIGH',
    description: 'Checks that GuardDuty has an enabled delegated administrator account, an enabled detector, and organization auto-enable configured for new member accounts.',
    remediation: 'Enable a GuardDuty delegated administrator (aws guardduty enable-organization-admin-account), ensure the detector is enabled, and set auto-enable for organization members (aws guardduty update-organization-configuration --auto-enable-organization-members ALL).',
    tags: ['guardduty', 'organizations', 'governance'],
  },
  {
    checkId: 'guardduty_s3_protection_enabled',
    provider: 'aws',
    service: 'threatdetection',
    title: 'GuardDuty S3 Protection Disabled',
    severity: 'HIGH',
    description: 'Checks that the GuardDuty detector has S3 Protection (S3 data event log analysis) enabled to detect suspicious access to S3 data.',
    remediation: 'Enable S3 Protection on the detector: aws guardduty update-detector --detector-id <id> --data-sources S3Logs={Enable=true}.',
    tags: ['guardduty', 's3', 'threat-detection'],
  },
  {
    checkId: 'guardduty_eks_audit_log_enabled',
    provider: 'aws',
    service: 'threatdetection',
    title: 'GuardDuty EKS Audit Log Monitoring Disabled',
    severity: 'HIGH',
    description: 'Checks that the GuardDuty detector has EKS Audit Log Monitoring enabled to detect suspicious activity in Kubernetes audit logs.',
    remediation: 'Enable EKS Audit Log Monitoring on the detector: aws guardduty update-detector --detector-id <id> --data-sources Kubernetes={AuditLogs={Enable=true}}.',
    tags: ['guardduty', 'eks', 'threat-detection'],
  },
  {
    checkId: 'guardduty_eks_runtime_monitoring_enabled',
    provider: 'aws',
    service: 'threatdetection',
    title: 'GuardDuty EKS Runtime Monitoring Disabled',
    severity: 'MEDIUM',
    description: 'Checks that the GuardDuty detector has the EKS Runtime Monitoring feature enabled to detect runtime threats on EKS workloads.',
    remediation: 'Enable the EKS_RUNTIME_MONITORING feature: aws guardduty update-detector --detector-id <id> --features Name=EKS_RUNTIME_MONITORING,Status=ENABLED.',
    tags: ['guardduty', 'eks', 'runtime', 'threat-detection'],
  },
  {
    checkId: 'guardduty_ec2_malware_protection_enabled',
    provider: 'aws',
    service: 'threatdetection',
    title: 'GuardDuty EC2 Malware Protection Disabled',
    severity: 'HIGH',
    description: 'Checks that the GuardDuty detector has Malware Protection for EC2 (EBS volume scanning on findings) enabled.',
    remediation: 'Enable Malware Protection for EC2 on the detector so EBS volumes of instances with findings are scanned: aws guardduty update-detector --detector-id <id> --features Name=EBS_MALWARE_PROTECTION,Status=ENABLED.',
    tags: ['guardduty', 'ec2', 'malware', 'threat-detection'],
  },
  {
    checkId: 'guardduty_rds_protection_enabled',
    provider: 'aws',
    service: 'threatdetection',
    title: 'GuardDuty RDS Protection Disabled',
    severity: 'HIGH',
    description: 'Checks that the GuardDuty detector has RDS Protection (RDS login activity monitoring) enabled.',
    remediation: 'Enable the RDS_LOGIN_EVENTS feature: aws guardduty update-detector --detector-id <id> --features Name=RDS_LOGIN_EVENTS,Status=ENABLED.',
    tags: ['guardduty', 'rds', 'threat-detection'],
  },
  {
    checkId: 'guardduty_lambda_protection_enabled',
    provider: 'aws',
    service: 'threatdetection',
    title: 'GuardDuty Lambda Protection Disabled',
    severity: 'HIGH',
    description: 'Checks that the GuardDuty detector has Lambda Protection (Lambda network activity monitoring) enabled.',
    remediation: 'Enable the LAMBDA_NETWORK_LOGS feature: aws guardduty update-detector --detector-id <id> --features Name=LAMBDA_NETWORK_LOGS,Status=ENABLED.',
    tags: ['guardduty', 'lambda', 'threat-detection'],
  },
  {
    checkId: 'guardduty_no_high_severity_findings',
    provider: 'aws',
    service: 'threatdetection',
    title: 'GuardDuty High Severity Findings Unresolved',
    severity: 'HIGH',
    description: 'Checks that the GuardDuty detector has no unarchived high severity (8.0+) findings awaiting triage.',
    remediation: 'Investigate each high severity GuardDuty finding, remediate the underlying threat, then archive the finding once resolved.',
    tags: ['guardduty', 'findings', 'incident-response'],
  },
];
