import { CheckMetadata } from '../../types';

// Titles must stay byte-identical to the pre-registry hardcoded titles:
// the scan worker dedupes OPEN findings on service:title:fingerprint, so a
// reworded title would re-open every existing finding as "new".
export const vpcChecks: CheckMetadata[] = [
  {
    checkId: 'vpc_default_vpc_exists',
    provider: 'aws',
    service: 'vpc',
    title: 'Default VPC Exists',
    severity: 'LOW',
    description: 'Checks for the presence of a default VPC, which ships with an internet route, default security group, and default ACL that resources launched into it inherit.',
    remediation: 'Delete the default VPC if unused, or replace it with a custom VPC. Always launch workloads into a custom VPC.',
    tags: ['vpc', 'default-vpc', 'cis-5.1'],
    compliance: {
      cis_2_0_aws: ['5.1'],
    },
  },
  {
    checkId: 'ec2_securitygroup_default_restrict_traffic',
    provider: 'aws',
    service: 'vpc',
    title: 'Default Security Group Not Restricted',
    severity: 'MEDIUM',
    description: 'Checks that the default security group of every VPC restricts all traffic (no inbound rules and no non-default outbound rules).',
    remediation: 'Remove all inbound and outbound rules from the default security group in each VPC',
    tags: ['vpc', 'security-group', 'cis-5.3'],
    compliance: {
      cis_2_0_aws: ['5.3'],
    },
  },
  {
    checkId: 'vpc_peering_routing_tables_with_least_privilege',
    provider: 'aws',
    service: 'vpc',
    title: 'VPC Peering Route Not Least Access',
    severity: 'MEDIUM',
    description: 'Checks route tables for overly broad routes (/0 destinations) pointing to VPC peering connections, which violate least-privilege network access.',
    remediation: 'Review VPC peering routes and restrict to only the specific CIDR blocks that are required',
    tags: ['vpc', 'peering', 'routing', 'cis-5.4'],
    compliance: {
      cis_2_0_aws: ['5.4'],
    },
  },
  {
    checkId: 'vpc_ebs_default_encryption_disabled',
    provider: 'aws',
    service: 'vpc',
    title: 'EBS Default Encryption Not Enabled',
    severity: 'MEDIUM',
    description: 'Checks that EBS default encryption is enabled so new EBS volumes are automatically encrypted at rest.',
    remediation: 'Enable EBS default encryption in the EC2 console to automatically encrypt all new EBS volumes',
    tags: ['ec2', 'ebs', 'encryption', 'cis-2.2.1'],
    compliance: {
      cis_2_0_aws: ['2.2.1'],
    },
  },
  {
    checkId: 'vpc_different_regions',
    provider: 'aws',
    service: 'vpc',
    title: 'VPCs In Single Region Only',
    severity: 'MEDIUM',
    description: 'Checks that non-default VPCs exist in more than one region; a single-region network topology concentrates the blast radius of a regional outage.',
    remediation: 'Create VPCs in at least one additional region for critical workloads and replicate routing, security controls and endpoints consistently across regions.',
    tags: ['vpc', 'resilience', 'multi-region'],
  },
  {
    checkId: 'vpc_endpoint_connections_trust_boundaries',
    provider: 'aws',
    service: 'vpc',
    title: 'VPC Endpoint Policy Allows Untrusted Accounts',
    severity: 'HIGH',
    description: 'Checks that VPC endpoint policies restrict access to trusted AWS accounts; wildcard or foreign-account principals without restrictive conditions let non-trusted principals use the endpoint.',
    remediation: 'Restrict the endpoint policy to trusted accounts, e.g. add a Condition with StringEquals on aws:PrincipalAccount listing only trusted account IDs, and avoid wildcard principals without conditions.',
    tags: ['vpc', 'endpoint', 'trust-boundaries'],
  },
  {
    checkId: 'vpc_endpoint_for_ec2_enabled',
    provider: 'aws',
    service: 'vpc',
    title: 'VPC Missing EC2 Endpoint',
    severity: 'MEDIUM',
    description: 'Checks that in-use VPCs have a VPC endpoint for the EC2 API so instance management traffic stays on the AWS network instead of leaving via IGW/NAT.',
    remediation: 'Create an interface VPC endpoint for com.amazonaws.<region>.ec2 in the VPC, enable private DNS, and attach a least-privilege endpoint policy.',
    tags: ['vpc', 'endpoint', 'private-connectivity'],
  },
  {
    checkId: 'vpc_endpoint_multi_az_enabled',
    provider: 'aws',
    service: 'vpc',
    title: 'VPC Interface Endpoint Not Multi-AZ',
    severity: 'MEDIUM',
    description: 'Checks that interface VPC endpoints have network interfaces in more than one subnet so the endpoint survives an Availability Zone outage.',
    remediation: 'Add at least one more subnet in a different Availability Zone to the interface endpoint (Actions > Manage subnets in the VPC console).',
    tags: ['vpc', 'endpoint', 'resilience'],
  },
  {
    checkId: 'vpc_endpoint_services_allowed_principals_trust_boundaries',
    provider: 'aws',
    service: 'vpc',
    title: 'VPC Endpoint Service Allows Untrusted Principals',
    severity: 'HIGH',
    description: 'Checks that VPC endpoint services allow only trusted principals (or none); wildcard or foreign-account principals can create PrivateLink connections into the service.',
    remediation: 'Edit the endpoint service allowed principals to remove wildcards and untrusted accounts, keeping only vetted account IDs or role ARNs.',
    tags: ['vpc', 'endpoint-service', 'trust-boundaries'],
  },
  {
    checkId: 'vpc_subnet_different_az',
    provider: 'aws',
    service: 'vpc',
    title: 'VPC Subnets In Single AZ',
    severity: 'MEDIUM',
    description: 'Checks that in-use VPCs have subnets in more than one Availability Zone; single-AZ layouts are a single point of failure during zonal outages.',
    remediation: 'Create subnets in at least two Availability Zones with non-overlapping CIDR blocks and distribute workloads across them.',
    tags: ['vpc', 'subnet', 'resilience'],
  },
  {
    checkId: 'vpc_subnet_no_public_ip_by_default',
    provider: 'aws',
    service: 'vpc',
    title: 'Subnet Auto-Assigns Public IP',
    severity: 'HIGH',
    description: 'Checks for in-use subnets with MapPublicIpOnLaunch enabled, which give every launched instance a public IPv4 address by default.',
    remediation: 'Disable auto-assign public IPv4 on the subnet (aws ec2 modify-subnet-attribute --subnet-id <id> --no-map-public-ip-on-launch) and assign public IPs explicitly only where required.',
    tags: ['vpc', 'subnet', 'internet-exposed'],
  },
  {
    checkId: 'vpc_subnet_separate_private_public',
    provider: 'aws',
    service: 'vpc',
    title: 'VPC Without Public And Private Subnets',
    severity: 'MEDIUM',
    description: 'Checks that in-use VPCs are segmented with at least one public subnet (routed to an internet gateway) and one private subnet; VPCs with no subnets or a single tier lack segmentation.',
    remediation: 'Create both a public subnet (route 0.0.0.0/0 to an internet gateway) and a private subnet (no IGW route) in the VPC, placing internet-facing endpoints in the public tier and workloads in the private tier.',
    tags: ['vpc', 'subnet', 'segmentation', 'trust-boundaries'],
  },
  {
    checkId: 'vpc_vpn_connection_tunnels_up',
    provider: 'aws',
    service: 'vpc',
    title: 'VPN Connection Tunnel Down',
    severity: 'MEDIUM',
    description: 'Checks that Site-to-Site VPN connections have both IPsec tunnels UP; with one tunnel down the connection has no failover redundancy.',
    remediation: 'Configure both tunnels on the customer gateway device using the downloaded VPN configuration and verify both show Status UP in the console.',
    tags: ['vpc', 'vpn', 'resilience'],
  },
];
