import { CheckMetadata } from '../../types';

// Titles must stay byte-identical to the pre-registry hardcoded titles:
// the scan worker dedupes OPEN findings on service:title:fingerprint, so a
// reworded title would re-open every existing finding as "new".
export const wafChecks: CheckMetadata[] = [
  {
    checkId: 'waf_webacls_configured',
    provider: 'aws',
    service: 'waf',
    title: 'No WAF WebACLs Configured',
    severity: 'HIGH',
    description: 'Checks that AWS WAF WebACLs exist in the region; without them, internet-facing resources (ALB, API Gateway, CloudFront) are not protected against common web exploits (OWASP Top 10), bots, and DDoS attacks.',
    remediation: 'Create WAF WebACLs with AWS Managed Rules and associate them with internet-facing ALBs, API Gateway stages, and CloudFront distributions.',
    tags: ['waf', 'security'],
  },
  {
    checkId: 'waf_webacl_resource_associated',
    provider: 'aws',
    service: 'waf',
    title: 'WAF WebACL Not Associated With Any Resource',
    severity: 'MEDIUM',
    description: 'Checks that WAF WebACLs are associated with at least one ALB, API Gateway stage, or CloudFront distribution; a WebACL provides no protection until associated.',
    remediation: 'Associate the WebACL with an internet-facing resource in the WAF console.',
    tags: ['waf', 'configuration'],
  },
  {
    checkId: 'wafv2_webacl_logging_enabled',
    provider: 'aws',
    service: 'waf',
    title: 'WAF WebACL Logging Disabled',
    severity: 'MEDIUM',
    description: 'Checks that WAF WebACLs have logging enabled so blocked requests and attack patterns can be analyzed.',
    remediation: 'Enable WAF logging to CloudWatch Logs or S3 in the WAF console under Logging and metrics.',
    tags: ['waf', 'logging'],
  },
  {
    checkId: 'waf_webacl_managed_rule_groups_configured',
    provider: 'aws',
    service: 'waf',
    title: 'WAF WebACL Has No Managed Rule Groups',
    severity: 'HIGH',
    description: 'Checks that WAF WebACLs include AWS Managed Rule Groups, which provide protection against OWASP Top 10, known bad inputs, and IP reputation threats.',
    remediation: 'Add AWS Managed Rule Groups: AWSManagedRulesCommonRuleSet (OWASP), AWSManagedRulesKnownBadInputsRuleSet, and AWSManagedRulesAmazonIpReputationList to the WebACL.',
    tags: ['waf', 'rules'],
  },
  {
    checkId: 'waf_webacl_rate_based_rule_configured',
    provider: 'aws',
    service: 'waf',
    title: 'WAF WebACL Has No Rate Limiting Rule',
    severity: 'MEDIUM',
    description: 'Checks that WAF WebACLs include a rate-based rule; without rate limiting, the protected resource is vulnerable to brute force and DDoS attacks.',
    remediation: 'Add a rate-based rule to the WebACL limiting requests per IP to an appropriate threshold (e.g. 2000 req/5min).',
    tags: ['waf', 'rate-limiting'],
  },
  {
    checkId: 'wafv2_webacl_with_rules',
    provider: 'aws',
    service: 'waf',
    title: 'WAF WebACL Has No Rules Or Rule Groups',
    severity: 'HIGH',
    description: 'Checks that WAFv2 WebACLs have at least one rule or rule group attached; an empty WebACL inspects nothing and traffic is governed solely by the default action.',
    remediation: 'Attach at least one rule or managed rule group (e.g. AWSManagedRulesCommonRuleSet) to the WebACL so requests are actually inspected.',
    tags: ['waf', 'rules'],
  },
  {
    checkId: 'wafv2_webacl_rule_logging_enabled',
    provider: 'aws',
    service: 'waf',
    title: 'WAF WebACL Rule CloudWatch Metrics Disabled',
    severity: 'MEDIUM',
    description: 'Checks that every rule and rule group in a WAFv2 WebACL has CloudWatch metrics enabled; without rule-level metrics, traffic spikes, rule bypasses, and misconfigurations go unnoticed.',
    remediation: 'Enable CloudWatchMetricsEnabled in the VisibilityConfig of every rule and rule group in the WebACL, and build alarms over the emitted metrics.',
    tags: ['waf', 'logging', 'monitoring'],
  },
  {
    checkId: 'waf_global_rule_with_conditions',
    provider: 'aws',
    service: 'waf',
    title: 'WAF Classic Global Rule Has No Conditions',
    severity: 'MEDIUM',
    description: 'Checks that WAF Classic global rules contain at least one condition; a rule with no conditions never matches traffic and provides no filtering while suggesting coverage exists.',
    remediation: 'Add at least one condition (predicate) such as an IP match, SQLi, XSS, or size constraint to the rule, or delete placeholder rules. Plan migration to WAFv2.',
    tags: ['waf', 'classic', 'rules'],
  },
  {
    checkId: 'waf_global_rulegroup_not_empty',
    provider: 'aws',
    service: 'waf',
    title: 'WAF Classic Global Rule Group Is Empty',
    severity: 'HIGH',
    description: 'Checks that WAF Classic global rule groups contain at least one rule; an empty rule group performs no inspection even when attached to a WebACL.',
    remediation: 'Add at least one activated rule with an appropriate action (BLOCK or COUNT) to the rule group, or delete empty placeholder groups. Plan migration to WAFv2.',
    tags: ['waf', 'classic', 'rules'],
  },
  {
    checkId: 'waf_global_webacl_logging_enabled',
    provider: 'aws',
    service: 'waf',
    title: 'WAF Classic Global WebACL Logging Disabled',
    severity: 'MEDIUM',
    description: 'Checks that WAF Classic global WebACLs have logging enabled; without logs, allow/block decisions and attack patterns cannot be analyzed or used for incident response.',
    remediation: 'Enable logging on the WebACL with a Kinesis Data Firehose delivery stream (name starting with aws-waf-logs-) in us-east-1, and centralize the records for monitoring.',
    tags: ['waf', 'classic', 'logging'],
  },
  {
    checkId: 'waf_global_webacl_with_rules',
    provider: 'aws',
    service: 'waf',
    title: 'WAF Classic Global WebACL Has No Rules',
    severity: 'MEDIUM',
    description: 'Checks that WAF Classic global WebACLs contain at least one rule or rule group; an empty WebACL relies solely on its default action and inspects nothing.',
    remediation: 'Add at least one rule or rule group to the WebACL, or migrate the workload to WAFv2 with AWS Managed Rules.',
    tags: ['waf', 'classic', 'rules'],
  },
  {
    checkId: 'waf_regional_rule_with_conditions',
    provider: 'aws',
    service: 'waf',
    title: 'WAF Classic Regional Rule Has No Conditions',
    severity: 'MEDIUM',
    description: 'Checks that WAF Classic regional rules contain at least one condition; a rule with no conditions never matches traffic and provides no filtering while suggesting coverage exists.',
    remediation: 'Add at least one condition (predicate) such as an IP match, SQLi, XSS, or size constraint to the rule, or delete placeholder rules. Plan migration to WAFv2.',
    tags: ['waf', 'classic', 'rules'],
  },
  {
    checkId: 'waf_regional_rulegroup_not_empty',
    provider: 'aws',
    service: 'waf',
    title: 'WAF Classic Regional Rule Group Is Empty',
    severity: 'MEDIUM',
    description: 'Checks that WAF Classic regional rule groups contain at least one rule; an empty rule group performs no inspection even when attached to a WebACL.',
    remediation: 'Add at least one activated rule with an appropriate action (BLOCK or COUNT) to the rule group, or delete empty placeholder groups. Plan migration to WAFv2.',
    tags: ['waf', 'classic', 'rules'],
  },
  {
    checkId: 'waf_regional_webacl_logging_enabled',
    provider: 'aws',
    service: 'waf',
    title: 'WAF Classic Regional WebACL Logging Disabled',
    severity: 'MEDIUM',
    description: 'Checks that WAF Classic regional WebACLs (protecting ALBs and API Gateway stages) have logging enabled; without logs, allow/block decisions and attack patterns cannot be analyzed.',
    remediation: 'Enable logging on the WebACL with a Kinesis Data Firehose delivery stream (name starting with aws-waf-logs-) in the same region, and centralize the records for monitoring.',
    tags: ['waf', 'classic', 'logging'],
  },
  {
    checkId: 'waf_regional_webacl_with_rules',
    provider: 'aws',
    service: 'waf',
    title: 'WAF Classic Regional WebACL Has No Rules',
    severity: 'MEDIUM',
    description: 'Checks that WAF Classic regional WebACLs contain at least one rule or rule group; an empty WebACL relies solely on its default action and inspects nothing.',
    remediation: 'Add at least one rule or rule group to the WebACL, or migrate the workload to WAFv2 with AWS Managed Rules.',
    tags: ['waf', 'classic', 'rules'],
  },
];
